### ISSUE TITLE
autotest warnings

### ISSUE THREAD

**Issue by davnustratbac** [QQuick/Transcrypt#103]
hi there, Im running into problems running the autotests,
Clean install in clean virtualenv, latest python 3.5 downloaded direct 20 aug.
I have tried to run the created files however I also get a constant return of missing modules. That I can probably work through however Im wondering if this is due to something not completing due to the build warnings 
    `
       (py3.5Test) lenovo% transcrypt -b autotest.py  
       Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.213
       Copyright (C) Geatec Engineering. License: Apache 2.0

```
Saving result in: /home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js
Saving minified result in: /home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.min.js
/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js:3234: WARNING - unreachable code
                        catch (__except0__) {
                        ^

/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js:3245: WARNING - unreachable code
                        catch (__except0__) {
                        ^

/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js:3256: WARNING - unreachable code
                        catch (__except0__) {
                        ^

/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js:3267: WARNING - unreachable code
                        catch (__except0__) {
                        ^

0 error(s), 4 warning(s)

Ready
`
```

Hope someone can help me in the right direction

**Comment by JdeH** [comment]
I think I can.  The  autotest for /../automated_tests/trancrypt also tests assertions. This means that it requires the -da switch. So if you want to recompile use

`transcrypt -da -b autotest.py.`

Also run using:

'transcrypt -r autotest.py'

Then load the autotest.html or autotest.min.html into your browser to see the result.
If you also want sourcemaps add the -m switch to the -da and -b

Let me know if this works for you.

Kind regards
Jacques

**Comment by JdeH** [comment]
As for the missing modules: which are they, can you add a screendump, list or anything like it?

**Comment by davnustratbac** [comment]
Hi, The extra switches did indeed fix the problem.
As for the modules issue, the problem arises whilst trying to run the autotest

   `(py3.5Test) lenovo% transcrypt -r autotest.py                                                                                                              
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.213
Copyright (C) Geatec Engineering. License: Apache 2.0

Error: cannot run autotest.py using CPython: No module named 'attribs_by_name'

Aborted
`
the name of the module changes each time as each dependency is met by my manual pip installation, however im struggling to find what provides 'attribs_by_name',
edit: transcrypt provides a directory attribs_by_name,
so it appears that python isnt finding the transcrypt modules ?

I was wondering if this was a broken env issue where python cannot find the correct paths however running $PATH inside the venv shows the virtualenv path correctly & using python inside the venv in interractive mode allows me to import modules correctly.
I shall keep plugging  away 
Any help would be greatly appreciated
Dave

**Comment by JdeH** [comment]
Hi,

attribs_by_name is one of the modules contained in the autotest, so indeed it seems the transcrypt modules cannot be found.

Unfortunately currently I cannot reproduce this problem here.
To find what's wrong lets do some experimenting.
Setting the path happens in this code fragment near the start of __main__.py:

```
programDir = os.getcwd () .replace ('\\', '/')
transpilerDir = os.path.dirname (os.path.abspath (__file__)) .replace ('\\', '/')	
modulesDir = '{}/modules'.format (transpilerDir)

# Both CPython and Transcrypt will use all dirs in sys.path as search roots for modules
# CPython will also search relatively from each module, Transcrypt only from the main module

compilerPath = [programDir, modulesDir] + sys.path	# Used by Transcrypt rather than CPython, programDir isn't always part of the path under Linux
sys.path = sys.path	[1:] + [modulesDir]				# Used by CPython, leave out current dir to prevent importing modules root if there's a module by that name
sys.modules.pop ('org', None)						# Unload org from a packages dir, if it's there.

```

Right after this fragment, could you add the statement:

`print (sys.path)`

and tell me what it prints.

**Comment by davnustratbac** [comment]
Hi there, as requested ..
`
                                                                                                                 
    (py3.5Test) lenovo% transcrypt -r autotest.py                                                                                                              
    /home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt
    /home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/modules
    ['/home/dave/.virtualenvs/py3.5Test/lib/python35.zip', '/home/dave/.virtualenvs/py3.5Test/lib/python3.5', '/home/dave/.virtualenvs/py3.5Test/lib/python3.5/plat-linux', '/home/dave/.virtualenvs/py3.5Test/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages', '/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/modules']
    Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.213
    Copyright (C) Geatec Engineering. License: Apache 2.0

    Error: cannot run autotest.py using CPython: No module named 'attribs_by_name'

    Aborted

`

**Comment by ihph** [comment]
As a workaround you can manually add the path to the transcript modules in __main__.py
in your case it would look like this
...
**sys.path.insert(1,'/home/dave/.virtualenvs/py3.5Test/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt')**
print (transpilerDir)
print (modulesDir)
print (sys.path)

...seems to work now

**Comment by davnustratbac** [comment]
thanks for your help

**Comment by JdeH** [comment]
Haven't been able to get to the bottom of this.
