### ISSUE TITLE
The new website is currently online

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#119]
www.transcrypt.org

**Comment by pierrejean-coudert** [comment]
Seems to be buggy on Firefox/Win10... No text at all

**Comment by JdeH** [comment]
Wow, I haven't got win10, but I'll try firefox.

**Comment by artyprog** [comment]
Hello Jacques,

Bug on Windows 7 /FireFox42

Regards

2016-09-29 10:27 GMT+02:00 Jacques de Hooge <notifications@github.com>:

**Comment by JdeH** [comment]
Thanks!

@pierrejean-coudert @artyprog Is it better now? Only gallery to much zoomed in.

**Comment by JdeH** [comment]
Seems everything is alright now. O, those browser differences...

**Comment by pierrejean-coudert** [comment]
Yes Jacques, it's really better now :-)

On Thu, Sep 29, 2016 at 12:45 PM, Jacques de Hooge <notifications@github.com

**Comment by JdeH** [comment]
What do you think about the colors?
I wanted something different from blue, but it's a bit uncommon...

**Comment by pierrejean-coudert** [comment]
Hmmm colors and taste... ;-)

Keep it lean.

**Comment by JdeH** [comment]
Since nobody really liked the colors, I've withdrawn a bit to the mainstream...

**Comment by daboross** [comment]
Looks really nice! I think an easy way to access the FAQ and the different library examples besides scrolling might be nice, but besides that it looks and functions great!
