### ISSUE TITLE
Autotest Linux, time module: list of month names not correct due to timezone problem VMWare Player

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#126]
When running the autotest under Linux, the following piece of JS code throws an exception:

```
if (d == 'b') {     // Line nr 2596 (or so)
    if (!(__in__ (v, __months))) {
        var __except0__ = ValueError ('Month unknown in your locale');
        _except0__.__cause__ = null;
        console.log (v);                    // Inserted for debugging
        console.log (__months);      // Inserted for debugging
        throw __except0__;
    }
            ...
```

The two log statements print the following:

```
feb
["dec", "jan", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]

autotest.js:2602 Uncaught exception
```

**Month 'feb' is missing from the list and 'dec' is there twice.**

This is where the __months list is filled (line 2298 or so of autotest.js):

```
var __months = list ([]);
var __months_long = list ([]);
var __d = new Date (946681200000.0);
for (var i = 0; i < 12; i++) {
    var __iterable0__ = tuple ([tuple ([__months, 'short']), tuple ([__months_long, 'long'])]);
    for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
        var __left0__ = __iterable0__ [__index0__];
        var l = __left0__ [0];
        var s = __left0__ [1];
        l.append (__d.toLocaleString (window.navigator.language, dict ({'month': s})).lower ());
    }
    __d.setMonth (__d.getMonth () + 1);
```

Weird thing is that on Wiindows it works OK.

@AXGKl
Your code looks correct to me, maybe it's Chrome's JS interpreter or the Linux locale that has a problem here. But in that case I would expect this to be widely known, since many people use month names. Do you have a clue?

**Comment by AXGKl** [comment]
> Weird thing is that on Wiindows it works OK.
strange, vice versa would have been easier to swallow - since I tested exclusively in linux. And yes I do expect probs with certain locale settings in those functions having to do with how data is presented (like the in '%b' switch) - but actually not too many in our timezone.
And I'm also using Chrome :-/ - on Mac.

Just verified with GH transcrypt version and all good on linux.
```python
   elif d == 'b':
396             # month short. overruled by m if present
397             print (__months)     
398             if not v in __months:                               
399                 print (v)                                       
400                 print (__months)                                
401                 raise ValueError('Month unknown in your locale')
402             t[1] = __months.index(v) + 1           
```
does not run into the exception but prints `['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']` and the tests succeed.


Two things: 
- Can you forward me your output of your env on linux (run `env`) so I can try the same settings ?
- Your output of `date`

**Comment by JdeH** [comment]
My OS version is Ubuntu 14.04 LTS.
It runs as a virtual machine in VMWare player under Windows 8.

Typing  `env > env.txt` at the console gives:

	XDG_VTNR=7
	XDG_SESSION_ID=c2
	CLUTTER_IM_MODULE=xim
	SELINUX_INIT=YES
	XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/jacdeh
	SESSION=ubuntu
	GPG_AGENT_INFO=/run/user/1000/keyring-xKDIH3/gpg:0:1
	TERM=xterm
	SHELL=/bin/bash
	XDG_MENU_PREFIX=gnome-
	VTE_VERSION=3409
	WINDOWID=54525963
	UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2162
	GNOME_KEYRING_CONTROL=/run/user/1000/keyring-xKDIH3
	GTK_MODULES=overlay-scrollbar:unity-gtk-module
	USER=jacdeh
	LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
	XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
	XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
	SSH_AUTH_SOCK=/run/user/1000/keyring-xKDIH3/ssh
	SESSION_MANAGER=local/ubuntu:@/tmp/.ICE-unix/2318,unix/ubuntu:/tmp/.ICE-unix/2318
	DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
	XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
	PATH=/home/jacdeh/miniconda3/bin:/home/jacdeh/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jacdeh/miniconda3/lib/python3.5/site-packages/transcrypt
	DESKTOP_SESSION=ubuntu
	QT_IM_MODULE=ibus
	QT_QPA_PLATFORMTHEME=appmenu-qt5
	JOB=dbus
	PWD=/home/jacdeh/miniconda3/lib/python3.5/site-packages/transcrypt
	XMODIFIERS=@im=ibus
	GNOME_KEYRING_PID=2149
	LANG=en_US.UTF-8
	GDM_LANG=en_US
	MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
	IM_CONFIG_PHASE=1
	COMPIZ_CONFIG_PROFILE=ubuntu
	GDMSESSION=ubuntu
	SESSIONTYPE=gnome-session
	XDG_SEAT=seat0
	HOME=/home/jacdeh
	SHLVL=1
	LANGUAGE=en_US
	GNOME_DESKTOP_SESSION_ID=this-is-deprecated
	LOGNAME=jacdeh
	PYTHONPATH=:/mnt/cardioWorkflowNT/exe/pythonLibrary:/mnt/cardioWorkflowNT/src_pyo/pythonLibrary:/mnt/cardioWorkflowNT/src/pythonLibrary
	COMPIZ_BIN_PATH=/usr/bin/
	XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
	QT4_IM_MODULE=xim
	DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-QOg5Q6WdcA
	LESSOPEN=| /usr/bin/lesspipe %s
	INSTANCE=
	TEXTDOMAIN=im-config
	XDG_RUNTIME_DIR=/run/user/1000
	DISPLAY=:0
	XDG_CURRENT_DESKTOP=Unity
	GTK_IM_MODULE=ibus
	LESSCLOSE=/usr/bin/lesspipe %s %s
	TEXTDOMAINDIR=/usr/share/locale/
	COLORTERM=gnome-terminal
	XAUTHORITY=/home/jacdeh/.Xauthority
	_=/usr/bin/env
	OLDPWD=/home/jacdeh/miniconda3/lib/python3.5/site-packages

Output of date will follow...

**Comment by JdeH** [comment]
Think I've narrowed it down a bit. The following pure JS in HTML code (no Transcrypt or time module involved):

```
<script>
	var __months = [];
	var __months_long = [];
	var __d = new Date (946681200000.0);
	for (var i = 0; i < 12; i++) {
	    var __iterable0__ = [[__months, 'short'], [__months_long, 'long']];
	    for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
		var __left0__ = __iterable0__ [__index0__];
		var l = __left0__ [0];
		var s = __left0__ [1];
		l.push (__d.toLocaleString (window.navigator.language, {'month': s}));
	    }
	    __d.setMonth (__d.getMonth () + 1);
        }
	console.log (__months_long);
	console.log (__months);
</script>
```

prints:

```
timetest.html:15 ["December", "January", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
timetest.html:16 ["Dec", "Jan", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

```

Weird, huh...
I'll try to simplify further.

**Comment by JdeH** [comment]
Well, I think it can't be simplified much further:

```
<script>
	var __d = new Date (946681200000.0);
	for (var i = 0; i < 12; i++) {
	    console.log (__d.toLocaleString (window.navigator.language, {'month': 'long'}));
	    __d.setMonth (__d.getMonth () + 1);
        }
</script>
```

prints:

```
December
January
March
April
May
June
July
August
September
October
November
December
```

Seems my Linux has is collectors item: It has a Y2K problem!!
Finally a real Y2K problem has emerged.
All the fuss wasn't for nothing.
This could have meant the end of the world (as some people expected)
Others got very rich from Y2K consultancy... :)

**Comment by JdeH** [comment]
Check...

```
<script>
	var __d = new Date ('Jan 1, 2001');
	for (var i = 0; i < 12; i++) {
	    console.log (__d.toLocaleString (window.navigator.language, {'month': 'long'}));
	    __d.setMonth (__d.getMonth () + 1);
        }
</script>
```

prints:
```

January
February
March
April
May
June
July
August
September
October
November
December

```

Q.E.D.

I don't know the right nr of secs for this date since 1/1/1970. 
If you do, maybe we should change the code accordingly, to make it work on crappy Linuxes...

**Comment by AXGKl** [comment]
Hi, yes, y2k flushed 2k DeutschMark (which I miss) into my then empty pocket - for spending the night in a Siemens office ;-)

Regarding the problem: Crazy, looking at your isolation of it. 

One thing: Can you try export your timezone as CEST - you have currently pacific daylight time (PDT).

Unfortunately can't do here, messed up the % operator in the leap year modulo function, since I just copied the compiler from github, keen on the nested classes fix, but I think your recent change in % has a counterpart elsewhere - and its late here also...

```
root@localhost ~]# date
Wed Oct 12 01:47:01 CEST 2016
[root@localhost ~]# export TZ=PDT
[root@localhost ~]# date
Tue Oct 11 23:47:10 PDT 2016
```
then running the tests with that again. Maybe your browser somehow 'sees' the system timezone while you have another one in your environment and somewhere sth gets confused due to this.


In general I'm very sorry for the testing quality, did not realize when starting with time that there are so much locale related problems, mainly due to those daylight saving infos delivered. 

Honestly: When I did time, I was looking at transcrypt completely different then I do today  - today I don't bother anymore regarding missing python modules, I don't miss them.
Transcypt imho is ALL about having the Python *mechanics* you implemented so thoroughly  and not about the Python ecosystem.
Its not about getting a python module into the browser - when there is already a good js one present.   Trying to say: Would not be angry if you kick the module, guess there will be more bugs when users with weired settings start testing :-/

**Comment by JdeH** [comment]
Hi,

I'll do the experiments and show you the results.

Also I'll make a pragma for JS behaviour of '%', because it makes it easier to translate JS algorithms into Py ones (and solve backward compatibility problems).

About testing- and library-quality in general: Noting is perfect the first time. That's why feedback via issue's is vital. I'd really like to keep the time module, have more Python modules and gradually make them more complete.

Some reasons:

- They easy the transition for Pythonistas that want to try browser programming.
- They ease porting of CPython-only apps.
- They're suitable for education. Even the humble turtle module.
- Since they're optional, they don't cause bloat if people use only JS libs.
- Often they have a nice, pythonic API, resulting in clean code using them.

Having said that: Python libs are not central to the concept of Transcrypt, while standing with two feet firmly in the JS world is. But I'd like to make it usable for as many developers as possible without compromising compactness and speed: Front-end web, back-end, scientific computing and plotting, education etc. Having a broad user base will help it to get established by means of the network / synergy effect.

There's of course a continuous spectrum between what to port and what not. Currently I don't consider it worthwhile to make a pythonic API for plotly.js. Using it as-is is better, if only for the fact that plotly's native documentation will apply in that case.

On the other hand, something like Numscrypt can be useful. There are quite some JS numerical processing libs around, but they all suffer from verbose notation, given the limitations of JS.

And then there are 'elementary' operations like `<string>.replace` etc. They can be done in JS as well, but I must say I greatly prefer to have the Python versions at hand.

**Comment by AXGKl** [comment]
100% with you that the elementary operations of the basic python types are what EVERY transcrypt user want to use.

Everything else is (really) nice to have - as long as it is not bloating the js and it doesn't. I'll take your highlevel statements into my talk, they summarize very well the vision behind this fantastic tool.

**Comment by JdeH** [comment]
Did `sudo dpkg-reconfigure tzdata` and then change timezone to CEST, which indeed solved the problem.
Seems that VMWare player mixes up host time (Windows, CEST) and guest time (Linux, was PDT).
So Python uses one and Chrome uses the other.
