### ISSUE TITLE
Can't use the key 'keys' in a dict

### ISSUE THREAD

**Issue by fzzylogic** [QQuick/Transcrypt#127]
Hi

Noticed that one can't use the key 'keys' in a dict, purely by accident bcs PouchDB uses an object that includes that key when making certain queries. e.g.

Python 3.5.2 console:

    a = {"include_docs": "true", "keys": ["key1", "key2"], "limit": 50}
    print(a['keys'])

Returns: ['key1', 'key2']

Transcrypted:

    a = {"include_docs": "true", "keys": ["key1", "key2"], "limit": 50}
    # 'keys' key does not actually get created at all, so the next line ought to throw..
    print(a["keys"])

But it returns:
function __keys__() {
var keys = []
for (var attrib in this) {
if (!__specialattrib__ (attrib)) {
keys.push (attrib);
} 
}
return keys;
}

Hope this is useful..

**Comment by JdeH** [comment]
Thanks! Funny... I'll see what can be done about it, probably something with aliases...

**Comment by JdeH** [comment]
Committed and pip-installable as 3.5.232

**Comment by fzzylogic** [comment]
Thanks Jacques!
