### ISSUE TITLE
Metaclasses

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#128]
Hi. 

running a grep in `__metaclass__` with many usages in the new typing module I was for second thinking that you built metaclass support in(?) - but I got no success using them, e.g. `__new__` is never called, no matter if I try py2 or py3 syntax. Also in the compiler for the ClassDef I see no code which would parse a metaclass=... statement.

=> I put this in as an enhancement request, thinking that maybe its not even very hard to support, at least to call their `__new__`  and assign the result of it,  instead of calling the `__class__` function to create a new js "class" ?

**Comment by JdeH** [comment]
Hi Gunther,

I haven't built in any metaclass support, nor thought for a second on how to do that.
To me the are not central to 'classical'  OO as supported by Python.
But that's subjective, if you need them they may be very welcome indeed.

I'll mark this indeed as a possible enhancement. Don't want to give it a high priority now, since there are many other things in the queue (Better js6 support in loops, async/wait, python 3.6 incl. handy string operations etc. Can you indicate how important metaclasses are to you, maybe tell something about your possible use cases.

In general I only want to implement them if:

- They don't significantly slow down or bloat existing code
- They don't add out of proportion complexity

You suggest that they may not be hard to support. That's an interesting remark and may well be true, so I'll sure look into them. But I have to find a suitable time to do that in a thorough manner without time pressure. Since they will be at the very kernel of Transcrypt, if they're done, they'll have to be done right.

**Comment by AXGKl** [comment]
Hi,

I must admit that it sounds like an esoteric use case and hard to do - and 'importance' is always very subjective. In my specific case its the fact that I like to configure complex applications via nested classes, since this is a very readable format, almost like a DSL, exportable trivially to json but with all the features of cross referencing and most of all inheritance - and the python compiler already giving a lot of configuration errors. For this metaclasses are ideal to hook in some consistency checks and a lot of convenience shorthand features - don't want to go to deep into that since its really very subjective.

=> Since I said it might be not so hard I'll have a try to send you a PR when I have some time. As said to not bloat the code only the __new__ would be enough, in order to modify the attributes and base classes in user space.

**Comment by AXGKl** [comment]
Ok, I admit total failure.

With some give time restrictions I find no way to fully grok how to change the class visitor so that he does not built assignments from the class locals but a dict. Sounds simple but I must admit that I don't understand it enough to do it right. I still believe though that for you it would be ... say... at least straight forward.

So: I keep a hack for now where I import the module first in CPython, export the class defs to a string which I feed transcrypt with. Then after the config stuff is done with nested classes I explain you the use case, its about using class based configs for huge config trees, will explain why metaclasses are so handy here (or alternatively the new python3.6 `__init_classdef__` function, which also allows to modify classes programatically) - after having their attributes at hand but before objects are built.

 This I keep as a reminder for me, maybe I try again someday having more time:


![screen shot 2016-10-12 at 18 25 56](https://cloud.githubusercontent.com/assets/9989548/19318565/8504d7fe-90a9-11e6-977f-4a143f7d1224.png)

**Comment by JdeH** [comment]
OK, there's quite some work coming my way so I don't mind postponing it a bit and take a look at it later.
I've moved the repo from a personal account to the QQuick organization, and invited you and 6 regular participants as members.

**Comment by AXGKl** [comment]
thanks for having a look.

What I would love to have is indeed the `__new__`. I don't need `__init__`

Regarding use cases: "python metaclass usecases" in google produces a lot.
I can only give totally subjective examples which is irrelevant for nearly anybody but myself I guess, but you asked ;-)

As you know I like config trees based on classes.

We have config and state.
State is modified all the time and its hard to introspect it and reconstruct it by e.g. test tools, documentation builders, visualizers about the setup...


=> For me personally it proved quite effective the last years to keep (static) config in classes and their attributes (incl. nested classes).
And only state but not config in objects. Config influences state a lot and it is nice to keep the mechanics of that together, i.e. use the same classes to hold config but also process state: In static functions if state is serialized and transferred all the time, and in self's attributes and 'normal' functions, if its a single process: Then the config class itself might be instantiated to hold the state, besides the config.
In any case you can derive from such classes, add your own new config attribute and process its implications in overloaded / new state handling functions of that class. 
In tests you also just import the class tree and can be sure to have the same config than the stuff you test.  Would the config be in objects you never know since there are so many `self` modifying operations possible during the life time of the object that its hard and error prone to reconstruct them in order to know what to test. 

Hope I could motivate why I don't like to have config in objects. 


----

But keeping config in classes would have, without metaclasses, this downside that the application wanting it can't preprocess it before "going live", you don't have that constructor which you can rely on always being run before the thing is delivering functionality to the rest of the world.

But preprocessing *is* required in many situations, e.g. 

- validation: The user configured crap and you want to handle it. => in the metaclass `__new__` you check the validity of the configured attributes. 

- order: The `__new__` is processed in the physical order of the classes in the config module(s). When a config is dumped e.g. to xml the order remains, since you can register the classes in order. The user just expects that B is after A in such a config:
```python
class P(Project):
     class A(Cluster):
           class USWest(Datacenter):
                ....
     class B(Cluster):
            b = 2
```

- exotic stuff: Ok, this is *really* specific: When I have a really deeply nested tree, with a certain topology given, i.e. when A may only be in P but not in B then it makes a lot of sense to first register the hirarchy and then be able to allow this:

```
class A(Cluster, USWest, ....):
class P(Project, A, B): pass

```
which, in the common metaclasses' `__new__` returns a descendant of the first class but ADDS descendants(!) of the other classes in the mro INTO it, as attributes.  NOT inheriting from them. Resulting in sth like the subtree above.

If you want I can go into the details why such a crazy thing is saving a lot of lines of code in config trees. Has to do with the automatic cloning within my metaclass, so a later modification of an attribute, i.e. set the ip address at a node in a datacenter is only changing it for this specific Node but not for all nodes.  No worries for simple hirarchies like Transcrypt's such a thing is not useful at all. But I have a > 20 level deep hirarchy, from Project -> .... Container .... Library Environments .... -> down to client proxy connection TCP port.  
And then this is an pretty effective adapting method to inject specific deviations into a tree, having all the classes basically cloned at each mentioning of them within an mro path. 

With object tree this would be not a problem at all, you always just change the specific object but I hope I could motivate why I don't want object but class trees ;-)

**Comment by JdeH** [comment]
Metaclasses are in the latest commit (3.5.233), using a subset of Python 3.5 syntax, and requiring the __jsiter__ pragma in some cases. Only the type.__new__ is overridable. It proved rather hard, but it passes the testsuite now. @AXGKl: Let me know if this covers your usecase sufficiently. Feel free to reopen.

**Comment by AXGKl** [comment]
whew, finally: managed to get a config parser module with really a lot of 'unusual' python, writting w/o Transcrypt in mind to work *completely*. In Py3, Py2 and Transcrypt, same result, a  nice nested tree of classes ready to be producing nice informational trees, for the app but also the human. 

=> the __new__ is working like a charm, probs where all elsewhere.

Fantastic feature and thanks again for priorising, hope its beneficial for others as well.

**Comment by JdeH** [comment]
Hi Gunther

Politically incorrect? I must have missed something... Probably it's because I don't watch the news to often, it just makes me sad.

It was a pleasure to cooperate with you and others on Transcrypt! Currently I am a bit tied up in a medical research project, but in the second half of januari I hope to be able to free time for TS again.

I wish you and your familiy a happy christmas and new year. We've come a long way in one year. I am contemplating ways to generate some more publicity for Transcrypt.

All the best.
Jacques
