### ISSUE TITLE
Enable mainstream formatting of generated JavaScript

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#129]
Add a compiler switch to generate e.g.

`aFunction( param1, param2 )`

rather than

`aFunction (param1, param2)`

since it will enhance readability of the generated JS to many used to such formatting.
The actual formatting job can be delegated to the Closure compiler.

**Comment by AXGKl** [comment]
i like the idea to customize js output to personal prefs  - but I would not add yet another CLI switch but rather a config dir pointing to my personal .config/transcrypt.py  or .ini and where I can declare all such customizations, there will be more in the future than 'just' the space, I could think of  (with 5 seconds thinkgin):

- supply hook functions you call in compiler js, providing the node and the parent node and they return e.g. the formatting
- supply a list of js libs which should be included in my .html files - always
- supply a list of style sheets which I always want
- when we have strong server coupling: supply the cuppling mechanics and security token (e.g. websocket versus long poll, e.g. jwt tokens and so on.
- supply all command line switches
- supply debug mode on client side (outputting all core.js actions into the console)

(....)

more to follow. Trying to say: Lots of reasons for personal config file ;-)

**Comment by JdeH** [comment]
The config file is a good idea, will put it in the queue as an enhancement.
No harm in adding the CLI switch as well, I think.

**Comment by AXGKl** [comment]
sure, your decision. but don't overdo it, like they:

1.siptrunk_axc.DEV.NB01:/# uwsgi --help |grep '\-\-'  | wc -l
889

with nearly 900 options on the cli it makes things a little bit hard to handle (where are the 1% important ones which 95% nead all the time versus all the rest).

**Comment by JdeH** [comment]
The  nice thing about command line switches is that you can use them ad-hoc rather than editing a file. But indeed it shouldn't be overdone.
Config files are much more readable (but I sometimes have a hard time finding them, especially if there's a hierarchy of them, one overriding the other).
Have to think a bit more about this one.
Main thing for now is that the 'mainstream formatting' gets in.
Many people are very attached to it.

**Comment by AXGKl** [comment]
got it, you know the prios better. 

still: think twice about the single letter, (Transcrypt's entering into phase2): A cli switch is here to stay, you may never change later, it will cause a lot of hate when builds break due to version updates. speaking of my own crimes here (contradicting what  I said yesterday "maybe ditch the time module" ...). 
Ups, I did it again.

**Comment by AXGKl** [comment]
*Config files are much more readable (but I sometimes have a hard time finding them, especially if there's a hierarchy of them, one overriding the other).*

let me guess: ipython incl. the notebook ;-)

**Comment by JdeH** [comment]
About taking away switches and users getting sad or angry...
Yes, I realize that. Backward compatibility is a serious matter.
That also holds for config files, of course.

Still in some occasions backward compatibility isn't perfect.
Changing the % is one example, and it can be prevented.

The nice thing, however is that old versions of Transcrypt remain available (as long as GitHub and PyPi don't vanish).
So no-one can end up with code that doesn't work anymore.

It used to be so that old versions of sofware were nowhere to be had anymore.
So I made it a habit to always store a copy of the tools I used for a certain customer together with the software I made.

Still, as the number of serious users grows, it becomes more and more important to take on compatibility, testing, version control, documentation etc. in a truly professional manner.

**Comment by AXGKl** [comment]
hehe, the recursive extension switch is neat.  and the css joke... scoped css does help a bit, though.

Thought a lot about config machineries in my life but that Idea with the recursive x unfortunately bypassed my brain.  I invested recently a lot of time to make a really good tab completer for long cli options, directly from source code statements, also nested and where you always in the completion process can hit TAB twice and get help from the docstrings - and also it detects options in function signatures so that it can auto complete values as well.
But thats no option here since it depends on bash and transcrypt must run in windows as well.

**Comment by AXGKl** [comment]
Oh and the notebook should be ONE of the server sided components  to be able to sync with transcypt components. They released this widgets, which users can extend, based on very very awkward js to write. Absolutely full match for Transcrypt, believe me. And its a lot used in a community which you personally also seem to have a lot of stakes in still (I left it long ago getting my physics degree, sad sad)

**Comment by JdeH** [comment]
O well, once again I get pressed with my nose upon the fact that I really, really should dive into the IPython notebook. Indeed, I still have stakes in the physics world, due to the cardiology research I am involved in. We're also looking for a way to make the results of non-invasive diagnostics available over the Internet. I am almost certain Transcrypt will play a role there, it's one of my private reasons to embark on it.

**Comment by JdeH** [comment]
This issue is postponed since Google Closure currently can't prettify without leaving out the comments, thus making the code less readable...
Will post a feature request.
