### ISSUE TITLE
`%=` operator translated incorrectly

### ISSUE THREAD

**Issue by daboross** [QQuick/Transcrypt#134]
After https://github.com/QQuick/Transcrypt/commit/20894a72e0f2a1f7229a0c760ef83a20cc777050, a `x %= y` operation has been translated to the JavaScript code `x None= y`, which is probably incorrect.

Test case:
```python
x = 5
x %= 10
print(x)
```

`main.mod.js`:
```javascript
	(function () {
		var x = 5;
		x None= 10;
		print (x);
		__pragma__ ('<all>')
			__all__.x = x;
		__pragma__ ('</all>')
	}) ();
```

Expected result:
```javascript
	(function () {
		var x = 5;
		var x = __mod__ (x, 10); // or just `var x %= 10`
		print (x);
		__pragma__ ('<all>')
			__all__.x = x;
		__pragma__ ('</all>')
	}) ();
```

**Comment by JdeH** [comment]
Probably incorrect ;)

**Comment by JdeH** [comment]
Committed and pip-installable as 3.5.232
