### ISSUE TITLE
dict.get(key[, default]) not implemented ?

### ISSUE THREAD

**Issue by fabien-michel** [QQuick/Transcrypt#136]
dict.get seems to not being implemented.
I suppose this is a choice, but it is useful when a default value is needed. There is a recommended code replacement ?

```python
choices = {
    'a':1,
    'b':2,
    'c':3
}

choices.get('d', 4) # => TypeError: choices.get is not a function
```

**Comment by JdeH** [comment]
Thanks for the suggestion, dict.get will be added in the next commit.

**Comment by JdeH** [comment]
Committed and pip-installable as 3.5.232
