### ISSUE TITLE
Parse error using 'yield' in an expression

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#138]
The following code gives an Parse error. primary expression expected:

```
def test():
    r = 0
    while True:
        r = r + (yield r)
```
There is no error if it is changed to:
```
def test():
    r = 0
    while True:
        r = (yield r) + r
```

**Comment by JdeH** [comment]
Thanks!

**Comment by JdeH** [comment]
Seems that CPython doesn't support (yield r) being evaluated as a value.
The CPython parser, which is also used by Transcrypt, doesn't catch this.
It is only caught at runtime it seems.

So CPython can't run the following:

```
def testYieldL (limit):
	r = 0
	while r < limit:
		r = (yield r) + r

for r in testYieldL (7):
	print (r)
```

It complains with:

`TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

The value of (yield r) seemingly is None.
So it seems Transcrypt shouldn't support these constructs as well, if it is to be compatible with CPython.

By the way, when trying to compile this fragment with Transcrypt, the parser complaining is Google Closure, translating JS to JS, not Transcrypt.

Would be nice if Transcrypt complained, but since even CPython doesn't at parse time, I think it's relatively hard to have Transcrypt improve on that.

My proposal is to drop this, as it is a limitation of CPython.
What do you think?

**Comment by pjbonestroo** [comment]
I think the problem with your example is that you don't send any value into the generator, but it needs an value (an 'int').
The following works in Python and will print values 1 and 3:
```
def test():
    r = 0
    while True:
        r = r + (yield r)

gen = test()
next(gen)
print(gen.send(1))
print(gen.send(2))
```
If I try to make the same for compiling to Javascript I would write:
```
def test():
    r = 0
    while True:
        r = r + (yield r)

gen = test()
gen.js_next()
console.log(gen.js_next(1).value)
console.log(gen.js_next(2).value)
```
but then I get the Parse error. primary expression expected.

If I change the generator in this example to:
```
def test():
    r = 0
    while True:
        r = (yield r) + r
```
it will compile. But it prints the values 2 and 4, instead of 1 and 3!
If I look to the generated javascript things get clear:
```
var test = function* () {
    var r = 0;
    while (true) {
        var r = yield r + r;
    }
};
```
The javascript generator is not as it should be:
```
var test = function* () {
	var r = 0;
	while (true) {
		var r = (yield r) + r;
	}
};
```

Kind regards,
Pieter Jan Bonestroo

**Comment by JdeH** [comment]
Hi,

Thanks for your clear analysis and suggestions.
The parsing errors were easy to solve, but really I need some help with this...

If I run the following code

```
		var test0 = function* () {
			var r = 0;
			while (true) {
				var r = r + (yield r);
			}
		};
		var gen0 = test0 ();
		gen0.next ();
		console.log (gen0.next (1).value);
		console.log (gen0.next (2).value);
		var test1 = function* () {
			var s = 0;
			while (true) {
				var s = (yield s) + s;
			}
		};
		var gen1 = test1 ();
		gen1.next ();
		console.log (gen0.next (1).value);
		console.log (gen0.next (2).value);
```

on http://math.chapman.edu/~jipsen/js/ it prints:

1
3
4
5

While the following Python code

```
from org.transcrypt.stubs.browser import __pragma__
__pragma__ ('gsend')

def test0 ():
	r = 0
	while True:
		r = r + (yield r)

gen0 = test0()
next (gen0)
print (gen0.send (1))
print (gen0.send (2))

def test1 ():
	r = 0
	while True:
		r = (yield r) + r

gen1 = test1()
next (gen1)
print (gen1.send (3))
print (gen1.send (4))

```
used with CPython prints:

1
3
3
7

Could you help me understand what causes this difference between JS code and comparable Python code.

**Comment by JdeH** [comment]
Example in iterators_and_generators testlet of transcrypt autotest.
Note the pragma, to enable a nice notation.
Only use that locally, since there may be different, user defined, send methods on other classes.
However since Python has dyn typing there's no predicting what a var may contain (roughly speaking).

	__pragma__ ('gsend')

	def test0 ():
		r = 0
		while True:
			r = r + (yield

	gen0 = test0()
	next (gen0)
	autoTester.check (gen0.send (1))
	autoTester.check (gen0.send (2))

	def test1 ():
		r = 0
		while True:
			r = (yield r) + r

	gen1 = test1()
	next (gen1)
	autoTester.check (gen1.send (3))
	autoTester.check (gen1.send (4))

CPython and Transcrypt output are identical now.

**Comment by pjbonestroo** [comment]
In my opinion it should be possible for Transcrypt to compile
```
def test():
    r = 0
    while True:
        r = (yield r) + r
```
to 
```
var test = function* () {
    var r = 0;
    while (true) {
        var r = (yield r) + r;
    }
};
```
Why is that not possible? Am I missing something?
I think the main problem is that Transcrypt omits the parentheses, causing either incorrect behavior or an parse error.
During compilation it should just copy the parentheses from the Python source to the javascript destination, right?

Kind regards,
Pieter Jan

**Comment by JdeH** [comment]
Hi,

It all should work properly now, after yesterday's commit.
Can you confirm?

KR
Jacques

**Comment by pjbonestroo** [comment]
Hello,


I think your examples in the mail below are different. They both behave as expected to me.

You should have as javascript code (bold are differences from your code):


var test0 = function* () {
    var r = 0;
    while (true) {
        var r = r + (yield r);
    }
};
var gen0 = test0 ();
gen0.next ();
console.log (gen0.next (1).value);
console.log (gen0.next (2).value);
var test1 = function* () {
    var s = 0;
    while (true) {
        var s = (yield s) + s;
    }
};
var gen1 = test1 ();
gen1.next ();
console.log (gen1.next (1).value);
console.log (gen1.next (2).value);


This will print (as expected):

1

3

1

3


If you have this in Python you get (again, bold is different from your code):


def test0 ():
    r = 0
    while True:
        r = r + (yield r)

gen0 = test0()
next (gen0)
print (gen0.send (1))
print (gen0.send (2))

def test1 ():
    r = 0
    while True:
        r = (yield r) + r

gen1 = test1()
next (gen1)
print (gen1.send (1))
print (gen1.send (2))


And again you will see:

1

3

1

3


So I think there are no differences between javascript and python code.


Kind regards,

Pieter Jan Bonestroo



________________________________
Van: Jacques de Hooge <notifications@github.com>
Verzonden: zondag 30 oktober 2016 16:34
Aan: QQuick/Transcrypt
CC: pjbonestroo; Author
Onderwerp: Re: [QQuick/Transcrypt] Parse error using 'yield' in an expression (#138)


Hi,

Thanks for your clear analysis and suggestions.
The parsing errors were easy to solve, but really I need some help with this...

If I run the following code

        var test0 = function* () {
            var r = 0;
            while (true) {
                var r = r + (yield r);
            }
        };
        var gen0 = test0 ();
        gen0.next ();
        console.log (gen0.next (1).value);
        console.log (gen0.next (2).value);
        var test1 = function* () {
            var s = 0;
            while (true) {
                var s = (yield s) + s;
            }
        };
        var gen1 = test1 ();
        gen1.next ();
        console.log (gen0.next (1).value);
        console.log (gen0.next (2).value);


on http://math.chapman.edu/~jipsen/js/<http://math.chapman.edu/%7Ejipsen/js/> it prints:

Online JavaScript Interpreter - Chapman University<http://math.chapman.edu/~jipsen/js/>
math.chapman.edu
Comment // this is a one-line comment /* this comment could contain linebreaks */ Constant: numbers 12.3 and strings "hi", "hi".charAt(0) is "h" Variable



1
3
4
5

While the following Python code

from org.transcrypt.stubs.browser import __pragma__
__pragma__ ('gsend')

def test0 ():
    r = 0
    while True:
        r = r + (yield r)

gen0 = test0()
next (gen0)
print (gen0.send (1))
print (gen0.send (2))

def test1 ():
    r = 0
    while True:
        r = (yield r) + r

gen1 = test1()
next (gen1)
print (gen1.send (3))
print (gen1.send (4))



used with CPython prints:

1
3
3
7

Could you help me understand what causes this difference between JS code and comparable Python code.

-

**Comment by pjbonestroo** [comment]
Hi Jacques,

Yes, I can confirm! Thank you very much!
I really like Transcrypt and will definitely continue using it.

Kind regards,
Pieter Jan

**Comment by JdeH** [comment]
Glad to hear that!
If you ever make something publicly accessible that we can link to from the site as a showcase, please let me know.

KR
Jacques
