### ISSUE TITLE
Possibility to yield from (delegating subgenerator)

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#139]
It would be great to have the possibility to **yield from** (Syntax for Delegating to a Subgenerator). Python's **yield from** should be compiled to javascript **yield***.
It is just an idea, and I have no idea how complex it is to achieve.

**Comment by JdeH** [comment]
Thanks, will look into this.

**Comment by JdeH** [comment]
I've committed this as experimental. Could you take a look whether this covers your use cases?

KR
Jacques

**Comment by pjbonestroo** [comment]
This is what I was hoping for. Thanks!
