### ISSUE TITLE
Command-line --help / -h switch broken

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#140]
In honor of Murphy, who was right afterall (If anything is not in the shipment test, it will break).
It's the *$#@!!! % in the explanation of the -jm switch...
Will be repaired and in the shipment test in next commit.

**Comment by AXGKl** [comment]
stupid % , arg..

now i'm feeling *really* bad about the delay of the config mod :-/ 

I would prio this high, since it made it also into the pip distri, and people will hopefully try it after tomorrow.

**Comment by AXGKl** [comment]
this is really superhigh prio, again : it is in the pip install transcrypt version (!) *will* cause immediate run away effects, I would fix it first, and only after that think about how to include in tests.

**Comment by JdeH** [comment]
I've committed the fix already yesterday, so it should be no problem!

**Comment by AXGKl** [comment]
whew, so delighted. 

including the test...your productivity is so amazing.

**Comment by JdeH** [comment]
There's a new medical research project coming up for me though,
So the coming months I'll really have to concentrate upon the language core.
