### ISSUE TITLE
print sync. when in debugger

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#141]
Assignining this one to myself, to not forget:

When in debugging ("foreground") mode (i.e. after a debugger statement) then `print('foo')` should not do the `setTimeout (printAsync, 5)` dance.
There is no debugging output otherwise while stepping through code with print functions, due to the current single threaded nature of js in the browser.  There should be a way to know if we are in that mode and then console.log directly.

**Comment by AXGKl** [comment]
oh, seeing that I can't assign to myself...

**Comment by JdeH** [comment]
Seems you're not the only one missing his permission level:

https://github.com/isaacs/github/issues/268

For now, I am afraid you can't.
So I will upon request, a.s.a.p.

**Comment by JdeH** [comment]
Some explanation (on what you probably already understood). The code below:

```
        self.element = document.getElementById ('__terminal__')

        ....
        ...
        ....

	def print (self, *args, sep = ' ', end = '\n'):
		def printAsync ():
			if self.element:
				self.buffer = '{}{}{}'.format (self.buffer, sep.join ([str (arg) for arg in args]), end) [-4096 : ]	
				self.element.innerHTML = self.buffer.replace ('\n', '<br>')
				self.element.scrollTop = self.element.scrollHeight
			else:
				console.log (sep.join ([str (arg) for arg in args]))
		setTimeout (printAsync, 5)
```

does the following:

- As the DOM tree may not yet be ready, it waits a wile and then looks if there indeed was an element with id '__terminal__'. If there was, print to that element, else print to the console.

Indeed without threads it doesn't print to the console in debugging mode. Would be nice if you could improve that.

By the way, also the interaction with the `input` function is a unsatisfactory. I can very well live with the fact that prompts are done in a separate dialog, after all console input isn't a mainstream thing to do in a web GUI. Just wanted students to make simple console style programs to practice without the complexity of event driven GUI's.

But currently the prints are only done, once all the inputs are answered to (../demos/terminal_demo). I tried to solve this but couldn't find a simple, robust solution. It's still on my mental to-do list. To my memory this first worked correctly, it probably fell over when I introduced to asynch printing.

Of course an other inroad would be to just run a script if the DOM tree is ready. But as the script may modify the DOM tree, this isn't robust as well, so I came up with the rather ugly setTimeout 'solution'. Any hints to better ways of tackling this, without bloat or depence upon complicated 3rd party stuff would be welcome...

**Comment by AXGKl** [comment]
will have a look, after done the talk tomorrow and after checked in the config mgr. 
since you seem to be online: 

I have a hacky way to do it via try except but whats the official way to detect that I'm in the browser (i.e. without the sys module) ? would like to show how an isomorphic module could be written with server only, browser only code, and the rest for both.

**Comment by JdeH** [comment]
To find out if you're in the browser:

```
from org.transcrypt.stubs.browser import __envir__

...
...
...

if __envir__.executor_name == __envir__.transpiler_name:
    ...
    ...
else: 
    ....
    ....

```

**Comment by AXGKl** [comment]
argh, sure, where else, thats where __pragma__ is also, clear ;-)

another one where you could quickly remind me:

was digging through old versions as well but this:


```python
def run():
    a = [1,2,3]
    alert(a[-1])
```
was always undefined(?) 

Is there a pragma I'm missing to get `mylist[-1]` working ?

**Comment by AXGKl** [comment]
ups. https://github.com/QQuick/Transcrypt/issues/33  sorry, forget the a[-1]

**Comment by JdeH** [comment]
I'll reopen #33 as 'under consideration'
