### ISSUE TITLE
Offline link in documentation

### ISSUE THREAD

**Issue by Tamriel** [QQuick/Transcrypt#142]
In https://github.com/QQuick/Transcrypt/blob/master/transcrypt/docs/sphinx/integration_javascript.rst
is says 'As an alternative, responsiveness can simply be programmed using Transcrypt, as can be seen on this site written in Transcrypt.' but that side is offline.

**Comment by JdeH** [comment]
Thank you!
Indeed wiskundeles.com is currently off-line since the owner wanted to change the concep of his services.
I'll change it in the docs.

Kind regards
Jacques

**Comment by JdeH** [comment]
After consulting with the owner I've put the site on-line again.
