### ISSUE TITLE
`isinstance` deserves more compat

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#143]
```
simpletypes = (int, float, bool, str)
isinstance(1, simpletypes)
isinstance('a', simpletypes)
isinstance(1.1, simpletypes)
isinstance(True, simpletypes)
```

all fail with

``````
``` Uncaught TypeError: Cannot use 'in' operator to search for '__class__' in a(…)isinstance @ ```
``````

because of 

```
        return '__class__' in anObject ? isA (anObject.__class__) : anObject instanceof classinfo;
```

I think there could be simple typeof checks before the  `'__class__' in anObject` check

can be assigned to me (low prio, simple)

**Comment by JdeH** [comment]
I would welcome if you look into this
It's something that you'd have to run through the shipment test (= manual tests + automated tests) since, while maybe in itself not too complicated, it may make some things fall over in subtle ways.

**Comment by AXGKl** [comment]
see latest PR. 

it is still not complete but is covering the 95% I guess.

**Comment by JdeH** [comment]
Problem with es6 and Closure. Not yet clear what...

**Comment by AXGKl** [comment]
oh, so the autotester has to be run with different js compile switches? which ones do you use normally?   

just tried: 

/Users/klessinger/GitHub/AXGKl\:Transcrypt/transcrypt/run_transcrypt -bn -e 6 autotest.py 

works as well, same result than cpython. can I have your output ?

**Comment by JdeH** [comment]
The switches are those used in shipment_test.py.
From the head -e 6 and -f. (apply the -e 6 switch also in combi with the -r switch)
Also the .js and the .min.js files are tested.

**Comment by AXGKl** [comment]
understood regarding the test procedure:

- e 5 and -e 6 
- -f and no -f
- min and normal

-> 8 combinations.

just pulling the jre, never use min I must admin...

----

Another thing I must admit: Testing isinstance I deleted all tests except classes - since I have a failure: Uncaught ReferenceError: complex is not defined(…) , var a = __add__ (234, complex (0, 3.0));  , thought the tests are currently not running, and isinstance is not used in any other test => thought its safe to only test classes.

I  do not see a change of classes/__init in the current head. 

When I do run_transcrypt -bn -e 6 -f autotest.py with 

```python
~/GitHub/AXGKl:Transcrypt/transcrypt/development/automated_tests/transcrypt $ cat autotest.py 
from org.transcrypt.stubs.browser import __pragma__
import org.transcrypt.autotester
import classes
autoTester = org.transcrypt.autotester.AutoTester ()

autoTester.run (classes, 'classes')
autoTester.done ()
```

it works with all 4 switch combis except the 4 for min.

**Comment by JdeH** [comment]
Autotest also requires -c and -da switch.
But if you run the shipment-test its all done for you: python3.5 shipment_test.py -d -c -f in its most complete form (or on windows python35 I believe).
It will even open browser windows for you.
It requires node.js to be installed, because some tests are about node.

**Comment by JdeH** [comment]
Don't invest too much trouble in repairing isinstance, think I'm close to a solution (ever optimistic...)

**Comment by JdeH** [comment]
Seems to work now. Will be in next commit. I've used your autotest, which was quite effective.

One improvement that I directly took from your sourcecode, is the fact that classinfo can also be a tuple, rather than a single class. Had never noticed that.

Another  improvement that was in your source code, is to account for the fact that isinstance (True, int) is True.

Another piece of the puzzle  is that I had to look to the  type (so py_typeof) and isinstance functions together. Because my py_typeof had problems, implementing isinstance was needlessly difficult. Now they're both improved.

**Comment by AXGKl** [comment]
and again we witness my ability to judge time and effort required : "can be assigned to me (*low prio*, **simple**)".

travis I also thought costs me an hour or so. argh..

**Comment by JdeH** [comment]
My experience is that effort estimates only work if I'm doing the same trick over and over again.
With anything new its completely uncertain.
And the more 3rd party products you depend upon, the more uncertain it gets.

So if you say you cannot estimate efforts, you're in fact telling me:
I am not the person who sells the promises, but the person who in the end has to fulfill them.

**Comment by AXGKl** [comment]
you are one year older: did you find a way to explain your wife why you picked the second camp ;-) ?

**Comment by JdeH** [comment]
Well, she has been working in IT too, from programmer to project manager for I think some 20 years. But rightnow she teaches classical languages. However, she still understands...

**Comment by AXGKl** [comment]
tell her dankewell from munich ;-)
