### ISSUE TITLE
list sorting

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#145]
Hi, I found some strange sorting problem. Here is example code:

```
def randomword(length):
    possible = 'abcdefghijklmnopqrstuvwxyz'
    text = ''
    for i in range(8):
        text += possible[Math.floor(Math.random() * possible.length)]
    return text


class SortTest:
    def __init__(self):
        self.rows = []
        for i in range(15):
            words = []
            for j in range(6):
                word = randomword(8)
                words.append(word)
            self.rows.append(words)

    def sort(self, column):
        self.rows.sort(key=lambda x: x[column])
        for r in self.rows:
            console.log(','.join(r))


st = SortTest()
st.sort(0)
```

and results are:
```
uajijtol,ojwhesef,zszfbnhs,bqvuefhc,ttyhodsw,hpsrwvzz
ofuilnor,darwzmkn,gstsyhjc,xytsxrag,hyovwwnj,hozoqhxy
kjvlfdik,erudyumj,fesroitj,gwerepbx,fkegangf,nzdnvrmu
duhojenp,aunpfjxa,rzlthcon,ognknizm,juqqxvuu,ycqlhmcr
migszoud,dsdwqbar,vsvbhjja,tmfsxcyx,phizywqi,kpsqgtkm
agyafqik,rqfltczq,wcdrdqev,mkdpngtr,hjvxokza,pvdfjnhl
lqetemtn,tmojnpwp,irfhqwdl,bcfrltjn,lrytyquz,jpiiovfk
lnhvkgem,tckeulwn,wpbwcquf,kfhtaqrf,yfeuauhr,uhetnape
fdgjcdnv,ttbywgzb,sggokqxf,wmgyyymw,gbdtzqmf,gkwoywyn
dwxlhpyn,ysgziqef,rwrczgge,dotjdmql,kbxcogng,kklyonho
rgtpqatb,vkmnewjn,kjaifmju,oexdqzrd,xfwvoewd,kwbwzxew
vkmgmwmb,mmerkkaj,ecoqyfhy,dxrxpxzw,jjfanigq,tobikfdp
vsoygdri,eumfkkaf,uwnndgrb,wpewlyeq,khmpyeac,axggqnno
yemvihnh,jhkneeqn,dlkajhgq,btnopzwv,nhrijdgh,sdwduptw
zfrzgiqs,awxboqrm,cwcunmsu,blfistjm,lhrogond,hmcghugk
```

As you see, the rows are not sorted by the first column. The strange thing is when I lower generated rows to 10 or less, results are always correct.

**Comment by neriusmika** [comment]
And there is a bug in `__sort__` function. Now comparison function returns:
`return key (a) > key (b);`
But it must return:
```
if (key (a) < key(b)) {
    return -1;
} else if (key (a) > key (b)) {
    return 1;
} else {
    return 0;
}
```
When I changed javascript by hand, it works as expected.

**Comment by JdeH** [comment]
By 'it works as expected', you mean that the results of your SortTest are now OK (with you hand coded JS)?

KR
J

**Comment by neriusmika** [comment]
Yes.

**Comment by JdeH** [comment]
Thank you for your finding out what causes this problem!
I'll add it to the autotest and your solution will most likely be in the next commit.

**Comment by neriusmika** [comment]
btw, there is an array comparison function example in mdn:
```
function compare(a, b) {
  if (a is less than b by some ordering criterion) {
    return -1;
  }
  if (a is greater than b by the ordering criterion) {
    return 1;
  }
  // a must be equal to b
  return 0;
}
```
it must return 1, -1 or 0

**Comment by neriusmika** [comment]
Ok, thanks

**Comment by neriusmika** [comment]
PS. of course we can keep one-liner
`return key (a) < key(b) ? -1 : key (a) > key (b) ? 1 : 0;`

**Comment by JdeH** [comment]
Yes, for speed and compactness sake we should

**Comment by JdeH** [comment]
Correction: oneliner would mean calling key (a) and key (b) twice, could be expensive. So will cache outcomes of key func.

**Comment by JdeH** [comment]
Correction 2:

For a stable sort, the case key (a) == key (b) turns out to be irrelevant.
Modifying the compare function to:

lambda a, b: 1 if key (a) > key (b) else -1

results in a stable multicolumn sort with 5000 rows, 10 columns and words of 10 chars.

I may have overlooked something, so please correct me if I'm wrong.
The fix will be in the next commit.

**Comment by neriusmika** [comment]
Yes, probably it doesn't matter if comparables are equal. Maybe internally it takes more steps, but final sorting result will be the same.

**Comment by JdeH** [comment]
Fix has been committed, not yet in pip-installable.
For now have taken the gamble that the performance benefit of the simple compare function outweights possible extra iterations in sorting.

KR
J
