### ISSUE TITLE
Update descendants when parent class is modified / __getattr__ support

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#146]
I guess this one is not possible but maybe you have an idea:

```python
class A:
    a= 1
class B(A):
    pass

A.a = 2

alert(B.a) -> still 1
```

unsolvable I guess.

If we wanted to support it:

Should we keep a list of all descendants of a parent? Guess no in the general case, garbage collection defunct then.

Should we allow it 'excaptionally', i.e. via some declaration, like: This class' changes are affecting inheriting ones? For my use cases I think this one is doable via the new metaclass feature, rite? I could have `A` be a 'descendant registering class' and then at least allow a patched `setattr` where I scan through all descendants.

Maybe just confirm that its not possible and if its not in the docu we should add it to the limitations section, imho.

**Comment by JdeH** [comment]
Wow, 


Using a kind of update chain means too much complexity.
And making B.a a mere reference to A.a would be easy in C++, but require unreadable trickery in JavaScript.
Indeed I am afraid, we'll have to forget about this one and put it in the docs as a limitation.

And indeed I think your metaclass solution would work, I think.

**Comment by AXGKl** [comment]
Just for the records:

> Should we keep a list of all descendants of a parent? Guess no in the general case, garbage collection defunct then.

that was terribly stupid.

Naturally, the real way to do it would be by supporting getattr and there is already a ticket:

https://github.com/QQuick/Transcrypt/issues/89


If you pass, in a local pragma, attribute gets into a function, then the superclass scanning would be a piece of cake ;-)

**Comment by JdeH** [comment]
Have not yet completely thought this throught, but indeed I think \_\_setattr\_\_ / \_\_getattr\_\_ are the way to go. Only they will have to be controlled by a pragma, otherwise they will unacceptably slow down the whole thing.  Also they shouldn't generate to much code, but I think that's doable. I'll bump prio of #89 to "should have" and assign it to myself, since it's very much in the core.

**Comment by AXGKl** [comment]
nice !

**Comment by JdeH** [comment]
Indeed proxies make this possible.
It'll be in the next commit :)

**Comment by JdeH** [comment]
Done

**Comment by AXGKl** [comment]
Impressive.
