### ISSUE TITLE
problem with __include__ and special character inside js

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#151]
Hi, I tried to encapsulate redux, but it failed to load javascript file with `__include__`. The problem is that inside js file is “ character (http://www.codetable.net/decimal/8220). You can try to include https://cdnjs.cloudflare.com/ajax/libs/redux/3.6.0/redux.js

**Comment by AXGKl** [comment]
Hi, 

I honestly don't understand "failed to load javascript file with __include__"

maybe this helps, thats how I wrapped redux within Transcrypt, forget the other stuff but redux worked like that, incl. the browser extension:

https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/ch6_reactive_redux.md

source:

https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/src/ch6/pykendo.py

with a direct inclusion of this redux version via stupid script tags:

https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/src/lib_pro/3rd/redux.js

**Comment by neriusmika** [comment]
But I want to encapsulate it, like fabric.js in transcrypt (without loading it via `<script src=...>`). Like this:
```
__pragma__('noanno')

redux = __pragma__('js',
    '''
(function () {{
    var exports = {{}};
    {}	// Puts redux in exports
    return exports;
}}) ().Redux;
    ''',
    __include__('redux/__javascript__/redux.js')
)
```
And later I can use:
```
from redux import redux
redux.createStore() etc...
```
But the problem is that transcrypt compilation fails, when inside javascript file is that special character. You can even put that single character in empty file and it fails to compile.

**Comment by neriusmika** [comment]
And after removing that single character from redux.js (it's in comments anyway) it works correctly.

**Comment by neriusmika** [comment]
Ok, I found that the cause of the error is encoding. In python 3 function `open` uses locale encoding, so I'm getting UnicodeDecodeError. Changing the line in compilers include function to `return open (filePath, encoding='utf-8') .read ()` fixes that problem.

**Comment by AXGKl** [comment]
@neriusmika : nice finding (and @JdeH : an important fix).

sidenote: Can't tell you how much I hate the unicode sandwhich idea of Py3...  Py2 with defaultencoding utf-8 was paradise.

**Comment by JdeH** [comment]
Great, thanks!

**Comment by JdeH** [comment]
Commited the proposed WITHOUT ANY TESTING.
Could you confirm that the problem is solved.
(Or that everything has blown up...)

**Comment by neriusmika** [comment]
Yes, with that encoding parameter compiler works without errors. Also tested last fixes with sorting and comprehensions with overloading. Everything is ok. Thank you.

**Comment by JdeH** [comment]
Thanks for the feedback!
