### ISSUE TITLE
Simple html5 canvas example

### ISSUE THREAD

**Issue by punkdit** [QQuick/Transcrypt#152]
Trying to get a simple html5 canvas example to work.
I tried putting this in example.html:

```
<html>
   <head>
     <title>Canvas element size: 600 x 300, Canvas drawing surface size: 600 x 300</title>

      <style> 
         body {
            background: #dddddd;
         }

         #canvas {
            margin: 10px;
            padding: 10px;
            background: #ffffff;
            border: thin inset #aaaaaa;
         }
      </style>
   </head>

  <body>
    <canvas id='canvas' width='600' height='300'>
      Canvas not supported
    </canvas>

    <script src='__javascript__/example.js'></script>
  </body>
</html>
```

and then this in example.py:

```
canvas = document.getElementById('canvas'),
context = canvas.getContext('2d');
   
context.font = '38pt Arial';
context.fillStyle = 'cornflowerblue';
context.strokeStyle = 'blue';

context.fillText("Hello Canvas", canvas.width/2 - 150,
                                 canvas.height/2 + 15);

context.strokeText("Hello Canvas", canvas.width/2 - 150,
                                   canvas.height/2 + 15 );
```

It compile fine to js, and the web browser shows a canvas, but it's empty.
Any ideas?

The pong demo is nice, but it would be good to see something simpler.

EDIT: the mistake is caused by a stray comma in the first line.

**Comment by neriusmika** [comment]
For me it's working and text is visible on the canvas
index.html:
```
<html>
<head><title>Canvas element size: 600 x 300, Canvas drawing surface size: 600 x 300</title>
  <style>
    body {
      background: #dddddd;
    }

    #canvas {
      margin: 10px;
      padding: 10px;
      background: #ffffff;
      border: thin inset #aaaaaa;
    }
  </style>
</head>
<body>
<canvas id='canvas' width='600' height='300'>Canvas not supported</canvas>
<script src='__javascript__/geometry.js'>
</script>
</body>
</html>
```
geometry.py:
```
canvas = document.getElementById('canvas')
context = canvas.getContext('2d')

context.font = '38pt Arial'
context.fillStyle = 'cornflowerblue'
context.strokeStyle = 'blue'

context.fillText('Hello Canvas', canvas.width / 2 - 150, canvas.height / 2 + 15)
context.strokeText('Hello Canvas', canvas.width / 2 - 150, canvas.height / 2 + 15)
```

**Comment by JdeH** [comment]
@punkdit

The pong example works via fabric.js just to demo the lib, which is indeed overkill.
The most beautiful graphics are achieved by SVG, which is used in the turtle module, as demoed at:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

Select the 'mandala' example to see what can be achieved.
The source of the turtle module shows how to use SVG, its at:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/turtle/__init__.py

Unfortunately there's no simple canvas demo yet.

KR
J

**Comment by JdeH** [comment]
@punkdit

The pong example works via fabric.js just to demo the lib, which is indeed overkill.
The most beautiful graphics are achieved by SVG, which is used in the turtle module, as demoed at:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

Select the 'mandala' example to see what can be achieved.
The source of the turtle module shows how to use SVG, its at:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/turtle/__init__.py

Unfortunately there's no simple canvas demo yet.

KR
J

**Comment by JdeH** [comment]
@punkdit

The pong example works via fabric.js just to demo the lib, which is indeed overkill.
The most beautiful graphics are achieved by SVG, which is used in the turtle module, as demoed at:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

Select the 'mandala' example to see what can be achieved.
The source of the turtle module shows how to use SVG, its at:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/turtle/__init__.py

Unfortunately there's no simple canvas demo yet.

KR
J

**Comment by JdeH** [comment]
@punkdit

The pong example works via fabric.js just to demo the lib, which is indeed overkill.
The most beautiful graphics are achieved by SVG, which is used in the turtle module, as demoed at:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

Select the 'mandala' example to see what can be achieved.
The source of the turtle module shows how to use SVG, its at:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/turtle/__init__.py

Unfortunately there's no simple canvas demo yet.

KR
J

**Comment by neriusmika** [comment]
That's not my example, I just cleaned the code and it worked :) Btw now I'm writting some riot/react clone, but based on snabbdom vdom. It's working great already, but code is messy while still testing various things. When I finish, you can add it to examples too.

Some example components:
```
class Page(Tag):
    
    def before_mount(self):
        Tag.before_mount(self)
        self.navigation = Navigation(
            {'tree': [
                {'title': 'first'},
                {'title': 'second'},
                {'title': 'submenu',
                 'children': [
                     {'title': 'sub1'},
                     {'title': 'sub2'},
                     {'title': '--'},
                     {'title': 'refresh table',
                      'selected': self.refresh_table
                     }
                 ]}
            ],
            'selected': self.menu_selected
            }
        )
        self.clock = Clock()
        self.table = AjaxTable({'url': '/table'})
        self.autocomplete = Autocomplete({
            'choices': [
                'Apple', 'Apricot', 'Banana', 'Bilberry', 'Blackberry', 'Blackcurrant',
                'Blueberry', 'Boysenberry', 'Cantaloupe', 'Currant', 'Cherry', 'Cherimoya', 'Cloudberry', 'Coconut',
                'Cranberry',
                'Damson', 'Date', 'Dragonfruit', 'Durian', 'Elderberry', 'Feijoa', 'Fig', 'Goji berry', 'Gooseberry',
                'Grape',
                'Grapefruit', 'Guava', 'Huckleberry', 'Honeydew', 'Jackfruit', 'Jambul', 'Jujube', 'Kiwi fruit',
                'Kumquat', 'Lemon',
                'Lime', 'Loquat', 'Lychee', 'Mango', 'Marion berry', 'Melon', 'Rock melon', 'Miracle fruit',
                'Mulberry', 'Nectarine', 'Olive', 'Orange', 'Clementine', 'Mandarine', 'Blood Orange', 'Tangerine',
                'Papaya',
                'Passionfruit', 'Peach', 'Pear', 'Bartlett pear', 'Persimmon', 'Physalis', 'Plum', 'Pineapple',
                'Pomegranate', 'Pomelo',
                'Purple Mangosteen', 'Quince', 'Raspberry', 'Rambutan', 'Redcurrant', 'Salal berry', 'Salmon berry',
                'Satsuma',
                'Star fruit', 'Strawberry', 'Tamarillo', 'Ugli fruit', 'Watermelon'
            ], 'min': 1, 'mode': 'contain'
        })

    def render(self):
        nav = t(self, self.navigation)
        clock = t(self, self.clock)
        auto = t(self, self.autocomplete)
        table = t(self, self.table)
        __pragma__('opov')
        btn = e.button('Refresh', onclick=self.clicked, class_='btn btn-primary btn-xs')
        div = e.div(nav, clock, auto, btn, table)
        __pragma__('noopov')
        return div.vnode

    def clicked(self):
        self.table.load_data()

    def menu_selected(self, item, e):
        console.log('menu selected: ' + item['title'])

    def refresh_table(self):
        self.table.load_data()
```
```
class AjaxTable(Tag):

    def __init__(self, opts):
        Tag.__init__(self, opts)
        self.url = self.opts.url or ''
        self.load_data()

    def render(self):
        __pragma__('opov')
        table = e.table(class_='table table-hover table-bordered table-striped table-condensed table-hover')
        if len(self.columns) > 0:
            # header
            thead = e.thead(class_='thin-border-bottom')
            thead <= (e.tr() <= [e.th(e.a(c, href='javascript:;', onclick=[self.sort, i])) for i, c in enumerate(self.columns)])

            # body
            tbody = e.tbody()
            for row in self.rows:
                tbody <= (e.tr() <= [e.td(c) for c in row])

            table <= [thead, tbody]
        __pragma__('noopov')
        return table.vnode

    def load_data(self):
        if self.url:
            ajax.get(self.url, {}, self.data_loaded, True)

    def data_loaded(self, result, status):
        console.log('data loaded')
        if status == 200:
            # load data
            data = JSON.parse(result)
            self.make_table(data)
            if self._mounted:
                self.update()
        else:
            raise Exception('Bad status returned')

    def make_table(self, data):
        self.columns = []
        self.rows = []
        for h in data['headers']:
            self.columns.append(h['title'])

        for row in data['rows']:
            self.rows.append(row)

        # TODO: implement sort column parameter and remove
        self.sort(0)

    def sort(self, col, e):
        # TODO: not working on IE
        self.rows.sort(key=lambda x: x[col])
        self.update()
```
It now supports automatic and manual components mounting. Rendering is more powerful than riot templates and very fast.

**Comment by JdeH** [comment]
The explosion of JS tools, libs, vdoms etc. is overwhelming.
Glad you're making this demo, since I've never used snabbdom,
Will add it to demos if ready.

**Comment by AXGKl** [comment]
@neriusmika : That is fantastic we need a default renderer, to replace riot or react.

questions:  what is e and t in:

```python
table = e.table(..)
nav = t(self, self.navigation)
```

btw, if you put write "```python" then we'd have syntax hilite, makes it better on the eyes ;-)

**Comment by neriusmika** [comment]
It's a module, I import it like that: import elementmaker as e and here is it's content:

```
from org.transcrypt.stubs.browser import __pragma__
from snabbdom import h

__pragma__('skip')
__new__ = console = Array = 0
__pragma__('noskip')


event_types = [
    'onclick',
    'onkeyup',
    'onkeydown',
    'onkeypress',
    'onchange',
    'onblur',
    'onfocus',
]


class HtmlTag:
    def __init__(self, name, children, attrs):
        self.name = name
        self.children = []
        self.add_child(children)
        self.attrs = dict(attrs)
        self.vn = None

    def add_child(self, child):
        # TODO: completely flatten any nested levels
        if type(child) in (list, tuple):
            for c in child:
                if type(c) in (list, tuple):
                    self.children.extend(c)
                else:
                    self.children.append(c)
        else:
            self.children.append(child)
        self.vn = None

    def make_attrs(self):
        attrs = {}
        props = {}
        events = {}
        for attr, value in self.attrs.items():
            if type(value) == str and value == '':
                continue

            if attr in event_types:
                events[attr[2:]] = value
            else:
                # property or attribute?
                if attr[0] == '_':
                    container = props
                    attr = attr[1:]
                else:
                    container = attrs

                if attr == 'class_':
                    container['class'] = value
                else:
                    container[attr] = value
        return {'attrs': attrs, 'props': props, 'on': events}

    def get_vnode(self):
        if not self.vn:
            attrs = self.make_attrs()
            children = []
            for c in self.children:
                if type(c) == str:
                    children.append(c)
                elif isinstance(c, HtmlTag):
                    children.append(c.vnode)
                else:
                    children.append(c)
            self.vn = h(self.name, attrs, children)
        return self.vn
    vnode = property(get_vnode)

    def __le__(self, other):
        self.add_child(other)
        return self

    def __repr__(self):
        s = '<' + self.name
        children = []
        for c in self.children:
            if type(c) == str:
                children.append(c)
            elif isinstance(c, HtmlTag):
                children.append(c.__repr__())
            else:
                children.append(c)
        if len(children) > 0:
            s += ': [' + ', '.join(children) + '] />'
        else:
            s += '/>'
        return s


class TagFactory:
    def __init__(self, name):
        self.name = name

    __pragma__('kwargs')
    def __call__(self, *children, **attrs):
        # return __new__(HtmlTag(self.name, children, attrs))
        return HtmlTag(self.name, children, attrs)
    __pragma__('nokwargs')


# usage example:
# def render(self):
#     d = __new__(Date())
#     time = d.toLocaleString()
#     __pragma__('opov')
#     d = div('start', div(time, h('span', 'inside time'), style='color:red;') <= 'inside 2', ['end1', 'end2'], class_='clock2')
#     d <= 'final' <= div('last one')
#     __pragma__('noopov')
#     return d.vnode


a = TagFactory('a')
div = TagFactory('div')
ul = TagFactory('ul')
ol = TagFactory('ol')
li = TagFactory('li')
table = TagFactory('table')
thead = TagFactory('thead')
tbody = TagFactory('tbody')
tfoot = TagFactory('tfoot')
th = TagFactory('th')
td = TagFactory('td')
tr = TagFactory('tr')
button = TagFactory('button')
nav = TagFactory('nav')
span = TagFactory('span')
input = TagFactory('input')
textarea = TagFactory('textarea')
option = TagFactory('option')
select = TagFactory('select')
form = TagFactory('form')
h1 = TagFactory('h1')
h2 = TagFactory('h2')
h3 = TagFactory('h3')
h4 = TagFactory('h4')
h5 = TagFactory('h5')
h6 = TagFactory('h6')
pre = TagFactory('pre')
abbr = TagFactory('abbr')
u = TagFactory('u')
b = TagFactory('b')
i = TagFactory('i')
em = TagFactory('em')
strong = TagFactory('strong')
small = TagFactory('small')
sub = TagFactory('sub')
sup = TagFactory('sup')
p = TagFactory('p')
dl = TagFactory('dl')
dt = TagFactory('dt')
dd = TagFactory('dd')
hr = TagFactory('hr')
br = TagFactory('br')
blockquote = TagFactory('blockquote')
img = TagFactory('img')
meta = TagFactory('meta')
svg = TagFactory('svg')
article = TagFactory('article')
section = TagFactory('section')
script = TagFactory('script')
```

of course it's not finished. Actually it's a wrapper over snabbdom h function, but much more simpler, so now I can render not only from bottom to top, but from top to bottom too (using overloaded <= operator)

**Comment by neriusmika** [comment]
I created it because I hate jsx and riot templates :) Btw it would be good to render like that:

```
with e.div():
    e.p('some paragraph')
    e.div('another inside div')
```

but still not tried to overide `__enter__` `__exit__` in transcrypt, don't know is it possible now.

**Comment by neriusmika** [comment]
And that "t" is function to create and mount or render (if already mounted) child component. If you want I can send the whole project. Like I said it's in testing mode so complete mess, but it works. Now I am trying  to implement redux and some other things.

**Comment by AXGKl** [comment]
Hi, yes would be interesting. gk at axiros.com is my email.

I'm working a similar thing, component trees in transcrypt comming from riot - but I'm coming more from the high level side, working my way down to the phsycial DOM and I thought up to now I'll use a library for the actual rendering of redux state into html. Fall a bit in love with kendoui allthough its completely banging the DOM directly via jquery. A vdom backed component lib in transcrypt would indeed by nice, but its a long way to go, check out e.g. kendo grid....

I'll ping you as well when sth is useable but I think as strong as you are you won't learn much. Only interesting maybe for you that instead of using contexts for nesting I'm using nested class trees, because those can be overridden and specified to do other/more things better than contexts.

Currently thinking about if I wrap my classes into javascript Proxy objects so that I can map attribute dotted lookups into direct lookups into the store, if the attribute is not config but state (killing IE compliance)...

**Comment by neriusmika** [comment]
Thanks, I actually started from your riot examples, but had some problems (in riot itself), so decided to make from scratch. Only taken snabbdom as vdom (it's used by vue js, cycle js) and it's faster than riot or react, is clean and have hooks for insert (vnode to dom), remove etc. But your examples was very helpful to me.

**Comment by JdeH** [comment]
@neriusmika 

__enter__ and __exit__ are not (yet) supported.

**Comment by AXGKl** [comment]
@neriusmika 

the riot example I should clean up a little, got a little stuffed with = realizing more and more the possibilities of transcrypt - ending with the conclusion that I don't want to use Riot at all any more, which is funny.

Snabbdom I also heard good things, this is an interesting one about riot / react and also snabbdom: https://github.com/riot/riot/issues/484

**Comment by neriusmika** [comment]
The same for me. I looked inside riot code, they use slow innerhtml. I tried to use innerhtml myself and it was many times slower than creating nodes directly and patch with snabbdom.

P.S. I read that post in your link several days ago :)
Did you receive my example?

**Comment by AXGKl** [comment]
:-) 

e-mail contact established

@JdeH: this one you can close, imho.

**Comment by AXGKl** [comment]
@neriusmika:

I'm old enough to not be ashamed to ask brutally noobish questions:

What is this doing, not understood how this can generate a table body tag:

```python
tbody <= (e.tr() <= [e.td(c) for c in row])
```

**Comment by AXGKl** [comment]
lol, got it.  `def __le__` in HTMLTag and the pragma oopov

hehe, this is cool, Python's elegance was not enough, you create your own DSL on top of it all ;-)

**Comment by neriusmika** [comment]
I'm old enough too :)
<= is overloaded, it pushes inside other elements, strings or snabbdom vnodes and stores them in "children" attribute, parentheses are needed, because first I need to push td inside tr (because overloading does not change order of operations). And when I'm done with all elements render function must return snabbdom vnode. There is such vnode property in HtmlTag if you looked in example. If it's still not clear, please ask. I'm not good at explaining things :)

**Comment by neriusmika** [comment]
Yes, and as I mentioned before, extending it with "with" would be even more elegant.

**Comment by neriusmika** [comment]
Actually I want to create readable and easy rendering without involving templates. Of course jinja equivalent would be great, but parsing text will always be slower and not so powerful as direct elements creation with python code.

**Comment by punkdit** [comment]
Thankyou @neriusmika @JdeH for your help. Looks like this example is working now. Btw, I pulled it straight off this website: http://corehtml5canvas.com/code-live/

Going forward I am hoping to build some interactive animations / simulations / games. Normally I use pycairo and pygame for this, but it would be great to get this live on a webpage instead. What do people recommend? I like to keep to as few moving parts as possible, hence the html5 canvas. My js knowledge is close to nil. But I do like the sweet vector graphics that cairo makes.

**Comment by neriusmika** [comment]
If you want animations / games, you can use webgl. For example look at http://www.pixijs.com/

**Comment by JdeH** [comment]
A very personal, subjective, possibly wicked advice:

1. My impression is that SVG graphically is superior to the canvas, although probably less suitable for some types of games. But I'd certainly investigate, depending on what you want to make.

2. I've tried both fabric.js (used in the pong demo) and d3.js (used in the d3.js demo). Both these libraries are large and require significant effort in grabbing the basic concepts and way of thinking behind then. On the other hand, directly working with SVG or WebGL on a canvas turned out to compact, fast, and quite doable , since they are abundantly documented in many places on the web.

As opposed to this, getting answers to some questions about e.g. fabric.js, e.g. on stackoverflow. This also holds for other JS libs I've used. If you use them for the same thing everyone is using them for, you'll get your answers, but as soon as you're trying to do something special, you're forced to delve into a huge amount of JS functional programming style library source code, which I find difficult to read.

So before you use any library at all, maybe take courage and try what you can achieve without one. At the start progress will be slow, but eventually you'll have a larger degree of control. And the knowledge of WebGL and SVG you acquire in the process will serve you for years, since these are mainstream technologies, rather than JS libs popping up and being superseded.

Well, as can be seen by Transcrypt, I the type of person who, if I don't like something, is quickly inclined to roll my own. So this advice is indeed very subjective. Most people love libs because they can achieve results quickly with them.
