### ISSUE TITLE
Problem with NodeJS

### ISSUE THREAD

**Issue by artyprog** [QQuick/Transcrypt#153]
Hello, i am back to Transcrypt :-)

I have a script which simply do a console.log
I have compiled it with 

   `transcrypt  -nomin -p .none  t.py `

I get the following error
```
nodejs /tmp/__javascript__/t.js 
/tmp/__javascript__/t.js:179
					var __envir__ = __call__ (__Envir__);
					                ^

TypeError: __call__ is not a function
    at Object.__nest__.__all__.__init__ (/tmp/__javascript__/t.js:179:22)
    at __init__ (/tmp/__javascript__/t.js:42:19)
    at t (/tmp/__javascript__/t.js:512:25)
    at Object.<anonymous> (/tmp/__javascript__/t.js:1920:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

Regards

**Comment by AXGKl** [comment]
hi, 

does run here:

```
5..DE:~/waxapp# cat p.py 
console.log('hi')
5..DE:~/waxapp# wax/transcrypt/run_transcrypt -n -p .none  p.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.233
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /root/waxapp/__javascript__/p.js

Ready
5..DE:~/waxapp# node __javascript__/p.js 
hi
5..DE:~/waxapp# node --version
v4.6.0
```

=> whats your versions of transcrypt and node?

**Comment by AXGKl** [comment]
maybe its the `-nomin`, should be `--nomin`

**Comment by JdeH** [comment]
Awaiting conclusion / further info

**Comment by artyprog** [comment]
Hy,

Thanks, I still have the problem...

I am using node 4.2.6
Ubuntu hosted by Windows via VirtualPC

Regards

**Comment by artyprog** [comment]
I will upgrade to the latest of Node...

**Comment by artyprog** [comment]
In fact the problem is not Node, i still have the problem without any options
Here the end of the transcrypted file

```
  __all__.__call__ = __call__;

        (function () {
                var greet = function () {
                        alert ('Hello from Python');
                };
                greet ();
                __pragma__ ('<all>')
                        __all__.greet = greet;
                __pragma__ ('</all>')
        }) ();
        return __all__;
}
window ['main'] = main ();
```

**Comment by JdeH** [comment]
Since you said it's only small, could you give the  complete Python source to experiment with?

**Comment by AXGKl** [comment]
- `window['main']` => you *must* use `-p .none`  for node
-  `alert ('Hello from Python')` => can't work on the server. Pls. use `console.log` for tests

cheers.
G.

**Comment by artyprog** [comment]
Thank you all,

I have tried directly on my window host, and all is fine.
Jacques you can close the ticket, thank's again for your welcome :-)

Regards
