### ISSUE TITLE
`foo.type` is not possible. Workaround: `foo['type']`

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#158]
Hi,

since you idle too much, I thought I'll create an issue to keep you entertained :-)

(adding @neriusmika since he is also dealing with redux.)

----

I already mentioned it, `.type` is currently causing trouble when used as a class attribute - but its more severe - the current version of transcrypt is really preventing **any** dot access of it.

That is nasty with a lib like Redux, which wants so called actions with a `type` attribute, `action.type` and its everywhere, in all docus: http://redux.js.org/docs/basics/Reducers.html

I think it came with the metaclass feature, which I love, but in current Transcrypt `foo.type` is no more possible at all:

```python
def foo(m):
    console.log(m.type)
foo({'type': 1})
```
is transpiled into:

```js
    (function () {                                                         
         var foo = function (m) {                                           
             console.log (m.py_metatype);                                   
         };                                                                 
         foo (dict ({'type': 1}));                               
```

And since Redux is really hype many people will be bitten by that, thats why it should be findable in the issues or really prominently in limits / reserved words if its not fixable.

----

And now seriously: Don't fix it NOW. I can help myself -  there is clearly the workaoround `action['type']` , postpone it to next year, whatever.

Still, people should find it.

Thanks.
G.

**Comment by JdeH** [comment]
Thanks for the workaround. Didn't know _type_ was so important to some libs. In due time will devote some time to this problem, don't know what that will yield, though.

Come to think of it, have you attempted to use:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#pragma-alias

locally?

No idea if it solves this, just a hunch...

**Comment by AXGKl** [comment]
I was not smart enough, to understand that its solvable by an alias, its working... you really thought about everything, all necessary indirections in (but not more).

**Comment by JdeH** [comment]
Glad that it works. There can always be things I overlooked.
