### ISSUE TITLE
Add  a 'Differences with CPython' or 'Main Limitations' chapter.

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#159]
Only limitatively summing up and showing all features in the testlets isn't enough anymore. There has to be a chapter explicitly mentioning the main differences: Limitations (most needed, exec and eval, string formatting, introspection, special methods), subtle differences (modules and packages, global versus nonlocal), extra's (pragma's like ifdef elif endif, optional JS style keys, ways to cooperate with JS code)

**Comment by AXGKl** [comment]
My 2 cents: Help us users help ourselves better to avoid you = hitting a burn out wall, with the success of transcrypt.

2 Levels:

1. **workaround** in pure user space python. Examples: `def mro()` to work around missing `mro` method.  `.format`...

2.  the compiler / builtins combo could get customization hooks / allow subclassing. Explain how. To allow advanced users to add stuff by their own.
   Example: Nobody except you could have done metaclass support, realistically. But I think it would be possible, with a customization guide and hooks or subclassing, to add support for '%' formatting (which I also miss) alone in the compiler. 

3. Documentation: we need an online system where we can annotate your docu with our comments. Clearly seperated from original but ready for you to redigate and include, to offlooad you from docu work.

**Comment by JdeH** [comment]
Many good idea's!  I am currently thinking a lot about the future of TS and about my own balance between managing and coding.

- There's now so much useful feedback, bugs, enhancements, general hints, that I want to devote a significant part of my time to making those land in fruitful soil. One important point is communication: explaining why things are in or out, why certain choices were made, what the design goals are. So clearly reacting on issues is central business. You've frequently contributed to that, and I value that very much since it saves me lots of time.

- Things could easily scale up to a level where reviewing and improving the contributions and testing fill up all of my time. In that case:
 - Testing might have to be further automated, e.g. by having Windows and Linux working in tandem unattended.
 - Releases will be less frequent, to limit the effort invested in testing, doc updates and writing demo's. It is of prime importance that releases are of good quality, well tested, well documented.

- I want to free 50% of my TS time to keep coding the core myself, since that is where I can add most value. Want to keep up with the essentials of new PY and JS versions.  But a code reorganization improving long term simplicity and maintainability is more important that adding a new feature.

About annotating documentation: Do you have a particular system in mind. Would a Wiki be handy. It should be reviewed. How do we organize that? Or should we just benefit more from StackOverflow with its well functioning review system?

About TS in general: The biggest risk to manage is to keep it focused and small. This means explaining over and over again why some things are in and others aren't. And maybe it also means being rigid at some points, which I find hard, since I respect very much the intelligent feedback we get.

**Comment by AXGKl** [comment]
@JdeH : Relax on this one, its on "us", the users. Pulling up platforms and such to accompany the tool. Lets see what we reach.

**Comment by JdeH** [comment]
OK, good to hear. And curious what comes out.
