### ISSUE TITLE
List Comprehensions / Operator Precedence Bug

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#178]
Hi, 

While working on the re module, I've into the following bug. Here is my python code: 

```
def convertFlags(flags):
    bitmaps = [
        (2 , ""),
        (4 , ""),
        (8, "i"),
        (16, "m"),
        (32, "y"),
        (64, "u"),
        (128, "g")
    ]
    ret = "".join( [x[1] for x in bitmaps if (x[0] & flags) > 0] )
    return(ret)
```

This compiles into: 

```
		var convertFlags = function (flags) {
			var bitmaps = list ([tuple ([2, '']), tuple ([4, '']), tuple ([8, 'i']), tuple ([16, 'm']), tuple ([32, 'y']), tuple ([64, 'u']), tuple ([128, 'g'])]);
			var ret = ''.join (function () {
				var __accu0__ = [];
				var __iterable0__ = bitmaps;
				for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
					var x = __iterable0__ [__index0__];
					if (x [0] & flags > 0) {
						__accu0__.append (x [1]);
					}
				}
				return __accu0__;
			} ());
			return ret;
		};
```

The critical part of this is the following: 

```
	if (x [0] & flags > 0) {
		__accu0__.append (x [1]);
	}
```

In javascript, [the operator precedence takes the '>' operator before the '&' operator](http://www.scriptingmaster.com/javascript/operator-precedence.asp). In this context, it means that `flags > 0` converts to a boolean which then gets cast to a integer (1) and then is '&' is applied which in this function means that the '&' doesn't do what we want. 

The python has the appropriate `()` to make the operator precedence behave but it doesn't get translated. I've tried a couple different combinations but they all get removed in the end product.

**Comment by JdeH** [comment]
Good find! Will fix a.s.a.p.

**Comment by JdeH** [comment]
This was the tip of the iceberg.
I naively assumed that operator precences in Python and JavaScript were 'largely the same'.
Not.
Should be all fixed now.
