### ISSUE TITLE
Synchronize console I/O

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#183]
All demo's using Python's console `input` do I/O in the wrong order.

Console I/O is handy for first-time programmers. They don't have to deal with the intricacies of the event driven world yet.

Unfortunately JavaScript is getting more and more obsessive compulsive async: Even `window.prompt` refuses to await its turn these days, synch ajax is deprecated on the main thread (which happens to be the only one that can access the DOM), and not allowed to have a timeout and doModalDialog is deprecated and gone in the newest Chrome. :(

There is one very fundamental solution out there. It's called `suspensions` and it is part of the Skulpt 'in browser' compiler, which is heavily used educational purposes on the [Trinket website](https://trinket.io/) . Since it has consequences for code complexity, performance and code size, it isn't suitable for Transcrypt, where the primary goal isn't educational but production use, lean, fast code favored over 100% CPython compliance.

I am currently investigating a different route for simple programs. Anything less simple should simply use event driven I/O, since that's what GUI's of any kind do these days.

> Can't help but giving a strong personal opinion here:
> 
> - Synchroneous processing can be very handy in some cases, as can the use of the GOTO statement (for finite state machines, and yes I know about the while loop with the switch statement). Developers, not browser manufacturers should choose wether or not to use it. The argument that 'it can hang the browser' is bogus. There are a million ways to hang a browser, and this is not one of them. A simple timeout watchdog would solve that problem. As for 'the user experience': that's the responsibility of the developer, any developer ignoring it will soon be out of a job.
> 
> - Asynch processing can be very handy too, and can be covered by very simple means like semaphores. The complexity of all concepts now introduced in JS and Python make me frown quite a bit: send, yield, promises, async / await. Having programmed real time control systems for most of my life, I hereby express serious doubts as to the effectiveness of all this. Asynch programming used to be very popular in this type of applications, using the same concepts, and it proved to create lots of problems that developers couldn't handle, unless they were either very clever or very experienced. Sequential, purely synchroneous, controls, most notably [PLC's](http://www.qquick.org/simpylchowto) still hold 90% of that market.
> 
> Let me state it differently: With all the complexity recently introduced in JS and Python, both languages now seem to have reached the stage of cooperative multitasking (Windows 95, remember...).  I predict that within the next few years these languages will actually include preemptive multitasking. And once again many blogs will be filled about how to use it. Wow. Must say I still believe in simplicity.

**Comment by artyprog** [comment]
Hello Jacques,

I don't know if it fits your needs, but never now

http://bluebirdjs.com/docs/async-dialogs.html


Regards

2016-11-17 15:34 GMT+01:00 Jacques de Hooge <notifications@github.com>:

**Comment by JdeH** [comment]
Simple, purely text based programs can now be made using blocking I/O.
This is enough for the first steps in programming:

if...else...
while...
for...
functions
classes
modules

After that (and some non-interactive turtle graphics) it's time to introduce buttons, input fields and event handlers...
