### ISSUE TITLE
Improved Browser View of AutoTest Results

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#184]
Hi, 

So I've been working with the autotest browser results and it is very frustrating to compare the results. Additionally, the browser results as shown don't allow an easy way to determine where a particular issue is. In addition, the current browser view only highlights the first error that it encounters. To fix this I've refactored the "autotester" HTML generation to look more like the attached image:

<img width="713" alt="screen shot 2016-11-17 at 9 03 13 am" src="https://cloud.githubusercontent.com/assets/15036736/20399130/b46bf1d2-aca4-11e6-89b3-f70dbf2a51b6.png">

The idea here is to use the [inspect](https://docs.python.org/3/library/inspect.html) library in python and the exception stack trace in javascript to determine the location in the file where an autotester.check method is called. (I have not implemented the python side, but you can see the javascript side in the image). The aesthetics for this are obviously pretty rough still but that could be fixed with a CSS script. 

Additionally, I've refactored the output to use a html TABLE instead of a list of values. I haven't worked out all the bugs in this yet, but this method allows for the results to be compared directly and hopefully, when I have the python inspect stack trace shown in the first column, it will allow the developer to identify exactly where the issue is. 

Ideally, I would like to make the table expandable via a button so that tests that pass completely are shown collapsed and the tests with errors are shown expanded. The user could then click a button to expand/collapse test suite results. 

Would you accept a PR for this feature?

**Comment by JdeH** [comment]
Looks very promising.
Am I right that the testlets stay as simple as they are rightnow?

I can only make a final decision based on the end result.
But for now this sounds like a very useful improvement.
So it stands a high chance of being accepted.

**Comment by RCL-Carl** [comment]
> Am I right that the testlets stay as simple as they are rightnow?

That's correct - nothing in the testlets would change. This is change would only affect the frontend and adds some additional meta data in the `autoTester.check` method for the code location information.

**Comment by JdeH** [comment]
What exactly do you mean by adding metadata in autoTester.check? It would pick up the location where it's called I guess? But syntactically the call would remain as simple as it is now, right?

**Comment by RCL-Carl** [comment]
the call signature in `autoTester.check` stays the same. 

Excerpt of check : 
```
def check(self, *args):
    position = getCallerLocation()
    item = ' '.join ([self.sortedRepr (arg) for arg in args])	
    if __envir__.executor_name == __envir__.transpiler_name:
		self.testBuffer.append ((position,item))
    else:
		self.referenceBuffer.append (item)
```

**Comment by JdeH** [comment]
Just really a good idea.

**Comment by RCL-Carl** [comment]
I think this issue can be closed now.
