### ISSUE TITLE
"warnings" module

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#191]
Given the state of the project where there are quite a few gotchas that are based on decisions to not implement portions of the python API, I think it may make sense to include the [warnings](https://docs.python.org/3/library/warnings.html) module in the distribution. That would provide developers with a mechanism to relay runtime issues that are known short comings either to the console or elsewhere. This is definitely not intended to replace the compile-time static checking at all. But could be useful for example, logging modules where we don't necessarily want the application to fail if a dev tries to configure a "FileHandler" but we also need to inform them that this isn't available. 

Other use cases could be for deprecated features or features that won't necessarily work as you expect.

**Comment by RCL-Carl** [comment]
In the `warnings` module, there is code to attempt to determine the call location of where the warning is coming from. This is using something very similar to what we are doing in the autotester right now. We can do this for the javascript side but I don't think it would be very useful to give the javascript call location in the warning. I think the python file and line number would be more useful. The issue is how to get that information into the js runtime. 

Given that I don't think there will be many warnings in a typical application, I think one solution would be to just embed the filename and lineno directly as literals. To do this, I think it makes the most sense to have a definition of some macros or properties for `__file__` and `__line__` in `org.transcrypt.utils` or some similar location (or may be not in the namespace at all). 

The idea would be that when `utils.__file__` is encountered, the compiler would insert the filename from which that location was referenced (kind of like what python does now). `utils.__line__` would be similar, the compiler would reference the line number of the file where the value was used. The way this is done in python runtime is that the `inspect` module is used but this is a runtime accessible module that we don't really have access to in the js runtime. The `__file__` and `__line__` would behave more like their C/C++ counter parts instead of like python.

Does something like this exist or would it need to be developed? I know that there is a source annotation concept, so the __file__ should definitely be possible, I don't think the line number should be that much harder. 

Thoughts?

**Comment by AXGKl** [comment]
Hi Carl,

> Does something like this exist 

the -a switch also inserts the line numbers into the generated js source, e.g.

```js
// ============ Source: /Users/gk/test/r.py ============

/* 000001 */ 	(function () {
/* 000001 */ 		var i = 23;
```

and with `<functionname>.toString()`  you can access those comments from within js - if you have the function name.

If we would put the filename into the function body than it would be, guess, "easy" to present the user with all infos.

Or did I misunderstand what you intend to do?

**Comment by RCL-Carl** [comment]
I had played with the `-a` option before and in the generated js code, the header with the source file name was present, but the line numbers as you show them were not. Very odd - not sure why mine did not have that.

In any case, I think that putting this information as comments in the javascript is going to end up with a whole lot of content that for the most part will never be used. So - I agree that you could do what I'm trying to do with what you have proposed. But I feel it goes against the idea of having transcrypt generate lean js output. This approach would also not work in the minified variant of the javascript. This is why I'm suggesting a macro because then you only include the content you actually need to provide the warning information.

I like the mechanism that you have brought up though. This could be used to make a `inspect` module that could map the javascript stack to a python stack, including file names, line numbers, etc. Might get a little complicated but it could be super useful for exceptions. I've had problems with the autotester's "getFileLocation" because it is very difficult to map the javascript stack to the python stack as the output is currently generated. I think this could solve the problem nicely, but would be quite unwieldy to deploy in the wild.

**Comment by AXGKl** [comment]
hi, regarding the line number annotations, I tried again and also had the feeling that it did not work as it did the first time, strange. Then it did and I could not reproduce it, deleted the console output unfortunately. Maybe the switches have to be in certain order, can't explain, its argparse => should not.
In any case here the switches how I use them:

```
~/test $ rm -rf __javascript__/
~/test $ cat r.py 
def foo():
    alert(foo.toString())

foo()

~/test $ transcrypt -an r.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.3
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /Users/gk/test/__javascript__/r.js

Ready
~/test $ tail -n 10 __javascript__/r.js 
/* 000002 */ 			alert (foo.toString ());
/* 000002 */ 		};
/* 000004 */ 		foo ();
/* 000004 */ 		__pragma__ ('<all>')
/* 000004 */ 			__all__.foo = foo;
/* 000004 */ 		__pragma__ ('</all>')
/* 000004 */ 	}) ();
/* 000004 */    return __all__;
}
window ['r'] = r ();

```

----

anyway:
There seem to be good js tools to inspect the call stack, including source code (comments).
e.g. https://github.com/fresheneesz/stackinfo

So.. yeah.. I guess there would be no principal showstopper preventing us to write e.g. a pdb which could spit out javascript and python source side by side, or only python source.... 
Or do that in an exception catcher... ;-)

I must pass though, at least until x-mas, facing a pile of other stuff currently :-(

**Comment by JdeH** [comment]
Annotations not working anymore? Maybe the've fallen over, haven't used them for a long time.
Annotations BTW are only inserted for parts that are generated from a .py source, so not e.g. for __builtins__.

About __file__ and __line__. Both annotations and sourcemaps rely on this info being available in principle. So something like that will be doable I guess. Must say sourcemaps were quite complicated, esp. the cascaded ones. But in the end they should hold enough info to go from minified JS back to Python. Because that's exactly what the debugger in the browser does in case of an exception.

The cascading was complicated enough not to dupplicate it!! So __file__ and __line__ should use the cascaded sourcemaps. Will not be in overnight, but 'll create a 'nice to have' issue for it. 'Nice to have' not because it's not important, but because its a bit  more complicated than it seems.

**Comment by JdeH** [comment]
Annotations have been repaired.
Will look into __file__ and __line__ now.

**Comment by JdeH** [comment]
__file__ and __line__ added

**Comment by RCL-Carl** [comment]
I've tested that out real quick on my local machine, and I think that it works great. I've pushed a PR that builds on this and adds `__name__` and `__filename__`. #227
