### ISSUE TITLE
Bug: try / finally without except

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#192]
Hi, 

While going through the logging module I've found an issue with the try/except/finally code generation. 

Here is the python code: 
```
_acquireLock()
try:    
        _levelToName[level] = levelName
        _nameToLevel[levelName] = level
finally:
        _releaseLock()
```

Here is the javascript code: 
```
_acquireLock ();
try {
	_levelToName [level] = levelName;
	_nameToLevel [levelName] = level;
}
catch (__except0__) {
	else {
		throw __except0__;
	}
}
finally {
	_releaseLock ();
}
```

The above is a valid python sequence, but the second has an invalid syntax issue in the "catch" block. It seems that the code that generates the javascript exception vs python exception handling in the catch block is still operating even when there is no except block in python. 

Keep in mind that the transcrypt compiler generates the code and the static checking after the fact does catch this as an error - but the test_server.py seems to swallow the error and displays the faulty javascript regardless. Regardless, this is an issue because this is not translating to the appropriately from the python source.

**Comment by JdeH** [comment]
Should be  fixed on master, please reopen if still problems
