### ISSUE TITLE
CI: test_server.py with no args throws exception

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#195]
Hi, 

When I run `test_server.py` with no arguments, I get the following exception: 

$> test_server.py

```
$ ./test_server.py 
Usage:
Start me with ./test_server.py <[host:]port> [dev]
e.g. ./test_server.py 8080 or ./test_server.py 0.0.0.0:7777
Traceback (most recent call last):
  File "./test_server.py", line 398, in <module>
    usage()
  File "./test_server.py", line 379, in usage
    print 'Hit me at http://%s:%s/do/<tests>' % (h, p)
NameError: global name 'h' is not defined
```

It seems to be throwing the exception while it is trying to print out the usage text for the utility.
If I pass with valid arguments, it does not throw an exception.

**Comment by AXGKl** [comment]
ty, fixed here https://github.com/QQuick/Transcrypt/pull/198

@JdeH : can be closed.
