### ISSUE TITLE
Extending arrays using `+` operator

### ISSUE THREAD

**Issue by agosto-karlkroening** [QQuick/Transcrypt#200]
Is this intended behavior?
```
print(['abc', 'def'] + ['ghi'])
```
Output:
```
abc,defghi
```
(Running with cpython of course produces `['abc', 'def', 'ghi']`)

Generated JS:
```
print (list (['abc', 'def']) + list (['ghi']));
```

**Comment by JdeH** [comment]
Using + for lists requires operator overloading to be switched on.
To prevent number addition and string concatenation from becoming slow, use it locally:

```
__pragma__ ('opov')

# Lots of list concatenation using + operator here.

__pragma__ ('nopov')
```

This should work. If it doesn't something has fallen over, please let us know.

Kind regards
Jacques

**Comment by agosto-karlkroening** [comment]
Makes sense - operator overloading must be expensive and is enabled by default. It's cool that you can enable it if needed.

Thanks for the quick reply! And great work on this project - I'm excited to see where it goes.
