### ISSUE TITLE
kwargs limitations

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#203]
Hi, 

As I'm going through the logging module, there are a lot of cases where `**kwargs` are used to provide flexibility in the UI. When I enable the kwargs option using `__pragma__('kwargs')` the function receives an object that from what I can tell is a javascript object but not a full dict object. In other words, the function cannot call dict methods like "keys()" or "pop()" on kwargs even though these are defined for standard dict objects. What is the rationale for not having the kwargs object be a full-fledged dict object?

I'm having issues because I'm trying to simulate the certain functionalities of a dict on this quasi-dict object like pop(). To do this I have the following python code: 

```
def basicConfig(**kwargs):
   ...
  style = kwargs["style"]
  if ( style is None ):
    style = '{'
```

This generates the following javascript: 
```
   ...
var style = kwargs ['style'];
if (style === null) {
    var style = '{';
}
```

The problem is that `===` is the identity operator and it will not coerce 'undefined' to 'null'. So the when we try to pull the missing `style` attribute from kwargs, `style = undefined` and hence the comparison between style and null using the identity operator fails. The `style` value never gets a default value. I could of course compare style to "undefined" but that seems antithetical to the goal of transcrypt.

I think it would make a whole lot more sense if kwargs was a full dict object like in python.

**Comment by JdeH** [comment]
The rationale was that I wanted to keep this mechanism as cheap and lightweight as possible. But I may have underestimated the need for a real dictionary, and a real dict isn't that heavy. It could be that there are some technical problems as well, but I expect them to be solvable. So my proposal is to indeed make it a full fledged dict, unless severe implementation problems arise, which as said I don't expect.

The 'kwargs' code was rather tricky at some points (forgot the details, but not the feeling...), so I'd like to postpone correcting until I am free to concentrate upon the core again (don't expect that to take longer than say 2 weeks). But if this hinders progress of your code to much I'll give it priority. Awaiting your reaction.

**Comment by RCL-Carl** [comment]
> But if this hinders progress of your code to much I'll give it priority. 

I don't think there is any need to change your schedule. I can work around it for now. Thanks!

**Comment by JdeH** [comment]
Done, let me know if not OK

**Comment by boxed** [comment]
I don't think it's ok :P 

At least fail on it, so I know I have to work around it.
