### ISSUE TITLE
Bug: List coerce to Bool

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#204]
Hi, 

I ran into an issue with the way lists are converted to booleans in python vs javascript. In javascript, an empty list converts to true. In Python, an empty list converts to false. 

Here is the Python: 
```
a = []
b = True if a else False
test.check(b)
c = [1,2,3]
d = True if c else False
test.check(d)
```

Here is the javascript:
```
var a = list ([]);
var b = (a ? true : false);
test.check (b);
var c = list ([1, 2, 3]);
var d = (c ? true : false);
test.check (d);
```

This results of this when run through autotester is the following excerpt image: 
![screen shot 2016-11-21 at 10 30 14 pm](https://cloud.githubusercontent.com/assets/15036736/20513365/43a8f456-b03a-11e6-9d23-995fede76960.png)

**Comment by fzzylogic** [comment]
See '[automatic conversion to truth value](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#automatic-conversion-to-truth-value-pragma-tconv-and-pragma-notconv)' in the docs. Jacques would know more about the rationale behind that. Thanks for your detailed feedback and valuable contributions to Transcrypt.

**Comment by JdeH** [comment]
Should indeed work with the 'iconv' pragma (or switch). If not it's a bug, so let me know.

**Comment by RCL-Carl** [comment]
Great - thanks.
