### ISSUE TITLE
Process inline compilation

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#209]
Hi Jacques,

I know you had been asked a few times already but I just need a pointer:

Is it realistic that Transcrypt could be used as library, accepting strings of python, returning JS ? I.e. not via subprocess but inline? If you say its straight forward I give it a shot but I don't want to burn hours on the wrong path.

If its very awkward then just close this one and we'll live with the process call.

**Comment by JdeH** [comment]
I've given this a low priority.

While there are no fundamental problems with, it would require a reorganization that would take more of my time than I currently want to devote to issue, almost certainly make things fall over that are not part of any autotest.

I would not want to run that risk now, my estimation is that currently other issues, and above all reliability, gaining trust of devs, and absence of regressions are more important.

This is really something that I want to think through very thoroughly and, above all, rigorously test.

But I have left the issue (#48) open, which isn't merely symbolical.
