### ISSUE TITLE
Request confirmation: Discontinue subject branches

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#219]
@AXGKl @RCL-Carl 

Since they're causing chaos, at least in my mind, I propose **shutting down the subject branches a.s.a.p.** Since this may interfere with your work, please explicitly confirm that this is OK for you and will not destroy any of your work done.

I've labeled this a bug, because in my view, that's the only right word for it...
KR
Jacques

**Comment by AXGKl** [comment]
OK

**Comment by RCL-Carl** [comment]
That is fine by me.

**Comment by JdeH** [comment]
Done
