### ISSUE TITLE
Dict Creation Issue

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#221]
In python one can create a copy of a dict by calling the following (this is obviously a contrived example but the concept of making a copy of a dict is relatively prevalent one): 

```
c = dict({ "a": 1, "b" : 2 })
d = dict(c)
d["a"] = 2

# Now 
# d["a"] -> 2
# c["a"] -> 1
```

In transcrypt, if one attempts to do this, the js runtime throws a `TypeError: Cannot redefine property: __class__` exception because the `Object.defineProperty` method is invoked on `c` to create dict `d`. Per the [documentation here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), the properties added through this method are immutable.

I've noticed that sometimes it throws on redefinition of `__iter__` and sometimes on `__class__` - not sure why it isn't consistent.

**Comment by JdeH** [comment]
Fine!
