### ISSUE TITLE
Possibility of using ES6 "destructuring assignment"?

### ISSUE THREAD

**Issue by daboross** [QQuick/Transcrypt#244]
Currently, when writing something like this:

```python
a, b, c, d = 1, 2, 3, 4
e, f = {}, {}
e['a'], f['b'] = 5, 6
```
Transcrypt creates something like this:
```javascript
var __left0__ = tuple ([1, 2, 3, 4]);
var a = __left0__ [0];
var b = __left0__ [1];
var c = __left0__ [2];
var d = __left0__ [3];
var __left0__ = tuple ([dict ({}), dict ({})]);
var e = __left0__ [0];
var f = __left0__ [1];
var __left0__ = tuple ([5, 6]);
e ['a'] = __left0__ [0];
f ['b'] = __left0__ [1];
```

I don't yet know enough about the python AST to do this, but I believe it could instead be translated to something like this:

```javascript
var [a, b, c, d] = [1, 2, 3, 4];
var [e, f] = [dict ({}), dict ({})];
[e ['a'], f ['b']] = [5, 6];
```

One thing I don't know how we should/would handle is Python code like `e['b'], a = 3, 4`, but maybe it could be turned into JavaScript like the following?
```javascript
var a;
[e ['b'], a] = [3, 4];
```

This wouldn't be high priority, but I believe it could be possible, and would definitely make the produced code 'cleaner'.

**Comment by geatec** [comment]
I've thought about this one for quite a while.
Simulation of the destructuring assignment had a very complicating influence on the code generator, not only for assignment, but e.g. also for the "for" loop.

I't be very glad to get rid of it! Only I am not yet sure if JS destructuring can over all the cases Python destructuring can, seem to remember that there were some problems with it, although I forgot which.

Another thing is that we still have to support JS5, so this complicated, recursive generation code cannot go from Transcrypt yet.

All in all the subject was so thorny to me that I at least postponed it. I'd like to keep on doing so until JS6 becomes ubiquitous and then give it more priority. But in the end I hope indeed these complicated "polyfills" can go.

Agreed to postpone for a while?

**Comment by daboross** [comment]
Yeah, postponing sounds good!
