### ISSUE TITLE
Autotest gives non-specific error 

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#255]
When errors were in a testlet, message "No Valid UI instance yet" was shown.
This made it very hard to find the cause of that feat.
So I made it reraise the original exception.

```
 -				# Error - no UI yet
 -				raise Exception("No Valid UI instance yet")
 +				# Error - No UI yet, reraise specific exception to enable finding out why
 +				raise
```

@RCL-Carl, since you're the subject owner on this: Is that OK for you?
Or is something more clever needed.
I can very well live with this now.

KR
J

**Comment by RCL-Carl** [comment]
Yes - that is the better way to manage this. I think part of the problem is when the Python implementation has an issue and there is no UI at all to setup.

**Comment by JdeH** [comment]
Ok, thanks!
