### ISSUE TITLE
Parentheses aren't translated

### ISSUE THREAD

**Issue by daboross** [QQuick/Transcrypt#256]
This seems like something we might want, I seem to remember there being an existing issue about this but I couldn't find it. I noticed this recently, when creating a function which accepts multiple types of parameters. Here's a simplified example:

```python
def is_yellow(obj):
    """
    Tells if obj or obj's ColorScheme is 'yellow'.
    """
    return (obj.colorScheme or obj).color == 'yellow'
```
This is translated into the following (incorrect) JavaScript code, which returns an object's color scheme rather than the intended boolean output:

```javascript
var is_yellow = function (obj) {
    return obj.colorScheme || obj.color == 'yellow';
};
```

Ideally it would generate something like this:

```javascript
var is_yellow = function (obj) {
    return (obj.colorScheme || obj).color == 'yellow';
};
```

While most things affected by this could be fixed easily be fixed easily by splitting out `obj.colorScheme or obj` into a separate variable, the behavior is currently counter intuitive, and it took quite a bit of time for me to figure out why this wasn't working.

I'm not at all sure what would need to be changed to fix this, but I think it would be ideal to either fix this, or document the behavior.

**Comment by JdeH** [comment]
That's a tricky one!
Amazing how these things keep coming out.
Putting parenthesis around every boolean or logical expression seems overkill.
Since CPython does it right, the AST must hold enough info to solve it.
I'll look into it a.s.a.p.

**Comment by daboross** [comment]
OK, awesome! I'm also looking around, but there doesn't seem to be any easy way to get the info on what parentheses were used in the source.

If that's the case, do you think this could also be solved by storing contextual data on what the 'parent' node is? Maybe with some kind of 'order of priority' list, where if a parent has a higher priority than a sub node, surround it in parenthesis. I'm not sure if that'd be at all possible, but it would all I would think to do if the AST nodes don't have the data.

**Comment by JdeH** [comment]
Fixed and committed compiler.py:

```
    def visit_Attribute (self, node):
        if type (node.value) in (ast.BinOp, ast.BoolOp, ast.Compare):
            self.emit ('(')

        self.visit (node.value)

        if type (node.value) in (ast.BinOp, ast.BoolOp, ast.Compare):
            self.emit (')')

        self.emit ('.{}', self.filterId (node.attr))
```

Testcase added to div_issues testlet, python:

```
    def issue256 ():
        autoTester.check ('Issue 256')

        class C:
            def __init__ (self, value):
                self.value = value

        def f1 (value):  # Generate parens after return
            return (C (value) .value or 'second') .capitalize () == 'First'
            
        def f2 (value):  # Generate parens after return
            return (C (value) .value or 'second') .capitalize () == 'Second'
            
        def f3 (value):  # Generate NO parens after return
            return C (value) .value or 'second'
            
        def f4 (value):  # Generate NO parens after return
            return (C (value) .value or 'second')
                
        autoTester.check (f1 ('first'))
        autoTester.check (f1 (''))
        autoTester.check (f2 ('first'))
        autoTester.check (f2 (''))
        autoTester.check (f3 ('first'))
        autoTester.check (f4 (''))
        
    issue256 ()

```

JavaScript:

```
    var issue256 = function () {
        autoTester.check ('Issue 256');
        var C = __class__ ('C', [object], {
            get __init__ () {return __get__ (this, function (self, value) {
                self.value = value;
            });}
        });
        var f1 = function (value) {
            return (C (value).value || 'second').capitalize () == 'First';
        };
        var f2 = function (value) {
            return (C (value).value || 'second').capitalize () == 'Second';
        };
        var f3 = function (value) {
            return C (value).value || 'second';
        };
        var f4 = function (value) {
            return C (value).value || 'second';
        };
        autoTester.check (f1 ('first'));
        autoTester.check (f1 (''));
        autoTester.check (f2 ('first'));
        autoTester.check (f2 (''));
        autoTester.check (f3 ('first'));
        autoTester.check (f4 (''));
    };
    issue256 ();
```

**Comment by daboross** [comment]
Ok, thanks!
