### ISSUE TITLE
UTF-8 'à' characters

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#261]
Hi,

I'm having issue with 'à' character.

Python UTF-8 file
test = "àâäéèêëiîïoôöùüû"

gives

Javascript UTF-8 file
var test = 'Ĝxa0âäéèêëiîïoôöùüû';

Thanks

**Comment by geatec** [comment]
That's a weird problem!
Have not yet been able to solve it, but posed the following question on StackOverflow:

o generate JavaScript from Python in the Transcrypt Python to JS compiler, Python 3.5's ast module is used in combination with the following code:

```
class Generator (ast.NodeVisitor):
    ...
    ...

    def visit_Str (self, node):
        self.emit (repr (node.s))

    ...
    ...
```
This works fine e.g. for the following line of Python:

`test = "àâäéèêëiîïoôöùüû"`
which is correctly translated to:

`var test = 'âäéèêëiîïoôöùüû';`
Only the character à gives problems:

test = "àâäéèêëiîïoôöùüû"
is translated to:
`
var test = 'Ĝxa0âäéèêëiîïoôöùüû';`
However the following simple script:

`print ("àâäéèêëiîïoôöùüû")`
does the right thing.

Seems repr can't deal with character à.

Are there any alternatives to generate a correct string literal that may contain all kinds of quotes etc.

I've been trying all kinds of solutions like using:

`decode('unicode_escape')`
but I can't seem to find the right way to do this. Anyone knows what's a correct way to generate an arbitrary JavaScript 5.0 / 6.0 string literal from an arbitrary Python 3.5 / 3.6 string literal?

**Comment by JdeH** [comment]
That's a weird problem!
Have not yet been able to solve it, but posed the following question on StackOverflow:

To generate JavaScript from Python in the Transcrypt Python to JS compiler, Python 3.5's ast module is used in combination with the following code:

```
class Generator (ast.NodeVisitor):
    ...
    ...

    def visit_Str (self, node):
        self.emit (repr (node.s))

    ...
    ...
```
This works fine e.g. for the following line of Python:

`test = "àâäéèêëiîïoôöùüû"`

which is correctly translated to:

`var test = 'âäéèêëiîïoôöùüû';`

Only the character à gives problems:

test = "àâäéèêëiîïoôöùüû"

is translated to:
`
var test = 'Ĝxa0âäéèêëiîïoôöùüû';`

However the following simple script:

`print ("àâäéèêëiîïoôöùüû")`

does the right thing.

Seems repr can't deal with character à.

Are there any alternatives to generate a correct string literal that may contain all kinds of quotes etc.

I've been trying all kinds of solutions like using:

`decode('unicode_escape')`

but I can't seem to find the right way to do this. Anyone knows what's a correct way to generate an arbitrary JavaScript 5.0 / 6.0 string literal from an arbitrary Python 3.5 / 3.6 string literal?

**Comment by JdeH** [comment]
o open a Python file for parsing, use

tokenize.open
rather than the ordinary

open
function.

It will open, read the pep263 coding hint and return the open file as if it were opened by the ordinary open using the right encoding.

Quite hard to find, not currently in the Green Tree Snakes doc. Actually found in by searching for 'coding' in the CPython sources on GitHub.

**Comment by JdeH** [comment]
Fixed & committed.
Thanks for reporting!

Jacques

**Comment by bradiso** [comment]
Faster than light ^^
Thanks a lot.

Just when I found a dirty hack you fixed it :)

My useless hack : 
    def visit_Str (self, node):
        import json
        self.emit('{}', json.dumps(node.s, ensure_ascii=False))

**Comment by JdeH** [comment]
Well, if I hadn't found it, I would have appied a hack myself...

**Comment by fzzylogic** [comment]
50c.. I'm using "Windows Subsystem for Linux" on Win 10 with anniversary update, which basically gives you a bash shell under windows. I started using it a while ago because I was having issues transcrypting certain unicode characters under the windows command shell. Transpiling your test string under the bash shell returns the correct results.. 

So i went to the normal windows command prompt and tried from there and it gives the same error you had (except that notepad++ asserts my output js file is in ANSI format, though I'm definitely not looking at ANSI characters). 

Remembered [someone had a similar problem](https://github.com/QQuick/Transcrypt/issues/151) a while ago that was resolved by forcing Transcrypt to import in utf-8 format. Since the problem here seemed to be output, i set transcrypt to output to utf-8 in line 299 in Lib\site-packages\transcrypt\modules\org\transcrypt\compiler.py which resulted in the correct output (though the file is still claimed to be in ANSI format by notepad++). 

Hope that helps you.

**Comment by JdeH** [comment]
@fzzylogic : To make it work for utf-8 I actually should have applied @neriusmika 's fix on two places. But with the current fix (on two places) it will work for any encoding.

KR
J

**Comment by bradiso** [comment]
Hi again,

It's not working as expected for me. Maybe I'm missing something.

Attached a ZIP archive containing a basic test case.
[issue.zip](https://github.com/QQuick/Transcrypt/files/708590/issue.zip)

The bad.js provided is transpiled from previous Transcrypt version (the one before this commit), because the newer refuses to do the job.

Thanks

**Comment by bradiso** [comment]
oops, <html> is missing in index.html but it is not what makes it wrong.

**Comment by JdeH** [comment]
I've tried the following code:

```
a_string = 'à'.encode ('utf-8')
print (a_string)

b_string = '₩'.encode ('utf-8')
print (b_string)

a_bytes = a_string.decode ('utf-8')
print (a_bytes)

b_bytes = b_string.decode ('utf-8')   # This line give an error: Character maps to undefined
print (b_bytes)
```

Note the comment with the error message. What this means is that CPython 3.5 seems to think that while the byte sequence resulting from encoding  'à' is part of the regular utf-8 chars,  the byte sequence resulting from encoding '₩' isn't part of the code page but rather maps to undefined.

KR
Jacques

**Comment by bradiso** [comment]
Many thanks for your responsiveness. So meanwhile I use my dirty hack with your previous commit.

KR

**Comment by JdeH** [comment]
Seems this is a Windows problem:

[Answers on stackoverflow ](http://stackoverflow.com/questions/41680270/python-3-5-cant-decode-korean-won-currency-symbol?noredirect=1#comment70558525_41680270)

**Comment by bradiso** [comment]
Yes, I know outputing UTF-8 to Windows terminal is prone to error on Windows, that's why is prefer use a file to output.

repr (node.s) output is wrong, while json.dumps(node.s, ensure_ascii=False) is right.

I tested it on bigger project and it's ok. I can't say what's wrong with repr.

Try it (compiler.py on commit  9040707) : 

    def visit_Str (self, node):
        import json
        with open("test.txt", "a") as myfile:
            myfile.write("node.s [%s], repr (node.s) [%s], json.dumps [%s]\r\n" % (node.s, repr (node.s), json.dumps(node.s, ensure_ascii=False)))

        self.emit ('{}', repr (node.s)) # Use repr (node.s) as second, rather than first parameter, since node.s may contain {}

**Comment by bradiso** [comment]
So finally, this is working fine for me : 

    def visit_Str (self, node):
        import json
        self.emit('{}', json.dumps(node.s, ensure_ascii=False))

**Comment by bradiso** [comment]
This is working with repr, looks like file output has to be opened with argument encoding='utf-8'

```
import json

s = "à â ä é è ê ë i î ï o ô ö ù ü û Ѫ Ԋ ₩"

with open("wrong.txt", "w", encoding='utf-8') as myfile:
	myfile.write("s [%s], repr(s) [%s], json.dumps [%s]\r\n" % (s, repr(s), json.dumps(s, ensure_ascii=False)))
```

**Comment by JdeH** [comment]
I've tried on Linux, there it works fine.
So it's indeed a Windows code page problem.
I'll keep your hack in mind for emergencies...

**Comment by JdeH** [comment]
@bradiso Your latest comment REALLY seems to solve the problem!!

Since I also want it to work for other encodings, I'll still have to find out the encoding of the source file.
Or just bluntly encode the target as utf-8 anyhow.

This is coming close to a solution.

**Comment by bradiso** [comment]
Glad it helped. Your transpiler is wonderful and it deserves to be known among Python community. Big javascript code maintenance is a pain. I'm going to rewrite javascript source files to Python when I have to modify it.

**Comment by JdeH** [comment]
All target files are now utf-8

In transcrypt/modules/org/transcrypt/utils.py, line86:
```
def create (path):
    os.makedirs (os.path.dirname (path), exist_ok = True)
    return open (path, 'w', encoding = 'utf-8')
```

This seems a solid solution, utf-8 should be able to code anything, so no other output codings needed.
Thanks for the contribution!

**Comment by fzzylogic** [comment]
@bradiso Thanks for contributing towards this. Works my side too, which makes me very happy :-).
