### ISSUE TITLE
@classmethod does not pass arguments as in Python

### ISSUE THREAD

**Issue by RunasSudo** [QQuick/Transcrypt#263]
MWE:

```python
class AClass:
	@classmethod
	def a_class_method(*args):
		print('args:')
		print(args)
		if this == AClass:
			print('this was AClass')

AClass.a_class_method('first parameter', 'second parameter')
```

In python, this prints:

```
args:
(<class '__main__.AClass'>, 'first parameter', 'second parameter')
args[0] was AClass
Traceback (most recent call last):
  File "mwe.py", line 13, in <module>
    AClass.a_class_method('first parameter', 'second parameter')
  File "mwe.py", line 10, in a_class_method
    if this is AClass:
NameError: name 'this' is not defined
```

The first argument passed to `a_class_method` is the class on which `a_class_method` was called, `AClass`, and `this` is unsurprisingly not defined.

In Transcrypt 3.6.4, however, this prints:

```
args: 
('first parameter', 'second parameter') 
args[0] was not AClass 
this was AClass
```

In other words, Transcrypt did not pass the class as the first parameter, and passed it instead in `this`. This means that `@classmethod`s do not work as expected, as a function like:

```python
@classmethod
def another_class_method(cls, arg1, arg2):
	cls(arg1, arg2)
```

will erroneously attempt to call the first argument, rather than instantiate a new instance of the class.

**Comment by JdeH** [comment]
Good point!

The following comment in /modules/org/transcrypt/compiler.py:

```
                # Method decorators ignored, but @classmethod trivially works, since the class is the prototype of the object
                # So the object is an extension of the class, and anything you can do with a class, you can do with an object
```

is overly optimistic. It just doesn't work, after all.

So generally, method decorators are not (yet) in. I've attempted to implement them but got stuck on this first attempt. However there's a postponed issue about this and someone working on it: Possibility for method decorators? #135. It is a courageous attempt but I don't know if it will succeed.

For now the only proper thing is to label this as a limitation. Thanks for the feedback. There are some places in the docs where this should be adapted I think. Will look into that

Kind regards
Jacques
