### ISSUE TITLE
Error messages seem to point to the wrong place

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#268]
```
Error in program python_tea.py, module _weakref, line 5:
	Attempt to load module: _weakref
	Can't find any of:
		/Users/boxed/Projects/pythonista-wip/__javascript__/_weakref.mod.js
[etc]
```

My file python_tea.py doesn't have an import of _weakref, so the error message pointing me to "line 5" isn't helpful. It seems like I import a lib, that imports a lib, that imports a lib that imports _weakref. The error message should give me such a traceback I think, or at least point to the place the import is done, not my code.

**Comment by JdeH** [comment]
That's not as it should be indeed.
We'll look into that.

Thanks for the feedback!

**Comment by JdeH** [comment]
I've committed fix for this.
Could you confirm that it works for you?

Kind regards
Jacques

**Comment by boxed** [comment]
It's a bit weird the new error in my case at least:

```
Error in program python_tea.py, module pyrsistent.pyrsistent._pmap.collections._collections_abc.abc._weakrefset, line 5: 
```
but it's understandable and workable at least.

**Comment by boxed** [comment]
Actually, after looking at this a bit more I don't think the error is good enough. A stack trace style error would be vastly superior. The problem now is that you get the error message only on the last file.

**Comment by JdeH** [comment]
With regard to the error message in your example:

> Error in program python_tea.py, module pyrsistent.pyrsistent._pmap.collections._collections_abc.abc._weakrefset, line 5: 

what exactly do you mean by:

> you get the error message only on the last file

It tells you that the error is in line 5 of module `_weakrefset`,

which can be reached from your main module by the qualified name:

`pyrsistent.pyrsistent._pmap.collections._collections_abc.abc._weakrefset`

Seems to me that exactly pinpoints the error.
But probably am I missing something important.

What information exactly to your opinion is missing here that you need to locate (and correct) the problem?

Could you perhaps give an example of what in your view the output should look like in this case.

**Comment by boxed** [comment]
Well it's sort of like an ImportError so you'd want the lines of the imports leading up to it. So something like:

foo.py:5
pyrsistent.py:8
_pmap.py:2
Etc

Hopefully with full paths to the files. Another problem I have is that the code I'm trying to use does try/importerror but the transcrypt compiler goes through it all of course. I have to create stub files with "raise ImportError" in them :P

**Comment by JdeH** [comment]
The stacktrace-style error reporting has been added and committed.

About the 'raise ImortError': Indeed import is resolved compile time, so unfortunately exceptions in it cannot be caught at runtime.
