### ISSUE TITLE
import socket

### ISSUE THREAD

**Issue by TNT-Samuel** [QQuick/Transcrypt#270]
I cannot use the python socket module
It says:

C:\Users\Owner\Desktop\Coding Projects\chatserver>Transcrypt import_test.py -b
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.4
Copyright (C) Geatec Engineering. License: Apache 2.0

```
Error in program import_test.py, module _socket, line 49:
        Attempt to load module: _socket
        Can't find any of:
                C:/Users/Owner/Desktop/Coding Projects/chatserver/__javascript__/_socket.mod.js
                C:/Users/Owner/Desktop/Coding Projects/chatserver/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/site-packages/transcrypt/modules/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/site-packages/transcrypt/modules/__javascript__/_socket.mod.js
                C:/Program Files (x86)/Python36-32/Scripts/__javascript__/_socket.mod.js
                C:/Program Files (x86)/Python36-32/Scripts/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/python36.zip/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/python36.zip/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/DLLs/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/DLLs/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/site-packages/__javascript__/_socket.mod.js
                c:/program files (x86)/python36-32/lib/site-packages/__javascript__/_socket.mod.js

Aborted
```

------------------------------------------------------------------------------------------------
Python File:

```
class Test:
    def __init__(self):
        print("HI")
        try:
            import socket
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        except Exception as ex:
            print("Error: " + str(ex))
```

**Comment by JdeH** [comment]
Hi,

Some tips:

- Transcrypt is a compiler, rather than an interpreter this means that imports are done compile time, to be able to compile also the imported modules. Since they are compile-time, they cannot be runtime conditional, generate runtime exceptions etc.. If you need compile time condional imports use \_\_pragma\_\_ ('ifdef', ... which works compile time
- You'll need websockets rather than the CPython sockets module, which is probably written in C, hence cannot run in a browser. Since you can use any JS library or API function, you can use e.g. HTML5 web sockets or any JS socket lib.
- In general, for Transcrypt, use JS libraries, since they're most suited to do their work in the browser.

Hope this helps, otherwise let me know.

**Comment by TNT-Samuel** [comment]
thx

**Comment by JdeH** [comment]
Since your question could also help others, could you repost on stackoverlflow under the [transcrypt] label.

http://stackoverflow.com/questions/tagged/transcrypt

No obligation of course, just if you find the time.

**Comment by TNT-Samuel** [comment]
Do you know any python libraries that i can use as websockets does not work as it requires sys

**Comment by JdeH** [comment]
You should use the Python websockets package only on the server side, so not with Trancrypt.

What I meant is that on the client you should use JavaScript websockets functionality as decribed a.o. at the following locations:

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

and

https://www.tutorialspoint.com/html5/html5_websocket.htm

**Comment by TNT-Samuel** [comment]
thanks for the great support!
