### ISSUE TITLE
Cannot find module?

### ISSUE THREAD

**Issue by jarradh** [QQuick/Transcrypt#272]
I created a file that imports my pure python module and runs a function, my hopes where to run transcrypt  on this and get my module as a javascript file with my example function as a hook into it.

Unfortunately it appears to `Attempt to load module ... Can't find any of  ....` error. 

Unsure what I am doing wrong or how can I transcrypt a module ?

**Comment by JdeH** [comment]
Hi 

Sounds like what you want should be entirely possible.
Could you give me what's on the dots, so the exact, complete error mesage.
Also I'd like to know which Transcrypt version you're using.

Kind regards
Jacques

**Comment by jarradh** [comment]
Thanks for the timely response.

https://github.com/ethereum/viper is the package


test.py:
```
#!/usr/bin/env python3

import viper
from viper import compiler_plugin

compiler = compiler_plugin.Compiler() 

code = '''
funders:{sender: address, value: wei_value}[num]
nextFunderIndex:num
beneficiary:address
deadline:timestamp
goal:wei_value
refundIndex:num
timelimit:timedelta

# Setup global variables
def __init__(_beneficiary: address, _goal: wei_value, _timelimit: timedelta):
    self.beneficiary = _beneficiary
    self.deadline = block.timestamp + _timelimit
    self.timelimit = _timelimit
    self.goal = _goal

# Participate in this crowdfunding campaign
def participate():
    assert block.timestamp < self.deadline
    nfi = self.nextFunderIndex
    self.funders[nfi] = {sender: msg.sender, value: msg.value}
    self.nextFunderIndex = nfi + 1

# Enough money was raised! Send funds to the beneficiary
def finalize():
    assert block.timestamp >= self.deadline and self.balance >= self.goal
    selfdestruct(self.beneficiary)

# Not enough money was raised! Refund everyone (max 30 people at a time
# to avoid gas limit issues)
def refund():
    ind = self.refundIndex
    for i in range(ind, ind + 30):
        if i >= self.nextFunderIndex:
            self.refundIndex = self.nextFunderIndex
            return
        send(self.funders[i].sender, self.funders[i].value)
        self.funders[i] = None
    self.refundIndex = ind + 30
'''

print(compiler.compile(code))
```

and the output

```
(testpackage) a_:viper/ (feature/examples✗) $ cd blah                                                                                                                                                                           [18:09:03]
(testpackage) a_:blah/ (feature/examples✗) $ transcrypt                                                                                                                                                                         [15:21:37]
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.5
Copyright (C) Geatec Engineering. License: Apache 2.0

Usage: transcrypt [-h] [-a] [-b] [-c] [-d] [-dc] [-da] [-de] [-dm] [-dt] [-ds]
                  [-e [esv]] [-f] [-g] [-i] [-jk] [-jm] [-k] [-l] [-m] [-n]
                  [-o] [-p [parent]] [-r] [-s [symbols]] [-t] [-v] [-x ext]
                  [-*]
                  [source]

Aborted
(testpackage) a_:blah/ (feature/examples✗) $ transcrypt test.py                                                                                                                                                                 [15:21:42]
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.5
Copyright (C) Geatec Engineering. License: Apache 2.0


Error in program test.py, line 3:
	Attempt to load module: viper
	Can't find any of:
		/Users/a_/Backup/Experiments/testpackage/experiments/viper/blah/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/experiments/viper/blah/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/transcrypt/modules/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/transcrypt/modules/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/bin/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/bin/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python36.zip/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python36.zip/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/lib-dynload/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/lib-dynload/__javascript__/viper.mod.js
		/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/__javascript__/viper.mod.js
		/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/viper-0.0.1-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/viper-0.0.1-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/serpent-1.16-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/serpent-1.16-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/__javascript__/viper.mod.js
		/Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/__javascript__/viper.mod.js


Aborted
(testpackage) a_:blah/ (feature/examples✗) $
```

**Comment by fzzylogic** [comment]
Hi

Interesting project by the way.

There are some differences in the way Transcrypt handles module imports that are [documented here](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html). 

It may be useful to see how some [existing pure python modules](https://github.com/QQuick/Transcrypt/tree/master/transcrypt/modules/) have been handled.

I noticed that parser.py requires some standard library modules that cannot currently be compiled to javascript: Crypto.Hash | sha3, ast, tokenize, binascii, io, copy. That's not the reason for the current problem, but will be further down the list. I've not used modules with transcrypt, but hope this helps.

**Comment by JdeH** [comment]
Due to your imports, Transcrypt is looking for viper.py. Since it can't find that it assumes that viper is a JS-only module and it starts looking for viper.mod.js.

Seems it's looking for viper.py in the wrong places.
From the error report you can deduce where it has been looking before it assumed that viper was a JS-only module and started to look in all those __javascript__ subdirectories.

It will have attempted to find any of the following:

    /Users/a_/Backup/Experiments/testpackage/experiments/viper/blah/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/transcrypt/modules/viper.py
    /Users/a_/Backup/Experiments/testpackage/bin/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python36.zip/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/lib-dynload/viper.py
    /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/viper-0.0.1-py3.6.egg/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/serpent-1.16-py3.6.egg/viper.py
    /Users/a_/Backup/Experiments/testpackage/lib/python3.6/site-packages/ethereum-1.3.7-py3.6.egg/viper.py

Seems viper.py is in none of these locations.
Right?

**Comment by jarradh** [comment]
yeah there is no such thing as viper.py, 
it's an egg and installed via `python setup.py install` 

as for dependencies they can mostly be cleaned up or made pure if it's possible to transpile

**Comment by JdeH** [comment]
No further info.
Solved?
Will close it for now, feel free to reopen.
