### ISSUE TITLE
Transcrypt fails on "a, b, *c = foo" style destructuring

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#273]

**Comment by JdeH** [comment]
This is currently a limitation, and one I hadn't noticed at that, so thanks!

Transcrypt's destructuring mechanism was designed before JS6 came out, supporting its own flavor of destructuring.
The result is that destructuring code currently is more verbose than needed if compiled to JS6.
The plan is to wait until JS6 has spread more widely, and then improve the TS destructuring mechanism to as much as possible use JS destructuring directly.
I think that's the best time to deal with this issue.

So I currently label this as an limitation and enhancement and close it, but with the label postponed (see #258). As soon as JS6 is really mainstream, or even JS7 is rolled out, all items carrying the label postponed will be reassessed and, if they can be solved efficiently in JS6 or JS7, be reopened and dealth with.

**Comment by jdthorpe** [comment]
related to this, the spread operators don't work either:

```
a = {'a':1}
b = {'b':2}
c = { **a, **b }
```
