### ISSUE TITLE
SyntaxError: Cannot delete unqualified property 'foobar' in strict mode.

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#274]
Deleting local variables is translated to the javascript command to delete a variable:

```python
foo = 1
del foo
```

becomes

```javascript
var foo = 1;
delete foo;
```
but that's not legal in modern javascript: http://stackoverflow.com/questions/16652589/why-is-delete-not-allowed-in-javascript5-strict-mode

**Comment by JdeH** [comment]
Quite right, it can only be used for methods and attributes.
Will look if there's a simple way to detect the case above and give decent error report.
Expected to be no problem.

**Comment by boxed** [comment]
Just not generating the delete is probably fine.

**Comment by JdeH** [comment]
Yes, that's best, since it doesn't alter semantics.

**Comment by boxed** [comment]
Unless someone does something crazy like inspecting locals() but that's a bit of an edge case :P

**Comment by JdeH** [comment]
Well, the only thing to be a bit worried about here, is that a developer may think he frees a lot of memory, while actually he don't...

**Comment by JdeH** [comment]
Fixed and committed
Feel free to reopen if not OK

**Comment by boxed** [comment]
Awesome. 

You guys are impressively quick I must say!
