### ISSUE TITLE
__new__ with calls to super results in errors

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#275]
I'm trying to use functools.partial but it has a `__new__` with a call to super. The resulting code is:

```javascript
var self = super (partial, cls).__new__ (cls);
```

which gives me the error message "SyntaxError: super is not valid in this context."

**Comment by boxed** [comment]
Ah, just saw #26. Closing this.

**Comment by JdeH** [comment]
Maybe it's time to have super ().
BTW your feedback is super!

**Comment by boxed** [comment]
Yea, I think you need super() for most non-trivial code. 

Thanks! I am working on a test run of implementing the Elm architecture with transcrypt+pyrsistent. Turns out pyrsistent uses quite a bit of the standard library that transcrypt doesn't support so I'm working my way around one obstacle at a time... hopefully it's workable. I'd hate to have to reimplement or fork pyrsistent.

**Comment by JdeH** [comment]
Which parts of the standard lib are you missing most?
We're looking into gradually supporting standard lib support.

**Comment by boxed** [comment]
datetime seems pretty obvious to me. For pyrsistent I've created stubs for _operator, abc, builtins, collections, functools, operator, os, sys so far and I just hit collections.abc. It's a bit spaghetti how stdlib modules depends on each other :P
