### ISSUE TITLE
"a @= b" is translated to "a None= b"

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#276]
A crash with "unsupported syntax" would have been preferable :P

**Comment by boxed** [comment]
And `@`  by itself is translated to `None`

**Comment by boxed** [comment]
...and `**` and `**=`

**Comment by JdeH** [comment]
Many ?= operators were initially left out to keep things lean.
But since they are repeatedly missed, they will be added (issue #264)
Same holds for **, so it will be added in a nearby commit.

**Comment by JdeH** [comment]
M2 @= M1 now translated to M2 = M2 @ M1

**Comment by JdeH** [comment]
Operator **= added

**Comment by JdeH** [comment]
True in-place overloads added for @=, **=, %=, *=, /=, +=, -=, <<=, >>=, |=, ^=
#283
