### ISSUE TITLE
"new" is not a keyword in python, but in JS, should rename it?

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#277]
I had some code like

```python
old = something()
new = old.transform(...)
```
the second line is translated into `var new = ...` which of course is invalid. Maybe just rename it "new_"?

**Comment by JdeH** [comment]
Will create an alias for that.
In line with other aliases will call it py_new.
So name `new` in Python will generate name 'py_new' in JS.
And the `__new__ `function covers the use of the `new` operator in JS.

**Comment by boxed** [comment]
Great!

**Comment by JdeH** [comment]
Just forgot...

**Comment by JdeH** [comment]
Fixed and committed
Feel free to reopen if not OK
