### ISSUE TITLE
Missing builtin: bin

### ISSUE THREAD

**Issue by boxed** [QQuick/Transcrypt#278]

**Comment by boxed** [comment]
And no `.format` on strings which was the workaround I tried first...

**Comment by daboross** [comment]
`bin` doesn't seem too hard to implement! `.format` on strings does exist though, and works well for me - what are you trying specifically that doesn't work?

**Comment by boxed** [comment]
```
"{0:b}".format(val)
```
got an error that format didn't exist.

**Comment by daboross** [comment]
```python
val = 3
print("{0:b}".format(val))
```
works for me, at least in terms of the function existing.

The format implemented by Transcrypt is fairly light-weight, and I don't believe it supports anything besides the basic `{}` and `{x}` syntax. That string is formatted just directly as `{0:b}`, but it does not error for me.

How are you compiling/running the code?

**Comment by boxed** [comment]
Ah crap, yea you're right. It does exist (although gives the incorrect output as you say). It really should fail on unsupported formatting options I think. 

My problem was that str.count didn't exist. I misread the error.

**Comment by daboross** [comment]
Yeah, it definitely isn't a full implementation of the Python format function, it does work for, well, I guess very basic formatting. Doesn't look like it checks for formatting options at all (implemented at https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js#L1063).

**Comment by JdeH** [comment]
The Python mini-formatting language was not implemented, mainly to keep the code lean.
If it's implemented, it (and similar functions) should probably in an extension module.
I feel I'll have to come up with a basic concept first.
If it's in an extension module anyone willing can work on it.
Currently I'll label it as a postponed enhancement.
This means I'll close it, but see #258
