### ISSUE TITLE
+= problem

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#284]
After some recent update `+=` inside opov stopped working

```python
__pragma__('opov')
li.attrs['class'] += ' dropdown'
__pragma__('noopov')
```

is translated to:
```javascript
var __getitem__ (li.attrs, 'class') = __iadd__ (__getitem__ (li.attrs, 'class'), ' dropdown');
```

and throws exception: `Uncaught SyntaxError: Unexpected token (`

**Comment by JdeH** [comment]
Thanks!

Seems the autotest has a hole in it on this spot...

**Comment by JdeH** [comment]
Fix  + autotest committed, not yet on pypi
