### ISSUE TITLE
Import of __pragma__ stub results in exception

### ISSUE THREAD

**Issue by mbrcw** [QQuick/Transcrypt#285]
I am trying to write some shared code between a django backend and a frontend written with transcrypt.

For that specific purpose i need some pragma enclosed code that runs both through transcrypt and the python in interpreter. For obvious reasons python needs a stub version for the `__pragma__` function, but because of the missing initialization of the source attribute it will result in an exception when imported.

I can monkey patch it on run time but that seems a bit hackish.

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path += ['/home/mbr/development/django/test/.venv/lib/python3.5/site-packages/transcrypt/modules']
>>> from org.transcrypt.stubs.browser import __pragma__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mbr/development/django/test/.venv/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/stubs/browser.py", line 10, in <module>
    class __main__:
  File "/home/mbr/development/django/test/.venv/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/stubs/browser.py", line 11, in __main__
    __file__ = utils.commandArgs.source
AttributeError: 'CommandArgs' object has no attribute 'source'
>>> 

```

**Comment by JdeH** [comment]
Hi,

Usually if I want to compile something both for CPython and Transcrypt I use

`transcrypt -r <sourcefile>`

in that way utils.commandArgs.source will be available, and you can import the stubs/browser module that comes with the distro.

However if all you want is get rid of the pragma's, probably that's overkill.
I wouldn't think it a big sin in that case to have your own little stubs module, only containing:

```
def __pragma__ (*args):
    pass
```
