### ISSUE TITLE
Will Transcrypt make the need to learn JavaScript obsolet?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [QQuick/Transcrypt#286]
There is no way around JS when it comes to building cool web frontends, right? Will Transcrypt change that? Will it make the need to learn JS obsolet?

Just a naive thought of a noob: Putting all the efforts (tranpilers, transscripters, frameworks, etc. etc. ) to overcome JavaScripts,s ugliness together wouldn't it be easier to invent next gen browsers which ship with Python of the box? :D

Cheers
Tset

**Comment by JdeH** [comment]
Hit Tset,

It would be great if next gen browsers would support Python natively.
Only I don't expect that to happen anytime soon.

You can build cool frontends with Transcrypt, don't need JS for that.
Still it's a good thing to master several languages.
Sometimes you need 5 lines of JS code to animate a page or use a JQ control
Transcrypt would be overkill in that case, so it's handy if you know some JS.

But for a larger application I would never choose it.
That was precisely the reason to start the Transcrypt project.

Kind regards
Jacques

**Comment by Tset-Noitamotua** [comment]
You have brought me to an idea: [prowser](https://github.com/prowser/prowser)  :smile: :smile: :smile:

**Comment by JdeH** [comment]
Could get big...
