### ISSUE TITLE
Pragmas in comments.

### ISSUE THREAD

**Issue by PerryBhandal** [QQuick/Transcrypt#295]
As far as I can tell there's no way to do a pragma in a comment. Is that correct?

My tests throw errors when I import any file that has a __pragma__ in it.  I'd prefer to avoid having to import it from the stubs library, particularly given how deep the import tree is for Transcrypt's core (or using some alternate hack like settings __pragma__ to a lambda at the top of each file). Something like the format below would be welcome.

#pragma: ('alias', 'JQ', '$')

**Comment by JdeH** [comment]
In itself a good idea.
Requires intercepting the tokenizer, since comments aren't in the AST.
Will look into this.

**Comment by JdeH** [comment]
Comment-like pragma's were added.
Note that they're required to follow indentation.
Since the tool coverage.py alreadyt uses `# pragma`, Transcrypt uses `# __pragma__` to avoid clashes.

Thanks for this clever, practical suggestion!
