### ISSUE TITLE
WebSocket requires new

### ISSUE THREAD

**Issue by shaolo1** [QQuick/Transcrypt#297]
While trying to convert some javascript to python I got an error with new.  Is this supported?

Original javascript code...
```
function create_web_socket(socket_name)
{
    var socket = null;
    if(window.WebSocket)
        socket = new WebSocket(socket_name, ['some_protocol'])  // this works
        // socket = WebSocket(socket_name, ['some_protocol']) // this generates TypeError: Constructor WebSocket requires 'new'
    else if(window.MozWebSocket)
        socket = MozWebSocket(socket_name)
    else
        console.log('WebSocket Not Supported')
    return socket
}

```

Attempt at conversion to python...

```
def create_web_socket(socket_name):
    if window.WebSocket:
        socket = new WebSocket(socket_name, ['some_protocol'])
    elif window.MozWebSocket:
        socket = MozWebSocket(socket_name)
    else:
        socket = None
        print('WebSocket Not Supported')
    return socket

```

Transpiler Version 3.6.4
Error encountered

socket = new WebSocket <SYNTAX FAULT] (socket_name, ['some_protocol'])

**Comment by JdeH** [comment]
Yes, this is supported by a function (to match Python syntax):

def create_web_socket(socket_name):
    if window.WebSocket:
        socket = __new__ (WebSocket(socket_name, ['some_protocol']))
    elif window.MozWebSocket:
        socket = MozWebSocket(socket_name)
    else:
        socket = None
        print('WebSocket Not Supported')
    return socket

**Comment by shaolo1** [comment]
That is generating 
	var socket = new (WebSocket (socket_name, list (['some_protocol'])));
Which still generates the error
	Constructor WebSocket requires 'new'

If I edit the generated code and remove the () it works
	var socket = new WebSocket (socket_name, list (['some_protocol']));

Both Firefox and Chromium are barking at this.
