### ISSUE TITLE
JSON iteration problem

### ISSUE THREAD

**Issue by shaolo1** [QQuick/Transcrypt#299]
I can't seem to figure out how to iterate over this JSON with transcrypted python.  The orginal python works as does the original javascript.  Both print the expected
5 10
3 20
... (sometimes in a different order, but that is understood and not a problem).
I tried multiple versions of iteration.  Those lines are commented out with the issues.

Original python

```
        def handle_foo_py():
            json_text = '{"5": {"foo": 10}, "3": {"foo": 20}}'
            import json
            foos = json.loads(json_text)
            print(foos)
            # for num in foos.keys(): # this works too
            # for num, v in foos.items(): # this works too
            for num in foos: # this works
                print(num, foos[num]['foo'])

```
Original javascript

```
function handle_foo_js()
{
    var json_text = '{"5": {"foo": 10}, "3": {"foo": 20}}';
    var foos = JSON.parse(json_text);
    console.log(foos);
    for(var num in foos)
    {
        console.log(num +" " + foos[num]['foo']);
    }
}

```
Attempt at transcrypt

```
def handle_foo():
    json_text = '{"5": {"foo": 10}, "3": {"foo": 20}}'
    foos = JSON.parse(json_text)
    print(foos)
    # for num in foos.keys(): # this gets no py_keys error
    # for num, v in foos.items():  # this gets no py_items error
    for num in foos: # this prints nothing...__iterable0__.length is undefined
        print(num, foos[num]['foo'])

```

**Comment by fzzylogic** [comment]
With Transcrypt, you can't iterate dicts by default using 'for i in dict:', without enabling that (cmd line -i or __pragma__('iconv'), but you can avoid having to enable it by just using the keys() member e.g.:

for key, value in dict.items():
    # do things for each key and value..

Section 3.9 of [the docs](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html) explains the reason for this.

**Comment by shaolo1** [comment]
for num, v in foos.items():  # this gets no py_items error

**Comment by fzzylogic** [comment]
One needs to do this:
`    foos = dict(JSON.parse(json_text))`

Not sure why. And also it has to be foos.items() (including the brackets)

So: 
```
def handle_foo():
    json_text = '{"5": {"foo": 10}, "3": {"foo": 20}}'
    foos = dict(JSON.parse(json_text))
    for key, value in foos.items():
        print(key, value)
```

**Comment by shaolo1** [comment]
Wrapping the return from JSON.parse() in a dict() does indeed allow the code to work with .items(), but it seems like there is an unnecessary extra level of work.  The native javascript works just fine with the return from JSON.parse().  Is this by design or something is being missed somewhere?

Thanks for the workaround though!

**Comment by JdeH** [comment]
Whereas something like {'aKey', 'aValue'} will automatically translate to a dict literal,
JSON.parse returns a pure JS object.

While the workaround is OK, another way out of this would be to port Python's json module, have its json.loads return a dict.
