### ISSUE TITLE
Autotest.html error: Uncaught ReferenceError: complex is not defined

### ISSUE THREAD

**Issue by lbell** [QQuick/Transcrypt#300]
Setting up Transcryt, and after following the solutions found here https://github.com/QQuick/Transcrypt/issues/103#issuecomment-242958627 I successfully ran  
```
transcrypt -r autotest.py
```
Results: 

```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.19
Copyright (C) Geatec Engineering. License: Apache 2.0

Ready
```
However, when I open the generated autotest.html file, I get a page with the table headings, no info, and an error in the consul: 

![transcrypt_consol](https://cloud.githubusercontent.com/assets/1029014/23618713/6b0fd5da-024e-11e7-8f2a-c5725ec65b9b.png)

Any thoughts?

**Comment by JdeH** [comment]
Hi,

The autotest contains also tests for complex numbers which need the -c switch.

Use:

transcrypt -r -c autotest.py
transcrypt -b -c -da autotest.py

The -da is to activate assertions, which are also tested.
Let me know if adding these switches works for you.

Kind regards
Jacques

**Comment by tubaman** [comment]
command line switch fixes added here: https://github.com/QQuick/Transcrypt/pull/373
