### ISSUE TITLE
zip() seems to be broken

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#301]
I've got the code
```Python
def filter_word(self, word1, word2):
    if len(word1) != len(word2):
        return False

    for c1, c2 in zip(word1, word2):
        if c1 != '_' and c1 != c2:
            return False

    return True
```

When built and run, the `zip()` code throws the error `Uncaught TypeError: shortest.map is not a function`
It claims this error is happening at `__builtin__.mod.js:526` but I can't find the code it's talking about there.

**Comment by JdeH** [comment]
Fixed and committed, autotest added.
Zipping was only tested with arrays.
Now it also works for strings.
Feel free to reopen if you still encounter problems with this.
