### ISSUE TITLE
string and list multiplication creates NaN

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#302]
In python, `'a'*5` creates `'aaaaa'`, and `['a']*5` creates `['a', 'a', 'a', 'a', 'a']`, but in transpiled code both of these examples create `NaN` which is quite a surprising difference between the base language behavior of python and javascript.

I imagine this might be something quite difficult to correct, since it only has special behaviour depending on the objects being multiplied, but I'm struggling to find a nice-looking pythonic way to create the same result in my projects.

**Comment by Levtastic** [comment]
Found the previous issue on this - my apologies

**Comment by JdeH** [comment]
Indeed, there's a switch and a pragma ('opov') to achieve 'pure Python behaviour' for this:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov

**Comment by JdeH** [comment]
Hi,

Since more people will have this question, if you find the time, please pose it on StackOverflow as well, so that can benefit from it.
There's a [Transcrypt] tag.

Kind regards
Jacques
