### ISSUE TITLE
Invalid JS when using --opov useflag

### ISSUE THREAD

**Issue by mbrcw** [QQuick/Transcrypt#304]
I get the following run time javascript error when running a simple helloworld python example transpiled with the -o/--opov useflag.
```
main2.js:180 Uncaught TypeError: __call__ is not a function
    at Object.__init__ (main2.js:180)
    at __init__ (main2.js:42)
    at main2 (main2.js:515)
    at main2.js:2339
__init__	@	main2.js:180
__init__	@	main2.js:42
main2	@	main2.js:515
(anonymous)	@	main2.js:2339
```
The following main2.py file was transpiled with the following command:
`> transcrypt --opov main2.py`

main2.py contains the following:
```python
def main():
     print("Hello World")

main()
```
For completeness:

```
> pip freeze | grep Transcrypt
Transcrypt==3.6.19
```
It has been tested in the newest versions of firefox and chrome under linux(Ubuntu 16.04)

It seems a bit weird that this should fail?

This pastebin contains the content of main2.js 

[http://pastebin.com/uegiKz4j](http://pastebin.com/uegiKz4j)

**Comment by JdeH** [comment]
Quite right, that certainly shouldn't fail.
Will look into this a.s.a.p.
Thanks!

**Comment by JdeH** [comment]
Fixed & committed.
Please reopen if you still encounter problems.

Remark: The global -- opov switch is a convenience, but it's better to use __pragma__ ('opov') locally for performance. Still, it should work, of course...
