### ISSUE TITLE
dict.popitem missing

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#306]
https://docs.python.org/3.6/library/stdtypes.html#dict.popitem

Currently getting the error `Uncaught TypeError: mydict.popitem is not a function`

(also sorry for posting so many issues recently - this library is absolutely fantastic, so of course I'm using it a lot, which is why I'm encountering issues)

**Comment by JdeH** [comment]
You issues are VERY welcome.
This is the only way for us to find and correct such things!

KR
Jacques

**Comment by JdeH** [comment]
Class dict now has popitem method.
Autotest for this issue added.
Committed too many files due to "human error" :(
Cleaned up.
