### ISSUE TITLE
hasattr() raises "Uncaught TypeError"

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#310]
Code that works in CPython raises the following when Transcrypted and run in Chrome.  Let me know if you need more context.

```
client.js:668 Uncaught TypeError: Cannot use 'in' operator to search for 'render' in N
    at hasattr (client.js:668)
    at client.js:2413
    at Function.<anonymous> (client.js:72)
    at client.js:2414
    at Function.<anonymous> (client.js:72)
    at makeBody (client.js:2480)
    at HTMLDocument.start (client.js:2520)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
```

client.js:668
```
    var hasattr = function (obj, name) {
        return name in obj;
    };
```

client.js:2413
```
if (hasattr (c, 'render')) {
	rlist.append (c.render ());
}
```

client.py source for 2413 above
```
if hasattr(c, 'render'):
      rlist.append(c.render())
```

**Comment by Michael-F-Ellis** [comment]
I can work around this by type-checking objects before passing them to hasattr().  I think it would be better, though, if hasattr () behaved in Transcrypted js as it does in CPython.

**Comment by JdeH** [comment]
Indeed that would be better.
Something wrong here.
Will look into this, thanks!

**Comment by JdeH** [comment]
After several experiments I think it's best to change Transcrypts hasattr to:

```
    var hasattr = function (obj, name) {
        try {
            return name in obj;
        }
        catch (exception) {
            return false;
        }
    };
```

This isn't completely equivalent to python semantics, but making things like
 hasattr (3, __add__) work would lead to bloated code.

This change will be in the next commit.

Kind regards
Jacques

**Comment by Michael-F-Ellis** [comment]
Thanks, that seems adequate for my typical usage.
