### ISSUE TITLE
Ann: Web App skeleton using Transcrypt

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#311]
I put together a little skeleton app that uses Transcrypt and Bottle to create a very minimalist pure Python web app framework.  Feedback welcome.

https://github.com/Michael-F-Ellis/NearlyPurePythonWebAppDemo

Thanks, Jacques, for making it possible!

**Comment by fzzylogic** [comment]
Fantastic, thanks so much for sharing!

**Comment by JdeH** [comment]
This is very elegant!!
It's one of the things I hoped someone would start doing...

**Comment by Michael-F-Ellis** [comment]
Thanks, Jacques and fzzylogic! 

I've added an input field to change the step size to make the app a complete demo with i/o in both directions between client and server.

**Comment by Michael-F-Ellis** [comment]
[New release](https://github.com/Michael-F-Ellis/NearlyPurePythonWebAppDemo/releases/tag/0.5.1) has demo with <meter> elements and slider instead of text field for setting step size. Also demonstrates how to put everything in one file (allinone.py)

Here's the trick I came up with for mixing CPython source and Transcrypt source in the same file:

```
## Common Code here.  (whatever can be used by both client and server) ##

try:
    __pragma__('js', '')
except NameError:
    # __pragma__('skip')

    ## Server Code here. (Executed by CPython, ignored by Transcrypt) ##

    # __pragma__('noskip')
    pass  ## So Transcrypt doesn't see an empty except clause.
else:

    ## Client Code here. (Transpiled by Transcrypt, ignored by CPython) ##
```
This seems to work beautifully. The only downside is an extra level of indentation for the server-only and client-only sections.  I can live with that.

Cheers,
Mike

**Comment by Michael-F-Ellis** [comment]
Newest is now [0.5.2](https://github.com/Michael-F-Ellis/NearlyPurePythonWebAppDemo/releases/tag/0.5.2). It adds two new simplified skeleton files.

**Comment by JdeH** [comment]
Sorry to lag back a bit, I will definitely look into this new version, but it will be some time.

**Comment by Michael-F-Ellis** [comment]
Thanks, Jacques. No hurry at all.  Looking forward to your feedback.
Cheers,
Mike

**Comment by JdeH** [comment]
Very useful!
Link added in Gallery section of Transcrypt.org
