### ISSUE TITLE
Documentation on decorators

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#312]
Hi,
Reading the documenation about decorators, it appears a bit contradictory to me:

> Transcrypt supports decorators **on methods** and classes. ......... Decorators **on methods are not supported**, ......

Decorators on methods are supported, right?
Regards,
Pieter Jan

**Comment by JdeH** [comment]
No, sorry, not yet!!
I thought they worked, but I was to optimistic...
#135

**Comment by JdeH** [comment]
Method and class decorators are now part of Transcrypt.
