### ISSUE TITLE
float(' ') returns 0

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#314]
I'm validating an input value with

```
    fail_msg = "Step size must be a number."
    v = jq('#stepinput').val()
    try:
        v = float(v)
    except ValueError:
        alert(fail_msg)
        return False
```
In CPython, passing any string that doesn't represent a decimal number to float() raises a ValueError.  

In Transcrypted js, Chrome DevTools is showing me that an empty string or one containing only space chars is coming back as 0.0.  Strings with other characters, e.g. 'asdf' fail as expected.

**Comment by Michael-F-Ellis** [comment]
I'm working around this, for now, with 
```
#__pragma__('js','{}','var vj = parseFloat(v); var isfloat = !isNaN(vj);')
```

It's really impressive that Transcrypt allows stuffing arbitrary lines of js to create vars that can referenced by the transpiled code.

Cheers,
Mike

**Comment by JdeH** [comment]
Following commit planned:

    var float = function (any) {
        if (any == 'inf') {
            return Infinity;
        }
        else if (any == '-inf') {
            return -Infinity;
        }
        else if (isNaN (parseFloat (any))) {    // Call to parseFloat needed to exclude ''
            throw ValueError (new Error ());
        }
        else {
            return +any;
        }
    };
