### ISSUE TITLE
filter() doesn't support None for func

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#316]
In the Python documentation, [filter()](https://docs.python.org/3.6/library/functions.html#filter) can take None as its filtering function, and will simply filter based on truthiness in this situation, making the following two lines of code functionally identical:
`mylist = filter(lambda item: item, self.mylist)`
`mylist = filter(None, self.mylist)`

Instead, Transcrypt generates Javascript that requires a function in the first positional argument.

**Comment by JdeH** [comment]
Thanks for the report.
It will be in the next commit.

Kind regards
Jacques
