### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#323]
Obfuscation of code is sometimes needed. Of course someone can use javascript obfuscation after compilation by Transcrypt. But Python code can also be obfuscated before compilation.

I tried using [Opy](https://github.com/QQuick/Opy). But configuration is a bit hard since all native javascript functions need to be excluded in the config file. Since Transcrypt wants to stand with both legs in the Javascript world (which I think is a good idea), obfuscation should be part of the compilation process.

Is this possible and maybe wanted by more people?

**Comment by pjbonestroo** [comment]
I now used the following javascript obfuscator:
[https://github.com/javascript-obfuscator/javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator)
It works good and solved my problems.
Nevertheless if someone tries to deobfuscate there are still some strings indicating class names and methods which could have been obfuscated by Transcrypt very easily, I think.
But it should not have high priority.
Best regards,
Pieter Jan

**Comment by JdeH** [comment]
Thanks!

I'll mark this as low prio & postponed (so close it, but it will be on the backlist).

KR
Jacques
