### ISSUE TITLE
Advice on module creation

### ISSUE THREAD

**Issue by theodox** [QQuick/Transcrypt#324]
I made a quick try at replicating the `fabric` module in the documentation for use with [Three.js](https://threejs.org/)   My intention was to make a wrapper because there is so much new object creation in Three that all those `__new__` calls were going to drive me crazy.    However I got bogged down at step one -- the anonymous function in the fabric example doesn't work for the global object `THREE` in three.js land (and yes, I did remember to change the names :) )  I assume that the initialization strategies for these modules are sufficiently different that the same trick doesn't work out of the box.  However I'm not really clear on what I'm looking for in this context apart from trying to grab a name out of the JS global scope and report it back out to my module variable.    Is there some good reference on what I want to be doing here?

**Comment by JdeH** [comment]
Hi,

A demo was added to show how to do this.
Note that only a (small) part of the `new` calls has been actually encapsulated.
But it shows how to do it.
Also note that THREE is still in the global namespace, since the three.js library itself seems to need that.
Should you find any way to circumvent that, please let me know.
But at least you won't have all those excplit `__new__` calls in your code, which now will look like:

```
from com.threejs import api

scene = api.Scene ();
camera = api.PerspectiveCamera (30, window.innerWidth/window.innerHeight, 0.1, 1000)

renderer = api.WebGLRenderer ()
renderer.setSize (window.innerWidth, window.innerHeight)
document.body.appendChild (renderer.domElement)

geometry = api.BoxGeometry (1, 1, 1 )
material = api.MeshLambertMaterial ({'color': 0xffffff})
cube = api.Mesh (geometry, material)
scene.add (cube)

ambientLight = api.AmbientLight (0x0000ff, 0.5)
scene.add (ambientLight )

directionalLight0 = api.DirectionalLight (0xff0000, 0.5)
scene.add (directionalLight0);

directionalLight1 = api.DirectionalLight (0x00ff00, 0.5)
directionalLight1.position.set (50, 50, 50)
scene.add (directionalLight1)

camera.position.z = 5

def render ():
    requestAnimationFrame (render)
    cube.rotation.x += 0.01
    cube.rotation.y += 0.01
    renderer.render (scene, camera)
    
render ()

```

**Comment by theodox** [comment]
Thanks! 

Would there be a speed hit if I did a python factory function to generate those stubs, ie:

```
def three_class(name):
     js_fn = THREE[name]
     def ctor (*args):
            js_fn(*args)
     return ctor

Scene = three_class("Scene")
PerspectiveCamera = three_class("PerspectiveCamera")
```
Or is it faster to do the inline JS as you have it here?

**Comment by theodox** [comment]
The PR  (#350 ) I made includes a complete wrapper made with the factory function above.
