### ISSUE TITLE
keyword arguments with special names

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#328]
If you make the following function:
```Python
# __pragma__('kwargs')
def build_element(tag, **attributes):
    element = document.createElement(tag)

    for key, value in attributes.items():
        setattr(element, key, value)

    return element
# __pragma__('nokwargs')
```
It mostly works as expected, except if any of the kwargs you pass are handled in a special way by transcrypt. For example, if you then do the following:
```Python
pwinput = build_element('input', type='password')
```
This code fails to set any "type" attribute on the element. The current fix in my code is to instead do the following:
```Python
pwinput = build_element('input', js_type='password')
```
This then gets converted to simply "type" in the converted code, and works as I need.

**Comment by JdeH** [comment]
The 'js_type' default alias was meant to be able to generate 'type' without clashing with the name of the builtin Python 'type' metaclass. So the way you're using it is entirely appropriate.

I've thought about this limitation for quite some time, and this solution was the best I could come up with, without necessitating a level of program semantics understanding by Transcrypt that I considered out of reach.

This is by far not the only case where the alias mechanism is a life saver, as you can see by the list of default aliases. For readers of this issue that (as opposed to @Levtastic) have not yet located it in compiler.py or in the docs:

http://www.transcrypt.org/docs/html/special_facilities.html#pragma-alias.

By the way, if anyone runs into other name clashes, you can define aliases your self.
