### ISSUE TITLE
Inability to define a class that extends from a JS class

### ISSUE THREAD

**Issue by texonidas** [QQuick/Transcrypt#329]
The most prominent example of this is when trying to use React.

All React components take the following form:
```js
class Foo extends React.Component {
    // Some code
}
```

This isn't currently possible in Transcrypt though, unless there is a specific way to tell this:
```py
class Foo(React.Component):
    # Some code
```
That React.Component is a JS class,  not a python class, and that it should be inserted as the class from which `Foo` inherits from at runtime.

**Comment by JdeH** [comment]
Hi,

I've attempted an answer at:

https://stackoverflow.com/questions/44213824/transcrypt-inherit-from-a-js-prototype/44333571#44333571

Let me know if it works for you.
Kind regards
Jacques

**Comment by texonidas** [comment]
Thanks for getting back to me! Is there an existing repo of Transcrypt wrappers for JS frameworks?

If not, I'd love to put forward that we create one.

**Comment by JdeH** [comment]
Good idea. Just wondering what's best, one repo, multile repos or a repo with subrepos. And should it be inside the qquick organisation? Opinion(s)?

**Comment by JdeH** [comment]
OK, lets cut this knot: Wrappers for JS libs are in principle welcome as a repo inside the QQuick organisation, one repo per JS lib!

Kind regards
Jacques
