### ISSUE TITLE
Negative list indexes not translated properly

### ISSUE THREAD

**Issue by shaolo1** [QQuick/Transcrypt#33]
Python

```
foo = [1, 2, 3]
print("foo last", foo[-1])

```

foo last 3

Generated Javascript

```
var foo = list ([1, 2, 3]);
print ('foo last', foo [-1]);

```

foo last undefined

**Comment by JdeH** [comment]
Thanks!

**Comment by JdeH** [comment]
Unfortunately this was left out for a reason.
Allowing negative indices in JS would mean overloading every [], which would incur an unacceptable runtime penalty.
It could be solved for index literals only:
     a[-1] would be recognized

     i = -1
    ... # lots of code with branches etc.
    a [i]

couldn't be.
This would make Transcrypt behave unpredictable.
So in this case speed and compactness has to be favored over completeness, sadly...

**Comment by AXGKl** [comment]
workarounds:

```python

    foo = [1, 2, 3]                                                                                               
    print("foo last", foo[len(foo)-1])
   # or
    print("foo last", foo[-1:][0])           
```

**Comment by JdeH** [comment]
Not sure
On one hand: handy
On the other: a bit irregular

**Comment by AXGKl** [comment]
the business man/devil in me says: lets do it, [-1], [-2] ... is what users expect and `[-1:][0]` is not what I wanted to put into a marketing document ;-)

the developer/angel in me says: No way to deliver [-1] correctly but not a=-1, [a]

funny journey all that....

**Comment by JdeH** [comment]
I think striking sensible compromises is the most difficult part of any design.
In fact I believe that IS design.

**Comment by AXGKl** [comment]
Guess you're right. 

just see that the Rubies also have a Transcrypt: Opal

They seem to not care about perf and turn every array index lookup into a function. 

<img width="903" alt="screen shot 2016-11-04 at 14 49 02" src="https://cloud.githubusercontent.com/assets/9989548/20007870/7c71602e-a29e-11e6-97b2-01a0d8cb3c73.png">

**Comment by JdeH** [comment]
I've never used Ruby, so I've no idea how handy it is.
But I know quite some system adminstrators use it.

**Comment by AXGKl** [comment]
just interesting to see how they transpile into js. Its definitely a function call, no matter the content of the square brackets.

**Comment by JdeH** [comment]
Looks like extraterrestrial to me.
But to martians it will no doubt look ok...

**Comment by JdeH** [comment]
With ref to issue #258
