### ISSUE TITLE
Understanding tests as documentation

### ISSUE THREAD

**Issue by merrellb** [QQuick/Transcrypt#333]
I am struggling to understand how the tests document behavior.  For example:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/development/automated_tests/transcrypt/proxies/__init__.py
``` 
autoTester.check (b.p, b.q, b.r, b.s)
b.p = 4
b.r = 5
autoTester.check (b.p, b.q, b.r, b.s)
```
How do we read this to understand the expected behavior?

**Comment by JdeH** [comment]
Hi, I have answered your question at:

https://stackoverflow.com/questions/44380590/understanding-how-transcrypt-autotests-document-the-code/44382927#44382927

Should you require any more info, let me know.

Kind regards
Jacques
