### ISSUE TITLE
Transcrypt on Gitter

### ISSUE THREAD

**Issue by merrellb** [QQuick/Transcrypt#334]
Would it make sense to provide a venue for folks to discuss Transcrypt in real-time?

**Comment by JdeH** [comment]
Hi

It certainly would!
I have never looked into Gitter, but I will...

KR
Jacques

**Comment by JdeH** [comment]
Should work now.
The chatroom is at:

https://gitter.im/Transcrypt/Lobby

I suppose it will be very quiet at the start.
But at least the possibility is there.

KR
Jacques

**Comment by merrellb** [comment]
Thanks Jacques.  Is it something you might eventually add to the documentation/README?

**Comment by JdeH** [comment]
I'll add it to the readme.
For the docs I will wait a while to see if Gitter works well in practice.
I've no experience in moderating it.
Had to make a separate account to avoid giving my GitHub password to Gitter.
This complicated matters a bit.
But probably it's alright.

**Comment by Wegge** [comment]
På Mon, 05 Jun 2017 21:30:53 -0700
Brian Merrell <notifications@github.com> skrev:

> Would it make sense to provide a venue for folks to discuss Transcrypt in
> real-time

Yet another re-invetion of IRC :(
-- 
//Wegge
