### ISSUE TITLE
More realistic __setattr__ and __getattr__ examples

### ISSUE THREAD

**Issue by merrellb** [QQuick/Transcrypt#336]
I would like to control how attributes are set on objects and am struggling to understand how this can be accomplished.  I see two issues:

1) There appears to be a default behavior that sets attributes regardless of what happens in `__setattr__`. 

> #Transcrypt doesn't need it, if there's no __setattrib__ it will just use self [name] = value`

2) If this default behavior can be suppressed it isn't clear to me how to actually set the attributes as I am having various struggles with `obj.__dict__`, `object.setattr` and `super().setattr`

Would it be possible to provide a more detailed example illustrating how one might use __setattr__ to modify the way attributes are stored and retrieved on objects?

**Comment by JdeH** [comment]
There are a few points to watch:

1. Compile for JS6, using e.g `transcrypt-b -m -e 6 attrib.py`

2. Provide your objects with a __dict__, bypassing the __getattr__ / __setattr__ mechanism. The simplest way to do it is:

```
class CodedStore:
    def __init__ (self):
        __pragma__ ('js', '{}', 'self ["__dict__"] = {}')

    def __setattr__ (self, name, message):
        self.__dict__ ['_' + name] = 'coded_' + message

    def __getattr__ (self, name):
        return 'decoded_' + self.__dict__ ['_' + name]
        
    def peek (self, name):
        return self.__dict__ ['_' + name]
        
s = CodedStore ()

s.john = 'brown'
s.mary = 'white'

print (s.peek ('john'))
print (s.peek ('mary'))

print (s.john)
print (s.mary) 

```

**Comment by JdeH** [comment]
The example has been uploaded as part of the transcrypt 'proxies' autotest.
