### ISSUE TITLE
ANN: htmltree.py

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#337]
I've put the htmltree.py module from NearlyPurePythonWebAppDemo into a repository of its own. 
https://github.com/Michael-F-Ellis/htmltree
Will try to get it up on PyPI when I have time.  

Cheers,
Mike

**Comment by fzzylogic** [comment]
Good idea, thanks. It's not there at the moment.

**Comment by JdeH** [comment]
I've tried to visit your repo, but the link gives me a 404.
Is it a private repo?

Kind regards
Jacques

**Comment by Michael-F-Ellis** [comment]
Oops! Now it's public. https://github.com/Michael-F-Ellis/htmltree

**Comment by Michael-F-Ellis** [comment]
Some major additions (72 tag wrappers) and a complete re-write of the readme emphasizing clean syntax.

**Comment by JdeH** [comment]
@Michael-F-Ellis 

I read the  following in your docs:

> You'll want to arrange for the htmltree.py file to be in or symbolically linked in the same directory as any other python files to be transpiled as part of your project. That's a current limitation of Transcrypt. It's on the list of issues at the Transcrypt repo and the author, Jacques de Hooge, has it on his list of upcoming enhancements.

This should not be necessary.
Unless something badly fell over it should be possible to put your modules in hierarchically organized directories that are rooted in multiple places, as described in:

http://www.transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism

Or maybe I am completely missing the point, and you refer to a limitation that I overlooked.
Please help me out on this one...

KR
Jacques

**Comment by Michael-F-Ellis** [comment]
@JdeH I'm sure the misunderstanding must be mine.  After more than a decade of active Python development, I confess I still dont *really* understand the module/package/import system. I wrote the Transcrypt section of the README in more haste than I should have and with issue #321 in the back of my mind.  BTW, thanks for the pointer in your earlier comment to Peter Downs's article on PyPi.

**Re: your list of options**
1. (pip) I like this for general users -- who may or may not be using Transcrypt.  The only thing that's hanging me up is not knowing how to set things up so that users can do `from htmtree import ...`  instead of from `from htmltree.htmltree import ...` after pip installing the package.

2. (Transcrypt modules) It's good to know about this one.  I'll add it to the README.

3. (in the project) I've done this in a more elaborate way (with git submodule) in [NearlyPurePythonWebAppDemo](http://github.com/Michael-F-Ellis/NearlyPurePythonWebAppDemo) Using git submodule allows discretion to bring in new versions of the htmltree project.  I still end up with having to import from `htmltree.htmltree`.  

4. (PYTHONPATH) Have to say I've never liked environment variables like PYTHONPATH, but I'll certainly mention it.  I find symlinks easy to create and delete at the command line without editing .bashrc or whatever is the WIndows equivalent.

My current thought is to update the README (once I've solved the htmltree.htmltree issue) with a recommendation to use option 1 and a link to a separate doc that enumerates and discusses the other options.

Cheers,
Mike

*"There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch."*

**Comment by Michael-F-Ellis** [comment]
Released version 0.7.0 and uploaded to PyPI

**Comment by JdeH** [comment]
Hey, great!!

**Comment by JdeH** [comment]
Transcrypt 3.6.28 has been uploaded, allowing you to augment the module search path either by a pragma or by a command switch.
