### ISSUE TITLE
Imported function undefined at run time

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#338]
I'm running into a problem using my revised htmltree project under Transcrypt.  There are now two modules, htmltree.py and elementwrappers.py.  Imported function wrappers are throwing errors in Transcrypt.  I think I see the location of problem with help DevTools debugger but I'm not sure what to do about it. The first of the two JS statements below succeeds but the second results in KWElement being undefined. Both Element and KWElement are defined in htmltree.py.  
```
  var Element = __init__ (__world__.htmltree).Element;
  var KWElement = __init__ (__world__.htmltree).KWElement;
```
The python code that's importing them looks like
```
from modules.htmltree import Element as E
from modules.elementwrappers import Label
```
Both modules are in a directory named "modules" and elementwrappers has the following import
```
from htmltree import Element, KWElement
```
Transcrypt isn't emitting any complaints at compile time.

Any help appreciated. Thanks!

**Comment by Michael-F-Ellis** [comment]
I'm attaching a tarball containing a reduction of the problem, its contents are:
```
-rw-r--r--  1 mellis  staff    241 Jun 21 17:15 client.py
-rw-r--r--  1 mellis  staff  15974 Jun 21 16:22 elementwrappers.py
-rw-r--r--  1 mellis  staff   9387 Jun 21 16:22 htmltree.py
-rw-r--r--  1 mellis  staff    625 Jun 21 17:16 test.py
```
Running `python test.py` will create test.html and client.js. If those succeed, it will try to open test.html using webbrowser.open.  In my testing, client.js is throwing an "Uncaught Reference Error". 

Note that test.py also serves as a test of the htmltree.py and elementwrappers.py files under CPython since it uses those to create test.html.

[bugtest.tar.gz](https://github.com/QQuick/Transcrypt/files/1092997/bugtest.tar.gz)

**Comment by the1337guy** [comment]
Can you try replacing

```python
from htmltree import Element, KWElement
``` 

with

```python
from modules.htmltree import Element, KWElement
``` ?

**Comment by Michael-F-Ellis** [comment]
@the1337guy Thanks. Unfortunately that didn't fix it. I've worked around the problems by putting everything into one file.  It's not the best solution because it precludes the option of just importing the low-level Element class (now renamed HtmlElement to avoid name conflict with JS built-in Element() but it's reliable and not too huge since the wrapper functions are one-liners.

I think I'm pushing the boundaries a bit in trying to develop a library that works the same under CPython and Transcrypt. That's ok because it's a worthwhile goal but I have to keep reminding myself that practicality beats purity.

**Comment by JdeH** [comment]
Is this already solved?
You shouldn't need to put everything in one file, modules should just work flawlessly.
Only no relative imports.

**Comment by JdeH** [comment]
No news  is good news?
Works now?
Feel free to reopen if not!
