### ISSUE TITLE
Is it possible to create tutorials like this

### ISSUE THREAD

**Issue by jeremy886** [QQuick/Transcrypt#343]
I'm thinking about using Transcrypt to create in-browser experiences like this:
[p5js simulate-force example](https://p5js.org/examples/simulate-forces.html)

I plan to use it for Y10 students.

Basically, you can edit the code and hit "run" to see the effect. Very neat. I used to use Processing.py but it needs Java and a plugin so creates a lot of issues in the classroom.

I probably need a server to compile the Transcrypt code, right?

**Comment by the1337guy** [comment]
No, you probably shouldn't use Processing.py in browser, it's meant for CPython, Transcrypt is only for Transcrypt-friendly packages.

**Comment by fzzylogic** [comment]
@jeremy886 Yes, Transcrypt compiles your python code to javascript using cpython, it doesn't do so in the browser.

**Comment by the1337guy** [comment]
@jeremy886 If you can use entr and ag (the silver searcher) you can probably edit the code in your fav. text editor and then refresh your browser, the new code will effect.

**Comment by jeremy886** [comment]
Not sure what "the silver searcher" can do? I found this: [p5.js with Python example](http://jsfiddle.net/villares/g2sL3eza)
It's based on Brython. It's probably easier if I just compile them and make sure they work with p5.js locally because my students are okay to download files and run them locally. I'll dive into transcrypt's documentation.

**Comment by the1337guy** [comment]
hmm, that means, combining entr and ag to re-transpile the sources whenever any Python sources change..

Example:

```bash
ag --python -l | entr -c -s 'transcrypt -b -m -e 6 -n main.py'
```

This is what I use.

**Comment by JdeH** [comment]
If I am understanding you correctly, you'd like something that works like the following demo:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

It features 'compile and run'. Compilation is done on the server, the resulting JS is run on the client.
Getting the source code to the server and the generated JavaScript to the client again is done by  using Ajax.

**Comment by theodox** [comment]
FWIW it seems like p5.js has an odd initialization strategy, to get a sketch running you need to promote the `setup` and `draw` functions it's expecting explicitly into the window object for them to be recognized. So

```

def setup(*args):
    pass

def draw():

    window.ellipse(50, 50, 80, 80)

window.setup = setup
window.draw = draw
```

will run the p5 "getting started" example

**Comment by the1337guy** [comment]
That's a bad way, I'm sure p5.js is not **THAT** beginner oriented that they will forget good principles and ram shit into the global namespace... Seriously?

**Comment by JdeH** [comment]
Maybe also take a look at  http://www.skulpt.org/.
Performance isn't high, but it is entirely client side.

**Comment by the1337guy** [comment]
If you are comparing Skulpt, it's beneficial to try to Brython as well.

**Comment by JdeH** [comment]
Take a look into Brython and Skulpt as well.
Performance is lower, but they are client side.
Especially Skulpt was meant for education.

**Comment by jeremy886** [comment]
Everyone, thanks.  I tried the link: http://www.transcrypt.org/live/turtle_site/turtle_site.html
The old demo remained unchanged after I tried to "compile and run" with new code.

I got the Brython version working by using their code: https://gist.github.com/jeremy886/7fcc964c32aa40f6efa07e585de40089

**Comment by JdeH** [comment]
Thanks for the tip.
I'll repair the demo!
KR
Jacques

**Comment by theodox** [comment]
@the1337guy  -- they offer an alternative method as well, but the global option is the default.  They assume a page with a sketch on it is basically a standalone web app.  
https://github.com/processing/p5.js/wiki/p5.js-overview

**Comment by jeremy886** [comment]
I tried the given example:

```
def setup(*args):
    pass

def draw():

    window.ellipse(50, 50, 80, 80)

window.setup = setup
window.draw = draw
```
1. put it in testp5js.py
2. transcrypt -b testp5js.py [ok]
3. transcrypt -r testp5js.py [NameError: name 'window' is not defined]
4. make testp5js.html
```
<html>
	<head>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/addons/p5.dom.min.js" charset="UTF-8"></script>
	</head>
	<body>
	  <script src="__javascript__/testp5js.js"></script>
	</body>
</html>

```

5. open testp5js.html


I got a blank page.
Any hints? Thanks.

**Comment by fzzylogic** [comment]
-r will run using python, however python does not have access to a DOM, so there is no window object by default under python. testp5js.js should not contain anything, since transcrypt minifies by default, so your output file should be testp5js.min.js. If you call transcrypt with the -n switch (do not minify), it should then put out the unminified version testp5js.js.

**Comment by JdeH** [comment]
@jeremy886 

Forgot to mention: The interactive demo has been repaired some time ago:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

You can now change code in your browser and recompile to see the result.
In the same way all kinds of online demo's could be made.

If your demo's involve physics and, in general, matrix/vector or signal processing applications, you may also have some benefits from: https://github.com/QQuick/Numscrypt

Kind regards
Jacques

**Comment by villares** [comment]
An example that might interest yo'all: https://4nomore.net/2018/transcrypt_p5js/
