### ISSUE TITLE
Bloat considered helpful :-)

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#346]
As an elderly ex-C programmer, I share and appreciate the instinct to make everything lean and clean -- so please consider this counter-argument as being offered with a light-hearted spirit.

For me, the mantra "Make it work, make it right and only then make it faster and smaller." took a long time to internalize, but once absorbed it seldom let me down.  It recognizes that in the early days of a project, the scarcest resource is developer time.

With respect to Transcrypt, the scarcest resource is Jacques's time as the prime developer followed by the time of those us making use of what he's developed.  I mention this because I want to distinguish between the case where fully supporting a particular CPython behavior is difficult and time-consuming to implement vs the case where it simply adds size to the generated code. 

For the latter case, my own preference would be for Transcrypt to default to full support -- however bloated -- with a path for optimizing when and where it's needed. Think of it as meta-EAFP, if you will. 

For the first case, where full support requires too much effort to implement, I'm wondering if some form of  compiler warnings with links to the doc or issues might save time for users of Transcrypt. Perhaps something like: 

 ```
WARNING: IncompletelyImplemented: strip() Optional arguments not supported. See issue #41
```

Cheers and thanks once again for developing this incredibly useful application!
Mike

**Comment by the1337guy** [comment]
Hmm, pragmas exist for a reason, pragmas could be used (and are being used) to add bloated code where needed (which otherwise, for simple reasons, don't need to exist).. I too think NotImplementedError should be raised **on runtime** if the code is trying to use something not turned on by pragmas

**Comment by Michael-F-Ellis** [comment]
@the1337guy Agree about pragmas. I like them. I'm just suggesting the defaults should be the unoptimized condition with pragmas and command line switches behaving the way most C compilers do -- no optimization unless you ask for it.

Where possible I'd rather have a compiler warning than a runtime error.  When I'm developing in CPython I keep an IPython session open and do lots of testing of a few lines at a time. That option really isn't easily available for transpiled code and browsers let most errors pass with just a message to the console. I'm not sure I'd ever get anything done without Chrome DevTools and Transcrypt's source maps. Even so, the process of figuring out what went wrong is at least an order of magnitude more effort than debugging most CPython problems.

**Comment by daboross** [comment]
I'd definitely be for emitting compiler warnings if it could be built, but that would, in my understanding, require a large shift in how the compiler operates.

Right now the compilation / translation is fairly "unknowing" about what code that's supported actually is - it just translates directly to JavaScript stuff and relies on the builtin scopes defining python builtins. There's no way to, say, know whether a variable is a string when there's a `some_var.strip()` line - the compiler literally doesn't have that information.

I think it would be awesome to build a transpiler / compiler which _could_ have that information, either through analysis or typings, but I don't think it's feasible for Transcrypt to have it without a large paradigm shift.

**Comment by JdeH** [comment]
Indeed this isn't easily solved without the compiler doing a lot more static analysis.
So I'm afraid it's off limits for now...

KR
J
