### ISSUE TITLE
not honoring ".bar" in __init__.py

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#349]
In a convenient directory, say /tmp create the following

/tmp/test.py
```
from foo import *
hello()
```

/tmp/foo/__init__.py
```
from .bar import *
```

/tmp/foo/bar.py
```
def hello():
    print('hello');
```

Under OS X and python 3.5, the test file prints `hello`,  as expected,
```
$ cd /tmp
$ python test.py
hello
```
but transcrypt 3.6.24 won't build test.py
```
cd /tmp
$ transcrypt -b -n test.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.24
Copyright (C) Geatec Engineering. License: Apache 2.0


Error while compiling (offending file last):
	File '/private/tmp/test.py', line 1, at import of:
	File '/private/tmp/foo/__init__.py', line 1, namely:
	
	Attempt to import module: bar
```

I can make both CPython and Transcrypt succeed by changing the content of  /tmp/foo/__init__.py to
```
from foo.bar import *
```
but I don't understand how import magically knows the name of the parent directory.

**Comment by Michael-F-Ellis** [comment]
... and, more important, both CPython and Transcrypt fail if I rename foo/ without remembering to edit the __init__.py within it.  The bare ".bar" import doesn't suffer that problem.

**Comment by JdeH** [comment]
Transcrypt's module import mechanism is considerably simpler than Python's, which is quite heavy weight.
To achieve this simplicity, some compromises were struck.
Specifically the statement `from .bar import *` is called a relative import and isn't supported in Transcrypt.
Directory foo is found relatively to the location of your main file test.py, not by looking up any parent directory, so no magic involved ;)

**Comment by Michael-F-Ellis** [comment]
"Python's, which is quite heavy weight" I'll say! I've read the doc several times and still get lost among the finders and loaders and namespace packages.  I think I'd go so far as to suggest it violates Zen[-3] *If the implementation is hard to explain, it's a bad idea*.

Anyway, thanks for the explanation.  Going forward my rule for imports is going to be:

Either put it in the same directory as the primary source file or package and pip install it.

**Comment by JdeH** [comment]
I don't think there's anything wrong with using subdirs of the primary source dir as well if you want to create a module hierarchy that's specific for a certain application you are creating.
