### ISSUE TITLE
After switch from py3.5 to py3.6, continuous integration seems broken.

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#354]
All tests still give OK results locally, but Travis CI fails.
This may have something to do with switching to Python 3.6 as default compiler.
It also may be connected with recent changes in the module search paths of Transcrypt.

To keep development moving, I've disabled showing results of Travis CI for now, running tests only locally before commit.
But it would be nice if this would work again.

@AXGKl  
We haven't had contact for quite some time, hope your are well.
Is it realistic that you find the time to look into this, or should I look into an other solution.
My preference is of course that you let your light shine over this, since you fathered it...

Kind regards
Jacques

**Comment by JdeH** [comment]
Fixed, module search path order was the problem, not CI!
Anyway, @AXGKl , how are you these days?

**Comment by AXGKl** [comment]
Man I'm good, hope you too!!

this year is just crazy with the company, I'm so darn sorry to not being able to invest time again in Transcrypt. But as it looks like you have strong people on board, congratulations, you are famous now :-)
