### ISSUE TITLE
How to get rid of enormous amounts of changed files

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#355]
I've tried to cleanup the repo, but at each commit GitHub reports enormous amounts of changed files.
These files have long gone.
Anyone knows why GitHub keeps reporting them?

**Comment by the1337guy** [comment]
Do a git ls on the folder, check the files you have long removed, then git rm --cached -r them manually.

**Comment by JdeH** [comment]
There are many such folders.
Can I do it in the root of a folder tree?

**Comment by the1337guy** [comment]
You can, but it won't recursively show files in child directories.

**Comment by JdeH** [comment]
Simplest thing turned out to be just to make a new clone, alter the version and commit it... :(
