### ISSUE TITLE
"py_TypeError is not defined" thrown in browser console

### ISSUE THREAD

**Issue by all3fox** [QQuick/Transcrypt#356]
Consider this `main.py` program:

```
try:
    raise TypeError("how are you?")
except TypeError as e:
    print(e)
```

Just transpile it without any flags with current version of transcrypt, put this `html` next to the generated `__javascript__`:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>TypeError</title>
    </head>
    <body>
        <script src="./__javascript__/main.js"></script>
    </body>
</html>
```

then open it up in your browser of choice, navigate to console and observe the error:

```
ReferenceError: py_TypeError is not defined
```

Now, I've seen that `compiler.py` has some kind of `aliasers` that include a pair of `(TypeError, py_TypeError)`. I've also made two attempts at defining a `TypeError` in `__standard__.py`:

1. Attempt (just below the `AttributeError`):

```
class TypeError(Exception):
    def __init__(self, message, error):
        Exception.__init__(self, message, error = error)
```

2. Attempt (with a different class name):

```
class py_TypeError(Exception):
    def __init__(self, message, error):
        Exception.__init__(self, message, error = error)
```

Both of these did not solve my problem. Could you please point out anything relevant that I am missing/misunderstanding?

**Comment by JdeH** [comment]
Resolved and committed.
TypeError isn't yet used by Transcrypt itself, however.
