### ISSUE TITLE
stale results are silently reused

### ISSUE THREAD

**Issue by all3fox** [QQuick/Transcrypt#358]
Consider the following `main.py`:

```
xs = ((i, 2 ** i) for i in range(3))

print(type(xs))

for i, j in xs:
    print(i, j)
```

transpile it with `transcrypt main.py`, put the following `main.html` next to the `__javascript__` and then open it in your browser:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Generator issue</title>
    </head>
    <body>
        <script src="./__javascript__/main.js"></script>
    </body>
</html>
```

navigate to your browser console and see a single `None` printed there. So, the loop does not run. After a while you might realize that the generators are only available once you transpile with the EcmaScript 6 turned on. So, let's do exactly that: `transcrypt -e 6 main.py`

If you take a look at `__javascript__/main.js` now, you'll see that it changed. For example, the `__symbols__` global variable now contains `__esv6__`, which gives you the impression that the file was retranspiled. However, if you open `main.html` and navigate to console, you will still see just `None`.

Only if you manually `rm -rf __javascript__` and transpile again, the loop will work and you will see console output: 

```
None
0 1
1 2
2 4
```

So, looks like Transcrypt silently reuses stale results :(

**Comment by the1337guy** [comment]
That's why -b exists to rebuild from scratch each time in development.

**Comment by JdeH** [comment]
Indeed it is needed to use -b here.
The alternative would be that TS has to remember with which switches it was uses last time (and on which project), which seemed overcomplicated.
But having to use -b isn't as careless as I'd like it to be...
