### ISSUE TITLE
Puzzling compile error in 3.6.34 under Python 3.6.1

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#361]
I've got a big file, 6051 lines, that's failing to compile under under Transcrypt 3.6.34 and python 3.6.1

```
pi@pi1:/tmp $ transcrypt -b -n -m CTL_register_list.py 

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.34
Copyright (C) Geatec Engineering. License: Apache 2.0


Error while compiling (offending file last):
	File '/tmp/CTL_register_list.py', line 0, namely:
	
	'ascii' codec can't decode byte 0xc2 in position 11071: ordinal not in range(128)
```

The file compiles without error under the following combinations on different machines.

Transcrypt  Python
3.6.34          3.5.3
3.6.25           3.5.2

The file has no imports and I've verified that the file is the same on all 3 machines by computing its md5sum.

Any advice for unraveling this much appreciated.

Cheers,
Mike

**Comment by fzzylogic** [comment]
There are a few characters that choke when compiling from the windows command prompt, even though this was largely taken care of by a pull request a while back. It might be worth checking whether this file can compile using the same versions of Transcrypt and Python on a Linux or Mac.

**Comment by Michael-F-Ellis** [comment]
> It might be worth checking whether this file can compile using the same versions of Transcrypt and Python on Linux or Mac.

I should have specified the machines and OS's. 

Outcome Transcrypt Python Machine OS
FAIL  3.6.34 3.6.1 Raspberry Pi3, Raspbian Jesse (Linux 4.4.34-v7+)
PASS 3.6.34 3.5.3 Mac, OS X 10.11.6
PASS 3.6.25 3.5.2 Raspberry Pi3, Raspbian Jesse (Linux 4.4.34-v7+)

No windows involved :-)

**Comment by Michael-F-Ellis** [comment]
Just to make things even more confusing, I created a new Python 3.6 virtual env on the Mac and retested. It compiled without error.  Then I created a Python3 environment on the Pi that was failing.  Still failed.  So now the table looks like:

Outcome Transcrypt Python Machine OS
FAIL 3.6.34 3.6.1 Raspberry Pi3#1, Raspbian Jesse (Linux 4.4.34-v7+)
FAIL 3.6.34 3.5.3 Raspberry Pi3#1, Raspbian Jesse (Linux 4.4.34-v7+)
PASS 3.6.34 3.6.1 Mac, OS X 10.11.6
PASS 3.6.34 3.5.3 Mac, OS X 10.11.6
PASS 3.6.25 3.5.2 Raspberry Pi3,#2 Raspbian Jesse (Linux 4.4.34-v7+)

So now I have it passing on the Mac with the same Transcrypt and Python versions that fail on one of the Raspberry Pi's.

I doubled-checked the file md5 sums on the machines and also rebooted the Raspberry Pi.  Same results.  Also completely uninstalled transcrypt, mypy and type-ast then cleared .cache/pip/ then reinstalled transcrypt.  Same results.

One other observation: The failure is occurring in the source mapping phase.  I've been compiling with -b -n -m in all the tests.  If I drop the -m, the compile succeeds on PI#1 under both Python 3.6 and 3.5.

**Comment by fzzylogic** [comment]
Interesting thanks. What is the output of `locale`?

**Comment by Michael-F-Ellis** [comment]
Thanks @fzzylogic! I think you're on to something.  There are differences between the Pi3's ...

**From the Pi3 that compiles without errors:**
```
ipi2dev001:~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
pi@pi2dev001:~ $ cd PGC-SmartTabletPlus/modules/
pi@pi2dev001:~/PGC-SmartTabletPlus/modules $ file --mime-encoding CTL_register_list.py 
CTL_register_list.py: utf-8
pi@pi2dev001:~/PGC-SmartTabletPlus/modules $ python
Python 3.5.2 | packaged by rpi | (default, Dec 14 2016, 17:51:49) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding()
'UTF-8'
>>> 
```
**From the Pi3 with compile failures:**
```
pi@pi1:~/PGC-SmartTabletPlus/app-ace-interface $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
(root) pi@pi1:~/PGC-SmartTabletPlus/app-ace-interface $ cd ../modules
(root) pi@pi1:~/PGC-SmartTabletPlus/modules $ file --mime-encoding CTL_register_list.py 
CTL_register_list.py: utf-8
(root) pi@pi1:~/PGC-SmartTabletPlus/modules $ python
Python 3.6.1 | packaged by rpi | (default, Apr 20 2017, 19:35:19) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding()
'ANSI_X3.4-1968'
```

**Comment by Michael-F-Ellis** [comment]
That was it! I applied the following fix from https://www.jaredwolff.com/blog/raspberry-pi-setting-your-locale/

> Edit /etc/locale.gen and uncomment the line with en_US.UTF-8
> Run locale-gen en_US.UTF-8
> Run update-locale en_US.UTF-8

Now it compiles without error.

Thanks for the diagnosis! Locale wasn't even on my radar.
Cheers,
Mike
