### ISSUE TITLE
removing all elements children

### ISSUE THREAD

**Issue by hir3npatel** [QQuick/Transcrypt#363]
Hi, is there any reason this would not work:

```
 for c in element.children:
      c.remove()
```

But then this does work:

```
while len(element.children) != 0:
            element.children[0].remove()

```
In my case I have a div with 6 children, the first method removes the first 3 children but not the rest. The second method removes them all. Is there some quirk and this is expected? Or could it be a bug and I should produce a small test sample?

Transcrypt Version 3.6.26

**Comment by hir3npatel** [comment]
Same issue with Version 3.6.34.

If I do this:

```
print(len(element.children))
for c in element.children:
    print("remove child" + c)
    c.remove()
```

The console prints 6, and then "remove child[object HTMLDivElement]" only 3 times. Why would the iteration not go through all 6 children?

**Comment by the1337guy** [comment]
ES6 or ES5?

**Comment by hir3npatel** [comment]
I compile with: run_transcrypt -bm test.py 

Looks like it defaults to 5. I could provide the relevant js if needed.

**Comment by the1337guy** [comment]
Try ES6. And yes that relevant JS would be useful.

**Comment by hir3npatel** [comment]
Same result with: run_transcrypt -e 6 -bm test.py

Snippets of the relevant js, I can pastebin the whole thing if needed.

```
self.orderList = document.getElementById ('orderlist');

get apply_entries () {return __get__ (this, function (self, entries) {
	for (var c of self.orderList.children) {
		c.remove ();
	}
});}
```

It seems to be a js thing, if I paste the relevant js into chrome dev tools console, it does the same thing - it shows me 6 children in that element. If I paste the for-loop into the dev tools it does not remove all the 6 children. Weird, it must be a js quirk?

**Comment by hir3npatel** [comment]
Seems to be a js thing, just doesn't work in a pythonic way. I found this explanation which helped:
https://stackoverflow.com/questions/11148066/removechild-loop-exits-before-finish

I've since changed the code to this, and it seems to work fine

```
for c in list(self.orderList.children):
    self.orderList.removeChild(c)
```

Going to close this issue, sorry for the noise.

**Comment by hir3npatel** [comment]
Actually python lists work the same way! I am just doing it wrong. Sorry.

**Comment by the1337guy** [comment]
Since Transcrypt monkey patches Array, you can just do the slice thing mentioned in the SO answer.
