### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by h5rdly** [QQuick/Transcrypt#366]
First, thank you for this awesome package. 

Not really an issue as it's stated in the readme, but it's easier to be able to see the license immediately in the top of the page (eyes already accustomed to darting that direction to know what you're dealing with :) ) 

Thanks,
Eli

**Comment by JdeH** [comment]
Unfortunately GitHub seems to have blocked `.. include::`.
So I've included a copy, which leads to some duplication.

**Comment by h5rdly** [comment]
The web interface allows direct addition. Github supports Apache 2.0, so it presents a nice icon on the upper right as well. I've made a pull request if you're interested.
