### ISSUE TITLE
key "name" in **kwargs dict is getting renamed to "py_name"

### ISSUE THREAD

**Issue by Pewpews** [QQuick/Transcrypt#377]
**Transcrypt v(3.6.46)**

Hi, sorry if I've missed something about this in the docs. Consider the following code:
```
__pragma__("kwargs")
def test(**kwargs):
    print(kwargs)
__pragma__("nokwargs")

test(name="test1")
test(notname={"name":"test2"})
```

This is the output:
```
1. {}
2. {'notname': {'name': 'test2'}}
```

This is the expected output:
```
1. {"name": "test1"}
2. {'notname': {'name': 'test2'}}
```

I've found out so far that only the keyword-name `name` won't function correctly. If you replace `print(kwargs)` with `console.log(kwargs)`, you can see that the keyword gets resolved to `py_name` instead.

Thought it was related to #148, but seems unlikely. 

Are there any workarounds? I need optional keyword arguments.

Thank you

**Comment by JdeH** [comment]
This is to prevent clashes with the Python's  special use of the attribute `name` for some classes.

You can do one of both:

If  you  use `js_name` in your sourcecode, it will be translated to `name`.

Another possibility, in a piece of code or sourcefile that doesn't use Python's special `name` attribute, is that you remove the `name` alias for that sourcefile or piece of code by calling `__pragma__ ('noalias', 'name')`

See:

__pragma__ ('noalias', <Python id part>)

**Comment by Pewpews** [comment]
Thanks for the quick response. Your suggested solutions are sufficient.
