### ISSUE TITLE
str() sometimes returns '???' instead of something more useful.  I suspect a bug.

### ISSUE THREAD

**Issue by jeffstearns** [QQuick/Transcrypt#379]
I'm seeing unexpected behavior from the str() function.  It seems like a bug.

str() sometimes returns '???' instead of something more useful.  I think this happens because str() and repr() seem to disagree on the API that they offer each other.  The API seems a little broken.

str() is coded with the assumption that repr() can raise exceptions.  But repr() won't raise exceptions back to its caller.  Instead, it logs exceptions to the console and then discards them.

The code below is from Transcrypt 3.6.39.  Note that str() calls repr() within a try/catch block.  But repr() doesn't cooperate with this.  Instead of raising exceptions back to its caller, repr() logs them to the javascript console.  str() never sees the exception, so the catch block never executes.

```
    function str (stringable) {
        try {
            return stringable.__str__ ();
        }
        catch (exception) {
            try {
                return repr (stringable);    <--- repr() may throw an exception, but IT WILL CATCH AND LOG IT.  It won't be seen by the catch() block below. 
            }
            catch (exception) {   <--- This catch isn't entered because repr() catches exceptions
                return String (stringable); // No new, so no permanent String object but a primitive in a temporary 'just in time' wrapper
            }
        }
    };
```

_N.B. I may be wrong.  I am definitely not a javascript programmer.  Everything I read suggests that javascript is irritatingly irregular, so I might be misunderstanding how javascript really behaves here.  Thanks for any insight!_

**Comment by JdeH** [comment]
Thanks for finding what certainly looks to me as a bug and analysing it so carefully.
I will take a thorough look at it and correct it.

Kind regards
Jacques

**Comment by jeffstearns** [comment]
Here's a code snippet that shows the problem:
```
class Foo: pass
alert('We have a ' + str(Foo()))
```
Compiling this code with Transcrypt and executing it in the browser causes two messages to be logged to the javascript console:

`display.js:882 ERROR: Could not evaluate repr (<object of type object>)`

```
display.js:883 TypeError: Function.prototype.toString is not generic
    at Function.toString (<anonymous>)
    at repr (display.js:878)
    at str (display.js:1490)
    at display.js:2394
    at display (display.js:2513)
    at display.js:2516
```

**Comment by daboross** [comment]
@jeffstearns I believe I understand the issue - I just want to point out one thing: the error is most likely [here](https://github.com/QQuick/Transcrypt/blob/9924f308b3711602ac282f1761c38d3487f3b84a/transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js#L292) - calling `anObject.toString ()`. It definitely is in your example, but and _probably_ in the actual code.

Calling `String(x)` or `x.toString()` on an object which inherits from a native JavaScript object without overriding `toString` will cause this error.

What I'm getting at here is even if the interaction between repr/str is fixed, the code at the end of `str` (`return String (stringable); // No new, so no ..`) would throw the exact same error that was caught.

**Comment by JdeH** [comment]
The default string representation of an object is now: <object of type: object>.
No error is reported in this default case.

The

            catch (exception) { 
                return String (stringable);  // No new, so no permanent String object but a primitive in a temporary 'just in time' wrapper
            }

is left in place as a savety net to deal with primitives rather than newed object instances,
since I am not sure typeof can be used on all primitives, now and in the (JS) future.
