### ISSUE TITLE
Arguments passed to @classmethod and @staticmethod are shifted

### ISSUE THREAD

**Issue by wrpscott** [QQuick/Transcrypt#384]
```python

# Test the arguments passed in to classmethod and staticmethods.
"""
<html>
    <head>
        <script src="__javascript__/classmethodtest.js"></script>
    </head>
    <body>
        Refresh browser window to restart
    </body>
</html>
"""


class cmtest:
    def __init__(self, o: int, t: int) -> None:
        self._one = o
        self._two = t

    def hello(self) -> None:
        print("hello {} {}".format(self._one, self._two))

    @classmethod
    def class1(cls, a: str, b: bool) -> None:
        print("class1  says: '{}' '{}'".format(a, b))

    @staticmethod
    def static1(a: str, b: bool) -> None:
        print("static1 says: '{}' '{}'".format(a, b))


cm = cmtest(10, 20)
cm.hello()
cmtest.class1("funky", False)
cmtest.static1("funky", False)

cm.class1("blabla", True)
cm.static1("blabla", True)

# expected output is:
# hello 10 20
# class1  says: 'funky' 'False'
# static1 says: 'funky' 'False'
# class1  says: 'blabla' 'True'
# static1 says: 'blabla' 'True'

# under transcrypt, run in the browser, I get:
# hello 10 20
# class1  says: 'False' '{}'
# static1 says: 'funky' 'False'
# class1  says: 'blabla' 'True'
# static1 says: '<object of type: object>' 'blabla'
```

**Comment by neriusmika** [comment]
Until now, class methods behave like a simple method and they are passing an instance as the first parameter, static methods are not supported too, so you can look at them as without decorators at all. I think, I fixed them and made a pull request, so they will work as expected. If you want to test this code now, just try with Transcrypt from my fork (https://github.com/neriusmika/Transcrypt).

**Comment by wrpscott** [comment]
Thank you for  your useful comments. Indeed, looking at the http://www.transcrypt.org/docs/html/supported_constructs.html#decorators-function-and-class-with-and-without-parameters more
carefully does indeed say this. For now at least, I can easily work around the issues.

It might be useful if the compiler issued a warning when it encounters a decorator on a method...
