### ISSUE TITLE
Installation link not responding correctly

### ISSUE THREAD

**Issue by holdenweb** [QQuick/Transcrypt#386]
The downloads page at http://www.transcrypt.org/download refers the reader to http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/installation_use.html#installation for details of "more complicated" situations.

This page currently responds with a 502 (Bad Gateway), displaying the message "Connection to upstream refused."

**Comment by JdeH** [comment]
Thank you!
That link is outdated, will be adapted a.s.a.p.

**Comment by JdeH** [comment]
Should be fixed now.
Let me know if it works for you.

Kind regards
Jacques

**Comment by holdenweb** [comment]
Yes, all good now thanks.
