### ISSUE TITLE
Support __module__ and __qualname__ for introspection

### ISSUE THREAD

**Issue by RunasSudo** [QQuick/Transcrypt#387]
It would be nice to be able to access `__module__` and `__qualname__` on classes, to allow the full name of the class to be determined from code.

**Comment by RunasSudo** [comment]
For reference, until this is implemented natively in the Transcrypt compiler, I have added a rudimentary level of support using the following patches to the generated Javascript:

```sh
perl -0777 -pi -e 's/var __nest__ = function \(headObject, tailNames, value\) \{/var __nest__ = function (headObject, tailNames, value) { if (headObject === __all__ && value.__all__) { value.__all__.__module__ = tailNames; }/g' /path/to/file.js
perl -0777 -pi -e "s/var (.*?) = __class__ \('\g1', \[(.*?)\], \{/var "'$1'" = __class__ ('"'$1'"', ["'$2'"], { __module__: __all__.__module__,/g" /path/to/file.js
```

Needless to say, this is a rather fragile bodge, and a compiler-side implementation would be vastly more desirable.

**Comment by JdeH** [comment]
Classes have now __module__ attribute.
Didn't add __qualname__, causes a lot of complexity at too little yield i.m.o.
Also in main module __name__ now gives '__main__', allowing for the "classic" main module check.

**Comment by JdeH** [comment]
Current solution isn't DRY.
Working on a better one, hopefully equiv.
Since it will be more compact, the modclass switch can probably go.

**Comment by JdeH** [comment]
\_\_module\_\_ is now supported in a lean way.
\_\_qualname\_\_ is not anticipated to be supported.
