### ISSUE TITLE
String repetition with * fails

### ISSUE THREAD

**Issue by johb** [QQuick/Transcrypt#388]
Hi all,

repeating a string with `*` and an integer fails.
Example:
`'!' * 3`
 gets `NaN`
because the generated Javascript code is the same:
`'!' * 3`.

Correct result would be `'!!!'`.

Version: 3.6.50

**Comment by neriusmika** [comment]
```python
# __pragma__('opov')
s = '!' * 3
# __pragma__('noopov')
console.log(s)
```
result: `!!!`

**Comment by johb** [comment]
Thank you, I missed that point in the documentation.

Are there any plans to automatically allow operator overloading at least for the python standard library?
Would this decrease performance significantly?
I think this could lead to subtle bugs because people got used to things things like <str> * <int> in python?

**Comment by neriusmika** [comment]
You can enable it with a command line switch -o, but yes, that would decrease performance, so better use \_\_pragma\_\_ where it is needed.
