### ISSUE TITLE
Operator overloading of division behaves incorrectly

### ISSUE THREAD

**Issue by RunasSudo** [QQuick/Transcrypt#389]
With operator overloading enabled, `a // b` does not use the overloaded `__floordiv__` operator, even if it is defined.

Similarly, with operator overloading enabled, `a / b` attempts to use `__div__` for overloading (as in Python 2) instead of `__truediv__` (as in Python 3.6, the advertised target version).

**Comment by JdeH** [comment]
Thanks!
Hadn't noticed this changed behaviour.
Will be in next commit.
Kind regards
Jacques

**Comment by JdeH** [comment]
Has been committed.
