### ISSUE TITLE
Transcrypt requires write priviledges on its own installation folder

### ISSUE THREAD

**Issue by mythsmith** [QQuick/Transcrypt#390]
1. I upgraded transcrypt in linux using `sudo pip3 install -U transcrypt`
2. Doing anything with it as a standard user (eg: try to build a file), I get permission denied errors or missing modules are reported. Seems I was missing the time module:

```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.50
[...]
Error while compiling (offending file last):
	[...]
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/time/__init__.py', line 1, namely:
	Can't import module 'time'
Aborted
```

3. I located my transcrypt installation folder, and tried to compile the automated tests. Got something like:
```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.50
[...]
Error while compiling (offending file last):
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/development/automated_tests/transcrypt/autotest.py', line 1, at import of:
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/autotester/__init__.py', line 10, at import of:
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/autotester/html.py', line 10, namely:
	Can't import from module 'org.transcrypt.autotester.html'
Aborted
```
 4. Granted write permission to anybody over the transcrypt folder: `sudo chmod 777 -R /usr/local/lib/python3.5/dist-packages/transcrypt`

5. Problem solved.

Feel like it will happen again next upgrade.

**Comment by JdeH** [comment]
Hi

This is a very valid issue, that has been extensively discussed in #189,
together with a workaround using virtualenv.
The issue was postponed, as it requires a major reorganisation.
All postponed issues were closed to keep the overview.
However they can be summarized by selecting the postponed label.

Jacques

**Comment by mythsmith** [comment]
Ok. Searched a bit but didn't notice it, sorry and thanks!

**Comment by JdeH** [comment]
No need to be sorry, as said it's a valid issue.

**Comment by JdeH** [comment]
This issue will be cured with the release of Transcrypt 3.7.1

**Comment by mythsmith** [comment]
Thanks!
