### ISSUE TITLE
Uncaught ReferenceError: gid is not defined

### ISSUE THREAD

**Issue by CarstenGrohmann** [QQuick/Transcrypt#392]
Hi,

I got this error message if I use `match.groupdict()` (Match object from RE module):

```
__init__.py:214 Uncaught ReferenceError: gid is not defined
    at __init__.py:214
    at Function.<anonymous> (__core__.mod.js:70)
    at example.py:13
    at Function.<anonymous> (__core__.mod.js:70)
    at HTMLButtonElement.onclick (example.html?_ijt=ke8d8679qujfgr8cjhi43j0fjq:3)
```

**Steps to reproduce:**
1. Create a file `example.py`
```
import re

class Example:

    d = {'A': 1, 'B': 2}
    rec = re.compile('(?P<decimal>\d+)', re.ASCII)

    def run(self):
        match = self.rec.match('42')
        if not match:
            print('ERROR: RE does not match')
        e = match.groupdict()
        print("before: self.d=", self.d)
        print("before: e=", e)
        self.d.update(e)
        print("after: self.d=", self.d)


example = Example()
```

2. Create a file `example.html`
```
<h2>Hello demo</h2>

<button onclick="example.example.run()">Click me and check error console</button>

<h2>Output:</h2>
<div id="__terminal__">
</div>

<script src="__javascript__/example.js"></script>
```
3. Run transcrypt
```
# transcrypt --build --map --nomin -e 6 example.py
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.50
Copyright (C) Geatec Engineering. License: Apache 2.0
Saving result in: /home/carsten/example/__javascript__/example.js
Process finished with exit code 0
```

4. Open the html file in a browser, press the butten and check the error console

**Affected version:**
* Transcrypt 3.6.50

It would be really great if you could fix this error.

Regards,
Carsten

**Comment by JdeH** [comment]
Hi Carsten

The regular expression module still has some loose ends.
It was contributed a.o by @RCL-Carl and I am not familiar with the code.
@RCL-Carl: Could you by any chance find the time to look into this? No obligation of course!

Kind regards
Jacques

**Comment by JdeH** [comment]
@CarstenGrohmann: I  think I found the problem and a fix.
Will familiarize myself a bit more with this module, since it's very useful.

@RCL-Carl: I hope I remember well that you did a lot of work on this. And I hope I have properly repaired this part (it was only a typo in a varname).

**Comment by JdeH** [comment]
Committed and uploaded to PyPi
