### ISSUE TITLE
PIP Installed and cannot reference

### ISSUE THREAD

**Issue by joehoeller** [QQuick/Transcrypt#393]
My error:

bash: transcrypt: command not found

Any ideas?

**Comment by JdeH** [comment]
Unfortunately I've no idea what's going on...
Assuming the 'python' command refers to Python 3.6, you could try:

`python -m transcrypt <filename> <options>
`

If that doesn't work there are some alternative ways to install Transcrypt, as described in:

http://www.transcrypt.org/docs/html/installation_use.html#installation

**Comment by JdeH** [comment]
Since this seems to have come to a standstill I'll close for now.
Please reopen if there's new info on this!

KR
J
