### ISSUE TITLE
ValueErrors cannot be constructed with a message in Transcrypt

### ISSUE THREAD

**Issue by daboross** [QQuick/Transcrypt#394]
In Python 3.6, the following code will produce an exception with a message:
```
raise ValueError('this specific error occurred')
```

```
>>> raise ValueError('this specific error occurred')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: this specific error occurred
```

In Transcrypt, the same code generates a generic "Erroneous Value" error message.

I believe the same is true of "KeyError". I'll try to send a PR for this if this is something we can change - I don't know what code relies on "Erroneous Value" being the default message in Transcrypt - this is opposed to the default message of an empty message in Python 3.6.

**Comment by daboross** [comment]
Looking back, I see this was introduce in https://github.com/daboross/Transcrypt/commit/9924f308b3711602ac282f1761c38d3487f3b84a#diff-493186bca6f730b8f74b3c21e15ab988.

I can't seem to find any significance of `"Erroneous Value"` and `"Invalid Key"`, but I would definitely like to know if there is some.

**Comment by JdeH** [comment]
Solution was merged.
Thanks.
Feel free to reopen if I overlooked anything!
