### ISSUE TITLE
Transcrypt + ReactJS Demo

### ISSUE THREAD

**Issue by doconix** [QQuick/Transcrypt#403]
Hi.  Love the project and hope it continues to gain steam.  I wrote a project that uses React and Transcrypt, and I afterward distilled the ideas into a demo for others.  I'm wondering if you want to reference or include it somehow.

For me, getting Transcrypt working with React wasn't easy.  The docs have an example, but it is for an older version of React.  The current React docs use ES6 classes and build everything with webpack.  I wanted to do it "right" by extending the JS classes directly.  

In the process, I created [a pyreact demo](https://github.com/doconix/pyreact) that may be a useful example to others.  The primary benefit is the abstract classes in`pyreact.py`, which encapsulate the difficult parts and make it easy to create React components as real Python objects.

As an aside, the Transcrypt docs give examples of inheritance between Python classes only.  What's missing is how to extend a JS class -- at least I couldn't find it.  This demo shows how to extend JS classes in normal python style, assuming I did it right. If it's in the docs, I'd love a pointer. If not, the demo is an example.

To restate, I'm wondering if the demo is useful to the Transcrypt team somehow, such as an example in the docs.  If not, no worries -- thanks for all you've done with Transcrypt.

**Comment by doconix** [comment]
P.S. here's a direct link to a file with a React component defined with a Python class:

https://github.com/doconix/pyreact/blob/master/scripts/clock.py

**Comment by JdeH** [comment]
See my  comment at #404

**Comment by doconix** [comment]
I submitted a PR for you to look at when you get a chance.  Not sure if you want to go that direction but I like the plugin ability.  You da boss. ;)

**Comment by JdeH** [comment]
I've included a link to PyReact on the gallery page or the Trancrypt site.
