### ISSUE TITLE
__pragma__('jsx')

### ISSUE THREAD

**Issue by doconix** [QQuick/Transcrypt#404]
In creating a Transcrypt-based React app (see my other question), I needed to write JSX into my code.  JSX is a transpiled language, just like Transcrypt.  I made it work by using strings:

```python
elem = self.jsx('''
    <div id="StudentContainer">
        {self.props.students.map((s) => (
            <StudentTile student={s}  key={s.searchval}  />
        ))}
    </div>
''')
```

Not the best way because the JSX is converted at runtime on the browser.

I'm wondering how hard it would be to have a `__pragma__` that takes some portion of code and "shells" out to a separate program for processing, piping the content over.  Then Transcrypt emits the return.  That would allow me to put JSX between two pragmas and get it converted to JS by some outside engine.

The code could then be something like this:

```jsx
elem = \
__pragma__('ext_on', 'jsx_transform_executable --o1 --o2')
    <div id="StudentContainer">
        {self.props.students.map((s) => (
            <StudentTile student={s}  key={s.searchval} />
        ))}
    </div>
__pragma__('ext_off')
```

This type of command would be useful to much more than JSX. Any kind of pre or post transformations of parts of code could be triggered by the transcrypt engine.

**Comment by JdeH** [comment]
That's a very original and powerful idea!
Contemplating it right now...

**Comment by JdeH** [comment]
I've committed a solution.
Please let me know if it works for you.

Kind regards
Jacques

**Comment by JdeH** [comment]
If this solution proves to be working, could you supply a simple stand-alone demo of your pyreact demo utilizing JSX for inclusion in Transcrypt's demos directory that is part of the distribution. I will then also make it visible on the website. I am asking because I am less than a React expert...

**Comment by doconix** [comment]
Awesome!  It's almost there. It works as long as I don't give the command any arguments.  However, it fails with any options.

The `Popen` call in compiler.py, line 1565 creates the array of args (with single arg) for the call.  Popen wants the args split, not in a single string: https://docs.python.org/3/library/subprocess.html#popen-constructor

The following is what fails:
```
        return __pragma__ ('xtrans', 'jsx-transform --factory React.createElement', '{}', '''
            ...
        ''')
```

I need a way to be able to get the three components into an array.  One option is for the xtrans option to call `https://docs.python.org/3/library/shlex.html#shlex.split` on whatever string I give it.  I'm not sure it would handle all cases, but it is an option.  To use this, I think your code would simply have to be:

```
import shlex

process = subprocess.Popen (
    shlex.split(node.args [1] .s),
    stdin = subprocess.PIPE,
    stdout = subprocess.PIPE
)
```

Thanks.

**Comment by fzzylogic** [comment]
Thank you so much for this Jacques, it's fantastic. Fwiw, I've found POpen's cwd argument to be very useful, for example in the case where one calls an external file that itself requires certain files that may not be available in the path.

**Comment by JdeH** [comment]
@doconix Looks like a good solution. How on earth did you find that in the docs...
@fzzylogic Will add cws as a keyword arg

**Comment by JdeH** [comment]
The proposed improvements have been committed.
Let me know if it all works for you.

**Comment by doconix** [comment]
All is working now.  THANKS.

On a related issue, I just posted a PR that allows me or anyone else to add pragmas through a plugin-type registry.  Last night (during sleep of course :) I realized that the plugin registry would have been a better way to handle this.  See what you think of it.

**Comment by kiwi0fruit** [comment]
@JdeH 

Resulting pragma looks rather long and it really should be defined once for all use cases not difined every time. Is it possible to define shortcuts somehow? Like

```
__pragma__ ('jsx', x)
```
means

```
__pragma__ ('xtrans', 'jsx-transform --factory React.createElement', '{}', x)
```
?

**Comment by metamarcdw** [comment]
There is now an option that allows you to define your external transpiler from the command line.

`__pragma__ ('xtrans', 'jsx-transform --factory React.createElement', '{}', x)`
can now be written as:
`__pragma__ ('xtrans', None, '{}', x)`

When using the
`transcrypt --xtrans="jsx-transform --factory React.createElement"`
Command line switch.

**Comment by kiwi0fruit** [comment]
@metamarcdw but still it looks ugly... Having something like this would be nicer: https://github.com/QQuick/Transcrypt/issues/551
