### ISSUE TITLE
Byte literals produce invalid javascript

### ISSUE THREAD

**Issue by mlyle** [QQuick/Transcrypt#405]
Important test vectors:

`b'\0'`
`b''`
`b''.join(myArray)`

**Comment by JdeH** [comment]
This unfortunatlely is a limitation that will not go away soon.

**Comment by mlyle** [comment]
Sorry, this is just ridiculous.

You can't stop yourself from emitting invalid javascript and do *something* sane for null/empty handling, when it's a constant? Even to just coerce it to behave like a string like Py2 did?

**Comment by JdeH** [comment]
I rarely use byte arrays so I'd appreciate some help here!
Could you supply me with a brief two column list of the most important Python constructs with byte arrays you use and what they should translate to?
Furthermore, since this is an open source project, anyone who is knowledgeable on this subject willing to help?

**Comment by mlyle** [comment]
Python byte arrays are basically strings without defined encoding information.  In Py2 they didn't exist, and we just used strings everywhere.  Now, in Python 3, they are returned/expected by various parts of the standard library, so if you're going to use various things-- like Struct or read/write from files natively, etc-- you are expected to use byte-array types.

I have code that uses Struct that I'd like to run in the browser.  I'm maintainer of dRonin, an autopilot for drones, that produces binary logfiles that I'd like end-users to be able to analyze in a browser app.  It currently runs happily in Python2/Python3 environments using six for adaptation-- doing stuff with strings in Py2, and natively with Py3.  Pretty soon I'll deprecate Py2 support, and can move this to Python3 native stuff.  I need the bits of python code to work as real python 3 bits, and also be able to run in the browser.

I don't really care if you just treat byte arrays as strings under the hood.  Right now I use from six int2byte (chr(j) / bytes((j,))), byte2int (ord(bs[0]) or bs[0])<-- this is probably the trickiest, iterbytes.  I need to construct empty byte arrays and be able to concatenate to them and slice them.

Right now brython / pypy have a pure-python Struct impl that would meet my need, if byte arrays would work properly.  And I'd be happy to do the work to port it to Transcrypt once byte array support is decided upon.

**Comment by JdeH** [comment]
OK let's take it one step at a time and start out using JavaScript's `Uint8Array`.
Some basic functionality will be initially added and then let's see what further facilities are most needed.

**Comment by mlyle** [comment]
That sounds great.  I don't really know modern Javascript that well, so I don't think I can contribute too much to the actual translator implementation.  But-- I'm willing to use whatever primitives are available as long as there's a sane subset way to do byte array ops in both real Python3 and Transcrypt, and I can contribute library implementations of things like struct.Struct based on whatever actually works.

**Comment by JdeH** [comment]
In today's commit support was added for the following:

```
b = b'bike'
s = bytes ('shop', 'utf8')
e = b''
bb = bytearray ([0, 1, 2, 3, 4])
bc = bytes ((5, 6, 7, 8, 9))

# __pragma__ ('opov')
bps = b + b'pump' + s
bps3 = 3 * bps + b'\0'
aBps3 = bps * 3 + b'\0'
l = [1, 2, 3] + [4, 5, 6]
# __pragma__ ('noopov')

def formatCheck (aBytes):
    print ([int (aByte) for aByte in aBytes])

formatCheck (b)
formatCheck (s)
formatCheck (e)
formatCheck (bb)
formatCheck (bc)
formatCheck (bps)
formatCheck (bps3)
formatCheck (aBps3)

# __pragma__ ('opov')
formatCheck (bb + bc)
formatCheck (bytearray ('ding', 'utf8') + b'dang' + bytes ('dong', 'utf8'))
# __pragma__ ('noopov')

formatCheck (l)
```
Output, both in Transcrypt and  CPython, is:

```
[98, 105, 107, 101]
[115, 104, 111, 112]
[]
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112]
[98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 0]
[98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 98, 105, 107, 101, 112, 117, 109, 112, 115, 104, 111, 112, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[100, 105, 110, 103, 100, 97, 110, 103, 100, 111, 110, 103]
[1, 2, 3, 4, 5, 6]
```

Does this already help?
Can you reasonably make your way with this or are other facilities needed?
Priorities?

PS Note that the pragma's switch operator overloading on and off.
Operator overloading is needed to concatenate arrays with a +,
since JavaScript normally doesn't support that.
It should be switched on only locally, since it's run time expensive.
The pragma's are ignored by CPython, so this code is portable between CP and TS.

KR
Jacques

**Comment by JdeH** [comment]
No news on this one.
Hope that the enhancements made fit the bill.
Otherwise feel free to reopen and add specific wishes.
