### ISSUE TITLE
bytes() builtin method is undefined

### ISSUE THREAD

**Issue by mlyle** [QQuick/Transcrypt#406]
Together with #405 it's getting increasingly difficult to do things with byte arrays.

**Comment by JdeH** [comment]
Hi,

Transcrypt is designed with the following in mind:

1. Keep it lean and fast, making it a viable alternative for JavaScript in production situations, see discussion at:
https://stackoverflow.com/questions/30155551/python-in-browser-how-to-choose-between-brython-pypy-js-skulpt-and-transcrypt/38564424#38564424
2. Allow seamless interaction with any JavaScript library
3. Within this limitations, make its behavior as CPython compatible as possible.

Point 3 speaks in favor of implementing bytes (), but point 1 and 2 indicate that it may be needed restrict this to the most important use cases.

The bytes () builtin function in CPython is the tip of a useful, but rather extensive iceberg.
Suppose there were a limited version of the bytes () builtin function in Transcrypt,
and given the fact that all underlying Transcrypt types are in fact JavaScript types,
could you supply some CPython (or JavaScript) examples of what functionality you need most?

Kind regards
Jacques

**Comment by mlyle** [comment]
I need to be able to slice, concatenate, and generate arbitrary byte arrays.  I have some code that does buffering of a binary protocol until entire messages are received, and then does pack/unpack.  I've been working on a pack/unpack implementation for Transcrypt but I've run into lots of problems:

* Using some existing code I have, I run into the issue where accessing non-extant members of dicts doesn't result in a KeyError.
* If I use get and throw the exception myself, isinstance to detect a KeyError seems to go awry.
* I can't form up empty byte arrays and concatenate up from there, since b'' / bytes(0) doesn't work

etc, etc.  So basically, doing anything in a way that will *also* work appropriately in Python3 seems to not work in TransCrypt.

**Comment by JdeH** [comment]
The lack of byte array support unfortunately is a limitation that will probably not go away soon.

Maybe in some cases JS typed arrays will help, as used in NumScrypt. (But in most cases this will NOT be what you're looking for. (https://github.com/QQuick/Numscrypt)

Yet another workaround in selected cases is using \_\_pragma\_\_ ('js', (http://www.transcrypt.org/docs/html/special_facilities.html#inserting-literal-javascript-pragma-js-and-include) It enables you make a "low level" escape directl to JavaScript.

**Comment by JdeH** [comment]
Reopened in relation to #405

**Comment by JdeH** [comment]
Bytes function and some other byte-oriented facilities added.
Hope this fits the bill.
If not feel free to reopen and add specific wishes.
