### ISSUE TITLE
Any SEO, social media or marketing animals out there?

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#409]
**Transcrypt is unique in its technical specifications:**

- very fast loading, compact and readable JS code
- seamless integration with any JS lib
- native CPython 3.6 syntax allows for true class based OOP with multiple inheritance, operator overloading, metaclasses, properties, comprehensions etc.
- Python source level debugging from minified JS files, setting breakpoints, inspecting variables etc.

**But securing its place under the sun takes more than technical merits.** Mindshare is very important for acceptance of Transcrypt as **the** tool to precompile Python to JS code. Googling for "**python javascript**", Transcrypt comes up **high at page 1**, googling for  "**python browser**", Transcrypt comes up **low at page 2**. All in all this is a SE position many companies would kill for. Still there's room for improvement.

**Anyone willing and able to help here**?
(and links, talks, evangelism as welcome as ever)

Jacques

**Comment by pierrejean-coudert** [comment]
To begin with, we could ask the community to upvote transcrypt responses in this kind of post:
https://stackoverflow.com/a/39829630/8450
https://www.quora.com/How-can-I-run-Python-in-the-browser
This could help to gain more traction.

**Comment by pierrejean-coudert** [comment]
Regarding the home page you should put the title "Transcrypt, Python in the browser" in a H1.
Perhaps add something like a "Python to javascript transpiler" H2 somewher in the homepage too.

**Comment by JdeH** [comment]
@pierrejean-coudert

I've added the <H1> and <H2> as you advised
They're (fortunately) covered by other dom elemens, but visible in the source just after <body>

**Comment by pierrejean-coudert** [comment]
You'll better have to use h1 on your existing text and style it accordingly.
Google does not like to have hidden h1 or h2 text.

**Comment by pierrejean-coudert** [comment]
you should have only one h1 in your page.
other titles should be h2 or h3 to reflect the page structure

**Comment by JdeH** [comment]
That's a bit more work (since I should adapt all pages to match the CSS), but I'll keep it on my todo list...

**Comment by JdeH** [comment]
The main page now indeed has one h1 and one h2 only.
However embedding the title into a visible h1 isn't easy, since it has some color juggling going on...
I'll wait a while to see if there's any effect of the current improvements.

**Comment by JdeH** [comment]
Correction: wasn't that hard after all.
h1 is now the true title.
h2 isn't since I'd rather not really show that text.
But the Google rating for "python to javascript" is already excellent.

![image](https://user-images.githubusercontent.com/1730289/33341370-11b68444-d47f-11e7-9711-d07d7a117670.png)

**Comment by JdeH** [comment]
@pierrejean-coudert 

Your advice seem to have worked. Transcrypt went from 4rd to 3rd on page 1 when searching for "Python JavaScript" and, more important, from low on page 3 to high on page 2 when searching for "Python Browser".

That's significant improvement...

**Comment by JdeH** [comment]
By the way just fell of my chair... Had no idea...

![image](https://user-images.githubusercontent.com/1730289/33514037-fe58bedc-d74c-11e7-8d65-120610e771ef.png)

**Comment by pierrejean-coudert** [comment]
Impessive download count !!

Some other suggestions:
- More descriptive Title: Transcrypt - Python in the browser: open Python 3 to Javascript transpiler
- add comas in keywords: "python, browser, javascript, compiler, transpiler"
- Move H2 after H1 to respect document hierarchy
- Replace images containing text by the text itself, or at least add alt text on it ; especially the workflow one.
- Replace Javascript links with real HTML links in the menu.

**Comment by pjbonestroo** [comment]
I made a small Javascript library for paginated lists in the browser. [https://github.com/pjbonestroo/PagedList](https://github.com/pjbonestroo/PagedList)
