### ISSUE TITLE
set().clear() causes TypeError: py_clear is not a function

### ISSUE THREAD

**Issue by serin-delaunay** [QQuick/Transcrypt#412]
Input Python:
```py
x = set()
x.add(1)
x.clear()
```
Compiled with `transcrypt -b -n -m -e 6`. Version 3.6.54. This should run with no errors and leave x as an empty set. When the output JS is run in the browser, the `clear()` call produces this error:
`Uncaught TypeError: x.py_clear is not a function`

 A workaround is to use `x = set()`, but this is not a replacement in all use cases.

Probably related to https://github.com/QQuick/Transcrypt/issues/254.

**Comment by JdeH** [comment]
Fixed & committed
Let me know if it works for you
KR
Jacques

**Comment by serin-delaunay** [comment]
It works, thanks :)
