### ISSUE TITLE
Issue using Plotly

### ISSUE THREAD

**Issue by stanep** [QQuick/Transcrypt#415]
Hi I am trying to use Plotly in my javascript and it works but if I call "update" method on Plotly

Plotly.update(jq(self.graph_id)[0],data)

it compiles to

Plotly.py_update ($ (self.graph_id) [0], data)

which is not correct and program fails

**Comment by stanep** [comment]
Hi , sorry I just found in doc
__pragma__ ('noalias')

**Comment by JdeH** [comment]
That's one way to do it.
Preferably use it to unalias only a specific name `__pragma__ ('noalias', 'update')`.

Another way is using:

Plotly.js_update(jq(self.graph_id)[0],data)

in your source.
It will generate:

Plotly.update ($ (self.graph_id) [0], data)

I  prefer the 'unalias' way.
You can reinstate the alias after the Plotly update call.

KR
Jacques

**Comment by stanep** [comment]
Thx
