### ISSUE TITLE
two stacktraces running simple test program

### ISSUE THREAD

**Issue by pjlbyrne** [QQuick/Transcrypt#416]
Hi, I am on debian stable. I setup a 'venv' in my app directory, activated it and then did 'python3 -m pip install wheel' & 'python3 -m pip install transcrypt'.

On my test program, '#!/usr/bin/python\nprint "hi"' - I get stacktrace:

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.61
Copyright (C) Geatec Engineering. License: Apache 2.0

```
list index out of rangeTraceback (most recent call last):
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 155, in __init__
    moduleMetadata = ModuleMetadata (self, self.mainModuleName)
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 67, in __init__
    '\n\tCan\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/__main__.py", line 147, in main
    compiler.Program (transpilationDirs, __symbols__)
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 160, in __init__
    message = '\n\t{}'.format (str (exception))
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 127, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (program.importStack [-1][0] .sourcePath, self.lineNr)
IndexError: list index out of range
```

**Comment by pjlbyrne** [comment]
Well this at least stops the exception handler stacktracing:


Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.61
Copyright (C) Geatec Engineering. License: Apache 2.0


list index out of rangeTraceback (most recent call last):
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 155, in __init__
    moduleMetadata = ModuleMetadata (self, self.mainModuleName)
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 67, in __init__
    '\n\tCan\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/__main__.py", line 147, in main
    compiler.Program (transpilationDirs, __symbols__)
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 160, in __init__
    message = '\n\t{}'.format (str (exception))
  File "/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 127, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (program.importStack [-1][0] .sourcePath, self.lineNr)
IndexError: list index out of range

This seems like a pretty basic issue??

**Comment by pjlbyrne** [comment]
ha! the underlying exception is caused by me submitting a script without the '.py' extension. The following prevents that in env/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py:

```
    src = self.sourceFileName
    self.mainModuleName = src if src.endswith( '.py' ) else src

```

**Comment by pjlbyrne** [comment]
Okay, so I went back to the docs here at http://www.transcrypt.org/docs/html/installation_use.html#installation:

> Open a command prompt in the demos/hello directory and type transcrypt hello.py. Then click on hello.html to load it into your browser.
`(env) patb@gronk:~/dev/appraise/env/lib64/python3.5/site-packages/transcrypt/demos/hello$ which transcrypt
/home/patb/dev/appraise/env/bin/transcrypt
(env) patb@gronk:~/dev/appraise/env/lib64/python3.5/site-packages/transcrypt/demos/hello$ transcrypt hello.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.61
Copyright (C) Geatec Engineering. License: Apache 2.0

dir: ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'provide']


source: hello.py

---
---
---
 hello.py

Error while compiling (offending file last):
	File '??', line 0, namely:
	
	Attempt to import module: hello.py
	Can't find any of:
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/demos/hello/hello/py.py
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/demos/hello/hello/__javascript__/py.mod.js
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/hello/py.py
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/transcrypt/modules/hello/__javascript__/py.mod.js
		/home/patb/dev/appraise/env/bin/hello/py.py
		/home/patb/dev/appraise/env/bin/hello/__javascript__/py.mod.js
		/usr/lib/python35.zip/hello/py.py
		/usr/lib/python35.zip/hello/__javascript__/py.mod.js
		/usr/lib/python3.5/hello/py.py
		/usr/lib/python3.5/hello/__javascript__/py.mod.js
		/usr/lib/python3.5/plat-x86_64-linux-gnu/hello/py.py
		/usr/lib/python3.5/plat-x86_64-linux-gnu/hello/__javascript__/py.mod.js
		/usr/lib/python3.5/lib-dynload/hello/py.py
		/usr/lib/python3.5/lib-dynload/hello/__javascript__/py.mod.js
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/hello/py.py
		/home/patb/dev/appraise/env/lib/python3.5/site-packages/hello/__javascript__/py.mod.js


Aborted
`

??!

**Comment by JdeH** [comment]
Hi,

What is your use case for having a Python script without a .py extension. 
It's  no big deal adding this but I can currently not come up with any situation in which this would be used.
Maybe I'm overlooking something?

Kind regards
Jacques

**Comment by pjlbyrne** [comment]
Hi Jacques,

When writing larger python programs it is my habit to put source code in .py files, but for one-off scripts I tend to write them so they can run like unix commands. Through the shebang mechanism unix allows script execution with bash, csh, perl, python etc and so I tend to use that.

In using transcrypt I wanted to convert such a python script into javascript. That is all.

I don't have a problem with transcrypt requiring a .py extension, but I suggest it could fail more gracefully ie with error message and not stacktrace.

Thanks
Patrick

**Comment by JdeH** [comment]
You've convinced me!
I'll add your solution to the code in the next commit...

KR
J

**Comment by pjlbyrne** [comment]
Thanks Jacques! Great tool by the way. I had never considered there might be such a thing until it occurred to me I might need it...

**Comment by JdeH** [comment]
Solution committed.
