### ISSUE TITLE
python 'random' module is taken to be a global 'random' function in javascript

### ISSUE THREAD

**Issue by pjlbyrne** [QQuick/Transcrypt#417]
I want to use transcrypt to convert a python script into javascript. The script uses 'shuffle' in the python 'random' module.

I boiled the problem down to this example:

```
l = [ 1, 2 ]
from random import shuffle
while True:
   thing = input( 'thing' )
   print( 'before: {}'.format( ' '.join( l )))
   shuffle( l )
   print( 'after: {}'.format( ' '.join( l )))
```

This fails - if I comment out the 'shuffle( l )' line then it runs fine.

From looking at the  javascript that the 'random' module in python is taken to be a  javascript function which returns a random number. The produced code, which attempts to get '.shuffle' from this, is presumably crashing the  runtime script:

```
var shuffle = init (world.random).shuffle;
```
 I asked this as a question here:
[https://stackoverflow.com/questions/47741172/random-shuffle-does-not-work-in-truecrypt#47741172](url)

**Comment by JdeH** [comment]
Transcrypt has its own bare bones random module, since CPython's random is written in C. It did not yet have the shuffle function. It was added in the most recent commit.
