### ISSUE TITLE
Adding lists produces incorrect result

### ISSUE THREAD

**Issue by wrpscott** [QQuick/Transcrypt#418]
Extending a list by using the + operator does not produce the expected result in Transcrypt. I.e.
alst + blst , or alst += blst are incorrect. 

    def test_report01(self):
        """File a transcrypt error"""
        print("test_report_01!")
        alst = ['one', 'two', 'three']
        blst = ['three', 'four']
        clst = alst + blst
        # clst is faulty
        dlst = ['one', 'two', 'three']
        dlst += blst
        # dlst is faulty
        elst = ['one', 'two', 'three']
        # elst is correct
        elst.extend(blst)
        print("alst : {}".format(alst))
        print("blst : {}".format(blst))
        print("clst : {}".format(clst))
        print("dlst : {}".format(dlst))
        print("elst : {}".format(elst))

The output (browser console) is:
alst : ['one', 'two', 'three']
blst : ['three', 'four']
clst : one,two,threethree,four
dlst : one,two,threethree,four
elst : ['one', 'two', 'three', 'three', 'four']

**Comment by pjbonestroo** [comment]
If you use the  __pragma__ ('opov'), it should produce the expected result. See [documentation](http://transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov)
