### ISSUE TITLE
Overriding methods

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#419]
In Python it is valid to override a method, like:

```
class A():
    def original(self):
        print("original")

def alternative(self):
    print("alternative")

A.original = alternative
a = A()
a.original()
```
which will print `alternative`. But after transpilation to Javascript you'll get the error: `Uncaught TypeError: Cannot set property original of function...`.
Of course this has to do with the fact that it is transpiled to:
```
var A = __class__ ('A', [object], {
	__module__: __name__,
	get original () {return __get__ (this, function (self) {
		print ('original');
	});}
});
```
where `original` is a property which cannot be overriden in this way.
Is there a workaround for this? It can be useful in some cases to have this behaviour.
Best regards

**Comment by notzoom** [comment]
I am interested in hearing if there's a workaround as well ! Thank you.

**Comment by JdeH** [comment]
Hi,

 The following workaround will do the trick:

```
class A():
    def original (self, anArg):
        print ('Original:', anArg)

def alternative (self, anArg):
    print ('Alternative:', anArg)

a0 = A ()
a0.original ('Time flies like an arrow')

__pragma__ ('js', '{}', 'Object.defineProperty (A, "original", {get: function (self) {return __get__ (this, alternative)}})')
a1 = A()
a1.original ('Fruit flies like a banana')

```

It will print:

```
Original: Time flies like an arrow.
Alternative: Fruit flies like a banana.
```

Kind regards
Jacques

**Comment by pjbonestroo** [comment]
Thanks. I've put it on [StackOverflow](https://stackoverflow.com/questions/47847067/overriding-methods-using-transcrypt)

**Comment by pjbonestroo** [comment]
It would be a nice enhancement to have the original CPython syntax work.

**Comment by JdeH** [comment]
Will postpone but keep the idea in stock.

KR
J

**Comment by neriusmika** [comment]
@JdeH I tried this code:
```python
    def other_method1(self):
        return self.__class__.__name__

    class A:
        def method1(self):
            return 'original method1'

        def method2(self):
            return 'original method2'

    a = A()
    autoTester.check(a.method1())
    autoTester.check(a.method2())
    # mokeypatch class
    A.method1 = other_method1
    autoTester.check(a.method1())
    # setattr(A, 'method1', other_method1)
    # monkey patch instance
    a.method2 = lambda: other_method1(a)  
    autoTester.check(a.method2())
    # add new method
    a.method3 = lambda: other_method1(a)
    autoTester.check(a.method3())
```
and after manually changing javascript to this, method assignments are working:
```javascript
        var other_method1 = function (self) {
		return self.__class__.__name__;
	};
	var A = __class__ ('A', [object], {
		__module__: __name__,
		__impl__method1: function (self) {
			return 'original method1';
		},
		get method1 () {return __get__ (this, this.__impl__method1);},
		set method1 (m) {this.__impl__method1 = m;},
		__impl__method2: function (self) {
			return 'original method2';
		},
		get method2 () {return __get__ (this, this.__impl__method2);},
		set method2 (m) {this.__impl__method2 = m;}
	});
	var a = A ();
	autoTester.check (a.method1 ());
	autoTester.check (a.method2 ());
	A.method1 = other_method1;
	autoTester.check (a.method1 ());
	a.method2 = (function __lambda__ () {
		return other_method1 (a);
	});
	autoTester.check (a.method2 ());
	a.method3 = (function __lambda__ () {
		return other_method1 (a);
	});
	autoTester.check (a.method3 ());
```
I don't know am I in the right direction. Of course there are many ways to assign instance methods in CPython (e.g. with \_\_get\_\_, types.MethodType, etc.), but I think we don't need to think about them right now. And there can be some problems with decorators. To not overbloat code, we can introduce a new pragma and make setters only for selected methods. What do you think, should I look deeper into this problem?

**Comment by JdeH** [comment]
@neriusmika 

I need some more time to seriously look into your proposal
 Probably tuesday, since rightnow I have to prepare something for a customer.
Will get back in this.

KR
Jacques
