### ISSUE TITLE
Example usage of Transcrypt for javascript library

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#421]
I made a small Javascript library for paginated lists in the browser:
[https://github.com/pjbonestroo/PagedList](https://github.com/pjbonestroo/PagedList)
It is not very special, but I use it quite a lot myself, so why not share it? Maybe it also helps Transcrypt getting mindshare.
(I also posted this in issue #409, but maybe it is better as a separate issue)
BR

**Comment by notzoom** [comment]
Thanks for sharing that with us !

**Comment by JdeH** [comment]
@pjbonestroo 
Thanks, I've put it in the Gallery.
KR
Jacques

**Comment by pjbonestroo** [comment]
Thanks! Happy to contribute to this great project!
