### ISSUE TITLE
Unexpected token ( when running working Python code as JavaScript

### ISSUE THREAD

**Issue by grabartley** [QQuick/Transcrypt#424]
I have been experimenting with Transcrypt in order to run my Python code in the browser and I have many small Python programs running. I am having an issue with a particular Python chess program where every time I transpile it I get this error when running the JavaScript: 

						function () {
						         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

I have tried running the JavaScript through the browser and through NodeJS but get the same error each time. I am using Node v6.11.2 and Google Chrome v63.0.3239.84.

When I run the Python code through python it works perfectly. This is the Python code:

    from random import randint

    class Player(object):
        allSpaces = [(x, y) for x in range(8) for y in range(8)]
        moves = 0
        def __init__(self, color, name):
            self.color   = color
            self.name     = name
            self.playedturns = 0
        def __str__(self):
            return self.name+' as '+self.color

        def setOpp(self, opponent):
            self.opponent = opponent

        def getPieces(self, board):
            return [pos for pos in board if board[pos].color is self.color]

        def potentialTargets(self, playerColour):
            return [pos for pos in self.allSpaces if pos not in playerColour]

        def kingPos(self, board):
            for my in self.getPieces(board):
                if board[my].pieceName is 'k':
                    return my

        def possibleMoves(self, board):
            myPieces=self.getPieces(board)
            for my in myPieces:
                for target in self.potentialTargets(myPieces):
                    if self.canMove(board, my, target):
                        if not self.makeCheck(my, target, board):
                            yield (my, target)

        def getPos(self, move):
            col  = int(ord(move[0].lower())-97)
            row  = int(move[1])-1
            colNext = int(ord(move[2].lower())-97)
            rowNext = int(move[3])-1
            start     = (row, col)
            target    = (rowNext, colNext)
            return start, target

        def isDraw(self, board):
            if not list(self.possibleMoves(board)) and not self.isCheck(board):
                return True
            if len(list(self.getPieces(board))) == \
               len(list(self.opponent.getPieces(board))) == 1:
                return True
            if Player.moves/2 == 50:
                if input("Is it a tie (yes/no) : ") in ['yes','y','Yes']:
                    return True

        def isCheckMate(self, board):
            if not list(self.possibleMoves(board)) and self.isCheck(board):
                return True

        def turn(self, board):
            whoTurn = "\n{}'s turn,".format(self.name)
            warning = "Your King is in check "
            if self.isCheck(board):
                whoTurn = whoTurn + warning
            return whoTurn

        def getMove(self, board):
            print ("\n")
            while True:
                move=input("\nMake a move : ")
                if move == 'exit':
                    break
                else:
                    start, target = self.getPos(move)
                    if (start, target) in self.possibleMoves(board):
                        return start, target
                    else:
                        raise IndexError

        def makeCheck(self, start, target, board):
            self.doMove(board, start, target)
            retval = self.isCheck(board)

            self.unmove(board, start, target)
            return retval

        def isCheck(self, board):
            kingPos = self.kingPos(board)
            for opp in self.opponent.getPieces(board):
                if self.opponent.canMove(board, opp, kingPos):
                    return True

        def doMove(self, board, start, target):
            self.oldPiece = None
            if target in board:
                self.oldPiece = board[target]
            board[target] = board[start]
            board[target].pos = target
            del board[start]
            board[target].noMoves += 1
            if board[target].pieceName is 'p' and not self.oldPiece:
                if abs(target[0]-start[0]) == 2:
                    board[target].turn_moved_twosquares = self.playedturns
                elif abs(target[1]-start[1]) == abs(target[0]-start[0]) == 1:
                    if self.color is 'white':
                        cappedPiece = (target[0]-1, target[1])
                    else:
                        cappedPiece = (target[0]+1, target[1])
                    self.savedpawn = board[cappedPiece]
                    del board[cappedPiece]

        def unmove(self, board, start, target):
            board[start] = board[target]
            board[start].pos = start
            if self.oldPiece:
                board[target] = self.oldPiece
            else:
                del board[target]
            board[start].noMoves -= 1
            if board[start].pieceName is 'p' and not self.oldPiece:
                if abs(target[0]-start[0]) == 2:
                    del board[start].turn_moved_twosquares
                elif abs(target[1]-start[1]) == abs(target[0]-start[0]) == 1:
                    if self.color is 'white':
                        cappedPiece = (target[0]-1, target[1])
                    else:
                        cappedPiece = (target[0]+1, target[1])
                    board[cappedPiece] = self.savedpawn

        def canPromote(self, board, target):
            pro = 'empty'
            while pro.lower() not in ['kn','q']:
                pro = \
                input("You may promote your pawn:\n[Kn]ight [Q]ueen : ")
            board[target].promote(pro)

        def isPathClear(self, start, target, board):
            col, row = start[1], start[0]
            colNext, rowNext = target[1], target[0]
            if abs(row - rowNext) <= 1 and abs(col - colNext) <= 1:
                return True
            else:
                if rowNext > row and colNext == col:
                    tmpstart = (row+1,col)
                elif rowNext < row and colNext == col:
                    tmpstart = (row-1,col)
                elif rowNext == row and colNext > col:
                    tmpstart = (row,col+1)
                elif rowNext == row and colNext < col:
                    tmpstart = (row,col-1)
                elif rowNext > row and colNext > col:
                    tmpstart = (row+1,col+1)
                elif rowNext > row and colNext < col:
                    tmpstart = (row+1,col-1)
                elif rowNext < row and colNext > col:
                    tmpstart = (row-1,col+1)
                elif rowNext < row and colNext < col:
                    tmpstart = (row-1,col-1)
                if tmpstart in board:
                    return False
                else:
                    return self.isPathClear(tmpstart, target, board)

        def canMove(self, board, start, target):
            myPiece = board[start].pieceName.upper()
            if myPiece == 'R' and not self.isRook(start, target):
                return False
            elif myPiece == 'KN' and not self.isKnight(start, target):
                return False
            elif myPiece == 'P' and not self.isPawn(start, target, board):
                return False
            elif myPiece == 'B' and not self.isBishop(start, target):
                return False
            elif myPiece == 'Q' and not self.isQueen(start, target):
                return False
            elif myPiece == 'K' and not self.isKing(start, target):
                return False
            if myPiece in 'RPBQK':
                if not self.isPathClear(start, target, board):
                    return False
            return True

        def isRook(self, start, target):
            if start[0] == target[0] or start[1] == target[1]:
                return True

        def isKnight(self, start, target):
            if abs(target[0]-start[0]) == 2 and abs(target[1]-start[1]) == 1:
                return True
            elif abs(target[0]-start[0]) == 1 and abs(target[1]-start[1]) == 2:
                return True

        def isPawn(self, start, target, board):
            if 'white' in self.color and target[0] < start[0]:
                return False
            elif 'black' in self.color and target[0] > start[0]:
                return False
            if start[0] == target[0]:
                return False
            if target in board:
                if abs(target[1]-start[1]) == abs(target[0]-start[0]) == 1:
                    return True
            else:
                if start[1] == target[1]:
                    if abs(target[0]-start[0]) == 1:
                        return True
                    if board[start].noMoves is 0:
                        if abs(target[0]-start[0]) == 2:
                            return True
                if start[0] == self.capRow:
                    if abs(target[0]-start[0]) == 1:
                        if abs(target[1]-start[1]) == 1:
                            if target[1]-start[1] == -1:
                                cappedPiece = (start[0], start[1]-1)
                            elif target[1]-start[1] == 1:
                                cappedPiece = (start[0], start[1]+1)
                            if cappedPiece in board and \
                            board[cappedPiece].color is not self.color and \
                            board[cappedPiece].pieceName is 'p'and \
                            board[cappedPiece].noMoves == 1 and \
                            board[cappedPiece].turn_moved_twosquares == \
                            self.playedturns-1:
                                return True

        def isBishop(self, start, target):
            if abs(target[1]-start[1]) == abs(target[0]-start[0]):
                return True

        def isQueen(self, start, target):
            if self.isRook(start, target) or self.isBishop(start, target):
                return True

        def isKing(self, start, target):
            if abs(target[0]-start[0]) <= 1 and abs(target[1]-start[1]) <= 1:
                return True
    class Piece(object):
        def __init__(self, pieceName, position, player):
            self.color    = player.color
            self.pieceName = pieceName
            self.pos  = position
            self.noMoves = 0
        def __str__(self):
            if self.color is 'white':
                return self.pieceName.upper()
            else:
                return self.pieceName

        def canbepromoted(self):
            if str(self.pos[0]) in '07':
                return True

        def promote(self, to):
            self.pieceName = to.lower()
    class Board(object):
        def __init__(self, player1, player2):
            self.board = dict()
            for player in [player1, player2]:
                if player.color is 'white':
                    aRow, bRow = 0, 1
                    player.capRow = 4
                else:
                    aRow, bRow = 7, 6
                    player.capRow = 3

                [self.board.setdefault((bRow,x), Piece('p', (bRow,x), player)) \
                for x in range(8)]
                [self.board.setdefault((aRow,x), Piece('r', (aRow,x), player)) \
                for x in [0,7]]
                [self.board.setdefault((aRow,x), Piece('kn',(aRow,x), player)) \
                for x in [1,6]]
                [self.board.setdefault((aRow,x), Piece('b', (aRow,x), player)) \
                for x in [2,5]]
                self.board.setdefault((aRow,3),  Piece('q', (aRow,3), player))
                self.board.setdefault((aRow,4),  Piece('k', (aRow,4), player))

        def printBoard(self):
            tmp = ""
            print ("      a     b     c     d     e     f     g     h")
            for i in range(8):
                print ("   -------------------------------------------------")
                print (str(i + 1), end='')
                for j in range(8):
                    if (i, j) not in self.board:
                        print (" | " + "   ", end='')
                    else:
                        print (" |  %s " % self.board[(i, j)], end='')
                print (" |")
            print ("   -------------------------------------------------")
            print ("\n")

        def refreshScreen(self, player):
            if player.color is 'white':
                player1, player2 = player, player.opponent
            else:
                player1, player2 = player.opponent, player
            self.printBoard()

        def run(self, player):
            self.refreshScreen(player)
            while True:
                print (player.turn(self.board))
                try:
                    start, target = player.getMove(self.board)
                except (IndexError, ValueError):
                    self.refreshScreen(player)
                    print ("\n\nThat move is not vaild.")
                except TypeError:
                    break
                else:
                    if target in self.board or self.board[start].pieceName is 'p':
                        Player.moves = 0
                    else:
                        Player.moves += 1
                    player.doMove(self.board, start, target)
                    player.playedturns += 1
                    if self.board[target].pieceName is 'p':
                        if self.board[target].canbepromoted():
                            player.canPromote(self.board, target)
                    player = player.opponent
                    if player.isDraw(self.board):
                        return 1, player
                    elif player.isCheckMate(self.board):
                        return 2, player
                    else:
                        self.refreshScreen(player)

        def end(self, player, result):
            loser = player.name
            win = player.opponent.name
            if result == 1:
                endstring = "\n{} and {} have tied".format(win, loser)
            elif result == 2:
                endstring = "\n{} put {} in checkmate.".format(win, loser)
            self.printBoard()
            return endstring

    class Chess():
        def whatColor(self):
            return randint(0, 9)

        def newgame(self):
            m = Chess()
            print (""" "Welcome, please enter your names in order to start the game and press the enter key. """)
            player1, player2 = m.getPlayers()
            player1.setOpp(player2)
            player2.setOpp(player1)
            game = Board(player1, player2)
            menu = """

            Player 1: {} - Will use uppercase lettering
            Player 2: {} - Will use lowercase lettering
            (Move format is 'a2b3'. Type 'exit' to quit the game.""".format(player1.name, player2.name, player1, player2)
            print (menu)
            input("\n\nHit the Enter button to play")
            randNum = m.whatColor()
            if (randNum == 0):
                player = player1
            else:
                player = player2
            try:
                result, player = game.run(player)
            except TypeError:
                pass
            else:
                print (game.end(player, result))
                input("\n\nPress any key to continue")

        def getPlayers(self):
            loop1 = True
            loop2 = True
            while loop1:
                name1 = input("\nPlayer 1 (white): ")
                if not name1:
                    print ("Try again")
                else:
                    player1 = Player('white', name1)
                    loop1 = False
            while loop2:
                name2 = input("\nPlayer 2 (black): ")
                if not name2:
                    print ("Try again")
                else:
                    player2 = Player('black', name2)
                    loop2 = False
            return player1, player2

        def chess(self):
            m = Chess()
            endGame="""To play again press enter. To quit type 'exit' >>  """
            try:
                while True:
                    m.newgame()
                    choice=input(endGame)
                    if choice == 'exit':
                        print ("\nNew Chess Game!")
                        break
            except KeyboardInterrupt:
                sys.exit("\n\nErrorl. Abort.")
    m = Chess()
    m.chess()

I'm not sure why this wont transpile correctly or if there is something I am doing wrong.

**Comment by JdeH** [comment]
At least part of the problems you're having are probably due to a bug in Transcrypt, so thanks for reporting.
You use list comprehensions purely for their side effects but you don't assign the result to anything.
This is perfectly legal Python, but not something we anticipated.
A fix for this will be in the next commit.

There are some other issues, such as Transcrypt's print statement not yet accepting the end= keyword arg. Will get back to you on this point.

Kind regards
Jacques

**Comment by JdeH** [comment]
Hi,

I've taken another good look at your example program.
It relies on console I/O and exceptions  like KeyboardInterrupt and the sys module.
Transcrypt runs in a browser environment which means that many of these things work differently.

The things you can do on a browser (even driven, non-blocking I/O) are different from the things you can do in the command prompt (blocking I/O). I think you'll have a hard time getting this to work in Transcrypt.

**Comment by grabartley** [comment]
@JdeH Thank you for the replies and taking the time to read my issue and the Python code. I see what you mean about the blocking I/O being difficult to get working in Transcrypt. I hope I have helped in some way with this issue!

**Comment by JdeH** [comment]
You certainly helped, thanks to you we found an important bug!

**Comment by grabartley** [comment]
@JdeH So, once the next commit is live should I expect that the error wont happen anymore or will there still be an issue transpiling because of the blocking I/O?

**Comment by JdeH** [comment]
There will still be an issue because of the blocking I/O.
To get an idea of what a game may look like without blocking I/O, e.g. take a look at:

http://www.transcrypt.org/examples#pong_demo

**Comment by grabartley** [comment]
@JdeH Okay thank you for the advice I really appreciate it!
