### ISSUE TITLE
Question About __iterable0__

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#425]
Aren't the characters before and after iterable0 making the code more cryptic while the goal is for the output to be readable ? For them to be there, there must be a good reason - just curious to know it. Thanks !

**Comment by JdeH** [comment]
Since these identifiers are automatically generated, conflicts with human made identifiers have to be prevented. In python as a habit this is done by sandwiching between __ __. Many system generated id’s in CPython also follow this convention.
