### ISSUE TITLE
pysteroids_demo doesn't work in Windows7

### ISSUE THREAD

**Issue by chopin** [QQuick/Transcrypt#426]
Following is the error message from the chrome browser

> __core__.mod.js:2 Uncaught TypeError: a.apply is not a constructor

The above one is a result using pysteroids.min.js. Following is the error message when using pysteroids.js compiled with the sourcemap option. 

> __init__.py:6 Uncaught TypeError: obj.apply is not a constructor
> at Object._c_ [as Vector3] (__init__.py:6)

The following is the python source of  the error location. The source file is pysteroids_demo/org/threejs/__init__.py

>4: def _ctor(obj):
>5:     def _c_(*args):
>6:         return __new__(obj (*args))
>7:     return _c_

The error occurs at "obj (*args)" in line 6.

**Comment by chopin** [comment]
three_demo works fine (other demos too).  I installed transcrypt using pip. I could't test the latest github version because it failed to be installed (error while running setup.py).

**Comment by JdeH** [comment]
Thanks for the feedback, we will look into it!

**Comment by JdeH** [comment]
The PySteriods demo requires the -e 6 switch (so needs JavaScript 6 or higher code generation). Could this be the problem?

**Comment by chopin** [comment]
The -e 6 switch fixed the problem. I think that it is great if this information is available in a Readme file  in the directory or somewhere. Thank you for your help.

**Comment by JdeH** [comment]
Of course it should be.
A readme will be added to the example.

KR
Jacques
