### ISSUE TITLE
Adding pycharm support

### ISSUE THREAD

**Issue by devxpy** [QQuick/Transcrypt#428]
It would really save a trip to the docs when you need to know if x is implemented in transcrpyt or is y valid in transcrpyt

**Comment by JdeH** [comment]
I know that many people use PyCharm, so if anyone were to pick this up it would probably be welcome as  long as it doesn't complicate matters too much.

Personally I don't have any experience with PyCharm, I just use a simple program editor, so I've no idea what PyCharm support would look like.

**Comment by devxpy** [comment]
If I were to create a plugin myself, should I fork this repo and then create a new directory or would it be better if I had a separate repository for it?

**Comment by JdeH** [comment]
Since it is a tool rather than a part of the language I think a separate repo would be appropriate.
Once it works, if you prefer you can bring it under the umbrella of the QQuick organisation.
Would be a great contribution anyhow!

**Comment by JdeH** [comment]
Haven't heard about this for some time.
Will close it, but feel free to reopen if you're working on it.
