### ISSUE TITLE
Convert Imported Libraries While Transpiling

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#429]
Google has achieved this with Grumpy and Go, would it be a possibility to have transcrypt actually go in the folders of the imported modules and do the conversion and include those as well ? Not talking about things tied to the operating system of course.

**Comment by JdeH** [comment]
Transcrypt takes into account modules in subdirectories and includes the resulting JavaScript, as described in:

http://www.transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism

It will also take into account modules in the CPython installation, as long as they are Python only and don't use facilities that Transcrypt doesn't support, like e.g. exec. This means that Transcrypt e.g. has its own implementations of math, random, re, time, etc.
