### ISSUE TITLE
Order of code execution with method decorators and metaclasses

### ISSUE THREAD

**Issue by syntonym** [QQuick/Transcrypt#430]
I'm using the current master branch ( 551c611366e0af6 ) and if I understand correctly this includes support for method decorators (introduced with 9a1f498cb2 19. Sep) and metaclasses ( 1d34a09ff822 5. Nov).  I'm trying to mark methods via decorators for further processing via metaclasses. But when the metaclass gets the attributes the decorators are not yet executed (but in cpython they are). This can be seen by the following code:

```
def log(msg):
    # __pragma__ ('ifndef', '__esv5__')
    print(msg)
    return
    # __pragma__ ('endif')
    console.log(msg)

def report(f):
    log("decorator")

class Meta:

    def __new__(cls, name, bases, namespace):
        log("metaclass")
        return type(name, bases, namespace)

class A(metaclass=Meta):

    @report
    def a():
        pass
```

In cpython this prints 
```
decorator
metaclass
```
But in transcrypt this prints
```
metaclass
decorator
```

Is this working as intended?  If so is there any other way to process decorated methods?

**Comment by JdeH** [comment]
While we would have preferred it to work just as in CPython, there are some differences. Transcrypt runs on top of JavaScript, and while it's possible to get close to CPython behaviour, adding method decorators proved a challenge. Only at a late stage a solution was found for this and while it comes a long way it does behave different from CPython at some points, among which this one you noticed.

@neriusmika This isn't easy to solve, a.f.a.i.k., right?

**Comment by syntonym** [comment]
Of course transcrypt doesn't need to behave exactly the same as CPython but unfortunately this means that basically any interaction between decorators and metaclasses will not work. I wanted to use a metaclass to generate [vue components](https://vuejs.org/v2/guide/components.html) and categorize methods based on decorators:

```
Class ViewModel(metaclass=VueMeta):
    data = {...}
    @method
    def mymethod() ...
    @computed
    def myproperty() ...
```
gets then translated to something like
```
new Vue({data:{...}, methods:{mymethod: ...}, computed:{myproperty: ...}})
```

I don't really know how common it is to use metaclasses and decorators in such a way, so maybe it's not worth to support this usecase.

I digged a bit into the code to change the generated js from
```
var A = __class__ ('A', [object], {
	__module__: __name__,
	__impl__a:  function () {...},
	get a () {return __get__ (this, this.__impl__a);}
}, Meta);
A.__impl__a = decorator(A.__impl__a);
```
to
```
var A = __class__ ('A', [object], {
	__module__: __name__,
	__impl__a:  decorator(function() {...}),
	get a () {return __get__ (this, this.__impl__a);}
}, Meta);
```
and for my code this seems to work fine, but I'm not really sure how that interacts with all the features transcrypt supports like the fcall mechanism. Is there a reason why it was not implemented like that?

Is there some command that runs all tests? I tried `transcrypt/development/shipment/shipment_test.py` but I think I used that wrong because the tests didn't run.

**Comment by JdeH** [comment]
- It's hard to really tell if metaclasses are used a lot. Decorators seem to be quite popular. Anyhow, if Transcrypt can approach CPython a little closer without sacrificing too much performance, that's always a good thing.

- Method declarators were contributed by  @neriusmika, so he knows most about the implementation. Before making any definitive changes here I'd like to have his judgement on this.

- Good that you discovered the shipment test, it's indeed the most complete one. For one thing the shipment test requires node.js to be installed, since it tests the node.js demo (line74):

`        test ('demos/nodejs_demo', 'nodejs_demo', False, True, switches + '-p .none ')
`

The shipment test will start your browser and generate lots of tabs. Besides running all autotests it runs some interacive "eyeballing" tests.

Maybe I am overlooking something that may cause it not to work. Could  you show me which console output in generates?

Meanwhile I am inclined to experiment a little bit with your solution. At first sight it looks OK, but I'll adapt the code generator a bit and try the shipment_test myself.

Kind regards
Jacques

**Comment by neriusmika** [comment]
I'll try to implement your proposed solution.

**Comment by JdeH** [comment]
@neriusmika: I would appreciate it very much if you look into this. All in all his part has become a quite complicated piece of code. The proposition of @syntonym looks effective to me for the signaled "use case", but there are many variations.

It is not so much that it isn't clear _which_ code has to be generated in this particular use case, but more that it seems hard to think  of a mechanism to do so in all kinds of weird edge cases. Those edge cases are in the shipment_test, however. That is, whenever I discovered an edge case, I've put it there, to be sure I didn't break anything. So if these still run correctly, incl. things like call caching, you can be quite sure it's OK.

I

**Comment by neriusmika** [comment]
I created pull request. All decorators now are inline, without intermediate variables. Autotests passed, but there still may be  some unknown cases when operator overloading is used. I just hardcoded \_\_call\_\_ function to work with class based decorators (class `adecorator` in autotest). And I haven't verified call order, just relied on @syntonym suggestion, that inline decorators should work.

**Comment by neriusmika** [comment]
Additionally, I added support for property decorators. Now only for getters, but it would be easy to implement for setters too. Just need to sleep a little bit :) They are added to 'method_and_class_decorators' test.

**Comment by neriusmika** [comment]
@JdeH, just found that when fastcall is enabled, the name for property decorators is left unchanged:

```javascript
get _get_simple_property () {return __get__ (this, function (self) {
    return self.greetings;
}, 'simple_property');},
...
Object.defineProperty (MyClass, 'simple_property', property.call (MyClass, MyClass._get_simple_property));
```
Can there be any conflicts or I can leave those names unchanged? At least tests with fastcall pass without errors.

**Comment by JdeH** [comment]
@neriusmika 

1. This looks very good. Simpler than it was, code nicely refactored etc. And if the tests run it's OK, but...

2. I've found out that the tests with the -f switch do run in the continuous integration. As a result of this there's a problem that predates your pull request. There's a syntax error in the generated JavaScript in that case:

```
	__impl__mymethod: function (self, py_name) {
		autoTester.check (py_name);
	}, 'mymethod',
                             ^
```
I am currently trying to find out when this got in, why, and how to get it out. So some delay. But I guess this can be solved.

**Comment by neriusmika** [comment]
That's strange, \_\_impl\_\_ prefixes had to disappear completely.

**Comment by JdeH** [comment]
I may have been unclear, this problem isn't a result of your latest changes!

> As a result of this there's a problem that **predates** your pull request.

On the contrary, your newest pull request seems to have solved this problem completely.
I've pulled it locally and ran all the tests, including -f and everything works perfectly.
I am **very impressed** with this beautiful piece of work and will now pull it in the master branch!

Jacques

**Comment by neriusmika** [comment]
It's nice to hear it. Tomorrow I'll finish to implement property decorator setters, just need to rest now.

**Comment by JdeH** [comment]
Take your time, there's no hurry.

**Comment by neriusmika** [comment]
I created pull request with property setters. Now just in simple form only getters and setters work. Deleters are rarely used so for now I don't think about implementation. #294 can be closed, don't know about #407

**Comment by JdeH** [comment]
@neriusmika 
The docs have been adapted.

**Comment by syntonym** [comment]
Very much thanks to both of you! It's incredible that after a week the feature is written, tested and merged into master. 

Also generally thanks for transcrypt. I always thought python on the client side is not viable, but it's unbelievable how effortlessly working with transcrypt is.
