### ISSUE TITLE
Keyword arguments for user-defined functions are ignored.

### ISSUE THREAD

**Issue by maciek16180** [QQuick/Transcrypt#432]
Compiled code doesn't seem to recognize keyword arguments. Minimal example:

```
# hello.py
def aaa(thing=3):
    print(thing)
        
def bbb(a):
    aaa()
    aaa(a)
    aaa(thing=a)
```

```
# hello.html
<script src="__javascript__/hello.js"></script>

<script type="text/javascript">
    hello.bbb(1);
</script>

```

This produces output `3 1 3`, whereas in python `bbb(1)` obviously gives `3 1 1`.

I compile this with `transcrypt -b -m hello.py`. I installed Transcrypt with pip, my python version:
```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
```

Why does it happen?

**Comment by JdeH** [comment]
Activate keyword args as explained in:

http://www.transcrypt.org/docs/html/special_facilities.html#keeping-your-code-lean-pragma-kwargs-and-pragma-nokwargs

**Comment by maciek16180** [comment]
Great, thank you for the fast response!

**Comment by JdeH** [comment]
You're welcome
