### ISSUE TITLE
node doesn't support Date.prototype.toLocaleString()

### ISSUE THREAD

**Issue by nicholascarroll** [QQuick/Transcrypt#438]
Hi, when I compile my python class (which imports *time*) using transcrypt -p, the generated js can have the Date toLocaleString() method. It uses *window.navigator.language* as the Locale argument and so fails to run in node.

**Comment by JdeH** [comment]
Do you happen to know what would be the node equivalent to _window.navigator.language_?

**Comment by nicholascarroll** [comment]
No in fact I know almost nothing about node I'm afraid.

**Comment by JdeH** [comment]
From this issue:

https://stackoverflow.com/questions/23199909/using-tolocalestring-in-node-js

it seems that toLocaleString isn't a standard part of node but rather an addon.
So I wouldn't know a way around that...

**Comment by nicholascarroll** [comment]
let me npm install intl, then replicate and load up some log files.

**Comment by JdeH** [comment]
Alright.
But I don't think it'll work now, since probably the time module has to be adapted slightly.
Should be doable.

**Comment by nicholascarroll** [comment]
OK here is what you can use to quickly set up the use case:
git clone https://github.com/bjonnh/PyOrgMode.git
cd PyOrgMode/PyOrgMode
transcrypt PyOrgMode.py
grep "window.navigator" __javascript__/PyOrgMode.js
 

>  l.append (__d.toLocaleString (window.navigator.language, dict ({'weekday': s})).lower ());
>  l.append (__d.toLocaleString (window.navigator.language, dict ({'month': s})).lower ());
>

**Comment by JdeH** [comment]
Thanks, it's a bit late now in the Netherlands, but I'll look at it probably tomorrow.

**Comment by JdeH** [comment]
Transcript 3.6.91 has a fix for this.
To adapt to browser time, call `time.adapt (request)` in your request handler.
If that is omitted, you'll get  en_US time.
Let me know if it works for you.

**Comment by nicholascarroll** [comment]
I'm not sure that I know what a request handler is! Sounds like a web thing. I am using this in a react native app.

29. Jan 2018 18:06 by notifications@github.com:

**Comment by JdeH** [comment]
Does it work without the

t`ime.adapt (request)`?

At least the error should be gone and you should get US date/time formats.
Can you try that first?

**Comment by JdeH** [comment]
No news on this one, so I'll close it.
Feel free to reopen if needed.
