### ISSUE TITLE
method/function re-assignment not supported

### ISSUE THREAD

**Issue by jurjanpaul** [QQuick/Transcrypt#439]
This might be a limitation by design, but I did not find it explicitly stated in the documentation.

Suppose:
```
class A(object):
    def m(self, arg):
        return 'A.m was invoked'

a = A()
a.m = lambda arg: 'a.m was invoked'
a.m()
```
Transcrypt compiles this, but when run complains about the method/function assignment on the last-but-one line:

Uncaught TypeError: Cannot set property m of function () {
                var args = [] .slice.apply (arguments);
                return cls.__new__ (args);
            } which has only a getter

**Comment by neriusmika** [comment]
It's limitation and already discussed in #419

**Comment by jurjanpaul** [comment]
Thank you for your response! This helps me understand better what Transcrypt is and isn't.

In my mind the freedom to assign any value (primitive, instance, function or ...) to any attribute is a rather fundamental cornerstone of the 'semantic essence of Python' (and of JavaScript btw) as referred to at [the start of the documentation](https://www.transcrypt.org/docs/html/what_why.html). But considering the tradeoffs you need to make, it now seems that this freedom would likely conflict with the other stated goal of keeping things lightweight.

It's a shame though; in my case the workaround would need to be much more elaborate and make things quite a bit harder to read, so I'm not going to pursue this at the moment.

All the best going forward!

**Comment by JdeH** [comment]
Thanks!
