### ISSUE TITLE
Output code in only one file

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#440]
Is this possible ? Now the output is 3 files or so and this restricts some uses.

**Comment by pjbonestroo** [comment]
If you have one python file e.g. `main.py`, running transcrypt without minification:
`transcrypt -n main.py` 
will produce 2 files:
- main.js
- main.mod.js

`main.js` contains all you need. If you run with minification:
`transcrypt main.py`
you will also get `main.min.js`. Then you have the choice: use `main.js` or `main.min.js`.

How can this restrict some uses? What else would you expect?

**Comment by notzoom** [comment]
Hello and sorry for the relatively late response.

If main.js has everything we need, why do we need main.mod.js ?

**Comment by JdeH** [comment]
You only need one of these files.
For production use it will be the one ending on .min.js.
The others you can discard.
