### ISSUE TITLE
Request to vote for Transcrypt

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#441]
To help some people, and to spread the word about Transcrypt, I wrote this answer on Stackoverflow:

https://stackoverflow.com/questions/14220321/how-do-i-return-the-response-from-an-asynchronous-call/48243403#48243403

Unfortunately not everyone likes it there. Buf if you like Transcrypt, and if you think the answer is sufficiently useful, please vote. It can use an upvote or two.

(I'm not trying to save my own reputation, but a negative sound about Transcrypt can not be allowed, right?)

**Comment by JdeH** [comment]
Done!
