### ISSUE TITLE
Avoid pragma statements

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#444]
Could the following be somehow avoided from appearing in the same file as the core of the program ? 

Perhaps we could have the option to embed them in another one ? 

		__pragma__ ('<all>')
			__all__.__name__ = __name__;
			__all__.arg0 = arg0;
			__all__.arg1 = arg1;
			__all__.arg2 = arg2;
			__all__.arg21 = arg21;
			__all__.arg22 = arg22;
			__all__.chars = chars;
			__all__.data2 = data2;
			__all__.file1 = file1;
			__all__.file2 = file2;
			__all__.first = first;
			__all__.fsexists = fsexists;
			__all__.functionlist = functionlist;
			__all__.i = i;
			__all__.importfs = importfs;
			__all__.importmark = importmark;
			__all__.item = item;
			__all__.last = last;
			__all__.lastindex = lastindex;
			__all__.lineleadlen = lineleadlen;
			__all__.lineleadlencached = lineleadlencached;
			__all__.mark = mark;
			__all__.marker = marker;
			__all__.num = num;
			__all__.second = second;
			__all__.space = space;
			__all__.spacelen = spacelen;
			__all__.py_split = py_split;
			__all__.var = var;
			__all__.varname = varname;
			__all__.wordcount = wordcount;
			__all__.x = x;
		__pragma__ ('</all>')

**Comment by JdeH** [comment]
Why should it be in a separate file?
Can you clarify your usecase?

**Comment by JdeH** [comment]
Since no reaction was received, I assume this isn't relevant anymore.
