### ISSUE TITLE
Cannot find socket

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#445]
Error while compiling (offending file last):
	File '/home/user/Python/irc.py', line 1, at import of:
	File '/usr/lib/python3.5/socket.py', line 49, namely:
	
	Attempt to import module: _socket
	Can't find any of:
		/home/user/Python/_socket.py
		/home/user/Python/__javascript__/_socket.mod.js
		/usr/local/lib/python3.5/dist-packages/transcrypt/modules/_socket.py
		/usr/local/lib/python3.5/dist-packages/transcrypt/modules/__javascript__/_socket.mod.js
		/usr/local/bin/_socket.py
		/usr/local/bin/__javascript__/_socket.mod.js
		/usr/lib/python35.zip/_socket.py
		/usr/lib/python35.zip/__javascript__/_socket.mod.js
		/usr/lib/python3.5/_socket.py
		/usr/lib/python3.5/__javascript__/_socket.mod.js
		/usr/lib/python3.5/plat-x86_64-linux-gnu/_socket.py
		/usr/lib/python3.5/plat-x86_64-linux-gnu/__javascript__/_socket.mod.js
		/usr/lib/python3.5/lib-dynload/_socket.py
		/usr/lib/python3.5/lib-dynload/__javascript__/_socket.mod.js
		/usr/local/lib/python3.5/dist-packages/_socket.py
		/usr/local/lib/python3.5/dist-packages/__javascript__/_socket.mod.js
		/usr/lib/python3/dist-packages/_socket.py
		/usr/lib/python3/dist-packages/__javascript__/_socket.mod.js

Aborted

**Comment by JdeH** [comment]
I would expect _socket to be written in C, which cannot run in the browser.
Although a number of standard libs has been ported, and more are to follow, in general:

http://www.transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries

Kind regards
Jacques
