### ISSUE TITLE
[Error 13] Permission denied on Arch Linux after pip install 

### ISSUE THREAD

**Issue by phorward** [QQuick/Transcrypt#446]
Hi!

I wanted to checkout transcrypt as described in the documentation, but it fails:

```
$ sudo pip install transcrypt
Collecting transcrypt
Requirement already satisfied: mypy in /usr/lib/python3.6/site-packages (from transcrypt)
Requirement already satisfied: psutil<5.5.0,>=5.4.0 in /usr/lib/python3.6/site-packages (from mypy->transcrypt)
Requirement already satisfied: typed-ast<1.2.0,>=1.1.0 in /usr/lib/python3.6/site-packages (from mypy->transcrypt)
Installing collected packages: transcrypt
Successfully installed transcrypt-3.6.82
```

Then I  tried to compile something:

```
$ transcrypt a.py 

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.82
Copyright (C) Geatec Engineering. License: Apache 2.0


[Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/__javascript__/__base__.mod.js'Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/transcrypt/__main__.py", line 150, in main
    compiler.Program (transpilationDirs, __symbols__)
  File "/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 141, in __init__
    Module (self, ModuleMetadata (self, self.baseModuleName))
  File "/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 309, in __init__
    self.generateJavascriptAndMap ()
  File "/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 473, in generateJavascriptAndMap
    with utils.create (self.metadata.targetPath) as aFile:
  File "/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 93, in create
    return open (path, 'w', encoding = 'utf-8')
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/__javascript__/__base__.mod.js'


Aborted
```

The folder `/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/__javascript__` does not contain a file `__base__.mod.js`, but this

```
$ ls -ltra
total 92
-rw-r--r-- 1 root root 15336 Jan 18 10:21 __core__.mod.js
-rw-r--r-- 1 root root 69534 Jan 18 10:21 __builtin__.mod.js
drwxr-xr-x 9 root root  4096 Jan 18 10:21 ..
drwxr-xr-x 2 root root  4096 Jan 18 10:21 .
```

I will try transcrypt now on my own by cloning the repo.
Any idea for this issue?

**Comment by phorward** [comment]
OK my fault ;-) the a.py imports a base, sorry.

**Comment by pyojo** [comment]
Hi @phorward! You must run as root or in a virtual environment, since the directory "/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/__javascript__" does not have write permissions.

**Comment by phorward** [comment]
Hi, unfortunatelly I was wrong and it does not seem to be my fault.

Trying to compile any of  the demos or even a simple

```
alert("Hello World")
``` 

comes to the same result. Running as root won't be an option, what do I have to do for using virtualenv?

**Comment by pyojo** [comment]
Here you can find the documentation of how to use virtual environments: https://docs.python.org/3/library/venv.html

**Comment by pyojo** [comment]
Here you can find the documentation for virtual environments: https://docs.python.org/3/library/venv.html.
Or you can try reinstalling Transcrypt? `sudo pip install --upgrade --force-reinstall transcrypt`

**Comment by phorward** [comment]
Reinstalling did not take any effect. I found out that the demo files from the git repo compile now when doing `sudo transcrypt hello.py` once and just `transcrypt hello.py` afterwards without any problems. The first run using sudo creates files in the above directory:

```
/usr/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/__javascript__ $ ls -ltrah
total 112K
-rw-r--r-- 1 root root  15K Jan 18 11:41 __core__.mod.js
-rw-r--r-- 1 root root  68K Jan 18 11:41 __builtin__.mod.js
drwxr-xr-x 9 root root 4.0K Jan 18 11:41 ..
drwxr-xr-x 2 root root 4.0K Jan 18 11:41 .
-rw-r--r-- 1 root root  731 Jan 18 11:42 __base__.mod.js
-rw-r--r-- 1 root root  13K Jan 18 11:42 __standard__.mod.js
```

**Comment by JdeH** [comment]
Transcrypt indeed needs write permission in the install dir, since it will generate JS files in the __javascript__ directories of the modules that are part of the distribution. This can't be done in advance, since it is unknown with which compiler switches it should be done (e.g. JS 5 vs JS 6 and complex number support).

This is known (e.g. #189, also some ways to deal with that explained there) but unfortunately not easily solved for the general.

**Comment by phorward** [comment]
@JdeH thanks for your reply, I also found this out already. After running as root once, it works as expected! So, for me, this issue is resolved and explained.

**Comment by JdeH** [comment]
Ok thanks.

**Comment by phorward** [comment]
Thanks for creating this cool piece of software 👍

**Comment by JdeH** [comment]
Glad you like it, spread the word...
