### ISSUE TITLE
decorator from module

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#448]
Hi,

Previously (3.6.69 and below), I was able to use decorator function from module
```

import a_module

@a_module.a_decorator(arg1)
def my_func():
```

Now (3.6.82), compilation fail, and I have to use alias :

```
__pragma__ ("alias", "a_decorator", "a_module.a_decorator")

import a_module

@a_decorator(arg1)
def my_func():
```

Is this behavior expected ?

Thanks

**Comment by neriusmika** [comment]
I think I know where the problem is. I'll fix it after the weekend.

**Comment by JdeH** [comment]
Thanks Nerius

**Comment by neriusmika** [comment]
I checked decorators from external module with the latest transcrypt version and I can't reproduce the error. Tried with absolute and relative imports on methods and functions, everything is compiling and working for me. @bradiso can you make some test case which is not working for you?

**Comment by bradiso** [comment]
[test_case.zip](https://github.com/QQuick/Transcrypt/files/1648666/test_case.zip)

Inside a directory named here_a_module I have a module : a_module.py containing a decorator function a_decorator.

```
def a_decorator(arg):
	def decorated(func):
		def wrapper(*args):
			console.log("decorator with argument", arg)
			return func(*args)
		return wrapper
	return decorated
```

Now, in my main module (transpiled with -b -n -e 5 -xt main.py). Note that here_a_module directory absolute path is added to PYTHONPATH environment variable.

What worked previously

```
import a_module

@a_module.a_decorator("foo")
def init():
	console.log("it's ok")

init()
```

This is not working anymore ("Error while compiling").

This is working :

```
import a_module

@a_decorator("foo")
def init():
	console.log("it's ok")

init()
```

But a_decorator from a_module is becoming local in namespace.

```
import a_module

def a_decorator(arg):
	console.log("not a decorator")

@a_decorator("foo")
def init():
	console.log("it's ok")

init()
```

This ugly workaround is working

```
__pragma__ ("alias", "a_decorator_from_module", "a_module.a_decorator")

import a_module

def a_decorator(arg):
	console.log("not a decorator")

@a_decorator_from_module("foo")
def init():
	console.log("it's ok")

init()
```

**Comment by neriusmika** [comment]
@bradiso, I found the error and it's easy to fix for your case, but I think there can be more variations depending on import depth and parameters, so I need to make additional tests. Thank you for finding this bug, I'll fix it in a day or two.

**Comment by neriusmika** [comment]
I created pull request to fix this error.

**Comment by JdeH** [comment]
Pull done.
Thanks Nerius!

**Comment by neriusmika** [comment]
You're welcome Jacques, there are a few different variations and it's quite difficult to anticipate everything. Earlier I was lazy and tested decorator from another module, just without any parameters and it worked.

**Comment by JdeH** [comment]
It isn't possible to anticipate everything.
One can do ones best, but personally I am always missing edge cases (and some not so edge ones).
Fortunately people give feedback, that's why issues are so valuable!
(So thanks as well, @bradiso )
