### ISSUE TITLE
callable(None)

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#450]
callable(None)

Python : False

Transpiled : "TypeError: invalid 'in' operand anObject"

Thanks.

**Comment by JdeH** [comment]
I am missing the exact point here.
Could you give a small, complete example?

**Comment by neriusmika** [comment]
I think @bradiso means that function `callable` (https://www.programiz.com/python-programming/methods/built-in/callable) is not working like in python when parameter is equal to `None`. It should return False, but throws some error instead.

**Comment by JdeH** [comment]
Thanks for the explanation.
I've never used this function myself.

**Comment by neriusmika** [comment]
@JdeH, I just changed `callable` implementation to:

```javascript
var callable = function (anObject) {
        if ( anObject && typeof anObject == 'object' && '__call__' in anObject ) {
            return true;
        }
        else {
            return typeof anObject === 'function';
        }
    };
```
and now it works with `None`. If you think this is correct solution, you can change it in transcrypt.

**Comment by JdeH** [comment]
Indeed, that works.
I've committed it.

**Comment by neriusmika** [comment]
And here we can save a few bytes with one-liner:
```javascript
var callable = function (anObject) {
    return anObject && typeof anObject == 'object' && '__call__' in anObject ? true : typeof anObject === 'function';
};
```

**Comment by JdeH** [comment]
Preferable, indeed.
This has been committed.
