### ISSUE TITLE
Unable to import math module

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#456]
This is the error I am getting:

Error while compiling (offending file last):
	File '/home/user/Desktop/geometry.py', line 1, at import of:
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/math/__init__.py', line 1, namely:
	
	Can't import from module 'math'

Aborted

**Comment by neriusmika** [comment]
Try to compile with -v switch to get more verbose information about the error.

**Comment by notzoom** [comment]
@neriusmika Thanks, here is the output:
Extracting module properties from: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/__core__.mod.js
Extracting module properties from: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/__base__.mod.js
Extracting module properties from: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/__standard__.mod.js
Extracting module properties from: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
Parsing module: /home/user/Desktop/geometry.py
Generating code for module: /home/user/Desktop/__javascript__/geometry.mod.js
Parsing module: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/math/__init__.py
Generating code for module: /usr/local/lib/python3.5/dist-packages/transcrypt/modules/math/__javascript__/__init__.mod.js

Error while compiling (offending file last):
	File '/home/user/Desktop/geometry.py', line 1, at import of:
	File '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/math/__init__.py', line 1, namely:
	
	Can't import from module 'math'

Aborted

**Comment by neriusmika** [comment]
Still there is to little information. If you don't want to share the code, then try to compile and run autotests. At least you will know that there is no problems with paths, permissions, etc. and the error is in your code.

**Comment by notzoom** [comment]
@neriusmika Oh sorry - I am perfectly fine with sharing the code.
Here it is:
```

from math import *

canvas = document.getElementById('canvas')
context = canvas.getContext('2d')

def drawBall():
    context.beginPath()
    context.arc(x, y, 10, 0, 0)
    context.fillStyle = "#0095DD"
    context.fill()
    context.closePath()

drawBall()
```

**Comment by neriusmika** [comment]
The example that you provided is compiling without errors, and after some modification to canvas.arc parameters, it draws blue circle on the canvas. Try to run Transcrypt autotests.

**Comment by notzoom** [comment]
@neriusmika I am not familiar with autotests but there must be something wrong here with the distribution of Transcrypt that I have - I haven't modified anything to interfere with this so I am possibly pointing out something that could affect others as well.

**Comment by notzoom** [comment]
@neriusmika Ok, I just upgraded Transcrypt to latest version and the issue was gone.

**Comment by neriusmika** [comment]
go to transcrypt/development/automated_tests/transcrypt and from there run:

`transcrypt -r autotest.py` and `transcrypt -b -c -da autotest.py`
if no compilation errors occur, open autotest.html and you should see:
Status:
Test succeeded

**Comment by notzoom** [comment]
@neriusmika Thanks I will keep that in mind for the next time !
