### ISSUE TITLE
Exploratory benchmark

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#457]
I've just compared CPython with Transcrypt.
On my machine, Windows 10, Google Chrome, quadcore, the results are:

**CPython:

Pystone(1.1) time for 50000 passes = 0.550
This machine benchmarks at 90909.0909090909 pystones/second**

**Transcrypt:

Pystone(1.1) time for 50000 passes = 0.196
This machine benchmarks at 255102.04081632654 pystones/second**

But I do not yet trust these results.
Could anyone verify this on another machine, preferable single core?
Very curious...

Here's the slightly adapted PyStone code, ran same code for Transcrypt and CPython:

    #! /usr/bin/env python

    """
    "PYSTONE" Benchmark Program

    Version:        Python/1.1 (corresponds to C/1.1 plus 2 Pystone fixes)

    Author:         Reinhold P. Weicker,  CACM Vol 27, No 10, 10/84 pg. 1013.

                    Translated from ADA to C by Rick Richardson.
                    Every method to preserve ADA-likeness has been used,
                    at the expense of C-ness.

                    Translated from C to Python by Guido van Rossum.
                    
                    Adapted to both run on Transcrypt and Python by Jacques de Hooge.

    Version History:

                    Version 1.1 corrects two bugs in version 1.0:

                    First, it leaked memory: in Proc1(), NextRecord ends
                    up having a pointer to itself.  I have corrected this
                    by zapping NextRecord.PtrComp at the end of Proc1().

                    Second, Proc3() used the operator != to compare a
                    record to None.  This is rather inefficient and not
                    true to the intention of the original benchmark (where
                    a pointer comparison to None is intended; the !=
                    operator attempts to find a method __cmp__ to do value
                    comparison of the record).  Version 1.1 runs 5-10
                    percent faster than version 1.0, so benchmark figures
                    of different versions can't be compared directly.
                    
                    For Transcrypt, some not yet supported contructs were avoided
    """

    LOOPS = 50000

    import time

    def clock ():
        print (time.time ())
        return time.time ()

    __version__ = "1.1"

    [Ident1, Ident2, Ident3, Ident4, Ident5] = range(1, 6)

    class Record:

        def __init__(self, PtrComp = None, Discr = 0, EnumComp = 0,
                           IntComp = 0, StringComp = 0):
            self.PtrComp = PtrComp
            self.Discr = Discr
            self.EnumComp = EnumComp
            self.IntComp = IntComp
            self.StringComp = StringComp

        def copy(self):
            return Record(self.PtrComp, self.Discr, self.EnumComp,
                          self.IntComp, self.StringComp)

    TRUE = 1
    FALSE = 0

    def main(loops=LOOPS):
        benchtime, stones = pystones(loops)
        print (f"Pystone({__version__}) time for {loops} passes = {benchtime}")
        print (f"This machine benchmarks at {stones} pystones/second")

    def pystones(loops=LOOPS):
        return Proc0(loops)

    IntGlob = 0
    BoolGlob = FALSE
    Char1Glob = '\0'
    Char2Glob = '\0'

    Array1Glob = [0 for i in range (51)]
    Array2Glob = [[0 for i in range (51)] for j in range (51)]

    '''
    Original code:
    Array1Glob = [0]*51
    Array2Glob = map(lambda x: x[:], [Array1Glob]*51)
    '''

    PtrGlb = None
    PtrGlbNext = None

    def Proc0(loops=LOOPS):
        global IntGlob
        global BoolGlob
        global Char1Glob
        global Char2Glob
        global Array1Glob
        global Array2Glob
        global PtrGlb
        global PtrGlbNext

        starttime = clock ()
        for i in range(loops):
            pass
        nulltime = clock () - starttime

        PtrGlbNext = Record()
        PtrGlb = Record()
        PtrGlb.PtrComp = PtrGlbNext
        PtrGlb.Discr = Ident1
        PtrGlb.EnumComp = Ident3
        PtrGlb.IntComp = 40
        PtrGlb.StringComp = "DHRYSTONE PROGRAM, SOME STRING"
        String1Loc = "DHRYSTONE PROGRAM, 1'ST STRING"
        Array2Glob[8][7] = 10

        starttime = clock ()

        for i in range(loops):
            Proc5()
            Proc4()
            IntLoc1 = 2
            IntLoc2 = 3
            String2Loc = "DHRYSTONE PROGRAM, 2'ND STRING"
            EnumLoc = Ident2
            BoolGlob = not Func2(String1Loc, String2Loc)
            while IntLoc1 < IntLoc2:
                IntLoc3 = 5 * IntLoc1 - IntLoc2
                IntLoc3 = Proc7(IntLoc1, IntLoc2)
                IntLoc1 = IntLoc1 + 1
            Proc8(Array1Glob, Array2Glob, IntLoc1, IntLoc3)
            PtrGlb = Proc1(PtrGlb)
            CharIndex = 'A'
            while CharIndex <= Char2Glob:
                if EnumLoc == Func1(CharIndex, 'C'):
                    EnumLoc = Proc6(Ident1)
                CharIndex = chr(ord(CharIndex)+1)
            IntLoc3 = IntLoc2 * IntLoc1
            IntLoc2 = IntLoc3 / IntLoc1
            IntLoc2 = 7 * (IntLoc3 - IntLoc2) - IntLoc1
            IntLoc1 = Proc2(IntLoc1)

        benchtime = clock () - starttime - nulltime
        if benchtime == 0.0:
            loopsPerBenchtime = 0.0
        else:
            loopsPerBenchtime = (loops / benchtime)
        return benchtime, loopsPerBenchtime

    def Proc1(PtrParIn):
        PtrParIn.PtrComp = NextRecord = PtrGlb.copy()
        PtrParIn.IntComp = 5
        NextRecord.IntComp = PtrParIn.IntComp
        NextRecord.PtrComp = PtrParIn.PtrComp
        NextRecord.PtrComp = Proc3(NextRecord.PtrComp)
        if NextRecord.Discr == Ident1:
            NextRecord.IntComp = 6
            NextRecord.EnumComp = Proc6(PtrParIn.EnumComp)
            NextRecord.PtrComp = PtrGlb.PtrComp
            NextRecord.IntComp = Proc7(NextRecord.IntComp, 10)
        else:
            PtrParIn = NextRecord.copy()
        NextRecord.PtrComp = None
        return PtrParIn

    def Proc2(IntParIO):
        IntLoc = IntParIO + 10
        while 1:
            if Char1Glob == 'A':
                IntLoc = IntLoc - 1
                IntParIO = IntLoc - IntGlob
                EnumLoc = Ident1
            if EnumLoc == Ident1:
                break
        return IntParIO

    def Proc3(PtrParOut):
        global IntGlob

        if PtrGlb is not None:
            PtrParOut = PtrGlb.PtrComp
        else:
            IntGlob = 100
        PtrGlb.IntComp = Proc7(10, IntGlob)
        return PtrParOut

    def Proc4():
        global Char2Glob

        BoolLoc = Char1Glob == 'A'
        BoolLoc = BoolLoc or BoolGlob
        Char2Glob = 'B'

    def Proc5():
        global Char1Glob
        global BoolGlob

        Char1Glob = 'A'
        BoolGlob = FALSE

    def Proc6(EnumParIn):
        EnumParOut = EnumParIn
        if not Func3(EnumParIn):
            EnumParOut = Ident4
        if EnumParIn == Ident1:
            EnumParOut = Ident1
        elif EnumParIn == Ident2:
            if IntGlob > 100:
                EnumParOut = Ident1
            else:
                EnumParOut = Ident4
        elif EnumParIn == Ident3:
            EnumParOut = Ident2
        elif EnumParIn == Ident4:
            pass
        elif EnumParIn == Ident5:
            EnumParOut = Ident3
        return EnumParOut

    def Proc7(IntParI1, IntParI2):
        IntLoc = IntParI1 + 2
        IntParOut = IntParI2 + IntLoc
        return IntParOut

    def Proc8(Array1Par, Array2Par, IntParI1, IntParI2):
        global IntGlob

        IntLoc = IntParI1 + 5
        Array1Par[IntLoc] = IntParI2
        Array1Par[IntLoc+1] = Array1Par[IntLoc]
        Array1Par[IntLoc+30] = IntLoc
        for IntIndex in range(IntLoc, IntLoc+2):
            Array2Par[IntLoc][IntIndex] = IntLoc
        Array2Par[IntLoc][IntLoc-1] = Array2Par[IntLoc][IntLoc-1] + 1
        Array2Par[IntLoc+20][IntLoc] = Array1Par[IntLoc]
        IntGlob = 5

    def Func1(CharPar1, CharPar2):
        CharLoc1 = CharPar1
        CharLoc2 = CharLoc1
        if CharLoc2 != CharPar2:
            return Ident1
        else:
            return Ident2

    def Func2(StrParI1, StrParI2):
        IntLoc = 1
        while IntLoc <= 1:
            if Func1(StrParI1[IntLoc], StrParI2[IntLoc+1]) == Ident1:
                CharLoc = 'A'
                IntLoc = IntLoc + 1
        if CharLoc >= 'W' and CharLoc <= 'Z':
            IntLoc = 7
        if CharLoc == 'X':
            return TRUE
        else:
            if StrParI1 > StrParI2:
                IntLoc = IntLoc + 7
                return TRUE
            else:
                return FALSE

    def Func3(EnumParIn):
        EnumLoc = EnumParIn
        if EnumLoc == Ident3: return TRUE
        return FALSE

    if __name__ == '__main__':
        main(LOOPS)

**Comment by neriusmika** [comment]
CPython:
Pystone(1.1) time for 50000 passes = 498
This machine benchmarks at 100.40160642570281 pystones/second

Transcrypt:
Pystone(1.1) time for 50000 passes = 165
This machine benchmarks at 303.030303030303 pystones/second

**Comment by JdeH** [comment]
Well, that's good news I think...

**Comment by neriusmika** [comment]
Jacques, I'm experimenting a little bit, and made a list indexing to work with negative indices. The same approach as with OrderedDict via \_\_getattr\_\_ and proxies, and only on ES6. How do you think, is it worth it and should I check performance or forget about that? It adds about 30-40 additional lines to builtin.mod.js.

**Comment by JdeH** [comment]
I believe it will work, but I think it will have quite some influence on performance.
Since this will be heavily used, if it influences performance it should be under a pragma and / or switch.
In that case I think it would be nice to have, since it increases CPython compatibility.

**Comment by neriusmika** [comment]
Yes, it's slower. To assign 1000000 values in a loop, it takes about 450 ms vs 20 ms.

**Comment by JdeH** [comment]
I suggest we forget about it then.
Even with a pragma I think this is too much of a speed penalty.
If very specific requests come in we could reconsider but for now I'd say no.

**Comment by neriusmika** [comment]
Yes, you're right. And by the way I found one ugly Proxy feature. Seems that it automatically converts name arguments to strings. So our plans to support any type as OrderedDict keys would fail. Every day I hate js more and more.

**Comment by JdeH** [comment]
I think we can agree on the quality of JS.
I don't know with which mindset it was developed, but it seems to lack any kind of persistent vision.

**Comment by neriusmika** [comment]
https://cdn-images-1.medium.com/max/1000/1*Kd0UGiDvgooFooCy28rs8Q.jpeg

**Comment by JdeH** [comment]
About the key types:

Lets use the same trick as with dicts:

If it's a string that can denote a numer it is interpreted as a number.
After all datastructure mixing the two are rare, at least well designed ones.

So asking e.g. for all keys, they may be:

[1, 'car', 'bird', 1000]

or

[1, 2, 3, 4, 5]

or

['the', 'quick', 'brown, 'fox']

but never

['1', '2', '3']

or

['one', '1', 'four', 4]

And also the jskeys pragma is irrelevant for OrderedDicts, since there are no OrderedDict literals.

**Comment by JdeH** [comment]
I've opened a special issue for benchmark results only, to get some more info if possible.
I'll close this one to avoid confusion, since it's used also for other things.
