### ISSUE TITLE
Benchmark request

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#459]
**This issue is (only) meant for gathering some preliminary benchmark results for Transcrypt against CPython**

Doing this test requires installation of Python 3.6 and Transcrypt as follows:

- Download Python 3.6 from www.python.org.
- Install Transcrypt: python -m pip install transcrypt.
- Create a folder for the tests with the html and python code below in files pystone.html and pystone.py respectively
- In this folder from the command prompt type transcrypt -b -n pystone.py
- Open pystone.html in your browser to see the result
- Also run pystone.py from the command prompt
- Let us know your results for both Transcrypt (browser) and CPython (command prompt) in a comment to this issue. Results will be made public both in this issue and in the Transcrypt docs. This issue will remain open for 1 week.

**[EDIT]**

**Summarized results:**

![image](https://user-images.githubusercontent.com/1730289/35825655-cec21356-0ab6-11e8-9cdf-695e68563347.png)

**Thanks for your cooperation!**

**[END EDIT]**

```
The results on an Intel i7, 2.4 GHz, Windows 10, Transcrypt running in Chrome, are:

CPython:
Pystone(1.1) time for 50000 passes = 0.550
This machine benchmarks at 90909.0909090909 pystones/second

Transcrypt:
Pystone(1.1) time for 50000 passes = 0.196
This machine benchmarks at 255102.04081632654 pystones/second
```

We'd like to have some information on how it runs on different machines, OS'es, browsers etc.
Please include some data on your hardware and OS.

The code is:

(HTML)

```
<html>
	<head>
		<style>
			#__terminal__ {
				width: 100%;
				height: 100%;
				background-color: black;
				color: white;
				font-family: courier;
				font-size: 14px;
			}
		</style>
	</head>
	<body>
	<div id="__terminal__">
	<div>
	<script src="__javascript__/pystone.js" charset="UTF-8"></script>
	</body>
</html>

```

(Transcrypt / CPython)
```

#! /usr/bin/env python

"""
"PYSTONE" Benchmark Program

Version:        Python/1.1 (corresponds to C/1.1 plus 2 Pystone fixes)

Author:         Reinhold P. Weicker,  CACM Vol 27, No 10, 10/84 pg. 1013.

                Translated from ADA to C by Rick Richardson.
                Every method to preserve ADA-likeness has been used,
                at the expense of C-ness.

                Translated from C to Python by Guido van Rossum.
                
                Adapted to run both on Transcrypt and Python by Jacques de Hooge.

Version History:

                Version 1.1 corrects two bugs in version 1.0:

                First, it leaked memory: in Proc1(), NextRecord ends
                up having a pointer to itself.  I have corrected this
                by zapping NextRecord.PtrComp at the end of Proc1().

                Second, Proc3() used the operator != to compare a
                record to None.  This is rather inefficient and not
                true to the intention of the original benchmark (where
                a pointer comparison to None is intended; the !=
                operator attempts to find a method __cmp__ to do value
                comparison of the record).  Version 1.1 runs 5-10
                percent faster than version 1.0, so benchmark figures
                of different versions can't be compared directly.
                
                For Transcrypt, some not yet supported contructs were avoided
"""

LOOPS = 50000

import time

def clock ():
    return time.time ()

__version__ = "1.1"

[Ident1, Ident2, Ident3, Ident4, Ident5] = range(1, 6)

class Record:

    def __init__(self, PtrComp = None, Discr = 0, EnumComp = 0,
                       IntComp = 0, StringComp = 0):
        self.PtrComp = PtrComp
        self.Discr = Discr
        self.EnumComp = EnumComp
        self.IntComp = IntComp
        self.StringComp = StringComp

    def copy(self):
        return Record(self.PtrComp, self.Discr, self.EnumComp,
                      self.IntComp, self.StringComp)

TRUE = 1
FALSE = 0

def main(loops=LOOPS):
    benchtime, stones = pystones(loops)
    print (f"Pystone({__version__}) time for {loops} passes = {benchtime}")
    print (f"This machine benchmarks at {stones} pystones/second")


def pystones(loops=LOOPS):
    return Proc0(loops)

IntGlob = 0
BoolGlob = FALSE
Char1Glob = '\0'
Char2Glob = '\0'

Array1Glob = [0 for i in range (51)]
Array2Glob = [[0 for i in range (51)] for j in range (51)]

'''
Original code:
Array1Glob = [0]*51
Array2Glob = map(lambda x: x[:], [Array1Glob]*51)
'''

PtrGlb = None
PtrGlbNext = None

def Proc0(loops=LOOPS):
    global IntGlob
    global BoolGlob
    global Char1Glob
    global Char2Glob
    global Array1Glob
    global Array2Glob
    global PtrGlb
    global PtrGlbNext

    starttime = clock ()
    for i in range(loops):
        pass
    nulltime = clock () - starttime

    PtrGlbNext = Record()
    PtrGlb = Record()
    PtrGlb.PtrComp = PtrGlbNext
    PtrGlb.Discr = Ident1
    PtrGlb.EnumComp = Ident3
    PtrGlb.IntComp = 40
    PtrGlb.StringComp = "DHRYSTONE PROGRAM, SOME STRING"
    String1Loc = "DHRYSTONE PROGRAM, 1'ST STRING"
    Array2Glob[8][7] = 10

    starttime = clock ()

    for i in range(loops):
        Proc5()
        Proc4()
        IntLoc1 = 2
        IntLoc2 = 3
        String2Loc = "DHRYSTONE PROGRAM, 2'ND STRING"
        EnumLoc = Ident2
        BoolGlob = not Func2(String1Loc, String2Loc)
        while IntLoc1 < IntLoc2:
            IntLoc3 = 5 * IntLoc1 - IntLoc2
            IntLoc3 = Proc7(IntLoc1, IntLoc2)
            IntLoc1 = IntLoc1 + 1
        Proc8(Array1Glob, Array2Glob, IntLoc1, IntLoc3)
        PtrGlb = Proc1(PtrGlb)
        CharIndex = 'A'
        while CharIndex <= Char2Glob:
            if EnumLoc == Func1(CharIndex, 'C'):
                EnumLoc = Proc6(Ident1)
            CharIndex = chr(ord(CharIndex)+1)
        IntLoc3 = IntLoc2 * IntLoc1
        IntLoc2 = IntLoc3 / IntLoc1
        IntLoc2 = 7 * (IntLoc3 - IntLoc2) - IntLoc1
        IntLoc1 = Proc2(IntLoc1)

    benchtime = clock () - starttime - nulltime
    if benchtime == 0.0:
        loopsPerBenchtime = 0.0
    else:
        loopsPerBenchtime = (loops / benchtime)
    return benchtime, loopsPerBenchtime

def Proc1(PtrParIn):
    PtrParIn.PtrComp = NextRecord = PtrGlb.copy()
    PtrParIn.IntComp = 5
    NextRecord.IntComp = PtrParIn.IntComp
    NextRecord.PtrComp = PtrParIn.PtrComp
    NextRecord.PtrComp = Proc3(NextRecord.PtrComp)
    if NextRecord.Discr == Ident1:
        NextRecord.IntComp = 6
        NextRecord.EnumComp = Proc6(PtrParIn.EnumComp)
        NextRecord.PtrComp = PtrGlb.PtrComp
        NextRecord.IntComp = Proc7(NextRecord.IntComp, 10)
    else:
        PtrParIn = NextRecord.copy()
    NextRecord.PtrComp = None
    return PtrParIn

def Proc2(IntParIO):
    IntLoc = IntParIO + 10
    while 1:
        if Char1Glob == 'A':
            IntLoc = IntLoc - 1
            IntParIO = IntLoc - IntGlob
            EnumLoc = Ident1
        if EnumLoc == Ident1:
            break
    return IntParIO

def Proc3(PtrParOut):
    global IntGlob

    if PtrGlb is not None:
        PtrParOut = PtrGlb.PtrComp
    else:
        IntGlob = 100
    PtrGlb.IntComp = Proc7(10, IntGlob)
    return PtrParOut

def Proc4():
    global Char2Glob

    BoolLoc = Char1Glob == 'A'
    BoolLoc = BoolLoc or BoolGlob
    Char2Glob = 'B'

def Proc5():
    global Char1Glob
    global BoolGlob

    Char1Glob = 'A'
    BoolGlob = FALSE

def Proc6(EnumParIn):
    EnumParOut = EnumParIn
    if not Func3(EnumParIn):
        EnumParOut = Ident4
    if EnumParIn == Ident1:
        EnumParOut = Ident1
    elif EnumParIn == Ident2:
        if IntGlob > 100:
            EnumParOut = Ident1
        else:
            EnumParOut = Ident4
    elif EnumParIn == Ident3:
        EnumParOut = Ident2
    elif EnumParIn == Ident4:
        pass
    elif EnumParIn == Ident5:
        EnumParOut = Ident3
    return EnumParOut

def Proc7(IntParI1, IntParI2):
    IntLoc = IntParI1 + 2
    IntParOut = IntParI2 + IntLoc
    return IntParOut

def Proc8(Array1Par, Array2Par, IntParI1, IntParI2):
    global IntGlob

    IntLoc = IntParI1 + 5
    Array1Par[IntLoc] = IntParI2
    Array1Par[IntLoc+1] = Array1Par[IntLoc]
    Array1Par[IntLoc+30] = IntLoc
    for IntIndex in range(IntLoc, IntLoc+2):
        Array2Par[IntLoc][IntIndex] = IntLoc
    Array2Par[IntLoc][IntLoc-1] = Array2Par[IntLoc][IntLoc-1] + 1
    Array2Par[IntLoc+20][IntLoc] = Array1Par[IntLoc]
    IntGlob = 5

def Func1(CharPar1, CharPar2):
    CharLoc1 = CharPar1
    CharLoc2 = CharLoc1
    if CharLoc2 != CharPar2:
        return Ident1
    else:
        return Ident2

def Func2(StrParI1, StrParI2):
    IntLoc = 1
    while IntLoc <= 1:
        if Func1(StrParI1[IntLoc], StrParI2[IntLoc+1]) == Ident1:
            CharLoc = 'A'
            IntLoc = IntLoc + 1
    if CharLoc >= 'W' and CharLoc <= 'Z':
        IntLoc = 7
    if CharLoc == 'X':
        return TRUE
    else:
        if StrParI1 > StrParI2:
            IntLoc = IntLoc + 7
            return TRUE
        else:
            return FALSE

def Func3(EnumParIn):
    EnumLoc = EnumParIn
    if EnumLoc == Ident3: return TRUE
    return FALSE

if __name__ == '__main__':
    main(LOOPS)
    
```

**Comment by JdeH** [comment]
On the machine of @neriusmika :

CPython:
Pystone(1.1) time for 50000 passes = 498
This machine benchmarks at 100.40160642570281 pystones/second

Transcrypt:
Pystone(1.1) time for 50000 passes = 165
This machine benchmarks at 303.030303030303 pystones/second

(Windows 8.1 Core i7 Google Chrome 63)

**Comment by syegulalp** [comment]
Windows 10 Core i7-3770k Google Chrome  64.0.3282.119

Pystone
Pystone(1.1) time for 50000 passes = 0.18999981880187988
This machine benchmarks at 263158.14570400683 pystones/second

CPython
Pystone(1.1) time for 50000 passes = 0.3959991931915283
This machine benchmarks at 126262.88351001029 pystones/second

**Comment by JdeH** [comment]
I assume the first entry is Transcypt?

**Comment by jaimergp** [comment]
Windows 10 Core i5 5200U

Transcrypt (Edge 41)

```
Pystone(1.1) time for 50000 passes = 0.7289998531341553
This machine benchmarks at 68587.11944184531 pystones/second
```

Transcrypt (Chrome 63)

```
Pystone(1.1) time for 50000 passes = 0.13700008392333984
This machine benchmarks at 364963.280080749 pystones/second
```

CPython (prompt)

```
Pystone(1.1) time for 50000 passes = 0.48534369468688965
This machine benchmarks at 103019.77865861956 pystones/second
```

**Comment by sinjp** [comment]
Windows 10 Core i7 7700K

CPython 3.6.4
Pystone(1.1) time for 50000 passes = 0.1804797649383545
This machine benchmarks at 277039.3679151689 pystones/second

Transcrypt Google Chrome 64.0.3282.119
Pystone(1.1) time for 50000 passes = 0.07199978828430176
This machine benchmarks at 694446.4864614274 pystones/second

Transcrypt Firefox 58.0
Pystone(1.1) time for 50000 passes = 0.08299994468688965
This machine benchmarks at 602410.0400141327 pystones/second

[OT] Pypy3 v5.10.1
Pystone(1.1) time for 50000 passes = 0.0240631103515625
This machine benchmarks at 2077869.372225745 pystones/second

**Comment by fzzylogic** [comment]
Windows [Version 10.0.16299.125]

Ran each test a few times to see what kind of fluctuations one might expect based on background processes. Various background processes can have a big impact on results and these would be different on every machine.

**Chrome Version 63.0.3239.84 (Official Build) (64-bit)**

Best
Pystone(1.1) time for 50000 passes = 0.1659996509552002
This machine benchmarks at 301205.452615644 pystones/second

Worst
Pystone(1.1) time for 50000 passes = 0.20000004768371582
This machine benchmarks at 249999.94039536943 pystones/second

**Edge 41.16299.15.0**

Best
Pystone(1.1) time for 50000 passes = 0.6490001678466797
This machine benchmarks at 77041.58254056421 pystones/second

Worst
Pystone(1.1) time for 50000 passes = 0.7699997425079346
This machine benchmarks at 64935.08664970075 pystones/second

**Firefox 57.0.4 (64-bit)**

Best
Pystone(1.1) time for 50000 passes = 0.22900009155273438
This machine benchmarks at 218340.52406256768 pystones/second

Worst
Pystone(1.1) time for 50000 passes = 0.4230000972747803
This machine benchmarks at 118203.28251016942 pystones/second

**CPython 3.6.3**

Best
Pystone(1.1) time for 50000 passes = 0.4289989471435547
This machine benchmarks at 116550.40258937662 pystones/second

Worst
Pystone(1.1) time for 50000 passes = 0.47099852561950684
This machine benchmarks at 106157.44483326086 pystones/second

**Comment by deto** [comment]
Windows build 16299.192
Intel i5-8600k

Python (in WSL Bash, Ubuntu):
Pystone(1.1) time for 50000 passes = 0.18953990936279297
This machine benchmarks at 263796.6862392891 pystones/second

Javascript (Chome Version 63.0.3239.132 (Official Build) (64-bit)):
Pystone(1.1) time for 50000 passes = 0.08099985122680664
This machine benchmarks at 617285.0843885583 pystones/second

**Comment by ethanhs** [comment]
Windows build 17083.1000 x64
i7-5820k OC'd to 4.6Ghz

Python 3.6.4 x64
Pystone(1.1) time for 50000 passes = 0.3186008930206299
This machine benchmarks at 156936.1577299861 pystones/second

Firefox 60.0a1 (nightly) 64bit
Pystone(1.1) time for 50000 passes = 0.1660001277923584
This machine benchmarks at 301204.58739973145 pystones/second

Chrome Version 66.0.3333.0 canary (64-bit)
Pystone(1.1) time for 50000 passes = 0.15200018882751465
This machine benchmarks at 328946.95977475744 pystones/second

**Comment by SafPlusPlus** [comment]
MacBook Air (11-inch, Mid 2012)
Processor 2 GHz Intel Core i7
OSX El Captain 10.11.6 (15G19009)

Python 3.6.4
Pystone(1.1) time for 50000 passes = 0.6144499778747559
This machine benchmarks at 81373.58906405813 pystones/second

Chrome 63.0.3239.132 (Official Build) (64-bit)
Pystone(1.1) time for 50000 passes = 0.21400022506713867
This machine benchmarks at 233644.61408539832 pystones/second

Safari Version 11.0.3 (11604.5.6.1.1)
Pystone(1.1) time for 50000 passes = 0.33100008964538574
This machine benchmarks at 151057.36090152452 pystones/second

Firefox 57.0.1 (64-bit)
Pystone(1.1) time for 50000 passes = 0.25999999046325684
This machine benchmarks at 192307.6993614967 pystones/second

**Comment by Wegge** [comment]
Dell precision M6400

CPU: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
OS: Linux (Fedora 26)

CPython 3.6.2:
Pystone(1.1) time for 50000 passes = 0.5933170318603516
This machine benchmarks at 84271.97824276928 pystones/second

Google Chrome
Pystone(1.1) time for 50000 passes = 0.2369997501373291
This machine benchmarks at 210970.68655569293 pystones/second

**Comment by Mocramis** [comment]
Linux 4.14.15-1-ARCH i7-3770K

CPython 3.6.4
Pystone(1.1) time for 50000 passes = 0.34229421615600586
This machine benchmarks at 146073.166416612 pystones/second

Chomium 64.0.3282.119 
Pystone(1.1) time for 50000 passes = 0.13900017738342285
This machine benchmarks at 359711.7711733438 pystones/second

firefox 52.6.0 (ESR)
Pystone(1.1) time for 50000 passes = 0.34400010108947754
This machine benchmarks at 145348.79449641367 pystones/second

PyPy 5.10.0 with Python 3.5.3
Pystone(1.1) time for 50000 passes = 0.030472755432128906
This machine benchmarks at 1640809.9395987857 pystones/second

**Comment by JdeH** [comment]
Thanks to all!
