### ISSUE TITLE
Negative indices

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#460]
Jacques, I tried some change in the compiler to allow negative indices with simple numbers. For example this code is working:
```python
lst = [1, 8, 5]
s = 'abcde'
console.log(lst[-1])
console.log(s[-2])
```
transpiled code:
```javascript
var lst = list ([1, 8, 5]);
var s = 'abcde';
console.log (lst [lst.length - 1]);
console.log (s [s.length - 2]);
```
fix:
```python
    def visit_Subscript (self, node):
        if type (node.slice) == ast.Index:

            # ============= added code =================================
            if type (node.value) == ast.Name and type (node.slice.value) == ast.UnaryOp and type (node.slice.value.op) == ast.USub and type (node.slice.value.operand) == ast.Num:
                node.slice.value = ast.BinOp (
                    left=ast.Attribute (
                        attr='length',
                        value=ast.Name (
                            id=node.value.id,
                            ctx=ast.Load ()
                        ),
                        ctx=ast.Load ()
                    ),
                    op=ast.Sub (),
                    right=node.slice.value.operand
                )
            # ================ end ================================

            if type (node.slice.value) == ast.Tuple:    # Always overloaded, it must be an RHS index
                self.visit (node.value)
                self.emit ('.__getitem__ (')
```
so for simple and most used cases it works without any hacks. You can add this fix, if you think it's worth it.

**Comment by JdeH** [comment]
I had this idea long ago, just never got around to realizing it.
It doesn't mean any performance loss, only advantages.
So yes, do it if you find the time!

**Comment by JdeH** [comment]
I'm working on this now.

**Comment by JdeH** [comment]
Isn't easy, but may be getting somewhere...

**Comment by JdeH** [comment]
Compile time support:

```
                    isRhsIndex = not self.expectingNonOverloadedLhsIndex
                    self.expectingNonOverloadedLhsIndex = False
                    if isRhsIndex and self.allowKeyCheck:
                        # We're sure it's an RHS index and dict keychecking is on
                        # We may not be dealing with a dict here, but it's just an extra harmless check, apart from performance
                        if type (node.slice.value) == ast.UnaryOp and type (node.slice.value.op == USub):
                            self.emit ('__nk__ (')
                            self.visit (node.value)
                            self.emit (', ')
                            self.visit (node.slice.value)
                            self.emit (')')
                        else:
                            self.emit ('__k__ (')
                            self.visit (node.value)
                            self.emit (', ')
                            self.visit (node.slice.value)
                            self.emit (')')
                    else:
                        # No overloading, no keycheck
                        if type (node.slice.value) == ast.UnaryOp and type (node.slice.value.op == USub):
                            self.emit ('__n__ (')
                            self.visit (node.value)
                            self.emit (', ')
                            self.visit (node.slice.value)
                            self.emit (')')
                        else:
                            self.visit (node.value)
                            self.emit (' [')
                            self.visit (node.slice.value)
                            self.emit (']')
```

And runtime support:

```
    function __k__ (keyed, key) {  //  Check existence of dict key via retrieved element
        var result = keyed [key];
        if (typeof result == 'undefined') {
             throw KeyError (key, new Error());
        }
        return result;
    }

    function __n__ (keyed, key) {  //  Deal with negative indexes, key is abs value of a negative literal, rest would be too slow!
        if keyed instanceof Array || typeof keyed == 'string' {
            // It's crucial that there are no enhanced JavaScript types based on Array's that should use the unaltered key
            return keyed [keyed.length - key];
        }
        else {
            // Javascript native object or Proxy, do not alter the key
            return keyed [key];
        }
    }
    
    function __nk__ (keyed, key) {  // Check existence of key c.q. deal with negative index literals, depending on type of 'keyed'
        if keyed instanceof Array || typeof keyed == 'string' {
            // It's crucial that there are no enhanced JavaScript types based on Array's that should use the unaltered key
            return keyed [keyed.length - key];
        }
        else {
            return __k__ (keyed, key);
        }
    }

```

**Comment by neriusmika** [comment]
Thanks, Jacques, I wanted to write that we must check the types in addition, but you done that. Negative indexing is rare in loops, so there will be no performance loss. I think that negative indices 9 of 10 times are used to get the last element. And by the way, when at compile time we aren't checking for ast.Num, then in runtime we must check that key parameter is positive. Otherwise such code may fail:
```python
idx = -1
a[-idx]
```

**Comment by JdeH** [comment]
The above doesn't work (even with corrections) for lefthand sides.
I will now try a completely different approach, assuming that negative indices are relatively rare.
Will (mis)use the opov switch to allow them, simple and straight (I hope)...

**Comment by neriusmika** [comment]
I think, if we need opov, then it's better to leave that code for righthand sides only. Because writing indices with "length" would be shorter then writing \_\_pragma\_\_('opov'). Except the case if opov would be needed only for left side.

**Comment by JdeH** [comment]
Looks like with operator overloading on locally, this will be all:

    var __getitem__ = function (container, key) {                           // Slice c.q. index, direct generated call to runtime switch
        if (typeof container == 'object' && '__getitem__' in container) {
            return container.__getitem__ (key);                             // Overloaded on container
        }
        else if (typeof container == 'string' || container instanceof Array) {
            return container [key % container.length];
        }
        else {
            return container [key];                                         // Container must support bare JavaScript brackets
        }
    };
    __all__.__getitem__ = __getitem__;

    var __setitem__ = function (container, key, value) {                    // Slice c.q. index, direct generated call to runtime switch
        if (typeof container == 'object' && '__setitem__' in container) {
            container.__setitem__ (key, value);                             // Overloaded on container
        }
        else if (typeof container == 'string' || container instanceof Array) {
            container [key % container.length] = value;
        }
        else {
            container [key] = value;                                        // Container must support bare JavaScript brackets
        }
    };
    __all__.__setitem__ = __setitem__;

And it will work even if the thing to be indexed or the index are unpredictable return values from a function. So CPython behavior, at the expense of a pragma. But that's the deal. Without pragma's no performance. It is the hallmark of this project, that should have production level performance.

**Comment by neriusmika** [comment]
It's ok, but I think, that it would be great to have some shorter version of \_\_pragma\_\_ (and even for one-liners). Because when I need to write:
```python
__pragma__('opov')
a[-1] = 'abc'
__pragma__('noopov')
```
then better I'll write:
```python
a[a.length - 1] = 'abc'
```
But if I could write (for example):
```python
a[-1] = 'abc'  # $$:opov
```
then it would be ok for me.

**Comment by JdeH** [comment]
This seems to be working.
But will also have to test Numscrypt with things as indexy and overloady as this.

**Comment by JdeH** [comment]
I've commited the neg indices + autotest
They work when operator overloading active
Will now work on the one liner pragma 
But first a meal

**Comment by neriusmika** [comment]
Thank you, Jacques.

**Comment by JdeH** [comment]
Single line pragma's have been committed.
I've choosen the following format:

`vector2 = vector0 + vector1  # __ : opov`

The blanks are insignificant.

**Comment by neriusmika** [comment]
Jacques, thank you for the short pragmas, but can you make the reverse variation too (to turn off already enabled pragma for a single line: `# __:noopov`).

**Comment by JdeH** [comment]
Yes, why not, no runtime costs

**Comment by JdeH** [comment]
Commited.
I guess this an be closed.
Feel free to reopen.
