### ISSUE TITLE
Do you have experience with Transcrypt?  Do yo like  it? Upvote it at Slant! (link is given in issue)

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#462]
https://www.slant.co/topics/101/viewpoints/34/~best-languages-that-compile-to-javascript~python-via-transcrypt

**Comment by chopin** [comment]
Transcrypt is the best!

**Comment by notzoom** [comment]
We love Transcrypt !

**Comment by fzzylogic** [comment]
Direct link: https://www.slant.co/topics/101/viewpoints/34/~best-languages-that-compile-to-javascript~python-via-transcrypt

**Comment by JdeH** [comment]
Thanks @fzzylogic, have updated the link.
