### ISSUE TITLE
__builtin__.mod.js fixes

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#465]
Jacques, I made some fixes in \_\_builtin\_\_.mod.js:
1) function  issubclass - IsA made inline with loop instead of recursion, because with recursion sometimes it takes about 30ms to execute, now this problem gone.
2) function py_typeof - additional checking for \_\_class\_\_ property in object, otherwise it returns undefined for javascript Object types. I think better is to return type object in such cases.

**Comment by JdeH** [comment]
Has been merged into main branch.
