### ISSUE TITLE
IndexError is not thrown

### ISSUE THREAD

**Issue by chopin** [QQuick/Transcrypt#469]
I found that IndexError was not thrown. Is it a part of intended design? Is there a pragma option to enable the exception?

```
a=[1,2,3]
print('a[10]=', a[10])

RESULT:
a[10]= None
```
 Is there -luxury or -mostpythonic options available? I don't need fast speed  except a core engine. Transcrypt is already fast enough for me.

I think that it is a good policy to disable features downgrading performance, and provide options for programmers to apply locally instead. However, I hope that disabled features are supported by options as much as possible.  I think that compatibility to Python will extend target users available. There are a lot of Python users who want to use Python in web. Please don't tell me to choose other transcompilers if I need compatibility. I used Pyjs and Brython before. It was ok most cases, but I had to give up using them due to a slow core engine which is just small part of program.

I think that Transcypt's approach designing for speed and providing options for expensive features is the best way. I hope that I can build core engine with fast options, and build most other parts using expensive options. 

Thanks a lot for providing this great program.

**Comment by neriusmika** [comment]
Look at the \_\_pragma\_\_ ('keycheck') it works for lists too.

**Comment by chopin** [comment]
I applied keycheck option. Uncaught exception is thrown instead of IndexError

```
#__pragma__ ('keycheck') # IndexError
a=[1,2,3]
print('a[10]=', a[10])

Result: Uncaught exception (line 3)
```

I tried to catch it, but it was not caught by IndexError as expected.

```
#__pragma__ ('keycheck') # IndexError
try:
    a=[1,2,3]
    print('a[10]=', a[10])
except IndexError:
    print('indexError')

RESULT:
Uncaught exception
```
It was caught if I didn't specify the exception type. However, how can I catch IndexError specifically?

**Comment by chopin** [comment]
I found that KeyError was thrown instead of IndexError.  In Python, IndexError is thrown in this case. Isn't it a bug to fix?

```
#__pragma__ ('keycheck') # IndexError
try:
    a=[1,2,3]
    print('a[10]=', a[10])
except IndexError:
    print('indexError')
except KeyError:
    print('KeyError')

RESULT:
KeyError
```

**Comment by neriusmika** [comment]
It was implemented only for dictionaries. In my fork I committed to throw IndexError on lists. But I don't know if it will be approved by Jacques.

**Comment by JdeH** [comment]
It is definitively in now.
