### ISSUE TITLE
Transcrypt website is not opening

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#475]
(At this very moment)

**Comment by notzoom** [comment]
It is still not opening here.

**Comment by neriusmika** [comment]
For me it's opening.

**Comment by notzoom** [comment]
> This site can’t be reached
www.transcrypt.org’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by neriusmika** [comment]
https://mxtoolbox.com/SuperTool.aspx?action=dns%3atranscrypt.org&run=toolpage

**Comment by JdeH** [comment]
It's still the provider having trouble.
I received the following reply from them.

> Hello,
> 
> We have software stability issues on a specific server (http1) which causes short downtimes (a couple of minutes) 3 or 4 times a day. We're still trying to figure out what causes those issues and will do a kernel upgrade this morning.
>  
> It's somewhat related to the issue you had on Saturday: these stability problems uncovered a bug in our HTTP proxy. This bug was fixed yesterday.
> 
> Sorry for the trouble.
> 
> Regards,

Since they did a good job over the past 10 years with some 15 websites I was responsible for, I'll cut them some slack on this one.
