### ISSUE TITLE
ONLY NON-FAKE STARS, PLEASE!!!

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#477]
We are very happy with all the sincere github stars we get.
But it has drawn my attention that at 6/2/2018 6 stars were added, all with similar names, all with icons rather than pictures and all with the same joining date.

This could be a coincidence, but it also could point to someone attempting to support us in this way.
In that case: PLEASE DON'T DO THIS, AS IT WILL SEVERELY DAMAGE THE INTEGRITY OF THE PROJECT!

If my analysis with regard to this is correct, please be so kind as to remove these 6 stars.
If you want to contribute to its popularity, tell colleagues, write about it, use it, contribute to it.
But things like signaled above are off limits.

Jacques

**Comment by notzoom** [comment]
@JdeH Sounds like a bot.

**Comment by JdeH** [comment]
I don't like this at all.
I've sent GitHub a request to remove these stars.
Transcrypt absolutely doesn't need any trickery like this.

**Comment by notzoom** [comment]
@JdeH Isn't it a responsibility of Github to detect spam and act accordingly ?

**Comment by JdeH** [comment]
I don't know, I just know I don't want to spend any more energy on this.
So I continue programming.

**Comment by JdeH** [comment]
GitHub has settled the matter to satisfaction.
Issue closed...
