### ISSUE TITLE
Anonymous, self-invoking function

### ISSUE THREAD

**Issue by doconix** [QQuick/Transcrypt#478]
Currently, Transcrypt has a `-p` option so I can set the parent object of the function.  Many times, I just need the JS to run at load time and then disappear.  It's not an "app" that needs to stick around.  Any way to do this with the options?

As an example, suppose I have `myscript.py`:
```
print('Hello World')
```

With default transcrypt options, `myscript.js` adds to the global namespace:
```
function myscript () {
    ...
}
window ['myscript'] = myscript ();
```

With `-p .none` option, `myscript.js` still puts the function `myscript` in the global namespace:
```
function myscript () {
    ...
}
myscript ();
```
(`-p .user` also puts the function in the global namespace)

What I'm after is this:
```
$(function() {
    function myscript () {
        ...
    }
    myscript ();
});
```

That way it never enters the global JS namespace.  In fact, we could even remove the inner function and get rid of the `myscript` reference entirely, but that's just a minor enhancement.  

Thanks again for the project.  Loving it.

**Comment by notzoom** [comment]
@JdeH In case you want to see the interest in this, I was thinking about it recently as well.

**Comment by JdeH** [comment]
Thanks both for the feedback.
Am considering adding something like this.
Will get back on it.

**Comment by JdeH** [comment]
This can now be done with 3.7.1 alpha, it just generates ES6 modules, but no particular way to start them. See demo's in the prerelease.
