### ISSUE TITLE
Add a Wiki to allow users to submit their own Transcrypt example programs

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#479]
Would that be a good idea ? 
 
A lot of people seem to be copying templates and code once starting a new program and while Transcrypt website currently has some nice examples, why not add a mechanism to allow the community to easily submit its own ? 

Could also have an upvote mechanism so that the best examples get to the front of the list, or you could manually select some. 

Curious to know your thoughts Jacques.

**Comment by JdeH** [comment]
The examples on the website in fact were almost all contributed by users! And we welcome that, of course.
While a wiki could be a nice addition, personaIly I have to make choices what to invest my time in. I try to work as much as possible on the core of Transcrypt, and on the medical imaging application that started the project. 

However examples and especially applications are always useful. And if anyone would set up a website, properly functioning like you describe, and attracting good quality examples, we may link to it from the Transcrypt site, providing it is a separate entity that is concisely moderated.
