### ISSUE TITLE
Pong Demo Question

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#480]
In the Pong demo, you import the fabric.js library with: 

`from com.fabricjs import fabric`

But its files are not there - I have tried to look for its files my self on its repo and I am unable to feed transcrypt what it needs. What fabric files need to be placed in the pong folder ? Perhaps other users could be wondering the same thing.

**Comment by neriusmika** [comment]
Fabric.js should be in transcrypt distribution. Check in transcrypt/modules/com/fabricjs. You don't need to place anything related to fabric.js in the pong folder.

**Comment by notzoom** [comment]
@neriusmika Got it ! Thanks !
