### ISSUE TITLE
Ubuntu 16.04: pip install reports success but fails on hello.py compilation

### ISSUE THREAD

**Issue by tobyspark** [QQuick/Transcrypt#486]
On Ubuntu 16.04 (i.e. Python 3.5) –

```
$ sudo pip3 install transcrypt
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting transcrypt
  Downloading Transcrypt-3.6.95.tar.gz (16.7MB)
    100% |████████████████████████████████| 16.7MB 109kB/s 
Collecting mypy (from transcrypt)
  Downloading mypy-0.560-py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.2MB/s 
Collecting psutil<5.5.0,>=5.4.0 (from mypy->transcrypt)
  Downloading psutil-5.4.3.tar.gz (412kB)
    100% |████████████████████████████████| 419kB 2.4MB/s 
Collecting typed-ast<1.2.0,>=1.1.0 (from mypy->transcrypt)
  Downloading typed_ast-1.1.0-cp35-cp35m-manylinux1_x86_64.whl (724kB)
    100% |████████████████████████████████| 727kB 1.7MB/s 
Installing collected packages: psutil, typed-ast, mypy, transcrypt
  Running setup.py install for psutil ... done
  Running setup.py install for transcrypt ... done
Successfully installed mypy-0.560 psutil-5.4.3 transcrypt-3.6.95 typed-ast-1.1.0
```

All seems fine (and other sudo pip3 installs are fine). However following the demo...

```
$ transcrypt -b -m -n hello.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.95
Copyright (C) Geatec Engineering. License: Apache 2.0


[Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/__main__.py", line 153, in main
    compiler.Program (transpilationDirs, __symbols__)
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/compiler.py", line 141, in __init__
    Module (self, ModuleMetadata (self, self.baseModuleName))
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/compiler.py", line 309, in __init__
    self.generateJavascriptAndMap ()
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/compiler.py", line 480, in generateJavascriptAndMap
    self.modMap.save ()
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/sourcemaps.py", line 286, in save
    with utils.create (self.mapPath) as mapFile:
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/utils.py", line 94, in create
    os.makedirs (os.path.dirname (path), exist_ok = True)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'


Aborted
```

That `extra` file does not exist.

Note I can download the zip, and get compilation working using `python3 __main__.py -b -n ../../hello.py`

Thanks for all the development. No demand here, this is just feedback =]

**Comment by fzzylogic** [comment]
@tobyspark Thanks for the detailed report. At the moment Transcrypt requires write access to its own folder. See these issues: 
https://github.com/QQuick/Transcrypt/issues/390
https://github.com/QQuick/Transcrypt/issues/189

A simple approach to this is to install Transcrypt using virtualenv (or python 3's built in venv). 

For example, on windows, you'd do this in cmd.exe:

    mkdir myproject
    cd myproject
    # uses windows py launcher to find system python3 binary path
    # then uses python3's venv to create a new virtual folder.
    py -3 -m venv myvirtualfolder
    # activates the virtual environment which means when you
    # type 'python' at the prompt it will be the version that is
    # in your virtualenv folder, not the system version.
    myvirtualfolder\Scripts\activate
    # maybe not needed, this is just to upgrade pip and setuptools
    # in case the system versions are outdated and works around a windows
    # issue where just running pip install --upgrade doesn't work
    python -m pip install --upgrade pip setuptools
    pip install transcrypt

From then on, whenever you want to use the virtual environment, just cd into the project folder and type 'myvirtualfolder\Scripts\activate' to activate it. Any pip packages you install will then go into the virtual env folder and not be installed system wide, which can make your life easier.

**Comment by tobyspark** [comment]
Ah, gotcha. Thanks for the reply.

Right now, I'm running a VM for (just) this project, so haven't been using `venv`. Thinking about it, your documentation does say to use `venv`, but I interpreted that as best practice rather than requirement of enforcing user-space.

**Comment by JdeH** [comment]
@tobyspark

Since this is a problem that many people run into, if you find the time could you please repeat your question on https://stackoverflow.com/ using the tags [transcrypt] and [python].
This enables other developers to benefit from the answer as well.
(no obligation of course)

Kind regards
Jacques

**Comment by tobyspark** [comment]
Jacques – I don't have a StackOverflow account. Hopefully search will bring at least some of those people here. Thanks all, again, for the time.
