### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#488]
This may not sound too important.

Does the __pragma__ syntax follow the Python "beautiful is better than ugly" mantra ? 

Talking about the __ specifically.

**Comment by JdeH** [comment]
Well, does `__init__` follow it ;)
It is a habit in python to include names of special methods in `__ __`, like `__call__`, `__init__` and `__getattr__`.
Transcrypt modestly follows that habit...

**Comment by notzoom** [comment]
@JdeH Right, right. That makes sense !
