### ISSUE TITLE
How to use the eval() function?

### ISSUE THREAD

**Issue by CesMak** [QQuick/Transcrypt#491]
Hey there, 

as explained [here](https://github.com/QQuick/Transcrypt/issues/490#issuecomment-368265121) overloading methods  works fine. Let me expalin it:

First I tried to do this with complex types:
```
            __pragma__('opov')
            c = complex('1','1')
            d = complex('1','2')
            e=(c*d)
            __pragma__('noopov')
            print(e)
```

For my symbols class I did it like this:

```
            a = Symbolic('2', '4s')
            __pragma__('opov')
            b=a+a
            __pragma__('noopov')
            print(b)#4+8s
```

That all works fine. But actually what I want to do is:
1. Set variables through an input field e.g: a=syms('1','1s')
2. Store these variables in my code 
3. Execute commands like a+a

Problem is I read in the commands as strings with my html input field e.g. 'a+a' 

And now is the question how to replace the variables a with the variables declared in the local storage and execute this command..... 

Without transcrypt in standard python you could do this like this:

```
b=Symbolic('2','4s')
scope = {}
scope["a"]=b
input_str="a+a"
print(eval(input_str,scope))
```
Using the eval function in normal python it works :) 

In transcrypt I tried it like this:
```
            scope = {}
            a = Symbolic('2', '4s')
            scope["a"]=a
            __pragma__('opov')
            print(eval("a+a",scope))
            __pragma__('noopov')
```

But I got an "ReferenceError: a is not defined" error .....

That brought me to the question how to use eval in transcrypt?

**Comment by neriusmika** [comment]
eval doesn't work in transcrypt. What is the purpose of your Symbolic type? Maybe you can solve your problem with some sort of parser and compile these expressions on the fly.

**Comment by JdeH** [comment]
It is however possible to use JavaScript's `eval`, like in the following snippet taken from:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

```
def run ():
    def success (result):
        global random
    
        turtle.reset ()
        rnd = random
        eval (result)
        random = rnd
```

In this case `result` would have to be a JavaScript expression.
The following works flawlessly:

```
a = 3
print (eval ('a * a'))

def f ():
    b = 4
    print (eval ('b * b'))
    
f ()

```

It prints to the console:
```
9
16
```

Note that it doesn't require the opov pragma, since there are no python operators involved,
only eval'ing a JS string.
