### ISSUE TITLE
exception  after converted document.querySelector('p').textContent 

### ISSUE THREAD

**Issue by redstoneleo** [QQuick/Transcrypt#493]
`document.querySelector('p').textContent`
This line works well in JS, but when written in Python code and converted using `transcrypt -b -m -n hello.py`, it throw exception :
```
Uncaught TypeError: Cannot read property 'textContent' of null
    at hello.py:3
    at hello (hello.py:3)
    at hello.py:3
```

**Comment by neriusmika** [comment]
I compiled an example and it works for me:
python:
```python
console.log(document.querySelector('p').textContent)
```
html:
```html
<body>
<p>test1</p>
<script src="__javascript__/test.js"></script>
</body>
```
result in console:
```test1```

Look at your compiled js code and try to figure out what's wrong.

**Comment by redstoneleo** [comment]
Thanks, I have found that if you put `<script src="__javascript__/test.js"></script>` before `<p>test1</p>` in html, i.e.
```
<body>
<script src="__javascript__/test.js"></script>
<p>test1</p>
</body>
```
then you would get the exception

**Comment by neriusmika** [comment]
Yes, I think in such case your code executes before the p tag is inserted to the dom.
