### ISSUE TITLE
scoping __pragma__('opov')

### ISSUE THREAD

**Issue by theodox** [QQuick/Transcrypt#499]
If I have an object with an operator overload:

    class A:
        def __init__(self, v):
              self.val
        def __iadd__(self, v2):
              self.val += 2

and I invoke it like this:

     __pragma__('opov')
    test = A()
    test += 1
    test += 1
    __pragma__('noopov'')

will the extra lookup costs by paid inside `A.__iadd__`?

I ask because I'm curious about how tightly I should scope those `opov` blocks.
On a somewhat related note, how complex would it be to invoke `opov` as a context manager?  Or is it entirely a compile time concept?

**Comment by neriusmika** [comment]
If you need a better performance, then try to scope as tight as you can. Just look into produced javascript to see how each statement is transpiled.

Yes, it's compile time concept.

**Comment by theodox** [comment]
Ouch, the costs are pretty brutal.  This shows a vector math class with an `opov`. Int this case I added an override to the prototype like this:

    Vector3.prototype['__iadd__'] = Vector3.prototype.addInPlace

and tested it like this, with the tightest possible scopes:

```
t1 = babylon.Vector3(3, 4, 5)
t2 = babylon.Vector3(.005, .006, .007)

console.time('opov')
for n in range(50000):
    __pragma__('opov')
    t1 += t2
    __pragma__('noopov')
console.timeEnd('opov')

console.time('opov with original method')
for n in range(50000):
    __pragma__('opov')
    t1.addInPlace(t2)
    __pragma__('noopov')
console.timeEnd('opov with original method')

console.time('no opov')
for n in range(50000):
    t1.addInPlace(t2)
console.timeEnd('no opov')
```

> opov: 29.10205078125ms
> 11:42:26.478 bab.py:74 opov with original method: 16.219970703125ms
> 11:42:26.482 bab.py:80 no opov: 2.108154296875ms

It was the result for the second test that surprised me, since the difference in the compiled JS is just:

		console.time ('opov with original method');
		for (var n = 0; n < 50000; n++) {
			__call__ (t1.addInPlace, t1, t2);
		}
		console.timeEnd ('opov with original method');

		console.time ('no opov');
		for (var n = 0; n < 50000; n++) {
			t1.addInPlace (t2);
		}
		console.timeEnd ('no opov');

It makes me think that this kind of substitution might benefit from an alternative pragma that just did a compile-time substitution of  `a.method(b)` for `a + b` without the generality of `__call__`

**Comment by neriusmika** [comment]
Yes, you're right. But I recommend using direct calls only in places where you have performance problems. I think the direct calls are not pythonic and probably harder to maintain.

**Comment by JdeH** [comment]
For what is worth, the thoughts behind this (always open to improvement).

Operator overloading was mainly supplied with linear algebra in mind.
If you can add, multiply etc. large vectors and matrices, the overhead becomes small, unless it's also used to do the nitty gritty per-component work.

So that's why numscrypt was added. Lots of things are done very directly there, on top of JS typed arrays. It's pretty fast, including e.g. FFT and 2dim FFT, also for complex numbers, and eigenvalues.

I think heavily used core algorithms should preferably be programmed directly in JS without any overhead. But I am talking about libraries.

Giving these libs a nice API is where operator overloading shines.
So never operator overloading in inner loops!

Apart from that, a shortcut avoiding `__call__` may be a good idea anyhow.
The idea is noted!

**Comment by theodox** [comment]
In this case I'm wrapping a 3d library which has it's own Vector and Matrix classes.  Since a lot of the work is being done 30 or 60 times per second the throughput is important. In lots of cases it's unlikely to be an issue compared to code clarity.

**Comment by theodox** [comment]
I submitted a PR which adds an extra flag to `__pragma__('opov') ` that bypasses `__call__` and swaps in the pythonic magic methods instead.  It has basically no runtime overhead.  The main drawback right now is that `Number` does not have the magic methods, it works if you shim them in but I'm not sure what the most elegant way to do it would be.

**Comment by theodox** [comment]
So -- i finally found the failing test result:

```
1520921567.3413107: INFO: Invoking transcrypt: development/automated_tests/__future__ run_transcrypt36 -bnc -da -e 5 ./autotest.py
Could not find mypy
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.101
Copyright (C) Geatec Engineering. License: Apache 2.0
Saving target code in: ./__javascript__/autotest.js
Ready
127.0.0.1 - - [13/Mar/2018 07:12:47] "GET /run_test/test_html::-bnc__-da__-e__5 HTTP/1.1" 200 3251
127.0.0.1 - - [13/Mar/2018 07:12:47] "GET /run_test/__javascript__/autotest.js HTTP/1.1" 200 111540
1520921577.957632: INFO: result reported
1520921577.9579353: DEBUG: test /home/travis/build/QQuick/Transcrypt/transcrypt/development/automated_tests/__future__
1520921577.9581082: DEBUG: res ERROR
1520921577.9582705: DEBUG: flags -bnc__-da__-e__5
1520921577.9586189: INFO: ERROR /home/travis/build/QQuick/Transcrypt/transcrypt/development/automated_tests/__future__ ERROR[/tmp/transcrypt_tester_stopflag_8080 set]
127.0.0.1 - - [13/Mar/2018 07:12:57] "GET /result?test=/home/travis/build/QQuick/Transcrypt/transcrypt/development/automated_tests/__future__&flags=-bnc__-da__-e__5&res=ERROR HTTP/1.1" 200 181
ERROR /home/travis/build/QQuick/Transcrypt/transcrypt/development/automated_tests/__future__ ERROR
 stopflag with status ERR found 
```
However when I run the autotester locally, the tests in `__future__` pass.  Is this maybe a firefox vs Chrome thing?

**Comment by theodox** [comment]
In case anybody is following this, the version in  PR #501 seems to work. It has not been integrated into the main transcrypt because it is not passing the CI tests -- even though it passes the same tests when I run them locally.  If you're interested in playing with it, the basic idea is to use

```
___pragma___('opov', 'fast')
a += 1
b = c + d
___pragma___('nopov')
```
The  `fast` keyword uses a more limited form of overloading that expects all items using the +, -, *, /, ^, &, | and **  operators to implement the Python magic methods `__add__`,` __sub__`,` __mul_` and so on.  The PR includes a patch to the Javascript `Number.prototype` that adds them there.  This is faster than the default transcrypt operator overloading, more or less on par with non-overloaded methods.  The primary  limitation is that you'll have make sure any JS objects inside a fast overload block implement methods with the right pythonic names and signatures.

If anybody can help figure out why the CI tests fail, Id appreciate it.  Im on OSX here so I can't run the CI builder locally.  The manual tests all pass, so I'm a bit up a tree.

**Comment by JdeH** [comment]
Does the shipment test also pass completely?

**Comment by theodox** [comment]
It seems to fail on the time test:
```
!!!time/strptime.py:30	'FEb .1.1902 [ %b .%d.%Y ] = ' (1902, 2, 1, 0, 0, 0, 5, 32, -1)		
!!!time/strptime.py:30	'3112199912:00:00pm [ %d%m%Y%H:%M:%S%p ] = ' (1999, 12, 31, 12, 0, 0, 4, 365, -1)		
!!!time/strptime.py:30	'FEb .1.1902 [ %b .%d.%Y ] = ' (1902, 2, 1, 0, 0, 0, 5, 32, -1)		
!!!time/strptime.py:30	'M1.1.1901 [ M%m.%d.%Y ] = ' (1901, 1, 1, 0, 0, 0, 1, 1, -1)		
!!!time/strptime.py:30	'2.1.1900 [ %m.%d.%Y ] = ' (1900, 2, 1, 0, 0, 0, 3, 32, -1)		
!!!time/strptime.py:30	'6.1.2000 [ %m.%d.%Y ] = ' (2000, 6, 1, 0, 0, 0, 3, 153, -1)		
!!!time/strptime.py:30	'nov .1.1900 [ %b .%d.%Y ] = ' (1900, 11, 1, 0, 0, 0, 3, 305, -1)		
!!!time/strptime.py:30	'2.1.1900 [ %m.%d.%Y ] = ' (1900, 2, 1, 0, 0, 0, 3, 32, -1)		
!!!time/strptime.py:30	'december 1.1999 [ %B %d.%Y ] = ' (1999, 12, 1, 0, 0, 0, 2, 335, -1)		
!!!time/strptime.py:30	'Tue Jul 18 19:32:11 2016 [ %a %b %d %H:%M:%S %Y ] = ' (2016, 7, 18, 19, 32, 11, 1, 200, -1)		
!!!time/strptime.py:30	'31.12.1999 12:00:00pm [ %d.%m.%Y %I:%M:%S%p ] = ' (1999, 12, 31, 12, 0, 0, 4, 365, -1)		
!!!time/strptime.py:30	'TueJul 18 19:32:11 2016 [ %a%b %d %H:%M:%S %Y ] = ' (2016, 7, 18, 19, 32, 11, 1, 200, -1)		
!!!time/strptime.py:30	'TueJul18 19:32:11 2016 [ %a%b%d %H:%M:%S %Y ] = ' (2016, 7, 18, 19, 32, 11, 1, 200, -1)		
!!!time/strptime.py:30	'TueJul1819:32x112016 [ %a%b%d%H:%Mx%S%Y ] = ' (2016, 7, 18, 19, 32, 11, 1, 200, -1)		
!!!time/strptime.py:30	'TueJul1819:32xx112016 [ %a%b%d%H:%Mxx%S%Y ] = ' (2016, 7, 18, 19, 32, 11, 1, 200, -1)
```
I'm stumped as to why this would be affected by the change to builtins js file

**Comment by theodox** [comment]
realized this should have been closed long ago...
