### ISSUE TITLE
Pragma Statement as Command Line Switch

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#502]
Jacques has told me in the past that this is possible but I haven't asked how.
If anyone knows, I would really appreciate it to find out.

**Comment by JdeH** [comment]
Hi notzoom,

Some functionality of pragma's is also available as commandline switches (but not all).
In general it's better to use the pragma's.

Command line switches are listed here:

http://www.transcrypt.org/docs/html/installation_use.html#available-command-line-switches

Pragma's are listed here:

http://www.transcrypt.org/docs/html/special_facilities.html#the-pragma-mechanism
