### ISSUE TITLE
Comparison against other pages

### ISSUE THREAD

**Issue by janat08** [QQuick/Transcrypt#505]
Reassure users that this is likely best choice, here's some info: http://stromberg.dnsalias.org/~strombrg/pybrowser/python-browser.html

My google returns brython, and skulpt, so highlighting advantages against those would be good.

**Comment by JdeH** [comment]
I think of Transcrypt, Skulpt and Brython as each having their own niche, advantages, disadvantages etc.
Comparing them would be useful, but should probably not be done by a contributer to Transcrypt.

The following gives a nice comparison, although of course incomplete:
https://stackoverflow.com/questions/30155551/python-in-browser-how-to-choose-between-brython-pypy-js-skulpt-and-transcrypt
