### ISSUE TITLE
Progress and planning w.r.t. ES6 modules

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#510]
https://github.com/QQuick/Transcrypt/issues/498#issuecomment-377674242

**Comment by doconix** [comment]
Kudos.  Fantastic direction to go!

**Comment by JdeH** [comment]
The shipment test is almost working.
Of course there are still loose ends, but in principle it has succeeded, even the sourcemaps.
I'll draw up a temporary release from the modules branch as soon as the shipment tests works.
Almost no doc yet, but one thing at a time.
