### ISSUE TITLE
Default named parameter

### ISSUE THREAD

**Issue by drummonds** [QQuick/Transcrypt#522]
Default named parameters don't seem to give the right response.  I don't know enough about javascript to be able to debug it.
```html
<!-- test.html !-->
<p id="comment">Original comment</p>
```
```python
# test.py
# Named parameters don't seem to work
def test(my_font="sans-serif2"):
    document.getElementById('comment').innerHTML = my_font

test(my_font='Verdana')
```
Gives text "sans-serif2" rather than expected "Verdana"

**Comment by metamarcdw** [comment]
Are you using the kwargs pragma, or the -k command line switch?
https://www.transcrypt.org/docs/html/special_facilities.html#keeping-your-code-lean-pragma-kwargs-and-pragma-nokwargs

**Comment by drummonds** [comment]
Thank you - I have resolved it now.  I did wonder if it could be automatically turned on or a warning given if
a named argument used but no pragma there.
