### ISSUE TITLE
Pure re+algorithmic code does not work on an old android Samsung Galaxy S3 device

### ISSUE THREAD

**Issue by shlomif** [QQuick/Transcrypt#527]
Hi!

In this code - https://github.com/shlomif/fc-solve/tree/a177b947aa093d4849b11dfdbfe15dc3307ff25d/fc-solve/site/wml - demoed here - http://www.shlomifish.org/1/1/ - the alert() with the numbers is not displayed on the android s3 device while working perfectly in firefox on mageia v7 x86-64. Can you help me get it to work?

**Comment by shlomif** [comment]
Note that I tried either or both of the workarounds in https://github.com/QQuick/Transcrypt/issues/298 and they didn't work.

**Comment by shlomif** [comment]
Ping! Can I get any help?

**Comment by shlomif** [comment]
An update: on the same phone, the code works fine in firefox mobile. Still doesnt work properly in mobile Chrome.

**Comment by shlomif** [comment]
Hi,

On Sun, 03 Jun 2018 06:23:27 -0700
Jacques de Hooge <notifications@github.com> wrote:

> Hi sholimif,
> 
> I've been off the radar for a few weeks, sorry for the delay.
> 
> I've just tried mobile Chrome on IPhone and the numbers get displayed there.
> Unfortunately I currently don't have access to an Android device.
> Could be a security setting of your Chrome installation on Android.
> 

could be.

> Please try to use `__pragma__ ('js', ...)` to display the alert, bypassing
> Trancsrypt altogether. If that does work, the problem must be in Transcrypt.
> Otherwise it seems to have to do with Android S3 itself.
>

the js code is:

        try {
            ints = s2i.find_index__board_string_to_ints(deal_str);
            alert(ints.map((i) => i.toString()).join(','));
        } catch (e) {
            alert(e);
        }

the alert is written in js and just wraps the "ints" result of the transcrypt
code.

> Could anyone please try to reproduce this on Android S3 / Chrome?
> 

I'll try to ask on forums.

Thanks!

> KR
> Jacques
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Humour - http://perl-begin.org/humour/

The way of the world is to praise dead saints, and persecute living ones.
    — Nathaniel Howe, http://www.ldsquotes.org/quote?q=1900

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi!

A friend on freenode told me the page worked fine for him on A Samsung Galaxy J1 with android 4.4.4. So it may only affect my device,

**Comment by shlomif** [comment]
Note that as far as I am concerned, this issue can be closed.

**Comment by JdeH** [comment]
Thanks, will close this
