### ISSUE TITLE
`SYNTAX FAULT` when using `.is()`

### ISSUE THREAD

**Issue by myii** [QQuick/Transcrypt#528]
Firstly, this is a fantastic package, a real gem -- kudos!

---

#### Problem

I've been tripped up trying to use `.is()`, i.e. [jQuery docs](http://api.jquery.com/is/), [w3schools docs](https://www.w3schools.com/jquery/traversing_is.asp).

For obvious reasons, gets flagged as a syntax error in the editor and that continues into the compilation:

```python-traceback
Error while compiling (offending file last):
        File 'test.py', line 712, namely:

        if S(this).is [<-SYNTAX FAULT] ('li'):
```

---

#### Workaround

Searching for the solution using `is` as a search term doesn't get very far.  Apologies if the answer is already out there.

What I did manage was to figure out a workaround by using `.IS()` and then substituting it in the compiled `js` files.

So starting with:

```python
        if S(this).IS('li'):
```

And then running a `find` & `sed` after compiling:

```bash
$ find __javascript__ -name "*.js" | xargs sed -i -e 's:\.IS (:.is (:'
```

Has been working fine for me since.

Is there an official method of using `.is()`?

---

#### Another workaround

As I was about to submit this, I came across #487.  Using `__pragma__ ('js', '{}', '''` does work but it isn't pleasant to use in this situation, mixing Python and JS code together.  However, it is good to know that there is a pass-through mode.

**Comment by theodox** [comment]
what about `__pragma__(alias, 'is_a', 'is')` or something like that? This is what the alias mechanism is great at:  https://www.transcrypt.org/docs/html/special_facilities.html#pragma-alias

**Comment by myii** [comment]
@theodox Looking closer at the predefined aliases, `('js_is', 'is')` is more consistent.  I've put that in a PR so that it can be considered for general inclusion.  Thanks once again.

**Comment by JdeH** [comment]
@theodox Thanks for the PR.
I have some backlog with the PR's.
Should be resolved in the coming weeks.
