### ISSUE TITLE
Default argument values are not overridden

### ISSUE THREAD

**Issue by pmdevita** [QQuick/Transcrypt#540]
Sorry for the dumb question but I haven't been able to find an answer. Given the following

```python
def test(one="a", two="b"):
    print(one, two)

test(one="string")
```
CPython prints
```string b```
whereas Transcrypt prints
```a b```

In the generated JavaScript we get this
```javascript
var test = function (one, two) {
	if (typeof one == 'undefined' || (one != null && one .hasOwnProperty ("__kwargtrans__"))) {;
		var one = 'a';
	};
	if (typeof two == 'undefined' || (two != null && two .hasOwnProperty ("__kwargtrans__"))) {;
		var two = 'b';
	};
	print (one, two);
};
```

In the test, the object ```one``` that is passed in is an object with a ```__kwargtrans__``` property and a ```one``` property that equals "string". Rather than setting ```one``` to the value on this object, the ```__kwargtrans__``` property causes the second condition of the || statement to be true and sets ```one``` to the default.

Is there some other way to do this or is the functionality not supported by Transcrypt?

Thanks!

**Comment by theodox** [comment]
Are you using  `__pragma__ ('kwargs')` to enable keyword arguments when you define `test()`?

See https://www.transcrypt.org/docs/html/special_facilities.html?highlight=kwargs#keeping-your-code-lean-pragma-kwargs-and-pragma-nokwargs

**Comment by pmdevita** [comment]
Yep that's it. Sorry about that, thanks for the help!
