### ISSUE TITLE
Not a bug : ES6 "const", "let" to replace ES5 "var"

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#545]
Hi,

After reading (a lot more resources available on the Web) : 
https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75
https://hackernoon.com/js-var-let-or-const-67e51dbb716f

I saw in my transpiled ES6 code (vs transpiled ES5) that there are a lot of var keywords (there are let keywords too), and no const keyword. This is obviously not a bug but may be something that could improve reliability and performance in some cases.

**Comment by bradiso** [comment]
Looking deeper in transcripted code, I think it's not easy to use const and let keywords, due to dynamic nature of Python variables and lack of real const.

Nothing to improve so...

**Comment by JdeH** [comment]
Indeed, it turned out to be not so easy to replace var by let, exactly due to the cause you indicate...

**Comment by mojimi** [comment]
Why not just make an idiom for it? I mean it wouldn't be python anymore but it's a solution...
