### ISSUE TITLE
Priority given to Transcrypt 3.7

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#546]
Hi,

Due to other activities some backlog has been incurred in dealing with issues and pr's.
Nevertheless priority will be given to to getting 3.7 out, supporting JS modules and dataclasses.
This will prevent double work in re-implementing (or manually merging) solutions from 3.6 in 3.7.

After that an attempt will be made to work away the backlog.
Inevitably regressions and omissions will occur, as 3.7 is a (rare) major refactoring, especially w.r.t. the module mechanism.
After the transition, ample time will be taken to iron out remaining issues that may (and will) emerge.

KR
Jacques

**Comment by BLeAm** [comment]
Glad to see you back. :D
