### ISSUE TITLE
Question: __javascript__ or __target__?

### ISSUE THREAD

**Issue by g40** [QQuick/Transcrypt#557]
The example here: 

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/tutorials/baseline/bl_010_hello_world/hello_world.html#L6 uses `__target__` for the script directory. 

Another, here:

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/tutorials/static_typing_tutorial/static_typing_tutorial.html#L1 uses `__javascript__`. 

Rather confusing. Any thoughts? TAIA.

**Comment by JdeH** [comment]
The static_typing tutorial has been repaired in 3.7.5.
However it's still a very basic tutorial, in the long run a series of gradually building up examples is needed.
