### ISSUE TITLE
Issue with compile

### ISSUE THREAD

**Issue by BelieveinStephen** [QQuick/Transcrypt#570]
Trying to use transcrypt and keeping running into an error.  Have ran the test autotests properly but when trying to run the hello example I am getting this error. 

Error while compiling (offending file last):
        File '<org.transcrypt.compiler.Module object at 0x04A62B30>', line 0, namely:

        Attempt to import module: hello.py
        Can't find any of:
                C:/Users/Steve/Desktop/hello/hello/py.py
                C:/Users/Steve/Desktop/hello/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/lib/site-packages/transcrypt/modules/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/lib/site-packages/transcrypt/modules/hello/py.js
                C:/Users/Steve/AppData/Local/Programs/Python/Python37-32/Scripts/hello/py.py
                C:/Users/Steve/AppData/Local/Programs/Python/Python37-32/Scripts/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/python37.zip/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/python37.zip/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/DLLs/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/DLLs/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/lib/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/lib/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/hello/py.js
                c:/users/steve/appdata/local/programs/python/python37-32/lib/site-packages/hello/py.py
                c:/users/steve/appdata/local/programs/python/python37-32/lib/site-packages/hello/py.js

Aborted

just wondering why this is.  Thanks.

**Comment by phorward** [comment]
hi, you have to call transcrypt without the .py extension to the module. In this case `transcrypt hello` and it should work.

**Comment by BelieveinStephen** [comment]
I have tried it without the extension and still get the same errors.

**Comment by JdeH** [comment]
I see you've closed the issue.
Does that mean your problem is solved?

**Comment by BelieveinStephen** [comment]
I am no longer getting errors however I do not see the proper output on my web browser.  It may be due to a cache issue. I also misunderstood what this complier does, I thought it took my python code and turned it into javascript code, not that it used code from python in js.

**Comment by phorward** [comment]
Transcrypt does exactly what you thought: Compiles Python into JavaScript.

**Comment by BelieveinStephen** [comment]
Ok I got it working thanks.

**Comment by BelieveinStephen** [comment]
I have figured it out, but fyi, the main transcrypt page has the wrong code for the html file.  It is suppose to be the one from the tutorial 
<script type="module">import * as hello from './__target__/hello.js'; window.hello = hello;</script>
instead of 
<script src="__javascript__/hello.js"></script>

**Comment by JdeH** [comment]
This should be fixed now.
Please let me know if there are still problems with this.
