### ISSUE TITLE
Deep __target__ rather than flat (see modulepaths branch)

### ISSUE THREAD

**Issue by doconix** [QQuick/Transcrypt#573]
When a .py source file is compiled, it and all of its imports are placed in a flat `__target__` directory. Suppose I have the following code files (with the noted imports):
```
src/main.py
    from utils.encoder import encode
src/utils/encoder.py
    import re
```

When `main.py` is compiled, we get a flat output directory:
```
__target__/
    main.js
    utils.encoder.js
    re.js
    re.translate.js
    org.transcrypt.__runtime__.js
```

Instead, I'm suggesting a deep output directory:
```
__target__/
    main.js
    utils/
        encoder.js
    re
        __init__.js
        translate.js
    org/
        transcrypt/
            __runtime__.js
```

This isn't hard to get transcrypt to do -- I created a branch called *modulepaths* that makes the deep structure and creates the right imports for it. This matches what people would expect (1-1 relationship between source and target).

The generated `import` statements now traverse. For example, in `encoder.js` we need to go up to get to the `re` directory:
```
import * as __module_re__ from '../re/__init__.js';
```

The primary reason I'm thinking this works better is it steps toward allowing compilation anywhere. The current method essentially hard codes all the names relative to the main .py file.

This is different than python and from JS, where relative imports deep in directories can simply refer to files in the parent directory. While transcrypt source files can do this, the generated files are hard coded in their locations.  

Since this new branch has relative imports in the generated .js files, the target files can be referenced to/from external locations (such as `node_modules`).

**Comment by doconix** [comment]
FYI, there's a related issue that is bigger than the above. Transcrypt always follows imports, essentially being a bundler. If something in `node_modules` is referenced, it gets included in the `__target__` directory.

When a full bundler like webpack or gulp are being used, transcrypt really shouldn't be following imports at all.  In can, essentially, be less smart. It should simply transcrypt the *current* file, which is returned to the bundler. Since the generated .js file contains import statements, the bundler can follow them. Other .py files in the project directory are transpiled by new calls to transcrypt -- all driven by the bundler.

There's just one location the bundler doesn't easily see: the built-in modules in transcrypt, such as `re` and `math`. In this case, we can still let the bundler be in charge by putting the common transcrypt modules in the `npm` repository OR by adding the transcrypt directory as a repo in the bundler settings.

This additional issue and the main one above are pushing towards my goal of making transcrypt a first-order transpiler that can be put into the build chain of any modern project.

**Comment by doconix** [comment]
P.S. I know there is an npm module that puts transcrypt into the webpack build chain. But it works around these issues to make it happen.

**Comment by JdeH** [comment]
This is doable and useful, but has more consequences than it seems at first sight.
I'd like it to be an option.
