### ISSUE TITLE
Can't import a JS lib with a dot in its filename (was: BUG: can't import a JS lib with a hyphen in its name)

### ISSUE THREAD

**Issue by garyo** [QQuick/Transcrypt#576]
I have some JS code I'm trying to rewrite in python with transcrypt. I have these JS lines:

```
import { saveAs } from 'file-saver';
import inspect from 'browser-util-inspect';
```
where those JS modules are in my node_modules subdir. How can I translate that to python, since the module names have hyphens ("-")? I can't write
```
from node_modules.file-saver import saveAs
```
because hyphens aren't allowed in python module names.

**Comment by metamarcdw** [comment]
If you're using Node, you should be able to just write

`saveAs = require('file-saver')`

**Comment by garyo** [comment]
I'm not using Node, unfortunately -- this is for front end, in the browser.

**Comment by metamarcdw** [comment]
Are you using a bundler?

**Comment by garyo** [comment]
I plan on using webpack. Does that affect things?

**Comment by metamarcdw** [comment]
Webpack will bundle based on require calls also. I use this currently in a project that depends on Transcrypt and Webpack:
https://github.com/metamarcdw/python-fullstack-transcrypt

**Comment by JdeH** [comment]
It should be possible to use module names contiaining a -, using aliases, but it was broken with TS 3.7.1
It'll be fixed in the next minor release, an example will be included in the autotest.
Sorry for the inconvenience.

**Comment by JdeH** [comment]
Fixed in 3.7.8.
Manual test added as 
`Transcrypt\transcrypt\development\manual_tests\import_export_aliases`
You need the -am switch (to maintain backward compatibility).
Feel free to reopen if still problems.
KR
Jacques

**Comment by JdeH** [comment]
Is ngl.esm a filename? So are there dots in filenames?

**Comment by JdeH** [comment]
Done
Feel free to reopen if still problems with this

Kind regards
Jacques
