### ISSUE TITLE
Can't import a module that exports a var with $ in its name

### ISSUE THREAD

**Issue by garyo** [QQuick/Transcrypt#578]
Here's a bug: create a Javascript module `foo.js`:
```
var Bar= 0;
var Foo$1 = 1;
export { Bar, Foo$1 as Foo };
```
and a python main which tries to import that:
```
from foo import Foo;
```
With the latest transcript (3.7.4) with python 3.7 on Linux, I get a very long error traceback, but the key part is this:
```
  File "/home/garyo/.virtualenvs/horizon-web/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 323, in digestJavascript
    result.exportedNames.extend (eval (re.sub (r'\w+', lambda nameMatch: f'\'{nameMatch.group ()}\'', match.group (1))))
  File "<string>", line 1
    { 'Bar', 'Foo'$'1' 'as' 'Foo' }
                  ^
SyntaxError: invalid syntax
```

Perhaps the regex `r'\w+'` needs to also accept `$`; patching that to `r'[\w$]+'` in utils.py works for me.

**Comment by JdeH** [comment]
Quite right.
Fixed in 3.7.8
