### ISSUE TITLE
Transcrypt Twitter Account

### ISSUE THREAD

**Issue by PythonLinks** [QQuick/Transcrypt#592]
The twitter account does not have a description, so I wrote one for you. 

Transcypt has Python's syntax, operators, classes. inheritance and modules, but transpiles to readable Javascript. Debug in the browser using source maps.   

It fits in the space provided.  Is that an accurate descriptions?
I hope that helps.
Chris

**Comment by JdeH** [comment]
Thanks, I added this in the Bio field of the Twitter profile with some minor modifications:

> Transcrypt has Python's syntax, operators, classes. inheritance and modules, but transpiles to fast, readable Javascript. Debug in the browser using sourcemaps.

Thanks!

**Comment by JdeH** [comment]
Feel free to reopen if I used the wrong field or missed something else essential about Twitter...
