### ISSUE TITLE
Link to "Practical example: a simple, responsive website using no HTML or CSS at all" is offline.

### ISSUE THREAD

**Issue by metaperl** [QQuick/Transcrypt#595]
[Section 5.1 of the manual](https://www.transcrypt.org/docs/html/integration_javascript.html#practical-example-a-simple-responsive-website-using-no-html-or-css-at-all) links to [a website](http://www.wiskundeles.com/) which is offline.

**Comment by JdeH** [comment]
Thank you!
Will be corrected in next minor version.
KR
Jacques

**Comment by JdeH** [comment]
Fixed in 3.7.12
