### ISSUE TITLE
.js file imports only work in the same directory.

### ISSUE THREAD

**Issue by doconix** [QQuick/Transcrypt#599]
I hit this working on the bundling, but it's really a separate issue, so I'm putting it in its own thread. Yes, it's about the flat vs. deep `__target__` structure. Again. This is a good example of the issue, so here you go again. 

I have the following project:

```
project/
    main.py  (main program file)
    constants.py
    utils/
        files.js

# files.js:
    import { config } from '../constants';
```

The `../` in the import matches things.  But once transcrypt runs, I get the following:

```
project/
    __target__/
        main.js
        constants.js
        utils.files.js
```

The `../` import in `utils.files.js` fails because it wasn't expecting flattening. **This is going to fail anytime we import `.js` files from `.py` files and the imports are in an parent or subdirectory.**

A deep `__target__` fixes this because it mirrors the source structure. 

```
project/
    __target__/
        main.js
        constants.js
        utils/
            files.js
```

Possible fixes:

* Use the deep structure. I have the code for this working, but it's not fully tested so ripple effects still probably there.
* Rewrite the imports in `.js` files so they reference the new names (IMO that opens a whole new world of issues). 
* Support both with a command-line switch. This wouldn't be hard, but I'm not sure that gains much. Users should be protected from the internal structure, so why give an option?
* Consider it an edge case and forget about it. If you definitely don't want to do it, I'll (finally) leave it alone. :)

**Comment by JdeH** [comment]
To have deep structure under a command line switch would be fine in the end. But for now I'd like to postpone it since I fear the added complexity and, indeed, the ripple effects. Currently I'd like to focus on resolving some other long standing issues.
