### ISSUE TITLE
Executable comments (seem to eliminate the need for browser stubs as a separate package)

### ISSUE THREAD

**Issue by brumar** [QQuick/Transcrypt#602]
I don't know if it's a good or wrong idea, but let me describe my use case. I want to ship an application where the transcrypt py files are actually interpretred by Cpython by import statements. I do that to grab some informations to strenghen the link between my js frontend (transcrypted) and my python backend. To do that I need to avoid exceptions at import time that would be caused by this kind of line: 
```py
document.addEventListener("DOMContentLoaded", lambda e: start())
```
As far as my understanding goes, I have the following options :  
1. mocking manually document within a `# __pragma__('skip') [...] # __pragma__('noskip').` The problem is that it add clutters for each file that use "document".
2. adding document in the stubs.py and add transcrypt as dependency of my project. The problem is that transcrypt has a lot of dependencies
3. building my own stubs.py which is a fork on the original stubs.py and imported inside a `__pragma__ skip`

I am following the option 3) . If I am not the only person with this kind of need, maybe that would be useful to publish an independent package that answer this need.

I have also though of a trick like that:  
```py
__pragma__("start_uncomment")
# document.addEventListener("DOMContentLoaded", lambda e: start())
__pragma__("stop_uncomment")
```
This kind of pragma would be very useful to me as it would hide stuff from Cpython but reveal it to Transcrypt (the reverse job of `__pragma__('skip') if you will`). But maybe there is already a trick like that I missed ?

**Comment by JdeH** [comment]
About your first idea:

> 3. building my own stubs.py which is a fork on the original stubs.py and imported inside a `__pragma__ skip`

> I am following the option 3) . If I am not the only person with this kind of need, maybe that would be useful to publish an independent package that answer this need.

So what you mean here is a more extensive stub module, that implements stubs for some often used objects of the JavaScript DOM API? I have no idea how many people would benefit from that. To estimate the value of that I'd like to understand why one would import Transcrypt modules that contain references to the DOM API in code that will be interpreted by CPython. Can you explain that to me in some more detail. I can imagine modules that are indeed useable both by Transcrypt and by CPython, in fact being able to write code that runs with both is one of the "reasons to be" of Transcrypt. But from  your issue it seems that it's also useful to import a module in a CPython application that has certain parts that have meaning only in a browser. And that it's easier to leave those parts out when this module is interpreted by CPython than to put them in a separate module. An example would probably clarify that to me.


About your second idea:

```
__pragma__("start_uncomment")
# document.addEventListener("DOMContentLoaded", lambda e: start())
__pragma__("stop_uncomment")
```

> This kind of pragma would be very useful to me as it would hide stuff from Cpython but reveal it to Transcrypt (the reverse job of __pragma__('skip') if you will).

I think that's a very clever and useful addition. Of course it may be the case that there are some "real" comments in such code, that should not be transformed into executable statements. But that is easily dealt with by using some form of special purpose "uncommentable comment". Seems clear to me that Transcrypt should have that one way or another. I'd like to give the syntax some more thought, but count it in for the next release.

Having the "uncommentable comments" would lessen or avoid the need for a more extensive stubs module, right? Or am I missing something?

Kind regards
Jacques

**Comment by JdeH** [comment]
The "weak comments" (uncommentable comments) are in the process of being added. Currently I'd like to drop the "browser stubs as a separate package" part, since the weak comments offer enough flexibility.

**Comment by brumar** [comment]
Yes it does! Thanks for this improvement, I am sure I won't be alone to find it useful. The only personal remaining advantage of advanced stubs would be to get some IDE auto-completion features and things related. The syntax and the multi-line weak comment is interesting. I believe "weak comment" is a bit confusing, because a weak comment is still a comment after all. As the transcrypt compiler is the primary target, maybe terms like "fake comment" or "sham comment" would fit better what's going on.

**Comment by brumar** [comment]
About `#:`, it seems that it's sometimes interpreted as docstrings for variables. I can't find the related PEP so maybe that's a convention out of nowhere. Still, maybe that's risky to use that.

**Comment by JdeH** [comment]
Indeed #: is used for variable comments in some tools:

[http://epydoc.sourceforge.net/manual-docstring.html)](http://epydoc.sourceforge.net/manual-docstring.html)

Also I agree that weak comment is a bit weak. Reason was that the -w switch was still unused, but it's agreed that should not be the final reason to choose something apparently unclear.

I've renamed it to "executable comments".

Syntax example:

```
# __pragma__ ('ecom') # ===================================================================

# --- Executed only by Transcrypt ---
'''?
for i in range (5):
    print (i)
?'''

# --- Executed only by CPython ---
# __pragma__ ('skip')
for i in range (10, 15):
    print (i)
# __pragma__ ('noskip')

# --- Executed only by Transcrypt ---
#?print (50)

# --- Executed only by CPython ---
print (150) #__: skip

def __pragma__ (*args):
    pass
    
#__pragma__ ('noecom') # ===================================================================


# --- Executed by none ---
'''?
for i in range (5):
    print (i)
?'''

# --- Executed only by CPython ---
# __pragma__ ('skip')
for i in range (10, 15):
    print (i)
# __pragma__ ('noskip')

# --- Executed by  none ---
#?print (51)

# --- Executed only by CPython ---
print (151) #__: skip

__pragma__ ('ecom') # ===================================================================

# --- Executed only by Transcrypt ---
'''?
for i in range (5):
    print (i)
?'''

# --- Executed only by CPython ---
# __pragma__ ('skip')
for i in range (10, 15):
    print (i)
# __pragma__ ('noskip')

# --- Executed only by Transcrypt ---
#?print (52)

# --- Executed only by CPython ---
print (152) #__: skip

__pragma__ ('noecom') # ===================================================================

# --- Executed by none ---
'''?
for i in range (5):
    print (i)
?'''

# --- Executed only by CPython ---
# __pragma__ ('skip')
for i in range (10, 15):
    print (i)
# __pragma__ ('noskip')

# --- Executed by none ---
#?print (53)

# --- Executed only by CPython ---
print (153) #__: skip

```

I will add an autotest for this, rename the branch and merge it into master.
Thanks for the feedback and feel free to add additional ideas/remarks.

**Comment by JdeH** [comment]
Autotest:

```
from org.transcrypt.stubs.browser import __pragma__

def run (autoTester):

    # __pragma__ ('ecom') # ===================================================================

    # --- Executed only by Transcrypt ---
    '''?
    for i in range (10):
        autoTester.check (i)
    ?'''

    # --- Executed only by CPython ---
    # __pragma__ ('skip')
    for i in range (10):
        autoTester.check (i)
    # __pragma__ ('noskip')

    # --- Executed only by Transcrypt ---
    #?autoTester.check (100)

    # --- Executed only by CPython ---
    autoTester.check (100) #__: skip
        
    #__pragma__ ('noecom') # ===================================================================


    # --- Executed by none ---
    '''?
    for i in range (10, 20):
        autoTester.check (i)
    ?'''

    # --- Executed by  none ---
    #?autoTester.check (200)

    __pragma__ ('ecom') # ===================================================================


    # --- Executed only by Transcrypt ---
    '''?
    for i in range (20, 30):
        autoTester.check (i)
    ?'''

    # --- Executed only by CPython ---
    # __pragma__ ('skip')
    for i in range (20, 30):
        autoTester.check (i)
    # __pragma__ ('noskip')

    # --- Executed only by Transcrypt ---
    #?autoTester.check (300)

    # --- Executed only by CPython ---
    autoTester.check (300) #__: skip

    __pragma__ ('noecom') # ===================================================================

    # --- Executed by none ---
    '''?
    for i in range (30, 40):
        autoTester.check (i)
    ?'''

    # --- Executed by  none ---
    #?autoTester.check (400)

```

**Comment by brumar** [comment]
I love "executable comments". This is much stronger.

**Comment by JdeH** [comment]
It's in 3.7.14
