### ISSUE TITLE
Importing star

### ISSUE THREAD

**Issue by berinhard** [QQuick/Transcrypt#616]
I'm trying to use `transcrypt` to integrate Python with p5.js, but I'm having some troubles when it comes to importing. Currently I have my code as following:

```
from pyp5js import start_p5, P5

def setup():
    P5.size(900, 900)
    .....
```

But when I try to import both functions as:

```
from pyp5js import *

def setup():
    P5.size(900, 900)
    .....
```

The code does transpile, but I get this error in the browser:

```
sketch.py:10 Uncaught ReferenceError: P5 is not defined
    at setup (sketch.py:10)
    at p5.wrapper [as setup] (pyp5js.py:23)
    at p5.<anonymous> (p5.js:48805)
    at p5.<anonymous> (p5.js:48740)
```

I read `transcrypt -h` for help trying to figure out if I was missing a flag or something related, but I guess I couldn't find. Is it possible to use import star with transcrypt? If so, how can I do it?

**Comment by AlexECX** [comment]
What is the resulting transpiled code of sketch.py? Just the beginning where the import statements are.

**Comment by berinhard** [comment]
```

**Comment by berinhard** [comment]
**sketch.js**

```
'use strict';import"./org.transcrypt.__runtime__.js";var __name__="__main__";export var t=0;export var setup=function(){P5.createCanvas(600,600);P5.noStroke();P5.fill(40,200,40)};export var draw=function(){var width=P5.width;var height=P5.height;P5.background(10,10);var xAngle=P5.map(P5.mouseX,0,P5.width,-4*P5.PI,4*P5.PI,true);var yAngle=P5.map(P5.mouseY,0,P5.height,-4*P5.PI,4*P5.PI,true);for(var x=0;x<width;x+=30)for(var y=0;y<height;y+=30){var angle=xAngle*(x/width)+yAngle*(y/height);var myX=x+
20*P5.cos(2*P5.PI*t+angle);var myY=y+20*P5.sin(2*P5.PI*t+angle);P5.ellipse(myX,myY,10)}t=t+.01;console.log(P5.frameRate())};export var my_p5=start_p5(setup,draw);

//# sourceMappingURL=sketch.map
```

**pyp5.js**

```
'use strict';import"./org.transcrypt.__runtime__.js";var __name__="pyp5js";export var P5=null;export var global_p5_injection=function(p5_sketch){var decorator=function(f){var wrapper=function(){P5=p5_sketch;return f()};return wrapper};return decorator};export var start_p5=function(setup_func,draw_func){var sketch_setup=function(p5_sketch){p5_sketch.setup=global_p5_injection(p5_sketch)(setup_func);p5_sketch.draw=global_p5_injection(p5_sketch)(draw_func)};return new p5(sketch_setup,"sketch-holder")};
```

**Comment by berinhard** [comment]
The repository I'm working on is this one: https://github.com/berinhard/pyp5js

**Comment by AlexECX** [comment]
That's odd, are you sure this is the resulting transpiled code? Using pyp5.py on the git and a simple sketch.py:
```
from pyp5js import *

def setup():
    P5.size(900, 900)
```
I obtain this (using transcrypt -n sketch.py, so it's readable):
```
// Transcrypt'ed from Python, 2019-04-25 02:22:35
import {AssertionError, AttributeError, BaseException, DeprecationWarning, Exception, IndexError, IterableError, KeyError, NotImplementedError, RuntimeWarning, StopIteration, UserWarning, ValueError, Warning, __JsIterator__, __PyIterator__, __Terminal__, __add__, __and__, __call__, __class__, __envir__, __eq__, __floordiv__, __ge__, __get__, __getcm__, __getitem__, __getslice__, __getsm__, __gt__, __i__, __iadd__, __iand__, __idiv__, __ijsmod__, __ilshift__, __imatmul__, __imod__, __imul__, __in__, __init__, __ior__, __ipow__, __irshift__, __isub__, __ixor__, __jsUsePyNext__, __jsmod__, __k__, __kwargtrans__, __le__, __lshift__, __lt__, __matmul__, __mergefields__, __mergekwargtrans__, __mod__, __mul__, __ne__, __neg__, __nest__, __or__, __pow__, __pragma__, __proxy__, __pyUseJsNext__, __rshift__, __setitem__, __setproperty__, __setslice__, __sort__, __specialattrib__, __sub__, __super__, __t__, __terminal__, __truediv__, __withblock__, __xor__, abs, all, any, assert, bool, bytearray, bytes, callable, chr, copy, deepcopy, delattr, dict, dir, divmod, enumerate, filter, float, getattr, hasattr, input, int, isinstance, issubclass, len, list, map, max, min, object, ord, pow, print, property, py_TypeError, py_iter, py_metatype, py_next, py_reversed, py_typeof, range, repr, round, set, setattr, sorted, str, sum, tuple, zip} from './org.transcrypt.__runtime__.js';
import {P5, global_p5_injection, start_p5} from './pyp5js.js';
var __name__ = '__main__';
export var setup = function () {
	P5.size (900, 900);
};

//# sourceMappingURL=sketch.map
```
As you can see, the `org.transcrypt.__runtime__.js` import is quite different, and we actually have an import on `./pyp5js.js`. I'm just not sure why your transpiled version is different than mine.

Tried with python 3.7.0, Transcrypt 3.7.12, on Windows 10

**Comment by berinhard** [comment]
Thank you so much @AlexECX! I got what I was doing wrong, but I don't know if it's a bug. When I run the same command as you it works as you are explaining. But I was running the following command: 

`transcrypt -b -m -a sketch`

Does this `-a` flag should block the `from x import *` from working?

**Comment by fzzylogic** [comment]
@berinhard [-n minifies](https://www.transcrypt.org/docs/html/installation_use.html#available-command-line-switches) the output using Google's Closure, which also recompiles the js to ES5 (i believe regardless of what one specifies with -e which relates to un-minified output), which may explain the problem.

**Comment by AlexECX** [comment]
Just tried it, and indeed it does. The -a option will add line numbers comments in the .js file
```
/* 000001 */ // Transcrypt'ed from Python, 2019-04-26 09:21:13
/* 000001 */ import {} from './org.transcrypt.__runtime__.js';
/* 000001 */ var __name__ = '__main__';
/* 000003 */ export var setup = function () {
/* 000004 */ 	P5.size (900, 900);
```
but it seems its broken and won't render the imports correctly. Since you are not using -n (not minified js) these comments are removed in the minification process anyway, so you could forgo the use of -a.

**Comment by berinhard** [comment]
Thanks @AlexECX for the explanation. I'm glad that at least I was able to help you guys to find out a bug =]

I'm closing this issue since it's resolved.
