### ISSUE TITLE
Pygame import error

### ISSUE THREAD

**Issue by Dustyposa** [QQuick/Transcrypt#626]
Can trans pygame to js? 
When i use it, raised an error.
`Import error, can't find any of:
                /opt/NearlyPurePythonWebAppDemo/to_js/pygame/locals.py
                /opt/NearlyPurePythonWebAppDemo/to_js/pygame/locals.js
                /usr/local/lib/python3.6/dist-packages/transcrypt/modules/pygame/locals.py
                /usr/local/lib/python3.6/dist-packages/transcrypt/modules/pygame/locals.js
                /usr/local/bin/pygame/locals.py
                /usr/local/bin/pygame/locals.js
                /usr/lib/python3.6/pygame/locals.py
                /usr/lib/python3.6/pygame/locals.js
                /usr/lib/python3.6/lib-dynload/pygame/locals.py
                /usr/lib/python3.6/lib-dynload/pygame/locals.js
                /opt/NearlyPurePythonWebAppDemo/to_js/pygame/color.py
                /opt/NearlyPurePythonWebAppDemo/to_js/pygame/color.js
                /usr/local/lib/python3.6/dist-packages/transcrypt/modules/pygame/color.py
                /usr/local/lib/python3.6/dist-packages/transcrypt/modules/pygame/color.js
                /usr/local/bin/pygame/color.py
                /usr/local/bin/pygame/color.js
                /usr/lib/python3.6/pygame/color.py
                /usr/lib/python3.6/pygame/color.js
                /usr/lib/python3.6/lib-dynload/pygame/color.py
                /usr/lib/python3.6/lib-dynload/pygame/color.js
                /usr/local/lib/python3.6/dist-packages/pygame/color.py
                /usr/local/lib/python3.6/dist-packages/pygame/color.js
                /usr/lib/python3/dist-packages/pygame/color.py
                /usr/lib/python3/dist-packages/pygame/color.js
`

I doubt the code make a circular reference problem.But I'm not sure.
I don't know how to solve it.
And do transcrypt support pygame?

**Comment by AlexECX** [comment]
from the git README:

> Web batteries: Seamless access to any existing JavaScript library has been favored over inclusion of many Python libraries in the distribution. There are some exceptions to this rule, e.g. math, cmath, random, itertools, re, time, datetime and turtle, and some more may follow, but in general the accent is on libraries that are relevant in the browser.

**Comment by JdeH** [comment]
PyGame is partially written in C++, hence unfortunately won't run with Transcrypt, which relies on the "bare" browser environment.

There are ways to compile C++ to web assembly, but unfortunately they are currently to slow to be practical when used over the Internet.
