### ISSUE TITLE
Can't import from module 'collections'

### ISSUE THREAD

**Issue by zaoqi** [QQuick/Transcrypt#644]
```

Error while compiling (offending file last):
	...
	File '/usr/lib/python3.7/ast.py', line 230, at import of:
	File 'collections', line 103, namely:
	
	Can't import from module 'collections'
```

**Comment by fzzylogic** [comment]
Transcrypt doesn't have access to a number of python standard libraries for reasons explained here:
https://www.transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries

Available modules (not identical to pythons, but covering many common needs)
https://github.com/QQuick/Transcrypt/tree/master/transcrypt/modules

**Comment by JdeH** [comment]
Indeed...
