### ISSUE TITLE
OpenCV support

### ISSUE THREAD

**Issue by galeone** [QQuick/Transcrypt#645]
Hi!

I'm trying to convert a Python application that uses NumPy and OpenCV to Javascript.

To replace NumPy I've just replaced every `import numpy as np` with `import numscrypt as np`, (is this correct?) but there isn't a module for opencv.

On its side, OpenCV has already a complete Javascript version available ( see: https://docs.opencv.org/3.4/d0/d84/tutorial_js_usage.html ), so I'm wondering: is it possible to add the opencv module to transcrypt?

Which are the steps required to add a module? I could give a hand

**Comment by fzzylogic** [comment]
Hi @galeone, encapsulating a js library as a Python module can be done using a [__pragma__()](https://www.transcrypt.org/docs/html/special_facilities.html#inserting-literal-javascript-pragma-js-and-include), and that section also links to an example using the fabric.js library. Note also using the __new__ method to call the encapsulated lib. e.g.

```
__pragma__ ('noanno')

fabric = __pragma__ ('js',
    '''
(function () {{
    var exports = {{}};
    {}  // Puts fabric in exports and in global window
    delete window.fabric;
    return exports;
}}) () .fabric;
    ''',
    __include__ ('com/fabricjs/fabric_downloaded.js')
)
```

Hope that helps.

**Comment by JdeH** [comment]
@fzzylogic Thanks!
@galeone Does this work for you? If not feel free to reopen.
