### ISSUE TITLE
Cant find standart python module - io

### ISSUE THREAD

**Issue by alex-pancho** [QQuick/Transcrypt#651]
Looks like Transcrypt can't find standard python 3.x module - io
into python 3.0 io was extended: https://docs.python.org/3.0/whatsnew/3.0.html
i need to use StringIO
(https://docs.python.org/3.0/library/io.html#io.StringIO)
but when i call:
```
    try:
        from StringIO import StringIO
    except ImportError:
        from io import StringIO
```
I get error:
Import error, can't find any of: (list of places)

**Comment by fzzylogic** [comment]
Transcrypt doesn't have access to a number of python standard libraries for reasons explained here:
https://www.transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries

Available modules (not identical to pythons, but covering many common needs)
https://github.com/QQuick/Transcrypt/tree/master/transcrypt/modules

**Comment by JdeH** [comment]
Indeed...
