### ISSUE TITLE
Game made using Transcrypt

### ISSUE THREAD

**Issue by vkbsb** [QQuick/Transcrypt#678]
Hi, 
I've created a game for [PyWeek](https://pyweek.org) contest using Transcrypt. I would like it if you could have a look at it and include in the gallery. I've used [Pixijs](https://pixijs.io), [pixi-particles](https://github.com/pixijs/pixi-particles), [pixi-tween](https://github.com/Nazariglez/pixi-tween) and [howlerjs](https://howlerjs.com/) libraries from javascript world to build the game. 

Git Repo: [https://github.com/vkbsb/TowerJumpers](https://github.com/vkbsb/TowerJumpers)
Play in Browser (Desktop): [https://vkrishna.itch.io/towerjumpers?password=pyweek28](https://vkrishna.itch.io/towerjumpers?password=pyweek28)

**Comment by JdeH** [comment]
Hi, REAL FUN PLAYING THIS!
I've added a link to the gallery.

Kind regards
Jacques
