### ISSUE TITLE
3D web game by Transcrypt

### ISSUE THREAD

**Issue by warrenchopin** [QQuick/Transcrypt#681]
I developed a 3rd-person 3D web game using Transcrypt.  No installation or update is required to play. I will be really happy if it is included in Gallery page of Transcrypt website.

[goldball.games](https://goldball.games) 

It was really cool to use Python developing a game. Transcrypt is great because it is good to integrate with Javascript in web environment. I integrated with Babylon.js, Firebase, Paypal, and other Javascript libraries without any problem.

**Comment by JdeH** [comment]
Hi, NICE JOB!!
I've added a link to the gallery.
Which JS libs did you use?

Kind regards
Jacques

**Comment by warrenchopin** [comment]
Thanks for adding my game to your Gallery. As I wrote above, I used Babylon.js as 3D graphic engine. Firebase for user authentication. Paypal for payment.

My source code size is growing bigger, but I still have no big mental stress to manage my code thanks to beautiful Python. Thanks to Transcrypt, I am enjoying using Python developing a web game. I really want to say thank you Jacques letting us enjoy using Python in the web.

**Comment by JdeH** [comment]
I had read about the libs, but I wasn't sure you used them all in this application. I am glad you like Transcrypt. I myself was fed up with programming in JS... I hope your game will be successful! I am not much of a gamer myself, but I showed it to someone one third of my age, and he thought it was fun.

**Comment by warrenchopin** [comment]
I designed my game to be very easy to start to play for everyone. I am glad that there is really someone who likes my game.  I want to develop my game further so that everyone wants to play together. Thanks again.
