### ISSUE TITLE
Typescript as target

### ISSUE THREAD

**Issue by kiwi0fruit** [QQuick/Transcrypt#685]
It's not even a feature request...

I've recently discovered mypy and I love it. And I guess lots of people would be glad to use Python type annotations and transpile to Typescript. It would also be helpful to transpile back Typescript type annotations of libraries to .pyi stubs so that PyCharm autocomplete and mypy typechecker could use them.

**Comment by AlexECX** [comment]
Nothing about typescript, but there has been work done with mypy in #105 and there is documentation on [static check validation](https://transcrypt.org/docs/html/installation_use.html#static-type-validation), although I'm not sure it is actively being kept up to date.

**Comment by JdeH** [comment]
Being able to generate Typescipt type info would surely be useful.
But given the current backlog in issues unfortunately I expect it won't be in any time soon.
I'll label it as postponed and, as with other postponed issues, close it for now, to keep some overview of what's reallistically in the pipeline.
