### ISSUE TITLE
Addition of lists of strings creates a list of chars?

### ISSUE THREAD

**Issue by RAbraham** [QQuick/Transcrypt#696]
Hi,
Thank you for making this library. I'm very excited to use it. 

I was playing with it and I noticed:

```python
# get the "app" div and add an ordered list
app = document.getElementById("app")
ol = app.appendChild(document.createElement("ol"))

# add a few names to the list
for name in ["Homer", "Marge"]:
    li = ol.appendChild(document.createElement("li"))
    li.textContent = f"{name} Simpson"


```
The output is as expected:

```
Homer Simpson
Marge Simpson
```

But if I change `["Homer", "Marge"]` to `["Homer"] + ["Marge"]` i.e.
```python
# get the "app" div and add an ordered list
app = document.getElementById("app")
ol = app.appendChild(document.createElement("ol"))


# add a few names to the list
for name in ["Homer"] + ["Marge"]:
    li = ol.appendChild(document.createElement("li"))
    li.textContent = f"{name} Simpson"


```

I get:
```

H Simpson
o Simpson
m Simpson
e Simpson
r Simpson
M Simpson
a Simpson
r Simpson
g Simpson
e Simpson
```

I'm on Python 3.7.5, Mac Mojave

**Comment by AlexECX** [comment]
Operator overloading is not enabled by default for performance reasons, see [Special facilities - Operator overloading](https://transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov) to enable selectively or globally. Javascript doesn't have operator overloading, so what you are seeing is the normal JS behaviour.

Chromium console:
```
> ["qwe"] + ["asdf"]
"qweasdf"
```

**Comment by RAbraham** [comment]
That's a great explanation. Thanks!
