### ISSUE TITLE
List concatenation not working

### ISSUE THREAD

**Issue by ftrias** [QQuick/Transcrypt#738]
In python, when you add two lists together you get a list with all elements of both. This doesn't seem to work on Transcrypt. I tested the following code:

```
test_array = [-1] + [-1]
print(test_array)
```

In Python that returns:
```
[-1, -1]
```

In Transcrypt it is:
```
-1-1
```

If I modify the print to display more details in Transcrypt:

```
print("!".join(map(str, test_array)), type(test_array))
```

The output show that `test_array` is treated as string instead of an array of ints:

```
-!1!-!1 function str(stringable){if(typeof stringable==="number")return stringable.toString();else try{return stringable.__str__()}catch(exception){try{return repr(stringable)}catch(exception){return String(stringable)}}}
```

**Comment by faerot** [comment]
You need to enable operator overloading in transcrypt.
