### ISSUE TITLE
Cannot get parcel-plugin-transcrypt to work

### ISSUE THREAD

**Issue by halloleo** [QQuick/Transcrypt#743]
I try a web project with `parcel-plugin-transcrypt` bundling the transpiled the Python code.

However the plugin has for me two issues:

1. The entrypoint HTML file in `dist` points to the `.py` file not the transpiled .js file.
1. Even when i fix this by hand the plugin  seems not  to bundle the Transcrypt runtime. (Browser console tells me it cannot find theruntime file.)

**Comment by JennaSys** [comment]
If you have your python entrypoint specified in the HTML file like `<script src="app.py"></script>`, and use the HTML file as the input source file, it should create a new HTML file that has the original python file name replaced with the bundled js file name.  You should not have to change anything by hand.

**Comment by halloleo** [comment]
Ah, yes of course! I will try this. Thanks @JennaSys.
