### ISSUE TITLE
wrong translation update function

### ISSUE THREAD

**Issue by emrum** [QQuick/Transcrypt#745]
I make a call (py file):
control.update()

but transcrypt converts to 
control.py_update()

(in js file)
so I have to fix after file generation every time

**Comment by JennaSys** [comment]
I believe this is by design to prevent name clashes with JavaScript.  See [issue 377](https://github.com/QQuick/Transcrypt/issues/377)

A list of aliases that Transcrypt defines is [here](http://www.transcrypt.org/docs/html/special_facilities.html#pragma-alias).

**Comment by emrum** [comment]
Thank you Jenna, 
I see: 
  js_update()  ==> update()

This helps a little.
