### ISSUE TITLE
Off-Topic: Cloudflare Workers uses Transcrypt

### ISSUE THREAD

**Issue by pauleveritt** [QQuick/Transcrypt#746]
Cloudflare Workers is a serverless computation engine. They just [announced support for Python](https://blog.cloudflare.com/cloudflare-workers-announces-broad-language-support/). 

And how do they do that, given that their engine is a very sophisticated V8 isolation thingy? "The README.md file in the directory links to instructions on setting up Transcrypt, the Python to JavaScript compiler we're using. "

**Comment by koeninger** [comment]
Yep, feel free to ping me if there's a concern.

**Comment by AAgar** [comment]
@koeninger Is Pandas not a compatible module?  I've got installed in the right location(s) but Transcrypt throws an error whenever I try to run it.

**Comment by koeninger** [comment]
I was under the impression that Pandas depends on C code extensions so I wouldn't expect it to work.  Looks like you opened https://github.com/QQuick/Transcrypt/issues/748 already, maybe someone more knowledgeable will chime in.

**Comment by pauleveritt** [comment]
@koeninger Cool to get someone from Cloudflare giving a reply. Good job on this feature, hope it works out well.

I'll close this ticket as it's just a comment.

**Comment by pauleveritt** [comment]
@koeninger If you have any advocates that can drive PyCharm, we'd love to have you on for a webinar promoting workers, the new Python support, Transcrypt.
