### ISSUE TITLE
using range in python code produces obscure error message

### ISSUE THREAD

**Issue by kkibria** [QQuick/Transcrypt#788]
I created a test python file,`test.py`
```python
def test_def(a: list):		
    for i in range(len(a)):
        print(i)

xx = [2, 3, 4]
test_def(xx)
```

I have python 3.9. If I run the python file, it runs and prints as expected.

Running transcrypt gives following error
```
> python -m transcrypt -b -m -n .\test.py
Error while compiling (offending file last):
        File 'test', line 2, namely:

        Error while compiling (offending file last):
        File 'test', line 2, namely:


Aborted
```

It's seems like something about the `range`. If you change `range` to a variable name like `xxxxx`, it compiles, but of course it won't have the correct functionality.

Ref: <https://stackoverflow.com/questions/68582595/error-message-seems-ambiguous-without-any-descriptive-clue>

**Comment by fzzylogic** [comment]
Thanks for reporting this @kkibria. What version of Transcrypt are you using? Wasn't able to replicate the error using Python 3.9.0 and Transcrypt 3.9.0. You can check like this (Win):

    transcrypt -h | find "Version"

The Python and Transcrypt versions should match, as Transcrypt uses Python's AST that may change between versions.

**Comment by kkibria** [comment]
I did have a mismatch in versions. Closing.
