### ISSUE TITLE
Is Python3.7 ok for transcrypt? I am getting a "list index out of range" error

### ISSUE THREAD

**Issue by halloleo** [QQuick/Transcrypt#794]
I have installed Transcrypt from pypi into a Python 3.7 environment, but I am getting the following error:

```
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.9.0
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: /devel/tstest/__target__/org.transcrypt.__runtime__.js

list index out of rangeTraceback (most recent call last):
[...]
  File "/opt/pipx/venvs/transcrypt/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 324, in findPaths
    message = '\n\tImport error, can\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (self.program.searchedModulePaths))
org.transcrypt.utils.Error: <unprintable Error object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[...]
  File "/opt/pipx/venvs/transcrypt/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 215, in __str__
    result += '\n\tFile \'{}\', line {}, namely:'.format (str (program.importStack [-1][0] .name), self.lineNr)
IndexError: list index out of range

Aborted
```

Any idea what's going wrong?

**Comment by JennaSys** [comment]
Transcrypt on PyPI has been updated to use Python 3.9.  So you either need to update to Python 3.9 with that version or install the 3.7 version of Transcrypt with:
`pip install Transcrypt==3.7.16`

**Comment by monschine** [comment]
I use python 3.7 and transcrypt ==3.7.16 and getting exactly the same error

**Comment by halloleo** [comment]
I have upgraded to Python 3.9 and everything is fine. :-)

**Comment by fzzylogic** [comment]
Just a note that I've had good results using a virtual environment instead of installing transcrypt globally. e.g.

    > python -m venv env
    > env\Scripts\activate.bat   # activate env (windows)
    > pip install transcrypt==3.7
    > transcrypt -b -m -n test.py

Just tested above on win 10 with python 3.7.9 and a small test script and it compiled.

**Comment by superuser-PCA** [comment]
> I use python 3.7 and transcrypt ==3.7.16 and getting exactly the same error

TYVM... 3.7.11 is fine for my usage right now so I will upgrade to 3.9.x in the future

![image](https://github.com/TranscryptOrg/Transcrypt/assets/117834103/9f6326fd-04c4-45be-a77a-6bce1bfdf6f0)
