### ISSUE TITLE
Working with `except ImportError`

### ISSUE THREAD

**Issue by mentalisttraceur** [QQuick/Transcrypt#796]
I often write code like this, precisely to try to support Pythons such as Transcrypt:

```python
try:
    from reprlib import recursive_repr as _recursive_repr
    _recursive_repr_if_available = _recursive_repr()
except ImportError:
    def _recursive_repr_if_available(function):
        return function
```

Unfortunately, Transcrypt compilation ignores this. It tries to import reprlib, which tries to import get_ident from _thread, which raises an ImportError as expected. But then it aborts with an error.

Of course, if I'm reusing my own Python libraries with Transcrypt, I'll can manually replace that whole thing with just the except block and compile again. But this is a manual step, which doesn't scale very well, especially for third-party libraries.

It would be nice it Transcrypt identified simple variations of this pattern: is the import in a try? did one of the excepts contain `ImportError`? then just compile the except body in place of the whole try-catch.

**Comment by mentalisttraceur** [comment]
Preempting "Transcrypt doesn't try to support third party Python libraries":

This is an example of library code that is *actively trying to do all the work needed to make itself work on Transcrypt*.

Are there any alternative ways to write general Python code that can gracefully degrade in the absence of certain imports that would work on Transcrypt?

**Comment by mentalisttraceur** [comment]
That last example is particularly interesting because it seems to fail at the `dummy_thread` import (whereas the `reprlib` import in the first example fails at its `from _thread` import).

Which makes me think that you're already support most of this functionality (because how else would you get to `from dummy_thread import`, if not by following the first two `except ImportError` clauses?).

So maybe all that's missing is falling through to the polyfilling code case at the end, if there is one?

**Comment by mentalisttraceur** [comment]
Ohhhh! I see. Transcrypt compilation is just following *all* imports, across _all_ the try-except blocks. It only seems like it's falling through in that last example, because it ends up trying or at least reporting the `dummy_thread` failure first. Then if you implement `dummy_thread.py`, it fails at the `from thread import` instead, and so on.

So it's effectively *penalizing* code which attempts to support two or more different possible imports, and users of that code, because now users of code that does the above triple-fallback have to implement _all three_ (of course they can copy/link the same file with the dummy `return 0` implementation into all three module names, but that's still more overhead all because the library tried to do a good helpful thing for implementations like Transcrypt and their users).

**Comment by mentalisttraceur** [comment]
To be fair, I think the other side of this argument looks something like this:

1. libraries generally should assume that the features they want exist, and can be found at their normal paths/names, because

2. it is an external-to-the-library responsibility to ensure that the stuff it needs (or an acceptably gracefully-degraded polyfill) is present, so

3. libraries should just not try to do conditional imports like that, and in fact help portability if they keep their imports naive to these issues.

I'm not sure if that holds up in all cases, but I think it's a good perspective, and is compelling enough that I can see how someone might argue that Transcrypt would do more good by actively and deliberately refusing to cooperate with `except ImportError`, even if the functionality was free, or even by removing the functionality as a deliberate breaking change if it was already available.

**Comment by fzzylogic** [comment]
I guess the reason is that the Transcrypt imports are compile time. You may be able to approach this from a different angle, using [pragma's](https://www.transcrypt.org/docs/html/special_facilities.html#skipping-transcrypt-code-fragments-when-running-with-cpython-pragma-ecom-and-pragma-noecom). 

For example, the 'skip' directive can be used to indicate code that should be executed only by CPython (in other words not compiled to js) and 'ecom' can be used to include code that will only be executed by Transcrypt (compiled to js).

**Comment by mentalisttraceur** [comment]
Thanks @fzzylogic! That does seem like it could work, and I think that's a sufficient solution and answer from Transcrypt.

I'm increasingly convincing myself of the philosophy expressed in my last comment: that such compatibility is not the library's responsibility, and is more appropriately solved at a higher level. So now I'm thinking that really I should always just unconditionally do things like `from reprlib import recursive_repr` or `from _thread import get_ident as _thread_id`, and if someone is using my libraries on Transcrypt, it is fair and in fact good if they themselves polyfill `_thread.get_ident` or whatever as needed.

Of course, that doesn't have to be a manual thing - if this is a common enough need, there could be another tool, a transpiler kinda like Transcrypt, specifically focused on "backpiling"/"portapiling" new code to more broadly/backwards-portable code, and injecting minimally-sufficient or gracefully-degraded polyfills of the stuff that it finds it used but unavailable.

And of course, such a backpiler/portapiler could generate the Transcrypt pragmas when targetting Transcrypt, and would both remove the need for such conditional imports in code, _and_ would be a better and more natural place to focus all the effort and intelligence of parsing and interpreting conditional imports. And from that vision, it's both justified and in fact better for Transcrypt to stay focused on the problem of Python-to-JavaScript transpiling and not put any effort into handling conditional imports.
