### ISSUE TITLE
cannot import from module PIL

### ISSUE THREAD

**Issue by Morsmalleo** [QQuick/Transcrypt#798]
I keep getting this everytime I use transcrypt no matter what I do

    python3 -m transcrypt -b -m -n file.py

        Error while compiling (offending file last):
        File 'file.py', line 4, at import of:
        File 'PIL', line 19, namely:

        Can't import from module 'PIL'

    Aborted

I have checked the lines of the files and they seem fine, so I have no idea why this is happening, python was never my strongsuit however.

- python version: 3.9.9
- pip version: 21.3.1
- OS: Kali Linux
- error arises with both Transcrypt version 3.7.16 and 3.9.0
- pillow version 8.4.0

**Comment by Morsmalleo** [comment]
Solved by running `pip3 install git+https://github.com/QQuick/Transcrypt`

**Comment by fzzylogic** [comment]
Welcome @Morsmalleo, thanks for the clear report! 'file.py' is importing PIL, which Transcrypt can't compile to js (it can't compile any C which PIL includes quite a lot of, it only handles a fairly extensive subset of Python), more info in the [docs](https://www.transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries).

**Comment by Morsmalleo** [comment]
> Welcome @Morsmalleo, thanks for the clear report! 'file.py' is importing PIL, which Transcrypt can't compile to js (it can't compile any C which PIL includes quite a lot of, it only handles a fairly extensive subset of Python), more info in the [docs](https://www.transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries).

Thank you for the information 😊
