### ISSUE TITLE
object() constructor

### ISSUE THREAD

**Issue by astavely** [QQuick/Transcrypt#840]
In my Python program I have:

    ANY = object()

Transcrypt translates this to:

    export var ANY = object ();

But the script won't execute.  My browsers (Firefox 109.0.1, Safari 15.6.1) apparently don't recognize "object" as a JavaScript function.  Something missing from the Transcript-generated runtime perhaps?

**Comment by astavely** [comment]
I should have said: that's perfectly good Python, and the Python program has worked fine for years.

**Comment by JennaSys** [comment]
Not sure I understand what your desired end result is. Are you trying to create a bare JavaScript object? If so, you can try using `window.Object()` which would be more explicit and might have a better chance of being transpiled correctly. You may also have to use the [Transcrypt \_\_new\_\_() function](https://www.transcrypt.org/docs/html/special_facilities.html#creating-javascript-objects-with-new-constructor-call) in this case as well.

Issue #665 may provide some more clues, and also check the docs on [Creating bare JavaScript objects](https://www.transcrypt.org/docs/html/special_facilities.html#create-bare-javascript-objects-and-iterate-over-their-attributes-from-python-pragma-jsiter-and-pragma-nojsiter) for another possible option.

**Comment by astavely** [comment]
I'm creating an atom, as in LISP or Erlang.  It 's just a marker.  It's an object that compares equal to itself and unequal to any other Python object using "is" or "==".  That's all it's for.

The proposed solutions are not more explicit, they are obfuscation.  I'm not doing anything with windows.  And I'm writing Python, not Javascript.

If I have to know about special cases that Transcrypt won't translate correctly, and write workarounds in which I have to think about the JavaScript translation, I won't use Transcrypt.

**Comment by JennaSys** [comment]
Sorry, I assumed you were translating Python to JS for use in a browser, `window` is a browser object that the JS `Object()` belongs to in that case and has nothing to do with the Windows OS.

**Comment by astavely** [comment]
Yes, I want to run the Python program in a browser window as if it were a
terminal window.

But the Python program will still be used in other environments, so I don't
want to put Transcrypt-specific code into it.

Thanks,

    - Allan

**Comment by astavely** [comment]
Thanks!  I took a look at PyScript and I thought it was exactly what I
wanted.

But it doesn't do input() nicely.  It pops up a text entry box and grays
out the rest of the window.  I can type input lines, but I don't see the
program's responses to them until the program terminates!  I don't see a
dialog as I would if I were running the program in a terminal window.

From the PyScript documentation and what I can find with online searches, I
don't think I can get PyScript to behave differently.  (No, I'm not asking
for help with PyScript.)  So I'm abandoning it.

I may come back to Transcrypt some day and deal with the the workarounds I
need.  But for now I'm stepping away from my project for a while.

Anyway, many thanks for the help!

    - Allan
